[FIX] account@{saas~12.3,13.0}: ignore deprecated accounts
Ignore deprecated accounts are being use during upgrade:

 - Regarding assets, these deprecated accounts were used in the depreciation lines,
   when converted to `account.move`, they must obviously still use the same, deprecated, account
 - Regarding taxes, it's only to migrate the taxes configuration,
   the fact we use deprecated accounts doesn't matter.

I have the feeling this will be required also for 13.0,
as we might create moves for invoices using deprecated accounts as well,
hence the symlink for version 13.0.

```
  File "/src/odoo/saas-12.3/odoo/addons/base/maintenance/migrations/account_asset/saas~12.3.1.0/pre-10-models.py", line 134, in migrate
    move_ids = env["account.move"].create([_convert_to_account_move_vals(res) for res in result])
  File "<decorator-gen-229>", line 2, in create
  File "/src/odoo/saas-12.3/odoo/api.py", line 439, in _model_create_single
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/src/odoo/saas-12.3/odoo/api.py", line 439, in <genexpr>
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/src/odoo/saas-12.3/addons/account/models/account_move.py", line 349, in create
    move = super(AccountMove, self.with_context(mail_create_nolog=True, check_move_validity=False, partner_id=vals.get('partner_id'))).create(vals)
  File "<decorator-gen-119>", line 2, in create
  File "/src/odoo/saas-12.3/odoo/api.py", line 457, in _model_create_multi
    return create(self, [arg])
  File "/src/odoo/saas-12.3/addons/mail/models/mail_thread.py", line 273, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-96>", line 2, in create
  File "/src/odoo/saas-12.3/odoo/api.py", line 439, in _model_create_single
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/src/odoo/saas-12.3/odoo/api.py", line 439, in <genexpr>
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/src/odoo/saas-12.3/odoo/addons/base/maintenance/migrations/base/0.0.0/pre-models-match_uniq.py", line 23, in create
    return super(Base, self).create(values)
  File "<decorator-gen-3>", line 2, in create
  File "/src/odoo/saas-12.3/odoo/api.py", line 457, in _model_create_multi
    return create(self, [arg])
  File "/src/odoo/saas-12.3/odoo/models.py", line 3639, in create
    records = self._create(data_list)
  File "/src/odoo/saas-12.3/odoo/models.py", line 3763, in _create
    for other, data in zip(others, data_list)
  File "/src/odoo/saas-12.3/odoo/fields.py", line 2506, in create
    self._write(record_values)
  File "/src/odoo/saas-12.3/odoo/fields.py", line 2574, in _write
    flush()
  File "/src/odoo/saas-12.3/odoo/fields.py", line 2535, in flush
    comodel.create(to_create)
  File "<decorator-gen-230>", line 2, in create
  File "/src/odoo/saas-12.3/odoo/api.py", line 458, in _model_create_multi
    return create(self, arg)
  File "/src/odoo/saas-12.3/addons/account/models/account_move.py", line 1307, in create
    raise UserError(_('The account %s (%s) is deprecated.') %(account.name, account.code))
odoo.exceptions.UserError: ('The account Warehouse Cost Rent (52010) is deprecated.', '')
```

```
  File "/src/odoo/saas-12.3/odoo/addons/base/maintenance/migrations/account/saas~12.3.1.1/end-10-taxes.py", line 136, in migrate
    migration_dicts_list = get_v13_migration_dicts(cr)
  File "/src/odoo/saas-12.3/odoo/addons/base/maintenance/migrations/account/saas~12.3.1.1/end-10-taxes.py", line 1791, in get_v13_migration_dicts
    inv = create_invoice(cr, partner, tax, journal, account, type=inv_type)
  File "/src/odoo/saas-12.3/odoo/addons/base/maintenance/migrations/account/saas~12.3.1.1/end-10-taxes.py", line 610, in create_invoice
    invoice_ctx.action_invoice_open()
  File "/src/odoo/saas-12.3/addons/sale/models/account_invoice.py", line 53, in action_invoice_open
    res = super(AccountInvoice, self).action_invoice_open()
  File "/src/odoo/saas-12.3/addons/account/models/account_invoice.py", line 1080, in action_invoice_open
    return to_open_invoices.action_move_create()
  File "/src/enterprise/saas-12.3/account_sepa_direct_debit/models/account_invoice.py", line 18, in action_move_create
    res = super(AccountInvoice, self).action_move_create()
  File "/src/odoo/saas-12.3/addons/stock_account/models/account_invoice.py", line 60, in action_move_create
    res = super(AccountInvoice, self).action_move_create()
  File "/src/odoo/saas-12.3/addons/account/models/account_invoice.py", line 1456, in action_move_create
    move = account_move.create(move_vals)
  File "<decorator-gen-296>", line 2, in create
  File "/src/odoo/saas-12.3/odoo/api.py", line 436, in _model_create_single
    return create(self, arg)
  File "/src/odoo/saas-12.3/addons/account/models/account_move.py", line 339, in create
    move = super(AccountMove, self.with_context(mail_create_nolog=True, check_move_validity=False, partner_id=vals.get('partner_id'))).create(vals)
  File "<decorator-gen-127>", line 2, in create
  File "/src/odoo/saas-12.3/odoo/api.py", line 457, in _model_create_multi
    return create(self, [arg])
  File "/src/odoo/saas-12.3/addons/mail/models/mail_thread.py", line 273, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-96>", line 2, in create
  File "/src/odoo/saas-12.3/odoo/api.py", line 439, in _model_create_single
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/src/odoo/saas-12.3/odoo/api.py", line 439, in <genexpr>
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/src/odoo/saas-12.3/odoo/addons/base/maintenance/migrations/base/0.0.0/pre-models-match_uniq.py", line 23, in create
    return super(Base, self).create(values)
  File "<decorator-gen-3>", line 2, in create
  File "/src/odoo/saas-12.3/odoo/api.py", line 457, in _model_create_multi
    return create(self, [arg])
  File "/src/odoo/saas-12.3/odoo/models.py", line 3639, in create
    records = self._create(data_list)
  File "/src/odoo/saas-12.3/odoo/models.py", line 3763, in _create
    for other, data in zip(others, data_list)
  File "/src/odoo/saas-12.3/odoo/fields.py", line 2506, in create
    self._write(record_values)
  File "/src/odoo/saas-12.3/odoo/fields.py", line 2574, in _write
    flush()
  File "/src/odoo/saas-12.3/odoo/fields.py", line 2535, in flush
    comodel.create(to_create)
  File "<decorator-gen-297>", line 2, in create
  File "/src/odoo/saas-12.3/odoo/api.py", line 458, in _model_create_multi
    return create(self, arg)
  File "/src/odoo/saas-12.3/addons/account/models/account_move.py", line 1297, in create
    raise UserError(_('The account %s (%s) is deprecated.') %(account.name, account.code))
odoo.exceptions.UserError: ('Le compte TVA collectée en attente 8,5% (445725) est déprécié.', '')
```

Request 44727
Request 51612

Closes #1513

closes odoo/upgrade#1515

Signed-off-by: Denis Ledoux (dle) <dle@odoo.com>