[FIX] analytic/saas~16.5: saved account_analytic_plan record
1. When we delete the account_analytic_plan for same name
without checking `project_plan_id` which we insert
that record in ir_config_parameter and  will
get plan ids from that ir_config_parameter record.
but during mapping , as will not check for `project_plan_id`
it is going to delete that record which was still
exist in ir_config_parameter. so will got traceback
about record does not exist.
to fix this we would be to redefine
`all_project_plans = [project_plan_id]`
when we create project_plan_id after that
and also
need to ensure project_plan_id is always in all_project_plans.
if not then append project_plan_id in all_project_plans

TGB: https://upgrade.odoo.com/web#id=786&cids=1&model=upgrade.request.traceback.group&view_type=form

```
Traceback (most recent call last):
   File "/tmp/tmpznjpo7x_/migrations/base/tests/test_mock_crawl.py", line 238, in crawl_menu
    self.mock_action(action_vals)
   File "/tmp/tmpznjpo7x_/migrations/base/tests/test_mock_crawl.py", line 334, in mock_action
    views = get_views(
   File "/home/odoo/src/enterprise/17.0/web_studio/models/ir_ui_view.py", line 53, in get_views
    return super().get_views(views, options)
   File "/home/odoo/src/odoo/17.0/odoo/addons/base/models/ir_ui_view.py", line 2435, in get_views
    result['views'] = {
   File "/home/odoo/src/odoo/17.0/odoo/addons/base/models/ir_ui_view.py", line 2436, in <dictcomp>
    v_type: self.get_view(
   File "/home/odoo/src/odoo/17.0/odoo/addons/base/models/ir_ui_view.py", line 2621, in get_view
    result = dict(self._get_view_cache(view_id, view_type, **options))
   File "<decorator-gen-50>", line 2, in _get_view_cache
   File "/home/odoo/src/odoo/17.0/odoo/tools/cache.py", line 104, in lookup
    value = d[key] = self.method(*args, **kwargs)
   File "/home/odoo/src/odoo/17.0/odoo/addons/base/models/ir_ui_view.py", line 2580, in _get_view_cache
    arch, models = view.postprocess_and_fields(arch, model=self._name, **options)
   File "/home/odoo/src/odoo/17.0/odoo/addons/base/models/ir_ui_view.py", line 984, in postprocess_and_fields
    name_manager = self._postprocess_view(node, model or self.model, **options)
   File "/home/odoo/src/odoo/17.0/odoo/addons/base/models/ir_ui_view.py", line 1103, in _postprocess_view
    name_manager.update_available_fields()
   File "/home/odoo/src/odoo/17.0/odoo/addons/base/models/ir_ui_view.py", line 3001, in update_available_fields
    info.update(self.field_info.get(name, ()))
   File "/home/odoo/src/odoo/17.0/odoo/tools/func.py", line 28, in __get__
    value = self.fget(obj)
   File "/home/odoo/src/odoo/17.0/odoo/addons/base/models/ir_ui_view.py", line 2777, in field_info
    field_info = self.model.fields_get(attributes=['readonly', 'required'])
   File "/home/odoo/src/odoo/17.0/addons/analytic/models/analytic_line.py", line 137, in fields_get
    fname = plan._column_name()
   File "/home/odoo/src/odoo/17.0/addons/analytic/models/analytic_plan.py", line 122, in _column_name
    return self.root_id._strict_column_name()
   File "/home/odoo/src/odoo/17.0/odoo/fields.py", line 2887, in __get__
    return super().__get__(records, owner)
   File "/home/odoo/src/odoo/17.0/odoo/fields.py", line 1208, in __get__
    self.compute_value(record)
   File "/home/odoo/src/odoo/17.0/odoo/fields.py", line 1388, in compute_value
    records._compute_field_value(self)
   File "/home/odoo/src/odoo/17.0/odoo/models.py", line 4858, in _compute_field_value
    fields.determine(field.compute, self)
   File "/home/odoo/src/odoo/17.0/odoo/fields.py", line 101, in determine
    return needle(*args)
   File "/home/odoo/src/odoo/17.0/addons/analytic/models/analytic_plan.py", line 133, in _compute_root_id
    plan.root_id = int(plan.parent_path[:-1].split('/')[0]) if plan.parent_path else plan
   File "/home/odoo/src/odoo/17.0/odoo/fields.py", line 1187, in __get__
    raise MissingError("\n".join([
 odoo.exceptions.MissingError: Record does not exist or has been deleted.
(Record: account.analytic.plan(1,), User: 2)
```

closes odoo/upgrade#5419

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>