[FIX] timesheet_grid/saas~18.3: add check for empty list
There are valid edge cases where `timesheet_vals_list` may be empty.
For the db which i faced this case `timer_timer.res_id` references a
`project.task` that no longer exists.

So, in order to safe check this cases to avoid any empty list for create.

```sql
apan_2979925=> SELECT t.id,t.res_id
              FROM timer_timer t
              JOIN hr_employee h
             USING (user_id)
             WHERE t.res_model = 'project.task'
               AND h.active = true;
 id | res_id
----+--------
 12 |     64
(1 row)

apan_2979925=> select id from project_task where id=64;
 id
----
(0 rows)
```

```py
  File "/tmp/tmpzddkhkw9/migrations/timesheet_grid/saas~18.3.1.0/post-migrate.py", line 53, in migrate
    util.iter_browse(AAL, []).create(timesheet_vals_list)
  File "/tmp/tmpzddkhkw9/migrations/util/orm.py", line 444, in create
    raise ValueError("`create` cannot be called with an empty `values` argument")
ValueError: `create` cannot be called with an empty `values` argument
```

opw-4863814
upg-2979925
tbg-2056

closes odoo/upgrade#7847

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>