[FIX] documents/0.0.0: ensure documents.share has available mail.alias
If one of the `documents.share` data records are deleted
and the corresponding `mail.alias` is remapped somewhere else,
an error will happen when the upgrade tries to re-create the record.

Similar case as #2558

upg-46339

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/15.0/odoo/tools/convert.py", line 680, in _tag_root
    f(rec)
  File "/home/odoo/src/odoo/15.0/odoo/tools/convert.py", line 583, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/home/odoo/src/odoo/15.0/odoo/models.py", line 4398, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/home/odoo/src/odoo/15.0/odoo/models.py", line 4327, in _load_records_create
    return self.create(values)
  File "<decorator-gen-229>", line 2, in create
  File "/home/odoo/src/odoo/15.0/odoo/api.py", line 391, in _model_create_single
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/home/odoo/src/odoo/15.0/odoo/api.py", line 391, in <genexpr>
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/home/odoo/src/enterprise/15.0/documents/models/share.py", line 211, in create
    share = super(DocumentShare, self).create(vals)
  File "<decorator-gen-131>", line 2, in create
  File "/home/odoo/src/odoo/15.0/odoo/api.py", line 409, in _model_create_multi
    return create(self, [arg])
  File "/home/odoo/src/odoo/15.0/addons/mail/models/mail_thread.py", line 264, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-130>", line 2, in create
  File "/home/odoo/src/odoo/15.0/odoo/api.py", line 410, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/15.0/addons/mail/models/mail_alias_mixin.py", line 43, in create
    alias_ids = iter(self.env['mail.alias'].sudo().create(alias_vals_list).ids)
  File "<decorator-gen-129>", line 2, in create
  File "/home/odoo/src/odoo/15.0/odoo/api.py", line 410, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/15.0/addons/mail/models/mail_alias.py", line 121, in create
    sanitized_names = self._clean_and_check_unique(alias_names)
  File "/home/odoo/src/odoo/15.0/addons/mail/models/mail_alias.py", line 195, in _clean_and_check_unique
    raise UserError(
odoo.exceptions.UserError: De e-mailalias inbox@localhost wordt al gebruikt door de Inbox Documenten Documents Share. Kies een andere alias of wijzig deze in het andere document.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/15.0/odoo/service/server.py", line 1246, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/odoo/src/odoo/15.0/odoo/modules/registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/15.0/odoo/modules/loading.py", line 470, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/home/odoo/src/odoo/15.0/odoo/modules/loading.py", line 363, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/odoo/src/odoo/15.0/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/home/odoo/src/odoo/15.0/odoo/modules/loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/home/odoo/src/odoo/15.0/odoo/tools/convert.py", line 745, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/home/odoo/src/odoo/15.0/odoo/tools/convert.py", line 811, in convert_xml_import
    obj.parse(doc.getroot())
  File "/home/odoo/src/odoo/15.0/odoo/tools/convert.py", line 731, in parse
    self._tag_root(de)
  File "/home/odoo/src/odoo/15.0/odoo/tools/convert.py", line 680, in _tag_root
    f(rec)
  File "/home/odoo/src/odoo/15.0/odoo/tools/convert.py", line 693, in _tag_root
    raise ParseError('while parsing %s:%s, somewhere inside\n%s' % (
odoo.tools.convert.ParseError: while parsing /home/odoo/src/enterprise/15.0/documents/data/documents_data.xml:265, somewhere inside
<record id="share_internal_folder" model="documents.share">
            <field name="name">Inbox Internal</field>
            <field name="alias_name">inbox</field>
            <field name="type">domain</field>
            <field name="folder_id" ref="documents_internal_folder"/>
            <field name="action">downloadupload</field>
            <field name="tag_ids" eval="[(6,0,[ref('documents_internal_status_inbox')])]"/>
            <field name="email_drop">True</field>
            <field name="activity_option">True</field>
            <field name="activity_type_id" ref="mail_documents_activity_data_Inbox"/>
            <field name="activity_date_deadline_range">0</field>
            <field name="activity_date_deadline_range_type">days</field>
        </record>
```

closes odoo/upgrade#3054

Signed-off-by: Christophe Simonis <chs@odoo.com>