[FIX] l10n_th: `l10n_th.acc_type_other` can be used
odoo/odoo@f2b4d98871051790c066b26031745868cc302c81
removes the type `acc_type_other`

According to the commit message:
```
Some l10n were creating a specific account type for the off balance
accounts, there is now a new account type defined for thsi in the
account module
```

In this case, `l10n_th`,
this "other" type is created,
but never referenced in any xml data file,
there is no account using it by default.

Meaning if this account type is used,
it can very well be used for other kind of accounts
than "Off balance" accounts.

So, if this type of account is used on an account
in a database, we better keep it than assigning the "off balance type
`data_account_off_sheet`, otherwise we might assign the off balance
type on an account which is not at all an off balance.

```
2020-07-17 21:51:23,935 1108 INFO template_0606f2bc225f_45461_13.0 odoo.modules.migration: module l10n_th: Running migration [>saas~12.5.2.0] pre-migrate
2020-07-17 21:51:25.779 UTC [1112] ERROR:  update or delete on table "account_account_type" violates foreign key constraint "account_account_user_type_id_fkey" on table "account_account"
2020-07-17 21:51:25.779 UTC [1112] DETAIL:  Key (id)=(19) is still referenced from table "account_account".
2020-07-17 21:51:25.779 UTC [1112] STATEMENT:  DELETE FROM "account_account_type" WHERE id=19
2020-07-17 21:51:25,779 1108 ERROR template_0606f2bc225f_45461_13.0 odoo.sql_db: bad query: DELETE FROM "account_account_type" WHERE id=19
ERROR: update or delete on table "account_account_type" violates foreign key constraint "account_account_user_type_id_fkey" on table "account_account"
DETAIL:  Key (id)=(19) is still referenced from table "account_account".

2020-07-17 21:51:25,782 1108 WARNING template_0606f2bc225f_45461_13.0 odoo.modules.loading: Transient module states were reset
2020-07-17 21:51:25,782 1108 ERROR template_0606f2bc225f_45461_13.0 odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/src/odoo/13.0/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/src/odoo/13.0/odoo/modules/loading.py", line 419, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/src/odoo/13.0/odoo/modules/loading.py", line 315, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/src/odoo/13.0/odoo/modules/loading.py", line 177, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/src/odoo/13.0/odoo/modules/migration.py", line 180, in migrate_module
    migrate(self.cr, installed_version)
  File "/src/odoo/13.0/odoo/addons/base/maintenance/migrations/l10n_th/saas~12.5.2.0/pre-migrate.py", line 18, in migrate
    util.remove_record(cr, "l10n_th.acc_type_other")
  File "/src/odoo/13.0/odoo/addons/base/maintenance/migrations/util.py", line 770, in remove_record
    cr.execute('DELETE FROM "%s" WHERE id=%%s' % table, (res_id,))
  File "/src/odoo/13.0/odoo/sql_db.py", line 168, in wrapper
    return f(self, *args, **kwargs)
  File "/src/odoo/13.0/odoo/sql_db.py", line 245, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.ForeignKeyViolation: update or delete on table "account_account_type" violates foreign key constraint "account_account_user_type_id_fkey" on table "account_account"
DETAIL:  Key (id)=(19) is still referenced from table "account_account".
```

Request 45461
M1812279383035

closes odoo/upgrade#1511

Signed-off-by: Denis Ledoux (dle) <dle@odoo.com>