[FIX] account_asset_ndt/15.0: allow to remove move lines related assets
1. Fixed TypeError: 'NoneType' object is not iterable

Add condition on filtered to return move lines which had credit and
debit both are zero and related move are in draft state.
on those case we are going to remove that move lines too.

on query
will get asset id and asset name but due to filter on move line
will get None in credit_move_lines and that will raise exception
when we extend that in
credit_line_ids using:
credit_line_ids.extend(res[2])

```
TGB:
https://upgrade.odoo.com/web#cids=1&menu_id=107&action=178&model=upgrade.request.traceback.group&view_type=form&id=1361

upg-17930007
upg-1789230

res result:
res>>>>>>>>>>>>>>>>>>> (101, 'P02020: HP LaserJet Enterprise MFP M283fdW Printer (CF066A)\nS/N: CNBRR3X2T9', None, None)

atp_1792592=> select credit, debit, id, move_id from account_move_line where id=302635;
 credit | debit |   id   | move_id
--------+-------+--------+---------
   0.00 |  0.00 | 302635 |   99351
(1 row)

atp_1792592=> select state,id,asset_Id from account_move where id=99351;
 state |  id   | asset_id
-------+-------+----------
 draft | 99351 |
(1 row)

Traceback (most recent call last):
  File "/home/odoo/src/odoo/15.0/odoo/service/server.py", line 1260, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/odoo/src/odoo/15.0/odoo/modules/registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/15.0/odoo/modules/loading.py", line 470, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/home/odoo/src/odoo/15.0/odoo/modules/loading.py", line 363, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/odoo/src/odoo/15.0/odoo/modules/loading.py", line 227, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/home/odoo/src/odoo/15.0/odoo/modules/migration.py", line 186, in migrate_module
    migrate(self.cr, installed_version)
  File "/tmp/tmpjofos0_t/migrations/account_asset_ndt/15.0.1.0/post-recompute.py", line 70, in migrate
    credit_line_ids.extend(res[2])
TypeError: 'NoneType' object is not iterable
```

2.
 after that also it's failed because there are
ome jounal items which contain redit = 0 and debit = 0
and related journal entry is in draft state.
that jounal items need to unlinked from assets.
so we got this error :

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/15.0/odoo/modules/registry.py", line 88, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/15.0/odoo/modules/loading.py", line 470, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/home/odoo/src/odoo/15.0/odoo/modules/loading.py", line 363, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/odoo/src/odoo/15.0/odoo/modules/loading.py", line 227, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/home/odoo/src/odoo/15.0/odoo/modules/migration.py", line 186, in migrate_module
    migrate(self.cr, installed_version)
  File "/tmp/tmp6_21xnqd/migrations/account_asset_ndt/15.0.1.0/post-recompute.py", line 133, in migrate
    util.recompute_fields(cr, "account.asset", ["non_deductible_tax_val"])
  File "/tmp/tmp6_21xnqd/migrations/util/orm.py", line 244, in wrapper
    return f(*args, **kwargs)
  File "/tmp/tmp6_21xnqd/migrations/util/orm.py", line 306, in recompute_fields
    flush(records)
  File "/tmp/tmp6_21xnqd/migrations/util/orm.py", line 210, in flush
    ((hasattr(records, "env") and getattr(records.env, "flush_all", None)) or getattr(records, "flush", lambda: None))()
  File "/home/odoo/src/odoo/15.0/odoo/models.py", line 5692, in flush
    self.recompute()
  File "/home/odoo/src/odoo/15.0/odoo/models.py", line 6165, in recompute
    process(field)
  File "/home/odoo/src/odoo/15.0/odoo/models.py", line 6149, in process
    field.recompute(recs)
  File "/home/odoo/src/odoo/15.0/odoo/fields.py", line 1273, in recompute
    self.compute_value(recs)
  File "/home/odoo/src/odoo/15.0/odoo/fields.py", line 1295, in compute_value
    records._compute_field_value(self)
  File "/home/odoo/src/odoo/15.0/addons/mail/models/mail_thread.py", line 411, in _compute_field_value
    return super()._compute_field_value(field)
  File "/home/odoo/src/odoo/15.0/odoo/models.py", line 4277, in _compute_field_value
    fields.determine(field.compute, self)
  File "/home/odoo/src/odoo/15.0/odoo/fields.py", line 88, in determine
    return needle(*args)
  File "/home/odoo/src/enterprise/15.0/account_asset_ndt/models/account_asset.py", line 26, in _compute_value
    super()._compute_value()
  File "/home/odoo/src/enterprise/15.0/account_asset/models/account_asset.py", line 133, in _compute_value
    record.original_value = self._get_related_purchase_value(record)
  File "/home/odoo/src/enterprise/15.0/account_asset/models/account_asset.py", line 172, in _get_related_purchase_value
    raise UserError(_("You cannot create an asset from lines containing credit and debit on the account or with a null amount"))

```

closes odoo/upgrade#6231

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>