[FIX] documents_account/saas~18.2:Link child actions to Invoicing group
Steps to reproduce
- Create the database in version 18.0 or 18.1
- Installed 'documents_account' module
- Upgrade the database with target 18.2
- In upgraded test database server action group should updated
  'Internal User' to 'Invoicing' and child actions should linked
  with 'Invoicing' group
```
[Code_changes](https://github.com/odoo/enterprise/commit/30968e831a92d4317025a2c312a273a0bd51f9a2#diff-c26d144753a74f985f04efb884127320104549e3f9207810dbb6676b60a89f2dR12)
[Old_code](https://github.com/odoo/enterprise/blob/saas-18.1/documents_account/data/ir_actions_server_data.xml#L6-L16)
We have created a new server action from https://github.com/odoo/upgrade/blob/master/migrations/base/saas~18.2.1.3/pre-ir_act_server.py#L52
but those server action need to liked with the Invoicing group

In upgraded test database, open the Finance document
and try to 'Create Vendor Bill'
facing the error
Traceback (most recent call last):
  File "/home/odoo/src/odoo/saas-18.2/odoo/http.py", line 2029, in _transactioning
    return service_model.retrying(func, env=self.env)
  File "/home/odoo/src/odoo/saas-18.2/odoo/service/model.py", line 161, in retrying
    result = func()
  File "/home/odoo/src/odoo/saas-18.2/odoo/http.py", line 1996, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/home/odoo/src/odoo/saas-18.2/odoo/http.py", line 2247, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/home/odoo/src/odoo/saas-18.2/odoo/addons/base/models/ir_http.py", line 340, in _dispatch
    result = endpoint(**request.params)
  File "/home/odoo/src/odoo/saas-18.2/odoo/http.py", line 758, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/home/odoo/src/odoo/saas-18.2/addons/web/controllers/dataset.py", line 29, in call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/saas-18.2/odoo/service/model.py", line 83, in call_kw
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/enterprise/saas-18.2/documents/models/documents_document.py", line 1230, in action_execute_embedded_action
    return self.env['ir.actions.server'].with_context(documents_active_ids=ids).browse(embedded_action.action_id.id).run()
  File "/home/odoo/src/odoo/saas-18.2/odoo/addons/base/models/ir_actions.py", line 1092, in run
    raise ServerActionWithWarningsError(_("Server action %(action_name)s has one or more warnings, address them first.", action_name=action.name))
odoo.addons.base.models.ir_actions.ServerActionWithWarningsError: Server action Create Vendor Bill has one or more warnings, address them first.

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    RPC_ERROR
        at makeErrorFromResponse (https://9.test.upgrade.odoo.com/web/assets/330f977/web.assets_web.min.js:2974:163)
        at XMLHttpRequest.<anonymous> (https://9.test.upgrade.odoo.com/web/assets/330f977/web.assets_web.min.js:2979:13)

```

closes odoo/upgrade#7768

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>