[FIX] base/16.0: fix html field BS5 convert crash if jsonb fields
When trying to convert 'html' fields context, in case at least 1 columns
if of type 'jsonb', the script will crash as follow:

2023-01-11 12:21:25,612 14344 ERROR openerp odoo.sql_db: bad query:
        SELECT id, "description"
          FROM event_booth_category
         WHERE ("description"->>'en_US' IS NOT NULL)
           AND ((((description ~ '\mclass\M\s*=' AND description ~ '\mr-|...
     AND event_booth_category.id IS NOT NULL
ERROR: operator does not exist: jsonb ~ unknown
LINE 5:            AND ((((description ~ '\mclass\M\s*=' AND descrip...

This commit adds proper field convertion (here `description->>'en_US')
so that `get_bs5_where_clause()` output a valid where clause

closes odoo/upgrade#4210

Signed-off-by: Christophe Simonis <chs@odoo.com>