[FIX] test_converter/saas~12.3: fix migration of test module
Avoid matt errors.
```
odoo.addons.base.maintenance.migrations.util.exceptions.MigrationError: 💥 It looks like you forgot to call `util.remove_field` on the following fields: test_converter.test_model.selection
```

closes odoo/upgrade#3719

See: odoo/odoo@a0e05e2ab9055fa060b1f3b5adf7aa322e2617fd
Signed-off-by: Christophe Simonis <chs@odoo.com>