[FIX] stock/7.saas~5.1.1: avoid ir_filters index constraint
While merging stock.picking.{in,out} into stock.picking we need to clear
the ir_filters (name,model,uid,action_id) unique constraint.

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/8.0/openerp/service/server.py", line 941, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/home/odoo/src/odoo/8.0/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/src/odoo/8.0/openerp/modules/loading.py", line 351, in load_modules
    force, status, report, loaded_modules, update_module)
  File "/home/odoo/src/odoo/8.0/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/odoo/src/odoo/8.0/openerp/modules/loading.py", line 142, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/home/odoo/src/odoo/8.0/openerp/modules/migration.py", line 171, in migrate_module
    migrate(self.cr, pkg.installed_version)
  File "/home/odoo/src/odoo/8.0/openerp/addons/base/maintenance/migrations/stock/7.saas~5.1.1/pre-10-nopicking-out-in.py", line 67, in migrate
    util.rename_model(cr, 'stock.picking.in', 'stock.picking', rename_table=False)
  File "/home/odoo/src/odoo/8.0/openerp/addons/base/maintenance/migrations/util.py", line 3551, in rename_model
    cr.execute(query, (new, old))
  File "/home/odoo/src/odoo/8.0/openerp/sql_db.py", line 171, in wrapper
    return f(self, *args, **kwargs)
  File "/home/odoo/src/odoo/8.0/openerp/sql_db.py", line 247, in execute
    res = self._obj.execute(query, params)
IntegrityError: duplicate key value violates unique constraint "ir_filters_name_model_uid_unique_action_index"
DETAIL:  Key (lower(name::text), model_id, COALESCE(user_id, '-1'::integer), COALESCE(action_id, '-1'::integer))=(openstaande leveringen, stock.picking, -1, -1) already exists.
```

upg-14143
opw-2526962