[FIX] base/saas~16.5: ignore invalid domains in attrs
Instead of failing the upgrade we log an error and ignore the invalid
domains (treat it as False).

```
...
  File "/home/odoo/src/odoo/17.0/odoo/osv/expression.py", line 235, in normalize_domain
    raise ValueError(f'Domain {domain} is syntactically not correct.')
ValueError: Domain ['|', '|', '|', ('state', '!=', <ast.Constant object at 0x7fdff6023ca0>), ('invoice_payment_term_id', '!=', <ast.Constant object at 0x7fdffa8d89d0>), ('type', 'not in', <ast.Tuple object at 0x7fdffa8da290>)] is syntactically not correct.
```

tbg-953
upg-1216648

closes odoo/upgrade#5531

Signed-off-by: Christophe Simonis (chs) <chs@odoo.com>