[FIX] payment_demo/saas~16.5: remove demo entry
In odoo/odoo#97047 the demo payment method was removed. Since there was
no explicit removal in the upgrade repo and tho records are noupdate=1
its xmlid remained.

This was OK until the re-introduction of the same xmlid with a different
meaning, in odoo/odoo#120446. Now it has payment.method as model, vs
the former account.payment.method. Having noupdate=1 prevents the
ORM from creating the right entry in ir_model_data, therefore the
former entry remains with wrong model.

```
...
 File "/tmp/tmpr63gk1tv/migrations/payment_demo/saas~16.5.2.0/post-migrate.py", line 7, in migrate
    util.update_record_from_xml(cr, "payment_demo.payment_method_demo", from_module="payment_demo")
  File "/tmp/tmpr63gk1tv/migrations/util/records.py", line 729, in update_record_from_xml
    __update_record_from_xml(
  File "/tmp/tmpr63gk1tv/migrations/util/records.py", line 864, in __update_record_from_xml
    importer.parse(new_root, **kw)
  File "/home/odoo/src/odoo/17.0/odoo/tools/convert.py", line 613, in parse
    self._tag_root(de)
  File "/home/odoo/src/odoo/17.0/odoo/tools/convert.py", line 556, in _tag_root
    f(rec)
  File "/home/odoo/src/odoo/17.0/odoo/tools/convert.py", line 567, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
odoo.tools.convert.ParseError: while parsing None:4
For external id payment_demo.payment_method_demo when trying to create/update a record of model payment.method found record of different model account.payment.method (21864)
```

closes odoo/upgrade#5641

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>