[FIX] mail/saas~15.1: enforce match record
Many saas DBs are failing the RR due to a missing xmlid. Since they are
come from the same template (kpmg-related) we add this generic fix.

```
...
  File "<decorator-gen-3>", line 2, in execute
  File "/home/odoo/src/odoo/saas-15.1/odoo/sql_db.py", line 90, in check
    return f(self, *args, **kwargs)
  File "/home/odoo/src/odoo/saas-15.1/odoo/sql_db.py", line 360, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "mail_channel_partner_partner_unique"
DETAIL:  Key (channel_id, partner_id)=(1, 3) already exists.
...
    raise ParseError('while parsing %s:%s, somewhere inside\n%s' % (
odoo.tools.convert.ParseError: while parsing /home/odoo/src/odoo/saas-15.1/addons/mail/data/mail_channel_data.xml:21, somewhere inside
<record model="mail.channel.partner" id="channel_partner_general_channel_for_admin">
            <field name="partner_id" ref="base.partner_admin"/>
            <field name="channel_id" ref="mail.channel_all_employees"/>
            <field name="fetched_message_id" ref="mail.module_install_notification"/>
            <field name="seen_message_id" ref="mail.module_install_notification"/>
        </record>
```

closes odoo/upgrade#3253

Signed-off-by: Christophe Simonis <chs@odoo.com>