[FIX] sale_subscription/saas~15.3: Fix respawn issue for custom M2M
Step to reproduce

1.create m2m field of ``sale.subscription.line`` from
studio with any table in 15.0 and migrate to 16.0
this traceback will raise
```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/16.0/odoo/modules/registry.py", line 90, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/16.0/odoo/modules/loading.py", line 619, in load_modules
    model._register_hook()
  File "/tmp/tmpoyxskllv/migrations/base/0.0.0/pre-models-ir_model_relation.py", line 48, in _register_hook
    raise util.MigrationError("The following m2m relations have respawn:\n%s" % back_m2m)
odoo.upgrade.util.exceptions.UpgradeError: The following m2m relations have respawn:
 - x_res_partner_sale_subscription_line_rel via sale.subscription.line
2024-02-26 06:20:05,142 26 CRITICAL test_testi_16.0 odoo.service.server: Failed to initialize database `test_testi_16.0`.
Traceback (most recent call last):
  File "/home/odoo/src/odoo/16.0/odoo/service/server.py", line 1299, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "<decorator-gen-16>", line 2, in new
  File "/home/odoo/src/odoo/16.0/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/16.0/odoo/modules/registry.py", line 90, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/16.0/odoo/modules/loading.py", line 619, in load_modules
    model._register_hook()
  File "/tmp/tmpoyxskllv/migrations/base/0.0.0/pre-models-ir_model_relation.py", line 48, in _register_hook
    raise util.MigrationError("The following m2m relations have respawn:\n%s" % back_m2m)
odoo.upgrade.util.exceptions.UpgradeError: The following m2m relations have respawn:
 - x_res_partner_sale_subscription_line_rel via sale.subscription.line
```

what is happening the model is removed early
so reference table is also got delete due to
that m2m tale got drop and all data transfer
to sale.order.line regarding this handling
[later]() and The m2M table again recreated
by orm because their is entry in ir_model_fields
which is correct.Due to this whole process custom
m2m table data lost and rasing the above mentioned
error and Their is remove_model script also present
in [end-migrate]().
So this part is wrong

before_fix
```
test_testi_16.0=> select * from x_res_partner_sale_subscription_line_rel;
 sale_subscription_line_id | res_partner_id
---------------------------+----------------
(0 rows)
```
after_fix
```
test_testi_16.0=> select * from x_res_partner_sale_subscription_line_rel;
 sale_subscription_line_id | res_partner_id
---------------------------+----------------
                        45 |             16
(1 row)
```

UPG-1377767
opw-3758441

closes odoo/upgrade#5737

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>