[FIX] base/saas~17.4: Don't init module `event_product`
The record `event_sale.product_product_event` has the noupdate flag and it's
moved to the new module `event_product`. The xmlid is renamed during the
upgrade.

Using the init mode might add an unwanted update of the record, which might
trigger validation errors.

upg-2095577
upg-1878961

```
odoo.tools.convert.ParseError: while parsing /home/odoo/src/odoo/saas-17.4/addons/event_product/data/event_product_data.xml:9
This product is already being used in posted Journal Entries.
If you want to change its Unit of Measure, please archive this product and create a new one.
```

closes odoo/upgrade#6483

Signed-off-by: Christophe Simonis (chs) <chs@odoo.com>