[FIX] product: during a month, `active` has been added on `product.supplierinfo` in 12.0 and saas-12.3
Added in odoo/odoo@5040c17e873b8476c754f1f3e1686c2a02b36e48
Removed in odoo/odoo@119f1a68278cde02a42b87bae0b267ba9bfcc1c3

See odoo/odoo#36471

The bugfix was added in 12.0, and ported to saas-12.3, but no further, it seems.

As databases in 12.0 and saas-12.3 can have the field in database,
and it no longer exists either in saas-12.3 or in 13.0,
the field must be removed during the upgrade to both
saas-12.3 and 13.0, hence the symlink.

```
odoo.addons.base.maintenance.migrations.util.MigrationError:  It looks like you forgot to call `util.remove_field` on the following fields: product.supplierinfo.active
```

Request 49786

closes odoo/upgrade#1454

Signed-off-by: Denis Ledoux (dle) <dle@odoo.com>