[FIX] base/14.0.1.3: sale_stock_margin implicit dependency
See for reference:
https://github.com/odoo/odoo/commit/e2dc415c46e5839173b26d1d19719aaed8dbba51

The module sale_stock_margin adds a dependency on `move_ids`, a field that is
added in module sale_stock but that it's not a explicit dependency.

Therefore, if the module sale_stock is uninstalled, since sale_stock_margin is
autoinstalled, an error will happen during the upgrade.

upg-44277
upg-93327

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/14.0/odoo/fields.py", line 635, in resolve_depends
    field = Model._fields[fname]
KeyError: 'move_ids'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/14.0/odoo/service/server.py", line 1199, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/odoo/src/odoo/14.0/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/src/odoo/14.0/odoo/modules/loading.py", line 461, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/home/odoo/src/odoo/14.0/odoo/modules/loading.py", line 349, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/odoo/src/odoo/14.0/odoo/modules/loading.py", line 279, in load_module_graph
    module.write({'state': 'installed', 'latest_version': ver})
  File "/home/odoo/src/odoo/14.0/addons/website/models/ir_module_module.py", line 92, in write
    return super(IrModuleModule, self).write(vals)
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 3687, in write
    self.modified(vals)
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 5777, in modified
    node = self.pool.field_triggers.get(self._fields[fname])
  File "/home/odoo/src/odoo/14.0/odoo/tools/func.py", line 26, in __get__
    value = self.fget(obj)
  File "/home/odoo/src/odoo/14.0/odoo/modules/registry.py", line 314, in field_triggers
    dependencies[field] = set(field.resolve_depends(self))
  File "/home/odoo/src/odoo/14.0/odoo/fields.py", line 638, in resolve_depends
    raise ValueError(msg % (self, fname, model_name))
ValueError: Field sale.order.line.purchase_price cannot find dependency 'move_ids' on model 'sale.order.line'.
```

closes odoo/upgrade#3146

Signed-off-by: Christophe Simonis <chs@odoo.com>