[FIX] account@{saas~12.4,saas~12.5}: `post_at_bank_rec` is removed in `saas-12.5`
https://github.com/odoo/odoo/blob/saas-12.4/addons/account/models/account.py#L610

This makes MATT fails.
```
Test upgrade the modules payment from saas~12.4 to saas~12.5

2020-09-07 11:19:08,763 40901 CRITICAL matt-payment odoo.service.server: Failed to initialize database `matt-payment`.
Traceback (most recent call last):
  File "/home/odoo/.local/share/Odoo/upgrade_ci/matt/odoo/saas-12.5/odoo/service/server.py", line 1146, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/odoo/.local/share/Odoo/upgrade_ci/matt/odoo/saas-12.5/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/.local/share/Odoo/upgrade_ci/matt/odoo/saas-12.5/odoo/modules/loading.py", line 454, in load_modules
    env['ir.model.data']._process_end(processed_modules)
  File "/home/odoo/.local/share/Odoo/upgrade_ci/matt/odoo/saas-12.5/odoo/addons/base/models/ir_model.py", line 1919, in _process_end
    record.unlink()
  File "/home/odoo/.local/share/Odoo/upgrade_ci/matt/odoo/saas-12.5/addons/mail/models/ir_model_fields.py", line 51, in unlink
    return super(IrModelField, self).unlink()
  File "/home/odoo/.local/share/Odoo/upgrade_ci/matt/odoo/saas-12.5/odoo/addons/base/maintenance/migrations/base/0.0.0/pre-models-ir_model.py", line 105, in unlink
    "💥 It looks like you forgot to call `util.remove_field` on the following fields: %s" % ", ".join(fields)
odoo.addons.base.maintenance.migrations.util.MigrationError: 💥 It looks like you forgot to call `util.remove_field` on the following fields: account.journal.post_at_bank_rec
```

closes odoo/upgrade#1743

Signed-off-by: Christophe Simonis <chs@odoo.com>