[FIX] account_reports_followup/9.0.1.0: fix conflict
The script
https://github.com/odoo/upgrade/blob/742e6573c9f571b8e15f55728f501a67cec8edc3/migrations/account_reports_followup/9.0.1.0/pre-10-rename-xid.py
which points to
https://github.com/odoo/upgrade/blob/742e6573c9f571b8e15f55728f501a67cec8edc3/migrations/account_followup/8.saas~6.1.0/pre-10-rename-xid.py
is in conflict with
https://github.com/odoo/upgrade/blob/742e6573c9f571b8e15f55728f501a67cec8edc3/migrations/base/9.0.1.3/pre-10-module-changes.py#L26

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/9.0/openerp/service/server.py", line 894, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/home/odoo/src/odoo/9.0/openerp/modules/registry.py", line 386, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/src/odoo/9.0/openerp/modules/loading.py", line 374, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/home/odoo/src/odoo/9.0/openerp/modules/loading.py", line 271, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/odoo/src/odoo/9.0/openerp/modules/loading.py", line 136, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/home/odoo/src/odoo/9.0/openerp/modules/migration.py", line 160, in migrate_module
    migrate(self.cr, installed_version)
  File "/home/odoo/src/odoo/9.0/openerp/addons/base/maintenance/migrations/account_reports_followup/9.0.1.0/pre-10-rename-xid.py", line 8, in migrate
    util.rename_xmlid(cr, *eb(module + ".view_account_followup_stat_{graph,pivot}"))
  File "/home/odoo/src/odoo/9.0/openerp/addons/base/maintenance/migrations/util/records.py", line 424, in rename_xmlid
    (new_module, new_name, old_module, old_name),
  File "/home/odoo/src/odoo/9.0/openerp/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/home/odoo/src/odoo/9.0/openerp/sql_db.py", line 233, in execute
    res = self._obj.execute(query, params)
IntegrityError: duplicate key value violates unique constraint "ir_model_data_module_name_uniq_index"
DETAIL:  Key (module, name)=(account_reports_followup, view_account_followup_stat_pivot) already exists.
```
The model of the views is also removed on
https://github.com/odoo/upgrade/blob/742e6573c9f571b8e15f55728f501a67cec8edc3/migrations/account_reports_followup/9.0.1.0/pre-20-models.py#L21

upg-21988

closes odoo/upgrade#2732

Signed-off-by: Christophe Simonis <chs@odoo.com>