[FIX] stock_account/11.0.1.1: cost_method also gets fifo
We need to set the default values for `cost_method` also.
https://github.com/odoo/odoo/blob/5b281c3cfbb0b8fc86c62171f321cde0fadfaf14/addons/stock_account/models/product.py#L30
with inverse `set_cost_method`
https://github.com/odoo/odoo/blob/5b281c3cfbb0b8fc86c62171f321cde0fadfaf14/addons/stock_account/models/product.py#L60-L70

```
22222_afu_14.0=> select * from ir_default where json_value='"real"'
+------+--------------+----------------------------+-------------+----------------------------+------------+-----------+--------------+-------------+--------------+
| id   | create_uid   | create_date                | write_uid   | write_date                 | field_id   | user_id   | company_id   | condition   | json_value   |
|------+--------------+----------------------------+-------------+----------------------------+------------+-----------+--------------+-------------+--------------|
| 12   | 1            | 2016-05-26 16:55:06.655162 | 1           | 2016-05-26 16:55:06.655162 | 14002      | <null>    | 1            | <null>      | "real"       |
+------+--------------+----------------------------+-------------+----------------------------+------------+-----------+--------------+-------------+--------------+
22222_afu_14.0=> SELECT id,model,name,ttype FROM ir_model_fields WHERE id=14002
+-------+------------------+-------------+---------+
| id    | model            | name        | ttype   |
|-------+------------------+-------------+---------|
| 14002 | product.template | cost_method | char    |
+-------+------------------+-------------+---------+
```

TB:
```
...
  File "/home/odoo/src/odoo/11.0/addons/stock_account/models/product.py", line 70, in _set_cost_method
    return self.write({'property_cost_method': self.cost_method})
  File "/home/odoo/src/odoo/11.0/addons/stock/models/product.py", line 546, in write
    return super(ProductTemplate, self).write(vals)
  File "/home/odoo/src/odoo/11.0/addons/product/models/product_template.py", line 325, in write
    res = super(ProductTemplate, self).write(vals)
  File "/home/odoo/src/odoo/11.0/addons/mail/models/mail_thread.py", line 283, in write
    result = super(MailThread, self).write(values)
  File "/home/odoo/src/odoo/11.0/addons/mail/models/mail_activity.py", line 369, in write
    return super(MailActivityMixin, self).write(vals)
  File "/home/odoo/src/odoo/11.0/addons/rating/models/rating.py", line 174, in write
    result = super(RatingMixin, self).write(values)
  File "/home/odoo/src/odoo/11.0/odoo/models.py", line 3182, in write
    record._convert_to_cache(new_vals, update=True)
  File "/home/odoo/src/odoo/11.0/odoo/models.py", line 4543, in _convert_to_cache
    for name, value in values.items()
  File "/home/odoo/src/odoo/11.0/odoo/models.py", line 4544, in <dictcomp>
    if name in fields
  File "/home/odoo/src/odoo/11.0/odoo/fields.py", line 1843, in convert_to_cache
    raise ValueError("Wrong value for %s: %r" % (self, value))
odoo.tools.convert.ParseError: "Wrong value for product.template.property_cost_method: 'real'" while parsing /home/odoo/src/odoo/11.0/addons/delivery/data/delivery_data.xml:4, near
<record id="product_product_delivery" model="product.product">
            <field name="name">Free delivery charges</field>
            <field name="default_code">Delivery</field>
            <field name="type">service</field>
            <field name="categ_id" ref="product.product_category_all"/>
            <field name="sale_ok" eval="False"/>
            <field name="purchase_ok" eval="False"/>
            <field name="list_price">0.0</field>
        </record>
```

upg-22222

closes odoo/upgrade#2735

Signed-off-by: Christophe Simonis <chs@odoo.com>