[FIX] sale_subscription/saas~15.3: cascade
Add cascade to drop all dependent objects.

```
2022-11-28 07:14:10,928 25 ERROR 418302_13.0_14.0_15.0_16.0 odoo.sql_db: bad query: DROP TABLE sale_subscription_template
ERROR: cannot drop table sale_subscription_template because other objects depend on it
DETAIL:  view gn_subscription_lines_v depends on constraint sale_subscription_template_pkey on table sale_subscription_template
view gn_mrr_details_v depends on view gn_subscription_lines_v
view gn_avg_mrr_detail_v depends on view gn_mrr_details_v
view gn_mrr_detail_aggr_v depends on view gn_mrr_details_v
view gn_pgs_details_v depends on view gn_subscription_lines_v
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
```

upg-418302

closes odoo/upgrade#4083

Signed-off-by: Christophe Simonis <chs@odoo.com>