[FIX] uom_uom/saas~1{4.5,5.1}: Add missing reference uom
After https://github.com/odoo/odoo/pull/57485 it was possible to leave a category
without a reference UoM. This was fixed with [this patch](https://github.com/odoo/odoo/commit/b1e328d369ce553bb14d0add127ff146cfce5e39).

It is possible then to have DBs with a missing reference uom, which will cause
an error while updating UoMs during the upgrade.

upg-290791
upg-155988

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/saas-15.2/odoo/service/server.py", line 1260, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "<decorator-gen-12>", line 2, in new
  File "/home/odoo/src/odoo/saas-15.2/odoo/tools/func.py", line 69, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/saas-15.2/odoo/modules/registry.py", line 88, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/saas-15.2/odoo/modules/loading.py", line 482, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/home/odoo/src/odoo/saas-15.2/odoo/modules/loading.py", line 371, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/odoo/src/odoo/saas-15.2/odoo/modules/loading.py", line 230, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/home/odoo/src/odoo/saas-15.2/odoo/modules/loading.py", line 71, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/home/odoo/src/odoo/saas-15.2/odoo/tools/convert.py", line 757, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/home/odoo/src/odoo/saas-15.2/odoo/tools/convert.py", line 823, in convert_xml_import
    obj.parse(doc.getroot())
  File "/home/odoo/src/odoo/saas-15.2/odoo/tools/convert.py", line 743, in parse
    self._tag_root(de)
  File "/home/odoo/src/odoo/saas-15.2/odoo/tools/convert.py", line 703, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
odoo.tools.convert.ParseError: while parsing /home/odoo/src/enterprise/saas-15.2/l10n_mx_edi_extended/data/product_data.xml:3
La categoría de UdM Unit debería tener una unidad de medida de referencia.

View error context:
'-no context-'
```

closes odoo/upgrade#3504

Signed-off-by: Christophe Simonis <chs@odoo.com>