[FIX] website/saas~14.5.1.0: Fix adapt contactus post script
Some databse upgrade fails because some contactus pages remain custom
or havn't been backuped

upg-369961
upg-369967
upg-369977
upg-369990
upg-369995
upg-369998
upg-370012
upg-370025

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/15.0/odoo/service/server.py", line 1260, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/odoo/src/odoo/15.0/odoo/modules/registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/15.0/odoo/modules/loading.py", line 470, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/home/odoo/src/odoo/15.0/odoo/modules/loading.py", line 363, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/odoo/src/odoo/15.0/odoo/modules/loading.py", line 227, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/home/odoo/src/odoo/15.0/odoo/modules/migration.py", line 180, in migrate_module
    migrate(self.cr, installed_version)
  File "/tmp/tmpwei84ufw/migrations/website/saas~14.5.1.0/post-define-contactus-details.py", line 63, in migrate
    set_value(nodes[0], partner.name)
IndexError: list index out of range
```

closes odoo/upgrade#3761

Signed-off-by: Christophe Simonis <chs@odoo.com>