[FIX] l10n_{mn,es}: syntax error when empty condition
[UPG-1184904](
https://upgrade.odoo.com/web#id=1184904&cids=1&menu_id=107&action=150&model=upgrade.request&view_type=form)

When no tax tags need to be migrated: (in this case `mod_303_61` is
disabled in a pre- script and thus not accounted for)

```SQL
pied@(none):pied_1184904> SELECT res_id, name FROM ir_model_data imd WHERE module = 'l
 10n_es' AND model = 'account.account.tag'
+--------+------------+
| res_id | name       |
|--------+------------|
| 58     | mod_303_61 |
+--------+------------+
```

The `IN` operator fails:

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/17.0/odoo/service/server.py", line 1302, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "<decorator-gen-16>", line 2, in new
  File "/home/odoo/src/odoo/17.0/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/17.0/odoo/modules/registry.py", line 113, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/17.0/odoo/modules/loading.py", line 476, in load_modules
    processed_modules += load_marked_modules(env, graph,
  File "/home/odoo/src/odoo/17.0/odoo/modules/loading.py", line 364, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/odoo/src/odoo/17.0/odoo/modules/loading.py", line 232, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/home/odoo/src/odoo/17.0/odoo/modules/migration.py", line 240, in migrate_module
    migrate(self.cr, installed_version)
  File "/tmp/tmpj89nxya7/migrations/l10n_es/saas~16.5.5.2/post-migrate.py", line 69, in migrate
    old_tag_ids = tag_migration_utils.migrate_tags_to_tax_tags_engine(cr, "l10n_es", tax_tag_changes)
  File "/tmp/tmpj89nxya7/migrations/l10n_mn/saas~16.5.1.1/post-migrate.py", line 81, in migrate_tags_to_tax_tags_engine
    cr.execute(
  File "/home/odoo/src/odoo/17.0/odoo/sql_db.py", line 332, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.SyntaxError: syntax error at or near ")"
LINE 6: ..._tag_invert AND tag_aml_rel.account_account_tag_id NOT IN ()
                                                                      ^
```

Use `ANY`, instead.

Part-of: odoo/upgrade#5463