[FIX] stock/saas~17.3: Change picking action context
PR https://github.com/odoo/odoo/pull/150360 changed the context, so
`allowed_company_ids` might not be accessible. The context from the actions
was changed accordingly, but if one of those actions gets modified through
Studio, it won't be updated when the module is loaded.

tbg-1542

```
ValueError: malformed node or string on line 1: <ast.Subscript object at 0x7f32535a6bf0>

During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "/tmp/tmplombdj90/migrations/base/tests/test_mock_crawl.py", line 256, in crawl_menu
    self.mock_action(action_vals)
   File "/tmp/tmplombdj90/migrations/base/tests/test_mock_crawl.py", line 272, in mock_action
    action = self.env[action["type"]].browse(action["id"]).run()
   File "/home/odoo/src/odoo/18.0/odoo/addons/base/models/ir_actions.py", line 991, in run
    res = runner(run_self, eval_context=eval_context)
   File "/home/odoo/src/odoo/18.0/odoo/addons/base/models/ir_actions.py", line 823, in _run_action_code_multi
    safe_eval(self.code.strip(), eval_context, mode="exec", nocopy=True, filename=str(self))  # nocopy allows to return 'action'
   File "/home/odoo/src/odoo/18.0/odoo/tools/safe_eval.py", line 403, in safe_eval
    raise ValueError('%r while evaluating\n%r' % (e, expr))
 ValueError: ValueError('malformed node or string on line 1: <ast.Subscript object at 0x7f32535a6bf0>') while evaluating
'action = model.get_action_picking_tree_incoming()'
```

closes odoo/upgrade#6883

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>