[FIX] base@tests: Crawler test, repr value for field filter for domain
Until to the introduction of `action_replenishment`
It looks like there were no `<field/>` filter for selection/char field
for which the default search value was set (through a server action in this case)

Use the `repr` format of the value instead of the `str` format
so the domain is correctly computed.

```
2020-08-04 11:06:26,917 22 ERROR 3759002-master-no-demo-all odoo.addons.base.maintenance.migrations.base.testsodoo.upgrade.base.tests.test_mock_crawl: Adding menu ('stock.menu_reordering_rules_replenish', 274, 'Inventory > Operations > Replenishment', 380) to the failing menus
Traceback (most recent call last):
  File "/data/build/odoo/odoo/tools/safe_eval.py", line 319, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
NameError: name 'manual' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/build/odoo/odoo/addons/base/maintenance/migrations/base/tests/test_mock_crawl.py", line 131, in crawl_menu
    self.mock_action(action_vals)
  File "/data/build/odoo/odoo/addons/base/maintenance/migrations/base/tests/test_mock_crawl.py", line 153, in mock_action
    return self.mock_action(action)
  File "/data/build/odoo/odoo/addons/base/maintenance/migrations/base/tests/test_mock_crawl.py", line 191, in mock_action
    domain, group_by = self.mock_view_search(model, view, action["domain"])
  File "/data/build/odoo/odoo/addons/base/maintenance/migrations/base/tests/test_mock_crawl.py", line 338, in mock_view_search
    domains = [self._safe_eval(domain) for domain in domains]
  File "/data/build/odoo/odoo/addons/base/maintenance/migrations/base/tests/test_mock_crawl.py", line 338, in <listcomp>
    domains = [self._safe_eval(domain) for domain in domains]
  File "/data/build/odoo/odoo/addons/base/maintenance/migrations/base/tests/test_mock_crawl.py", line 119, in _safe_eval
    return safe_eval(value, eval_context)
  File "/data/build/odoo/odoo/tools/safe_eval.py", line 335, in safe_eval
    raise ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr))
ValueError: <class 'NameError'>: "name 'manual' is not defined" while evaluating
"[('trigger', '=', manual)]"
```

closes odoo/upgrade#1549

Signed-off-by: Denis Ledoux (dle) <dle@odoo.com>