[FIX] sales_team/saas~14.2.1.1: create dummy team for admin
It may happen that there is no team with null company or for the
company of the admin user
```
48282_afu=> select id,company_id from crm_team
+------+--------------+
| id   | company_id   |
|------+--------------|
| 2    | 1            |
| 5    | 1            |
| 1    | 1            |
| 6    | 1            |
| 4    | 1            |
+------+--------------+
48282_afu=> select res_id from ir_model_data where name='user_admin' and module='base'
+----------+
| res_id   |
|----------|
| 2        |
+----------+
SELECT 1
Time: 0.065s
48282_afu=> select company_id from res_users where id=2
+--------------+
| company_id   |
|--------------|
| 2            |
+--------------+
```
In such cases this query
https://github.com/odoo/upgrade/blob/4509f840ad6ecf8ed917beecd7d3eba1893d33ef/migrations/sales_team/saas%7E14.2.1.1/pre-migrate.py#L92-L99
won't return anything, and thus the fetchone will fail
```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/15.0/odoo/service/server.py", line 1246, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/odoo/src/odoo/15.0/odoo/modules/registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/15.0/odoo/modules/loading.py", line 470, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/home/odoo/src/odoo/15.0/odoo/modules/loading.py", line 363, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/odoo/src/odoo/15.0/odoo/modules/loading.py", line 174, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/home/odoo/src/odoo/15.0/odoo/modules/migration.py", line 180, in migrate_module
    migrate(self.cr, installed_version)
  File "/tmp/tmpwd_s1aib/migrations/sales_team/saas~14.2.1.1/pre-migrate.py", line 103, in migrate
    team_id = cr.fetchone()[0]
TypeError: 'NoneType' object is not subscriptable
```

Here we create a dummy team just for the admin user to avoid issues.

upg-48282

closes odoo/upgrade#3083

Signed-off-by: Christophe Simonis <chs@odoo.com>