[FIX] sale_subscription/saas~15.3: fix SOL UOM inconsistencies
The upgrade request failed due to unit of measure inconsistencies in
sale.order.line. This was caused by the execution of recompute_fields in the
sale_subscription/saas~15.3.1.1/end-migrate.py script. To resolve the issue,
ensure that the verify_uom method from sale_subscription is called before
recompute_fields is executed.

In the saas-15.3 pre-version, all sale_subscription_line records are migrated
to sale_order_line, and the inconsistencies in this newly transfered records
cause the request to block.

To address this, the script was placed at the end of the sale_subscription
module in saas-15.3, just before recompute_fields is triggered. This ensures
that inconsistencies in those newly introduced sols are resolved.

upg-2592576, 2796907, 2755412, 2759474, 2793705, 2796907, 2841286, 2844532,
2887380

Traceback:

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/16.0/odoo/service/server.py", line 1323, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "<decorator-gen-16>", line 2, in new
  File "/home/odoo/src/odoo/16.0/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/16.0/odoo/modules/registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/16.0/odoo/modules/loading.py", line 524, in load_modules
    migrations.migrate_module(package, 'end')
  File "/home/odoo/src/odoo/16.0/odoo/modules/migration.py", line 189, in migrate_module
    migrate(self.cr, installed_version)
  File "/tmp/tmpdqr7ynhy/migrations/sale_subscription/saas~15.3.1.1/end-migrate.py", line 98, in migrate
    util.recompute_fields(
  File "/tmp/tmpdqr7ynhy/migrations/util/orm.py", line 248, in wrapper
    return f(*args, **kwargs)
  File "/tmp/tmpdqr7ynhy/migrations/util/orm.py", line 304, in recompute_fields
    recompute(records)
  File "/tmp/tmpdqr7ynhy/migrations/util/orm.py", line 218, in recompute
    (
  File "/home/odoo/src/odoo/16.0/odoo/api.py", line 741, in _recompute_all
    self[field.model_name]._recompute_field(field)
  File "/home/odoo/src/odoo/16.0/odoo/models.py", line 6301, in _recompute_field
    field.recompute(records)
  File "/home/odoo/src/odoo/16.0/odoo/fields.py", line 1382, in recompute
    apply_except_missing(self.compute_value, recs)
  File "/home/odoo/src/odoo/16.0/odoo/fields.py", line 1355, in apply_except_missing
    func(records)
  File "/home/odoo/src/odoo/16.0/odoo/fields.py", line 1404, in compute_value
    records._compute_field_value(self)
  File "/home/odoo/src/odoo/16.0/odoo/models.py", line 4259, in _compute_field_value
    fields.determine(field.compute, self)
  File "/home/odoo/src/odoo/16.0/odoo/fields.py", line 98, in determine
    return needle(*args)
  File "/home/odoo/src/enterprise/16.0/sale_subscription/models/sale_order_line.py", line 206, in _compute_qty_invoiced
    subscription_qty_invoiced = self._get_subscription_qty_invoiced()
  File "/home/odoo/src/enterprise/16.0/sale_subscription/models/sale_order_line.py", line 198, in _get_subscription_qty_invoiced
    qty_invoiced += line_sign * invoice_line.product_uom_id._compute_quantity(invoice_line.quantity, line.product_uom)
  File "/home/odoo/src/odoo/16.0/addons/uom/models/uom_uom.py", line 225, in _compute_quantity
    raise UserError(_('The unit of measure %s defined on the order line doesn\'t belong to the same category as the unit of measure %s defined on the product. Please correct the unit of measure defined on the order line or on the product, they should belong to the same category.') % (self.name, to_unit.name))
odoo.exceptions.UserError: L'unité de mesure Mois définie sur la ligne de commande n'appartient pas à la même catégorie que l'unité de mesure Units définie sur le produit. Veuillez corriger l'unité de mesure définie sur la ligne de commande ou sur le produit, elles doivent appartenir à la même catégorie.
```

closes odoo/upgrade#7746

Signed-off-by: Christophe Simonis (chs) <chs@odoo.com>