[FIX] account/16.0: add condition to adapter
This commit address a missing domain adaption for `user_type_id` during removal
of `account.account.type`

Domain:
```
["&", ("move_id.move_type","in",['out_refund', 'out_invoice']), ("account_id.user_type_id.id","=",13)]
["&", ("move_id.move_type","in",['out_refund', 'out_invoice']), ("account_id.user_type_id.id","in",[13,17])]
```

Before fix:
```
['&', ('move_id.move_type', 'in', ['out_refund', 'out_invoice']), ('account_id.account_type.id', '=', 'income')]
['&', ('move_id.move_type', 'in', ['out_refund', 'out_invoice']), ('account_id.account_type.id', 'in', ['income', 'expense_direct_cost'])]
```
error when domain eval:
```py
   File "/home/odoo/src/odoo/18.0/odoo/models.py", line 3106, in _condition_to_sql
    assert fname in self._fields, \
 AssertionError: Invalid field 'account_type.id' in domain term ('account_type.id', '=', 'income')
```

After fix:
```
['&', ('move_id.move_type', 'in', ['out_refund', 'out_invoice']), ('account_id.account_type', '=', 'income')]
['&', ('move_id.move_type', 'in', ['out_refund', 'out_invoice']), ('account_id.account_type', 'in', ['income', 'expense_direct_cost'])]
```

OPW - 4430734
UPG - 2402564

closes odoo/upgrade#7011

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>