[FIX] base/saas~14.5: avoid company address error
When the address format associated to the country of a company has
invalid fields the upgrade fails.

```
Traceback (most recent call last):
...
  File "/tmp/tmp9nl2lqgp/migrations/base/saas~14.5.1.3/end-migrate.py", line 18, in migrate
    company.company_details = env["base.document.layout"].with_company(company)._default_company_details()
  File "/home/odoo/src/odoo/15.0/addons/web/models/base_document_layout.py", line 44, in _default_company_details
    return Markup(nl2br(address_format)) % company_data
  File "/home/odoo/.odoo-venvs/15.0/lib/python3.8/site-packages/markupsafe/__init__.py", line 102, in __mod__
    return self.__class__(text_type.__mod__(self, arg))
  File "/home/odoo/.odoo-venvs/15.0/lib/python3.8/site-packages/markupsafe/__init__.py", line 301, in __getitem__
    return _MarkupEscapeHelper(self.obj[item], self.escape)
KeyError: 'province_name'
```

Here we propose to ignore the invalid fields and allow the upgrade to
continue.

upg-94541
upg-93972

closes odoo/upgrade#3153

Signed-off-by: Christophe Simonis <chs@odoo.com>