[FIX] l10n_mx_edi/saas~18.1: fallback for empty tuple
Empty tuple cannot be passed to `IN`, we cannot use `ANY` here
because we are adding parallel_filter(or explode_execute).

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/saas-18.1/odoo/service/server.py", line 1295, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "<decorator-gen-13>", line 2, in new
  File "/home/odoo/src/odoo/saas-18.1/odoo/tools/func.py", line 98, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/saas-18.1/odoo/orm/registry.py", line 143, in new
    load_modules(registry, force_demo, update_module=update_module)
  File "/home/odoo/src/odoo/saas-18.1/odoo/modules/loading.py", line 528, in load_modules
    processed_modules += load_marked_modules(
  File "/home/odoo/src/odoo/saas-18.1/odoo/modules/loading.py", line 405, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/odoo/src/odoo/saas-18.1/odoo/modules/loading.py", line 205, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/home/odoo/src/odoo/saas-18.1/odoo/modules/migration.py", line 263, in migrate_module
    mod.migrate(self.cr, installed_version)
  File "/tmp/tmp13m9a8qz/migrations/l10n_mx_edi/saas~18.1.0.3/pre-migrate.py", line 46, in migrate
    util.explode_execute(cr, query, table="account_move", alias="move")
  File "/tmp/tmp13m9a8qz/migrations/util/pg.py", line 379, in explode_execute
    return parallel_execute(
  File "/tmp/tmp13m9a8qz/migrations/util/pg.py", line 187, in parallel_execute
    return parallel_execute_impl(cr, queries, logger=_logger)
  File "/tmp/tmp13m9a8qz/migrations/util/pg.py", line 103, in _parallel_execute_threaded
    cr.execute(queries[0])
  File "/home/odoo/src/odoo/saas-18.1/odoo/sql_db.py", line 421, in execute
    self._obj.execute(query, params)
psycopg2.errors.SyntaxError: syntax error at or near ")"
LINE 8: ...                       OR move.invoice_payment_term_id IN ()
```

closes odoo/upgrade#7354

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>