[IMP] whatsapp/0.0.0: Remove match_uniq from whatsapp.template
Whatsapp templates have been marked with `forcecreate=0` in the enterprise
repo, so the `match_uniq` flag is not needed any more.

There could still be errors while using `_match_uniq` if one of the templates
had modified its attachments. That template would be matched to the proper xmlid
but it would still try to create and link the`header_attachment_ids` from the
data file, triggering an error:

```
odoo.tools.convert.ParseError: while parsing /home/odoo/src/enterprise/saas-17.4/whatsapp_pos/data/whatsapp_template_data.xml:10
You may only use one header attachment for each template
```

upg-2339460

closes odoo/upgrade#7393

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>