[FIX] base@10.saas~17: handle 'related' when preserving res.partner.fax
in ec465534d9fc8954b4a7ff4b7bfbd15da9afd732, we try to preserve the
'res.partner.fax' field by renaming it to 'x_fax'.
But we forgot to handle the 'related' field on res.users, leading to a
crash of the process:

File "/src/odoo/12.0/odoo/addons/base/maintenance/migrations/base/saas~11.3.1.3/end-models.py", line 17, in migrate
  env["ir.model.fields"].browse(ids)._compute_related_field_id()
File "/src/odoo/12.0/odoo/addons/base/models/ir_model.py", line 396, in _compute_related_field_id
  field = rec._related_field()
File "/src/odoo/12.0/odoo/addons/base/models/ir_model.py", line 449, in _related_field
  raise UserError(_("Unknown field name '%s' in related field '%s'") % (name, self.related))
odoo.exceptions.UserError: ("Unknown field name 'fax' in related field 'partner_id.fax'", '')

closes odoo/upgrade#744

Signed-off-by: Nicolas Seinlet (nse) <nse@odoo.com>