[IMP] base/saas~16.2.1.3: add uom check for failling module install
Starting from saas~16.2, `website_sale` now depends on `delivery`
module. When `website_sale` is installed but `delivery` is not,
`delivery` is automatically installed.

`delivery` add `sale.order.line.product_qty` field that have a compute
method `_compute_product_qty`. If some uom mismatch are found, the
compute fail and raise uom error.

tbg-845

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/saas-16.3/odoo/service/server.py", line 1302, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "<decorator-gen-14>", line 2, in new
  File "/home/odoo/src/odoo/saas-16.3/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/saas-16.3/odoo/modules/registry.py", line 90, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/saas-16.3/odoo/modules/loading.py", line 482, in load_modules
    processed_modules += load_marked_modules(env, graph,
  File "/home/odoo/src/odoo/saas-16.3/odoo/modules/loading.py", line 366, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/odoo/src/odoo/saas-16.3/odoo/modules/loading.py", line 205, in load_module_graph
    registry.init_models(env.cr, model_names, {'module': package.name}, new_install)
  File "/home/odoo/src/odoo/saas-16.3/odoo/modules/registry.py", line 538, in init_models
    func()
  File "/home/odoo/src/odoo/saas-16.3/odoo/addons/base/models/ir_model.py", line 1749, in _reflect_relation
    self.env.invalidate_all()
  File "/home/odoo/src/odoo/saas-16.3/odoo/api.py", line 696, in invalidate_all
    self.flush_all()
  File "/home/odoo/src/odoo/saas-16.3/odoo/api.py", line 706, in flush_all
    self._recompute_all()
  File "/home/odoo/src/odoo/saas-16.3/odoo/api.py", line 702, in _recompute_all
    self[field.model_name]._recompute_field(field)
  File "/home/odoo/src/odoo/saas-16.3/odoo/models.py", line 6386, in _recompute_field
    field.recompute(records)
  File "/home/odoo/src/odoo/saas-16.3/odoo/fields.py", line 1365, in recompute
    apply_except_missing(self.compute_value, recs)
  File "/home/odoo/src/odoo/saas-16.3/odoo/fields.py", line 1338, in apply_except_missing
    func(records)
  File "/home/odoo/src/odoo/saas-16.3/odoo/fields.py", line 1387, in compute_value
    records._compute_field_value(self)
  File "/home/odoo/src/odoo/saas-16.3/addons/sale/models/sale_order.py", line 1556, in _compute_field_value
    return super()._compute_field_value(field)
  File "/home/odoo/src/odoo/saas-16.3/addons/mail/models/mail_thread.py", line 396, in _compute_field_value
    return super()._compute_field_value(field)
  File "/home/odoo/src/odoo/saas-16.3/odoo/models.py", line 4491, in _compute_field_value
    fields.determine(field.compute, self)
  File "/home/odoo/src/odoo/saas-16.3/odoo/fields.py", line 99, in determine
    return needle(*args)
  File "/home/odoo/src/odoo/saas-16.3/addons/delivery/models/sale_order.py", line 143, in _compute_shipping_weight
    order.shipping_weight = order._get_estimated_weight()
  File "/home/odoo/src/odoo/saas-16.3/addons/delivery/models/sale_order.py", line 151, in _get_estimated_weight
    weight += order_line.product_qty * order_line.product_id.weight
  File "/home/odoo/src/odoo/saas-16.3/odoo/fields.py", line 1209, in __get__
    self.compute_value(recs)
  File "/home/odoo/src/odoo/saas-16.3/odoo/fields.py", line 1387, in compute_value
    records._compute_field_value(self)
  File "/home/odoo/src/odoo/saas-16.3/odoo/models.py", line 4491, in _compute_field_value
    fields.determine(field.compute, self)
  File "/home/odoo/src/odoo/saas-16.3/odoo/fields.py", line 99, in determine
    return needle(*args)
  File "/home/odoo/src/odoo/saas-16.3/addons/delivery/models/sale_order_line.py", line 24, in _compute_product_qty
    line.product_qty = line.product_uom._compute_quantity(
  File "/home/odoo/src/odoo/saas-16.3/addons/uom/models/uom_uom.py", line 214, in _compute_quantity
    raise UserError(_('The unit of measure %s defined on the order line doesn\'t belong to the same category as the unit of measure %s defined on the product. Please correct the unit of measure defined on the order line or on the product, they should belong to the same category.') % (self.name, to_unit.name))
odoo.exceptions.UserError: The unit of measure L defined on the order line doesn't belong to the same category as the unit of measure m defined on the product. Please correct the unit of measure defined on the order line or on the product, they should belong to the same category.
```

closes odoo/upgrade#5035

Signed-off-by: Christophe Simonis (chs) <chs@odoo.com>