[FIX] base/0.0.0: fix position anchor after comment in views fixer
Positioning a wrong element after a comment or any other special element
can cause issues since its tags are not strings.
```
>>> "//" + et.Comment("hi").tag
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    "//" + et.Comment("hi").tag
TypeError: can only concatenate str (not "cython_function_or_method") to str
```
Moreover it doesn't make sense to anchor elements after such special
items.

```
  File "/home/odoo/src/odoo/10.0/odoo/addons/base/maintenance/migrations/base/0.0.0/pre-models-ir_ui_view.py", line 235, in get_expr
    yield "//" + anchor.tag
TypeError: cannot concatenate 'str' and 'cython_function_or_method' objects
```
upg-1050904

closes odoo/upgrade#5022

Signed-off-by: Christophe Simonis (chs) <chs@odoo.com>