[FIX] helpdesk_sale_timesheet/saas~14.2.1.0: fix add compute
It seems that we need to compute also `sale_order_id`
It's not clear the relation between those fields since they are difined
here
https://github.com/odoo/enterprise/blob/8a42a50ead4da471486765cad5489a5c4bce1314/helpdesk_sale_timesheet/models/helpdesk.py#L33-L34
but also overridden here
https://github.com/odoo/enterprise/blob/8a42a50ead4da471486765cad5489a5c4bce1314/helpdesk_sale/models/helpdesk.py#L10

Moreover those TODO comments are rather confusing
https://github.com/odoo/enterprise/blob/75f46d784d93d923415fb803671adad41ca2bcdc/helpdesk_sale_timesheet/models/helpdesk.py#L35
https://github.com/odoo/enterprise/blob/75f46d784d93d923415fb803671adad41ca2bcdc/helpdesk_sale_timesheet/models/helpdesk.py#L232

The actual TB
```
 Traceback (most recent call last):
   File "/tmp/tmp5s7o_4d1/migrations/base/tests/test_mock_crawl.py", line 182, in crawl_menu
    self.mock_action(action_vals)
   File "/tmp/tmp5s7o_4d1/migrations/base/tests/test_mock_crawl.py", line 293, in mock_action
    mock_method(model, view, fields_list, domain, group_by)
   File "/tmp/tmp5s7o_4d1/migrations/base/tests/test_mock_crawl.py", line 319, in mock_view_form
    [data] = record.read(fields_list)
   File "/home/odoo/src/odoo/15.0/odoo/models.py", line 3227, in read
    return self._read_format(fnames=fields, load=load)
   File "/home/odoo/src/odoo/15.0/odoo/models.py", line 3247, in _read_format
    vals[name] = convert(record[name], record, use_name_get)
   File "/home/odoo/src/odoo/15.0/odoo/models.py", line 5867, in __getitem__
    return self._fields[key].__get__(self, type(self))
   File "/home/odoo/src/odoo/15.0/odoo/fields.py", line 1106, in __get__
    self.compute_value(recs)
   File "/home/odoo/src/odoo/15.0/odoo/fields.py", line 1265, in compute_value
    records._compute_field_value(self)
   File "/home/odoo/src/odoo/15.0/addons/sale_timesheet/models/sale_order.py", line 58, in _compute_field_value
    super()._compute_field_value(field)
   File "/home/odoo/src/odoo/15.0/addons/sale/models/sale_order.py", line 533, in _compute_field_value
    super()._compute_field_value(field)
   File "/home/odoo/src/odoo/15.0/addons/mail/models/mail_thread.py", line 410, in _compute_field_value
    return super()._compute_field_value(field)
   File "/home/odoo/src/odoo/15.0/odoo/models.py", line 4249, in _compute_field_value
    getattr(self, field.compute)()
   File "/home/odoo/src/enterprise/15.0/helpdesk_sale_timesheet/models/sale_order.py", line 22, in _compute_ticket_count
    mapped_data = dict((data['sale_order_id'][0], data['sale_order_id_count']) for data in ticket_data)
   File "/home/odoo/src/enterprise/15.0/helpdesk_sale_timesheet/models/sale_order.py", line 22, in <genexpr>
    mapped_data = dict((data['sale_order_id'][0], data['sale_order_id_count']) for data in ticket_data)
 TypeError: 'bool' object is not subscriptable
```

upg-41272

closes odoo/upgrade#2912

Signed-off-by: Christophe Simonis <chs@odoo.com>