[FIX] account_sepa_direct_debit/saas~13.3.1.0: psycopg out of mem
When fetching all the SEPA mandates psycopg may run out of memory.
Here we use the upgrade utility function that handles the
transformation with a server side cursor, hence avoiding the memory
issues.

```
Traceback (most recent call last):
...
  File "/tmp/tmpljy4xg2h/migrations/account_sepa_direct_debit/saas~13.3.1.0/pre-migrate.py", line 23, in migrate
    ''')
  File "<decorator-gen-3>", line 2, in execute
  File "/home/odoo/src/odoo/14.0/odoo/sql_db.py", line 101, in check
    return f(self, *args, **kwargs)
  File "/home/odoo/src/odoo/14.0/odoo/sql_db.py", line 298, in execute
    res = self._obj.execute(query, params)
psycopg2.DatabaseError: out of memory for query result
```
upg-9004

closes odoo/upgrade#2257

Signed-off-by: Christophe Simonis <chs@odoo.com>