[FIX] base/0.0.0/: xmlid_to_res_id is now private
Now it is `_xmlid_to_res_id` (note the extra _ in front)
See: odoo/odoo@c7bac3de

This breaks the restore of edited base views
```
Traceback (most recent call last):
  File "/tmp/tmpf6trq3b4/migrations/base/0.0.0/pre-models-ir_ui_view.py", line 695, in validate_view
    view._check_xml()
  File "/tmp/tmpf6trq3b4/migrations/base/0.0.0/pre-models-ir_ui_view.py", line 421, in _check_xml
    if not record._upgrade_fix_views(record):
  File "/tmp/tmpf6trq3b4/migrations/base/0.0.0/pre-models-ir_ui_view.py", line 556, in _upgrade_fix_views
    restore_from_file(self, md)
  File "/tmp/tmpf6trq3b4/migrations/base/0.0.0/pre-models-ir_ui_view.py", line 483, in restore_from_file
    view.arch_db = to_text(resolve_external_ids(arch_db, md.module).replace("%%", "%"))
  File "/tmp/tmpf6trq3b4/migrations/base/0.0.0/pre-models-ir_ui_view.py", line 462, in resolve_external_ids
    return re.sub(r"(?P<prefix>[^%])%\((?P<xmlid>.*?)\)[ds]", replacer, arch_fs)
  File "/usr/lib/python3.8/re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "/tmp/tmpf6trq3b4/migrations/base/0.0.0/pre-models-ir_ui_view.py", line 460, in replacer
    return m.group("prefix") + str(self.env["ir.model.data"].xmlid_to_res_id(xmlid))
AttributeError: 'ir.model.data' object has no attribute 'xmlid_to_res_id'
```

upg-424923

closes odoo/upgrade#4151

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>