[FIX] l10n_in/saas~17.5: change the account code according to standard
- As per our standard, the account code is 10058
  whenever we install the l10n_in module, we get the account code 100580.
  This occurs because, during the loading of template data, there is a check
  to ensure that the account code is 6 digit long. If it is not, a 0 is
  appended to the end of the account code.

- In this query, the xml_id of one of the record was renamed, in the condition
  they have used the code.

- So, during migration, this query was not executed, which caused an
  error: the xml_id 1_p10058 was not found.

OPW - 4375880
TBG - 1657

closes odoo/upgrade#6874

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>