[FIX] website_mass_mailing/18.0: update newsletter input form snippet
Newsletter input form snippet has been changed in v18 with new classes which
is required for the JS logic to handle the visibilty of subscribe or not.

As these newsletter snippet is used in many website pages which has been
created by end user, many instances of the snippet still use the old version
which lacks the required classes. After upgrading to `v18` a error message
pop-ups on pages where this snippets is used.

```
UncaughtPromiseError > TypeError

Uncaught Promise > Cannot read properties of null (reading 'classList')

Occured on localhost:8069 on 2024-12-10 08:35:46 GMT

TypeError: Cannot read properties of null (reading 'classList')
    at Class._updateSubscribeControlsStatus (http://localhost:8069/web/assets/1/6e6c0c6/web.assets_frontend_lazy.min.js:9444:866)
    at Class._updateView (http://localhost:8069/web/assets/1/6e6c0c6/web.assets_frontend_lazy.min.js:9444:355)
    at async Promise.all (index 1)
    at async Promise.all (index 0)
    at async Promise.all (index 73)
    at async Promise.all (index 1)
    at async Promise.all (index 1)
    at async createPublicRoot (http://localhost:8069/web/assets/1/6e6c0c6/web.assets_frontend_lazy.min.js:6157:1047)
```

Related commit: odoo/odoo@a1622ce

OPW - 4372680

closes odoo/upgrade#6904

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>