[FIX] saas_trial/16.0: fix modules kanban view
There is a conflict between `saas_trial.paid_apps_module_kanban`
https://github.com/odoo/internal/blob/2040235b239500ee9156e4e4322622ed7f99a925/trial/saas_trial/views/ir_module.xml#L34-L36
and `base_install_request.ir_module_module_view_kanban`
https://github.com/odoo/odoo/blob/6b101d5ff0ad78b9ae2ad312f362c2224e7af457/addons/base_install_request/views/ir_module_module_views.xml#L7-L11

We need to keep the button name, otherwise we get:
```
 ValueError: Element '<button name="button_immediate_install">' cannot be located in parent view
```

This issue blocks many RRs. The corresponding fix would be merged in
internal.

upg-473658

closes odoo/upgrade#4278

Signed-off-by: Christophe Simonis <chs@odoo.com>