[FIX] crm/8.saas~6.1.0: create model if does not exist in ir_model
When changing categories from a model to another, the upgrade crash
if the target model does not exist in the ir_model table.

Example Traceback:
```
2021-09-30 12:45:03,028 17 CRITICAL arg_36473_9.0 openerp.service.server: Failed to initialize database `arg_36473_9.0`.
Traceback (most recent call last):
  File "/home/odoo/src/odoo/9.0/openerp/service/server.py", line 894, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/home/odoo/src/odoo/9.0/openerp/modules/registry.py", line 386, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/src/odoo/9.0/openerp/modules/loading.py", line 374, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/home/odoo/src/odoo/9.0/openerp/modules/loading.py", line 271, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/odoo/src/odoo/9.0/openerp/modules/loading.py", line 136, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/home/odoo/src/odoo/9.0/openerp/modules/migration.py", line 160, in migrate_module
    migrate(self.cr, installed_version)
  File "/home/odoo/src/odoo/9.0/openerp/addons/base/maintenance/migrations/crm/8.saas~6.1.0/pre-10-adapt-models.py", line 107, in migrate
    _move_categ(cr, 'crm.lead', 'crm.lead.tag', {})
  File "/home/odoo/src/odoo/9.0/openerp/addons/base/maintenance/migrations/crm/8.saas~6.1.0/pre-10-adapt-models.py", line 33, in _move_categ
    util.replace_record_references(cr, ('crm.case.categ', o), (new_model, n))
  File "/home/odoo/src/odoo/9.0/openerp/addons/base/maintenance/migrations/util/records.py", line 698, in replace_record_references
    return replace_record_references_batch(cr, {old[1]: new[1]}, old[0], new[0], replace_xmlid)
  File "/home/odoo/src/odoo/9.0/openerp/addons/base/maintenance/migrations/util/records.py", line 808, in replace_record_references_batch
    model_dest_id = cr.fetchone()[0]
TypeError: 'NoneType' object has no attribute '__getitem__'
```

upg-36473
upg-40080

closes odoo/upgrade#2886

Signed-off-by: Christophe Simonis <chs@odoo.com>