[IMP] base/0.0.0: commit before analyze
It's unclear why there could be locked objects at the point when we
issue the ANALYZE command. In any case to avoid any potential pending
action from changes done by the ORM we now do a COMMIT.

```
2025-09-26 09:32:21,222 6606 INFO db_3146525 odoo.addons.base.maintenance.migrations.base.pre-10-create-idx-fk: Analyzing DB...
2025-09-26 09:32:51,745 6606 ERROR db_3146525 odoo.sql_db: bad query: ANALYZE
ERROR: canceling statement due to lock timeout

2025-09-26 09:32:51,748 6606 WARNING db_3146525 odoo.modules.loading: Transient module states were reset
2025-09-26 09:32:51,748 6606 ERROR db_3146525 odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/home/odoo/src/odoo/15.0/odoo/modules/registry.py", line 88, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/15.0/odoo/modules/loading.py", line 415, in load_modules
    loaded_modules, processed_modules = load_module_graph(
  File "/home/odoo/src/odoo/15.0/odoo/modules/loading.py", line 174, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/home/odoo/src/odoo/15.0/odoo/modules/migration.py", line 186, in migrate_module
    migrate(self.cr, installed_version)
  File "/tmp/tmp50bwl9kx/migrations/base/0.0.0/pre-10-create-idx-fk.py", line 30, in migrate
    cr.execute("ANALYZE")  # update statistics
  File "<decorator-gen-5>", line 2, in execute
  File "/home/odoo/src/odoo/15.0/odoo/sql_db.py", line 90, in check
    return f(self, *args, **kwargs)
  File "/home/odoo/src/odoo/15.0/odoo/sql_db.py", line 311, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.LockNotAvailable: canceling statement due to lock timeout
```

closes odoo/upgrade#8509

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>