[FIX] data_merge/15.0: update rule in end
Some rules may use models from yet to be loaded modules. This is an
outlier relevant for data_merge because some rules there apply to many
model.

In particular we get an error from here
https://github.com/odoo/enterprise/blob/2827a46b/data_merge/models/data_merge_record.py#L101
when the model in `r[0]` -- `crm.lead` in the example traceback below --
is not yet loaded. The issue is raised from
https://github.com/odoo/odoo/blob/2c49190615827a/odoo/addons/base/models/ir_rule.py#L79
that goes into `field.determine_domain` which for `company_id` ends up
on the `data.merge.record` line above.

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/15.0/odoo/service/server.py", line 1260, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/odoo/src/odoo/15.0/odoo/modules/registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/15.0/odoo/modules/loading.py", line 470, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/home/odoo/src/odoo/15.0/odoo/modules/loading.py", line 363, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/odoo/src/odoo/15.0/odoo/modules/loading.py", line 227, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/home/odoo/src/odoo/15.0/odoo/modules/migration.py", line 186, in migrate_module
    migrate(self.cr, installed_version)
  File "/tmp/tmphj7bylu2/migrations/data_merge/15.0.1.3/post-migrate-rule.py", line 5, in migrate
    util.if_unchanged(cr, "data_merge.data_merge_record_multi_company", util.update_record_from_xml)
  File "/tmp/tmphj7bylu2/migrations/util/records.py", line 461, in if_unchanged
    callback(cr, xmlid, **kwargs)
  File "/tmp/tmphj7bylu2/migrations/util/records.py", line 729, in update_record_from_xml
    __update_record_from_xml(
  File "/tmp/tmphj7bylu2/migrations/util/records.py", line 864, in __update_record_from_xml
    importer.parse(new_root, **kw)
  File "/home/odoo/src/odoo/15.0/odoo/tools/convert.py", line 734, in parse
    self._tag_root(de)
  File "/home/odoo/src/odoo/15.0/odoo/tools/convert.py", line 683, in _tag_root
    f(rec)
  File "/home/odoo/src/odoo/15.0/odoo/tools/convert.py", line 694, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
odoo.tools.convert.ParseError: while parsing None:4
Invalid domain: 'crm.lead'

View error context:
'-no context-'
```

upg-1261583
tbg-1014

closes odoo/upgrade#5624

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>