[FIX] website_sale/saas~16.5: Prevent duplicate cowed view
Due to duplicate cowed views with key```website_sale.extra_info```,
it throws below error while opening the Setting Application or
related website page.

```sql
Traceback (most recent call last):
  File "/home/odoo/src/odoo/saas-18.2/odoo/tools/cache.py", line 118, in lookup
    r = d[key]
  File "<decorator-gen-6>", line 2, in __getitem__
  File "/home/odoo/src/odoo/saas-18.2/odoo/tools/func.py", line 98, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/saas-18.2/odoo/tools/lru.py", line 33, in __getitem__
    a = self.d[obj]
KeyError: ('website', <function Website.is_view_active at 0x7efdad2b04c0>, 'website_sale.extra_info', 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/saas-18.2/odoo/orm/models.py", line 5499, in ensure_one
    _id, = self._ids
ValueError: too many values to unpack (expected 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/saas-18.2/odoo/http.py", line 2016, in _transactioning
    return service_model.retrying(func, env=self.env)
  File "/home/odoo/src/odoo/saas-18.2/odoo/service/model.py", line 161, in retrying
    result = func()
  File "/home/odoo/src/odoo/saas-18.2/odoo/http.py", line 1983, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/home/odoo/src/odoo/saas-18.2/odoo/http.py", line 2234, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/home/odoo/src/odoo/saas-18.2/odoo/addons/base/models/ir_http.py", line 340, in _dispatch
    result = endpoint(**request.params)
  File "/home/odoo/src/odoo/saas-18.2/odoo/http.py", line 745, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/home/odoo/src/odoo/saas-18.2/addons/web/controllers/dataset.py", line 29, in call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/saas-18.2/odoo/service/model.py", line 83, in call_kw
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/odoo/saas-18.2/addons/web/models/models.py", line 1559, in onchange
    snapshot1 = RecordSnapshot(record, fields_spec)
  File "/home/odoo/src/odoo/saas-18.2/addons/web/models/models.py", line 1645, in __init__
    self.fetch(name)
  File "/home/odoo/src/odoo/saas-18.2/addons/web/models/models.py", line 1660, in fetch
    self[field_name] = self.record[field_name]
  File "/home/odoo/src/odoo/saas-18.2/odoo/orm/models.py", line 6357, in __getitem__
    return self._fields[key].__get__(self)
  File "/home/odoo/src/odoo/saas-18.2/odoo/orm/fields.py", line 1370, in __get__
    self.recompute(record)
  File "/home/odoo/src/odoo/saas-18.2/odoo/orm/fields.py", line 1581, in recompute
    apply_except_missing(self.compute_value, recs)
  File "/home/odoo/src/odoo/saas-18.2/odoo/orm/fields.py", line 1554, in apply_except_missing
    func(records)
  File "/home/odoo/src/odoo/saas-18.2/odoo/orm/fields.py", line 1603, in compute_value
    records._compute_field_value(self)
  File "/home/odoo/src/odoo/saas-18.2/odoo/orm/models.py", line 4575, in _compute_field_value
    determine(field.compute, self)
  File "/home/odoo/src/odoo/saas-18.2/odoo/orm/fields.py", line 69, in determine
    return needle(*args)
  File "/home/odoo/src/odoo/saas-18.2/addons/website_sale/models/res_config_settings.py", line 115, in _compute_checkout_process_steps
    record.enabled_extra_checkout_step = website.is_view_active(
  File "<decorator-gen-100>", line 2, in is_view_active
  File "/home/odoo/src/odoo/saas-18.2/odoo/tools/cache.py", line 125, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/odoo/src/odoo/saas-18.2/addons/website/models/website.py", line 1478, in is_view_active
    return view.active if view else None
  File "/home/odoo/src/odoo/saas-18.2/odoo/orm/fields.py", line 1364, in __get__
    record.ensure_one()
  File "/home/odoo/src/odoo/saas-18.2/odoo/orm/models.py", line 5502, in ensure_one
    raise ValueError("Expected singleton: %s" % self)
ValueError: Expected singleton: ir.ui.view(6221, 3459)
```

Before fix
```sql

depr_2793372=> select id,name,website_id,key from ir_ui_view where website_id  is not null and key = 'website_sale.extra_info';
  id  |        name         | website_id |           key
------+---------------------+------------+-------------------------
 3459 | Checkout Extra Info |          1 | website_sale.extra_info
(1 row)

depr_2793372_upg=> select id,name,website_id,key from ir_ui_view where website_id is not null and key = 'website_sale.extra_info';
  id  |        name         | website_id |           key
------+---------------------+------------+-------------------------
 6221 | Checkout Extra Info |          1 | website_sale.extra_info
 3459 | Checkout Extra Info |          1 | website_sale.extra_info
(2 rows)

```

After fix

```sql
depr_2793372_saas~18.2=> select id,name,website_id,key from ir_ui_view where website_id is not null and key = 'website_sale.extra_info';
  id  |        name         | website_id |           key
------+---------------------+------------+-------------------------
 3459 | Checkout Extra Info |          1 | website_sale.extra_info
(1 row)

```

This commit ensure that a view with the new key(cowed_key) isn't already present
before attempting to insert a new one.
OPW-4788926
UPG-2793372

closes odoo/upgrade#7682

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>