[FIX] account_reports/11.0: allow addition of constraint
The data in stable was wrong, causing duplicated tags. The corresponding
bugfix in stable was never reflected into the upgrade scripts. Here we
correct that.

The fix is done in `account_reports` because once it loads the
constraint is never re-added later. By the time when l10n_fr_reports
it's already too late.

See odoo/enterprise@498a2d37f473e1baad35ea332e4addc558e1c906

Example error during the upgrade from 10 to 11 with `l10n_fr_reports`
installed:
```
ALTER TABLE "account_financial_html_report_line" ADD CONSTRAINT "account_financial_html_report_line_code_uniq" unique (code)
Traceback (most recent call last):
  File "/tmp/tmp5wt5g61a/odoo/11.0/odoo/tools/sql.py", line 132, in add_constraint
    cr.execute(query)
  File "/tmp/tmp5wt5g61a/odoo/11.0/odoo/sql_db.py", line 155, in wrapper
    return f(self, *args, **kwargs)
  File "/tmp/tmp5wt5g61a/odoo/11.0/odoo/sql_db.py", line 232, in execute
    res = self._obj.execute(query, params)
psycopg2.IntegrityError: could not create unique index "account_financial_html_report_line_code_uniq"
DETAIL:  Key (code)=(FRTAX77) is duplicated.
```

closes odoo/upgrade#7969

Signed-off-by: Christophe Simonis (chs) <chs@odoo.com>