[FIX] base@0.0.0: enable `res.partner` employee rule if disabled and private rule is enabled
Disabling the contact "employees" rule without disabling the contact "access to private address" rule
has as effect to restrict completely the read access to all contacts to all users.
Besides, even for users having the "Access to private addresses" rule, they can only see "private" contacts
That doesn't make sense, and this prevents the good use of the database, since any record which read
a field from a partner will raise an access error (if not read with sudo)

```
 Traceback (most recent call last):
   File "/tmp/tmpwbbkogfi/migrations/base/tests/test_mock_crawl.py", line 176, in crawl_menu
    self.mock_action(action_vals)
   File "/tmp/tmpwbbkogfi/migrations/base/tests/test_mock_crawl.py", line 267, in mock_action
    mock_method(model, view, fields_list, domain, group_by)
   File "/tmp/tmpwbbkogfi/migrations/base/tests/test_mock_crawl.py", line 293, in mock_view_form
    [data] = record.read(fields_list)
   File "/home/odoo/src/odoo/14.0/odoo/models.py", line 3016, in read
    return self._read_format(fnames=fields, load=load)
   File "/home/odoo/src/odoo/14.0/odoo/models.py", line 3036, in _read_format
    vals[name] = convert(record[name], record, use_name_get)
   File "/home/odoo/src/odoo/14.0/odoo/models.py", line 5662, in __getitem__
    return self._fields[key].__get__(self, type(self))
   File "/home/odoo/src/odoo/14.0/odoo/fields.py", line 2483, in __get__
    return super().__get__(records, owner)
   File "/home/odoo/src/odoo/14.0/odoo/fields.py", line 1021, in __get__
    self.compute_value(record)
   File "/home/odoo/src/odoo/14.0/odoo/fields.py", line 1175, in compute_value
    records._compute_field_value(self)
   File "/home/odoo/src/odoo/14.0/addons/mail/models/mail_thread.py", line 410, in _compute_field_value
    return super()._compute_field_value(field)
   File "/home/odoo/src/odoo/14.0/odoo/models.py", line 4057, in _compute_field_value
    getattr(self, field.compute)()
   File "/home/odoo/src/odoo/14.0/addons/payment/models/account_payment.py", line 35, in _compute_related_partners
    | p.partner_id.commercial_partner_id.child_ids
   File "/home/odoo/src/odoo/14.0/odoo/fields.py", line 2483, in __get__
    return super().__get__(records, owner)
   File "/home/odoo/src/odoo/14.0/odoo/fields.py", line 998, in __get__
    record._fetch_field(self)
   File "/home/odoo/src/odoo/14.0/odoo/models.py", line 3065, in _fetch_field
    self._read(fnames)
   File "/home/odoo/src/odoo/14.0/odoo/models.py", line 3176, in _read
    raise self.env['ir.rule']._make_access_error('read', forbidden)
 odoo.exceptions.AccessError: En raison de restrictions de sécurité, vous n'êtes pas autorisé à accéder aux enregistrements 'Contact' (res.partner).

Records: Laura Romero (id=30694)
Utilisateur : Stephen Labrosse (id=2)

Cette restriction est due aux règles suivantes:
- res.partner company
- res.partner.rule.private.group
```

Besides, there are specific scripts which go that way:
odoo/upgrade-specific@da6ef89498f4c5b5bd6df4c91d3cfa8dd2f8de2c
odoo/upgrade-specific@652d89f85500d24005a399f33a27d88a9a1722f3
odoo/migration-scripts@fdea9d46af166a3851f39e8e165fdd097d04e8ae
odoo/migration-scripts@7f91410bc860e553cbb4e32fbffe19cd4deb6e04

upg-17335
upg-19042
upg-19147
upg-19499
upg-20135
upg-20158
upg-20249

closes odoo/upgrade#2679

Signed-off-by: Christophe Simonis <chs@odoo.com>