[FIX] sale/0.0.0,saas~11.5: fixed wrong value state
1. `sale_onboarding_sample_quotation_state` field was selection field
in res.company from sale module introduced from saas~11.5.
see:
https://github.com/odoo/odoo/blob/e6c27216bee1198a76895496f2ea19e7466b8df5/addons/sale/models/res_company.py#L18
this selection field has three fixed value:
'not_done',
'just_done',
'done'.
but from generic script, it's add true/false value and that create
issues.

problem was on this assigned value:
https://github.com/odoo/upgrade/blob/dd927f88fd25a26b4b144ed606faf16c5fb7041e/migrations/sale/saas~11.5.1.1/pre-10-models.py#L30

we assigned :
```
sale_onboarding_sample_quotation_state=EXISTS(
                SELECT 1 FROM sale_order WHERE state='sent' AND company_id = c.id
            )
```
this will return true/false value.

because of this it will raise post upgrade issues for database migrated
from 16.0 to 17.0
because from saas~16.4, this field is deprecated and we have new model
`onboarding_onboarding_step` and inserting that value to
`current_state` field of this model from here our generic script:
https://github.com/odoo/upgrade/blob/dd927f88fd25a26b4b144ed606faf16c5fb7041e/migrations/onboarding/saas~16.4.1.2/pre-migrate.py#L115

as mostly issues are now from 16.0 to 17.0
fixed in saas-16.4 too.

unicorn task: 3856697

```
    result = endpoint(self, *args, **params_ok)
  File "/home/odoo/src/odoo/addons/onboarding/controllers/onboarding.py", line 29, in get_onboarding_data
    'onboarding.onboarding_panel', onboarding._prepare_rendering_values())
  File "/home/odoo/src/odoo/addons/account/models/onboarding_onboarding.py", line 24, in _prepare_rendering_values
    return super()._prepare_rendering_values()
  File "/home/odoo/src/odoo/addons/calendar/models/onboarding_onboarding.py", line 22, in _prepare_rendering_values
    return super()._prepare_rendering_values()
  File "/home/odoo/src/odoo/addons/onboarding/models/onboarding_onboarding.py", line 130, in _prepare_rendering_values
    'state': self.current_progress_id._get_and_update_onboarding_state(),
  File "/home/odoo/src/odoo/addons/onboarding/models/onboarding_progress.py", line 72, in _get_and_update_onboarding_state
    step_state = step.current_step_state
  File "/home/odoo/src/odoo/odoo/fields.py", line 1207, in __get__
    self.compute_value(recs)
  File "/home/odoo/src/odoo/odoo/fields.py", line 1389, in compute_value
    records._compute_field_value(self)
  File "/home/odoo/src/odoo/odoo/models.py", line 4869, in _compute_field_value
    fields.determine(field.compute, self)
  File "/home/odoo/src/odoo/odoo/fields.py", line 102, in determine
    return needle(*args)
  File "/home/odoo/src/odoo/addons/onboarding/models/onboarding_onboarding_step.py", line 60, in _compute_current_progress
    step.current_step_state = current_progress_step_id.step_state
  File "/home/odoo/src/odoo/odoo/fields.py", line 1302, in __set__
    self.write(protected_records, value)
  File "/home/odoo/src/odoo/odoo/fields.py", line 1121, in write
    cache_value = self.convert_to_cache(value, records)
  File "/home/odoo/src/odoo/odoo/fields.py", line 2826, in convert_to_cache
    raise ValueError("Wrong value for %s: %r" % (self, value))
ValueError: Wrong value for onboarding.onboarding.step.current_step_state: 'true'
```

closes odoo/upgrade#5942

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>