[FIX] mail/saas~16.2: remove field in manual models
Manual models inherit from mail.thread in a special way.
https://github.com/odoo/odoo/blob/faabaf798c70035b3faebad546d034bab268670a/addons/mail/models/ir_model.py#L91-L94
Thus manual models with mail_thread=True would inherit from mail and
when the missing field is remove the check is triggered:

```
  File "/tmp/tmpdlhktlo4/migrations/base/0.0.0/pre-models-no-model-data-delete.py", line 103, in _process_end
    return super(IrModelData, self)._process_end(modules)
  File "/home/odoo/src/odoo/saas-16.2/odoo/addons/base/models/ir_model.py", line 2315, in _process_end
    self._process_end_unlink_record(record)
  File "/home/odoo/src/odoo/saas-16.2/odoo/addons/base/models/ir_model.py", line 2244, in _process_end_unlink_record
    record.unlink()
  File "/tmp/tmpdlhktlo4/migrations/base/0.0.0/pre-models-ir_model.py", line 168, in unlink
    raise util.MigrationError(message)
odoo.upgrade.util.exceptions.MigrationError: 💥 It looks like you forgot to call `util.remove_field` on the following fields: x_workflows.message_main_attachment_id
```

upg-747388
tbg-606 (many more requests)

closes odoo/upgrade#4532

Signed-off-by: Nicolas Seinlet (nse) <nse@odoo.com>