[FIX] survey/7.saas~4.2.0: SleepyDeveloperError
model name is 'survey.survey' not 'survey_survey'
[Model](https://github.com/odoo/odoo/blob/saas-4/addons/survey/survey.py#L65)

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/8.0/openerp/service/server.py", line 941, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/home/odoo/src/odoo/8.0/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/src/odoo/8.0/openerp/modules/loading.py", line 351, in load_modules
    force, status, report, loaded_modules, update_module)
  File "/home/odoo/src/odoo/8.0/openerp/modules/loading.py", line 255, in load_marked_modules
    loaded, processed = load_module_graph(cr, graph, progressdict, report=report, skip_modules=loaded_modules, perform_checks=perform_checks)
  File "/home/odoo/src/odoo/8.0/openerp/modules/loading.py", line 183, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/home/odoo/src/odoo/8.0/openerp/modules/migration.py", line 171, in migrate_module
    migrate(self.cr, pkg.installed_version)
  File "/home/odoo/src/odoo/8.0/openerp/addons/base/maintenance/migrations/survey/7.saas~4.2.0/post-60-update_model.py", line 27, in migrate
    util.remove_field(cr, 'survey_survey', 'state')
  File "/home/odoo/src/odoo/8.0/openerp/addons/base/maintenance/migrations/util/fields.py", line 94, in remove_field
    _validate_model(model)
  File "/home/odoo/src/odoo/8.0/openerp/addons/base/maintenance/migrations/util/helpers.py", line 142, in _validate_model
    raise SleepyDeveloperError("`{}` seems to be a table name instead of model name".format(model))
SleepyDeveloperError: `survey_survey` seems to be a table name instead of model name
```
upg -1156650

closes odoo/upgrade#5336

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>