[FIX] account/18.3: Fix traceback on internal transfer
Step to Reproduce:-
1. Create db in 16.0 version with ``accountant`` module
   with l10n_mx localization.
2. Upgrade to odoo 18.0
3. Switch to ``ESCUELA KEMPER URGATE`` company or any company
  with localization
4. Open ``account`` module and navigate to ``Bank`` journal on
   Dashboard itself. After that create a new entry of statment
   and tap on that create ``Interanl Transfers`` for that
   statement
5. key error will raise as mentioned below.

Description:

For creating internal transfer it need ``account_id`` that fill
from reconcile model line and for standard record which were recently
created according to this commit
https://github.com/odoo/upgrade/commit/3cae0e0daf3dd26c6e5af6f5c4ebbd0fe5ad6ea3.
Due to missing of ``account_id`` on reconcile model line error is raised.

For fixing the traceback:

Adding default ``account_id`` in reconcile model line
according to this default
https://github.com/odoo/odoo/commit/71a423c427cf225c137f84be8e7621fdf94e2d15
for reconcile account.

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/18.0/odoo/http.py", line 2144, in _transactioning
    return service_model.retrying(func, env=self.env)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/18.0/odoo/service/model.py", line 156, in retrying
    result = func()
             ^^^^^^
  File "/home/odoo/src/odoo/18.0/odoo/http.py", line 2111, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/18.0/odoo/http.py", line 2359, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/18.0/odoo/addons/base/models/ir_http.py", line 333, in _dispatch
    result = endpoint(**request.params)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/18.0/odoo/http.py", line 754, in route_wrapper
    result = endpoint(self, *args, **params_ok)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/18.0/addons/web/controllers/dataset.py", line 36, in call_kw
    return call_kw(request.env[model], method, args, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/18.0/odoo/api.py", line 535, in call_kw
    result = getattr(recs, name)(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/18.0/addons/web/models/models.py", line 1005, in onchange
    record._apply_onchange_methods(field_name, result)
  File "/home/odoo/src/odoo/18.0/odoo/models.py", line 7379, in _apply_onchange_methods
    res = method(self)
          ^^^^^^^^^^^^
  File "/home/odoo/src/enterprise/18.0/account_accountant/models/bank_rec_widget.py", line 322, in _onchange_todo_command
    getattr(self, f'_js_action_{method_name}')(*todo_command.get('args', []), **todo_command.get('kwargs', {}))
  File "/home/odoo/src/enterprise/18.0/account_accountant/models/bank_rec_widget.py", line 1615, in _js_action_select_reconcile_model
    self._action_select_reconcile_model(reco_model)
  File "/home/odoo/src/enterprise/18.0/account_accountant/models/bank_rec_widget.py", line 1605, in _action_select_reconcile_model
    Command.create(self._lines_prepare_reco_model_write_off_vals(reco_model, x))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/enterprise/18.0/account_accountant/models/bank_rec_widget.py", line 942, in _lines_prepare_reco_model_write_off_vals
    'account_id': write_off_vals['account_id'],
                  ~~~~~~~~~~~~~~^^^^^^^^^^^^^^
KeyError: 'account_id'
```
UPG-3130362
OPW-5084008

closes odoo/upgrade#8506

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>