[FIX] project@saas~13.2: set tasks company to project company
In saas~11.3, `company_id` has been added on `project.project`
and it is required. Therefore, the upgrade script takes
care to assign a company on the project.
https://github.com/odoo/upgrade/blob/master/migrations/project/saas~11.3.1.1/pre-migrate.py#L10-L17

At that time, having a task with a company different than the project company
wasn't such a worry.

But nowadays, having a task having a company different than
its project company became a problem: it leads to access
error when reading task computed fields
It became mandatory with
https://github.com/odoo/odoo/commit/ac8c30beec072dd1f52735230eca86195bbeab7b#diff-9372fba6e4daf6d3cf93ee55ccaab6865ba4d99b7eb25a649cb2c1f4cb443c89R140

Therefore, it must be enforced tickets are in the same company
then their project company.

Besides, this is what the standard code is doing as well,
enforcing the task to have the same company then its
project:
https://github.com/odoo/odoo/commit/6716f47cceeb9f39e79ac337d1556d83d65f5e70#diff-dcdc6e8a2e65aff0582c53d72c3890c1b56725a8b9fcf7abbb0378097b5999afR646

In 14.0, in the interface at least, this is not possible to have a task in a company different than its project company.

```
2021-03-04 10:33:15,554 6583 INFO db_8863 odoo.addons.base.maintenance.migrations.base.testsodoo.upgrade.base.tests.test_mock_crawl: Mocking view form: project.task.form
2021-03-04 10:33:15,557 6583 INFO db_8863 odoo.addons.base.maintenance.migrations.base.testsodoo.upgrade.base.tests.test_mock_crawl: view_form, project.task(4638, 4258, 205), [('user_id', '=', 2)]
2021-03-04 10:33:15,668 6583 INFO db_8863 odoo.addons.base.models.ir_rule: Access Denied by record rules for operation: read on record ids: [528], uid: 2, model: account.analytic.account
2021-03-04 10:33:15,684 6583 INFO db_8863 odoo.addons.base.models.ir_rule: Access Denied by record rules for operation: read on record ids: [528], uid: 2, model: account.analytic.account
2021-03-04 10:33:15,691 6583 INFO db_8863 odoo.addons.base.models.ir_rule: Access Denied by record rules for operation: read on record ids: [528], uid: 2, model: account.analytic.account
2021-03-04 10:33:15,696 6583 INFO db_8863 odoo.addons.base.models.ir_rule: Access Denied by record rules for operation: read on record ids: [528], uid: 2, model: account.analytic.account
2021-03-04 10:33:15,706 6583 ERROR db_8863 odoo.addons.base.maintenance.migrations.base.testsodoo.upgrade.base.tests.test_mock_crawl: Adding menu ('project.menu_project_management', 225, 'Project > Tasks', 821) to the failing menus
Traceback (most recent call last):
    File "/tmp/tmp_v2qs13z/migrations/base/tests/test_mock_crawl.py", line 155, in crawl_menu
    self.mock_action(action_vals)
    File "/tmp/tmp_v2qs13z/migrations/base/tests/test_mock_crawl.py", line 234, in mock_action
    mock_method(model, view, fields_list, domain, group_by)
    File "/tmp/tmp_v2qs13z/migrations/base/tests/test_mock_crawl.py", line 260, in mock_view_form
    [data] = record.read(fields_list)
    File "/home/odoo/src/odoo/14.0/odoo/models.py", line 3023, in read
    return self._read_format(fnames=fields, load=load)
    File "/home/odoo/src/odoo/14.0/odoo/models.py", line 3043, in _read_format
    vals[name] = convert(record[name], record, use_name_get)
    File "/home/odoo/src/odoo/14.0/odoo/models.py", line 5664, in __getitem__
    return self._fields[key].__get__(self, type(self))
    File "/home/odoo/src/odoo/14.0/odoo/fields.py", line 1021, in __get__
    self.compute_value(record)
    File "/home/odoo/src/odoo/14.0/odoo/fields.py", line 1175, in compute_value
    records._compute_field_value(self)
    File "/home/odoo/src/odoo/14.0/addons/base_automation/models/base_automation.py", line 362, in _compute_field_value
    return _compute_field_value.origin(self, field)
    File "/home/odoo/src/odoo/14.0/addons/mail/models/mail_thread.py", line 410, in _compute_field_value
    return super()._compute_field_value(field)
    File "/home/odoo/src/odoo/14.0/odoo/models.py", line 4059, in _compute_field_value
    getattr(self, field.compute)()
    File "/home/odoo/src/odoo/14.0/addons/sale_timesheet/models/project.py", line 281, in _compute_analytic_account_active
    super()._compute_analytic_account_active()
    File "/home/odoo/src/odoo/14.0/addons/hr_timesheet/models/project.py", line 127, in _compute_analytic_account_active
    task.analytic_account_active = task.project_id.analytic_account_id.active
    File "/home/odoo/src/odoo/14.0/odoo/fields.py", line 998, in __get__
    record._fetch_field(self)
    File "/home/odoo/src/odoo/14.0/odoo/models.py", line 3072, in _fetch_field
    self._read(fnames)
    File "/home/odoo/src/odoo/14.0/odoo/models.py", line 3183, in _read
    raise self.env['ir.rule']._make_access_error('read', forbidden)
odoo.exceptions.AccessError: En raison de restrictions de sécurité, vous n'êtes pas autorisé à accéder aux enregistrements 'Analytic Account' (account.analytic.account).

Records: Stat-Bio07: PRO/20/185 - Meded Corpus (id=528)
Utilisateur : Anthony PERRUSSEL (id=2)

Cette restriction est due aux règles suivantes:
- Analytic multi company rule

Note : ce pourrait être un problème de multi-société.
```

upg-8863

closes odoo/upgrade#2251

Signed-off-by: Christophe Simonis <chs@odoo.com>