[FIX] base@0.0.0: set no_model_data_delete to always for res.lang
`delete_unused` doesn't handle the indirect references of the.
`lang` case which refer to the `lang` using the `code` column
and no the `id`.
Therefore, it was allowing the deletion of the lang even
if it was used, for instance in the `lang` of `res.partner`
records.

```
2021-07-21 23:30:36,542 24 CRITICAL db_19998 odoo.addons.base.maintenance.migrations.base.pre-models-no-model-data-delete: It looks like you forgot to call `util.delete_unused` on base.lang_es_HN,base.lang_es_SV,base.lang_es_NI
```

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/11.0/odoo/service/server.py", line 1054, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/odoo/src/odoo/11.0/odoo/modules/registry.py", line 85, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/src/odoo/11.0/odoo/modules/loading.py", line 487, in load_modules
    model._register_hook()
  File "/home/odoo/src/odoo/11.0/odoo/addons/base/maintenance/migrations/mail/0.0.0/pre-report-migration.py", line 27, in _register_hook
    util.announce_migration_report(self.env.cr)
  File "/home/odoo/src/odoo/11.0/odoo/addons/base/maintenance/migrations/util/report.py", line 78, in announce_migration_report
    admin_channel = get_admin_channel(cr)
  File "/home/odoo/src/odoo/11.0/odoo/addons/base/maintenance/migrations/util/orm.py", line 69, in get_admin_channel
    "group_ids": [(6, 0, [admin_group.id])],
  File "/home/odoo/src/odoo/11.0/addons/mail/models/mail_channel.py", line 145, in create
    ).create(vals)
  File "/home/odoo/src/odoo/11.0/addons/mail/models/mail_thread.py", line 254, in create
    track_thread = thread.with_context(lang=self.env.user.lang)
  File "/home/odoo/src/odoo/11.0/odoo/fields.py", line 959, in __get__
    self.determine_value(record)
  File "/home/odoo/src/odoo/11.0/odoo/fields.py", line 1072, in determine_value
    self.compute_value(recs)
  File "/home/odoo/src/odoo/11.0/odoo/fields.py", line 1026, in compute_value
    self._compute_value(records)
  File "/home/odoo/src/odoo/11.0/odoo/fields.py", line 1019, in _compute_value
    self.compute(records)
  File "/home/odoo/src/odoo/11.0/odoo/fields.py", line 591, in _compute_related
    record[self.name] = value[self.related_field.name]
  File "/home/odoo/src/odoo/11.0/odoo/models.py", line 4858, in __setitem__
    return self._fields[key].__set__(self, value)
  File "/home/odoo/src/odoo/11.0/odoo/fields.py", line 977, in __set__
    value = self.convert_to_cache(value, record)
  File "/home/odoo/src/odoo/11.0/odoo/fields.py", line 1843, in convert_to_cache
    raise ValueError("Wrong value for %s: %r" % (self, value))
ValueError: Wrong value for res.users.lang: 'es_HN'
```

upg-19884
upg-19994
upg-19995
upg-19996
upg-19997
upg-19998
upg-19999

closes odoo/upgrade#2662

Signed-off-by: Denis Ledoux (dle) <dle@odoo.com>