[FIX] payment*/saas~16.5: ensure correct update of xmlids
The `code` of payment providers is defined in their dedicated modules.
If for some reason the code is not set properly -- those record are
noupdate since various versions already -- then the deduplication
mechanism doesn't work. This leads to errors and inconsistencies during
the upgrade.

Here we ensure that all records are updated from both `payment` and
their dedicated modules.

This avoids a nasty issue happening only for production upgrades. Since
the neutralization script `addons/payment/data/neutralize.sql` will set
the state to `disabled` for all providers during test upgrades, this
hides some failure cases that trigger only if the provider are not
disabled.

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/17.0/odoo/service/server.py", line 1302, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "<decorator-gen-16>", line 2, in new
  File "/home/odoo/src/odoo/17.0/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/17.0/odoo/modules/registry.py", line 113, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/17.0/odoo/modules/loading.py", line 514, in load_modules
    migrations.migrate_module(package, 'end')
  File "/home/odoo/src/odoo/17.0/odoo/modules/migration.py", line 240, in migrate_module
    migrate(self.cr, installed_version)
  File "/tmp/tmp741i130v/migrations/payment/saas~16.5.2.0/end-migrate.py", line 8, in migrate
    providers._activate_default_pms()
  File "/home/odoo/src/odoo/17.0/addons/payment/models/payment_provider.py", line 407, in _activate_default_pms
    (pms + pms.brand_ids).filtered(lambda pm: pm.code in pm_codes).active = True
  File "/home/odoo/src/odoo/17.0/odoo/fields.py", line 1322, in __set__
    records.write({self.name: write_value})
  File "/home/odoo/src/odoo/17.0/addons/payment/models/payment_method.py", line 177, in write
    raise UserError(_(
odoo.exceptions.UserError: Ce mode de paiement a besoin d'un complice ; vous devez d'abord activer un fournisseur de paiement prenant en charge ce mode de paiement.
```

On this example the standard Stripe provider has code `none`
```
1329295_afu=> select id,name,code from payment_provider where code='stripe' or id=18
+----+----------------------------------------+--------+
| id | name                                   | code   |
|----+----------------------------------------+--------|
| 16 | {"en_US": "Stripe", "fr_FR": "Stripe"} | stripe |
| 18 | {"en_US": "Stripe", "fr_FR": "Stripe"} | none   |
+----+----------------------------------------+--------+
1329295_afu=> select * from ir_model_data where model='payment.provider' and res_id in (16,18)
+-------+------------+--------------------------+--------------------------+-----------+--------+----------+-------------------------+---------+------------------+
| id    | create_uid | create_date              | write_date               | write_uid | res_id | noupdate | name                    | module  | model            |
|-------+------------+--------------------------+--------------------------+-----------+--------+----------+-------------------------+---------+------------------|
| 37523 | <null>     | 2023-04-29 13:18:48.6811 | 2023-04-29 13:18:48.6811 | <null>    | 18     | True     | payment_provider_stripe | payment | payment.provider |
+-------+------------+--------------------------+--------------------------+-----------+--------+----------+-------------------------+---------+------------------+
```

Part-of: odoo/upgrade#5688