[FIX] base/0.0.0: check view is standard and arch from file
Trying to restore a view just because it has an xmlid and arch_fs set
was not correct. It later lead to an error in `restore_from_file`
because `arch_db` is None.
```
Traceback (most recent call last):
  File "/tmp/tmp1feakvdv/migrations/base/0.0.0/pre-models-ir_ui_view.py", line 643, in validate_view
    view._check_xml()
  File "/tmp/tmp1feakvdv/migrations/base/0.0.0/pre-models-ir_ui_view.py", line 403, in _check_xml
    if not record._upgrade_fix_views(record):
  File "/tmp/tmp1feakvdv/migrations/base/0.0.0/pre-models-ir_ui_view.py", line 523, in _upgrade_fix_views
    restore_from_file(self, md)
  File "/tmp/tmp1feakvdv/migrations/base/0.0.0/pre-models-ir_ui_view.py", line 461, in restore_from_file
    view.arch_db = to_text(resolve_external_ids(arch_db, md.module).replace("%%", "%"))
  File "/tmp/tmp1feakvdv/migrations/base/0.0.0/pre-models-ir_ui_view.py", line 444, in resolve_external_ids
    return re.sub(r"(?P<prefix>[^%])%\((?P<xmlid>.*?)\)[ds]", replacer, arch_fs)
  File "/usr/lib/python3.8/re.py", line 210, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object
```

Here we avoid both errors:
1. We check that the view is actually coming from a standard module.
2. We check that we are able to recover the arch from the file.

upg-420877

Part-of: odoo/upgrade#4112