[FIX] stock@saas~12.5: multi-company `stock.quant.package`
A multi-company record rule has been added to `stock.quant.package`:
https://github.com/odoo/odoo/commit/a5b6f31cf28e5381e1c85f66730bcdb55998e643#diff-c9c621ea1107cebd485855984cf2b5f52107f449788b48313383e2b9ba9798bfR161

If `company_id` is not set up on the quant packages,
this can result on an access error
when having a package using a product from a different company

```
Traceback (most recent call last):
  File "/tmp/tmpmlg9keo6/migrations/base/tests/test_mock_crawl.py", line 155, in crawl_menu
    self.mock_action(action_vals)
  File "/tmp/tmpmlg9keo6/migrations/base/tests/test_mock_crawl.py", line 234, in mock_action
    mock_method(model, view, fields_list, domain, group_by)
  File "/tmp/tmpmlg9keo6/migrations/base/tests/test_mock_crawl.py", line 260, in mock_view_form
    [data] = record.read(fields_list)
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 3023, in read
    return self._read_format(fnames=fields, load=load)
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 3043, in _read_format
    vals[name] = convert(record[name], record, use_name_get)
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 5664, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/odoo/src/odoo/14.0/odoo/fields.py", line 1021, in __get__
    self.compute_value(record)
  File "/home/odoo/src/odoo/14.0/odoo/fields.py", line 1175, in compute_value
    records._compute_field_value(self)
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 4059, in _compute_field_value
    getattr(self, field.compute)()
  File "/home/odoo/src/odoo/14.0/addons/delivery/models/stock_picking.py", line 29, in _compute_weight
    weight += quant.quantity * quant.product_id.weight
  File "/home/odoo/src/odoo/14.0/odoo/fields.py", line 998, in __get__
    record._fetch_field(self)
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 3072, in _fetch_field
    self._read(fnames)
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 3183, in _read
    raise self.env['ir.rule']._make_access_error('read', forbidden)
odoo.exceptions.AccessError: Due to security restrictions, you are not allowed to access 'Product' (product.product) records.

Records: Hand Sanitizer - 30 ML (Box of 200) (id=2216)
User: Angelina Garcia (id=2)
```

upg-8604