[FIX] website/saas~17.3: remove website_id for internal user
when a user becomes an internal user and they have a website id
the  website id was kept which restricted
the user to sign in with one website. When an internal user has a
website id, they can't sign in with another website. This restriction
only makes sense for portal users and it confused odoo customers (we had
support tickets about that) so we decided to prevent having a website
id for internal users.

so to make upgrade successfull remove website reference from internal
user

see:
https://github.com/odoo/odoo/commit/479e8d0cae98f7e086e5fb4a0ca4e33ed24bfc12

upg-1919003

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/saas-17.4/odoo/service/server.py", line 1302, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "<decorator-gen-16>", line 2, in new
  File "/home/odoo/src/odoo/saas-17.4/odoo/tools/func.py", line 84, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/saas-17.4/odoo/modules/registry.py", line 124, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/saas-17.4/odoo/modules/loading.py", line 480, in load_modules
    processed_modules += load_marked_modules(env, graph,
  File "/home/odoo/src/odoo/saas-17.4/odoo/modules/loading.py", line 364, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/odoo/src/odoo/saas-17.4/odoo/modules/loading.py", line 227, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "/home/odoo/src/odoo/saas-17.4/odoo/modules/loading.py", line 71, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "/home/odoo/src/odoo/saas-17.4/odoo/tools/convert.py", line 630, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "/home/odoo/src/odoo/saas-17.4/odoo/tools/convert.py", line 701, in convert_xml_import
    obj.parse(doc.getroot())
  File "/home/odoo/src/odoo/saas-17.4/odoo/tools/convert.py", line 616, in parse
    self._tag_root(de)
  File "/home/odoo/src/odoo/saas-17.4/odoo/tools/convert.py", line 570, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
odoo.tools.convert.ParseError: while parsing /home/odoo/src/enterprise/saas-17.4/accountant/security/accounting_security.xml:7
Elimine el sitio web del contacto relacionado antes de que se convierta en usuario interno.
```

closes odoo/upgrade#6405

Signed-off-by: Christophe Simonis (chs) <chs@odoo.com>