[FIX] account@saas~12.4: remove `account_voucher` views
Remove views from deleted file
`addons/account_voucher/views/account_voucher_views.xml`

Their xmlid module is `account` rather than `account_voucher`
because of the call to
`util.merge_module(cr, "account_voucher", "account")`
in `migrations/base/saas~12.4.1.3/pre-10-modules.py`

```
2020-06-23 22:07:41,466 2842 INFO template_fcb38c0104df_49376_13.0 odoo.addons.base.models.ir_model: Deleting 1098@ir.ui.view (account.view_purchase_receipt_form)
2020-06-23 22:07:41.471 UTC [2846] ERROR:  update or delete on table "ir_ui_view" violates foreign key constraint "ir_ui_view_inherit_id_fkey" on table "ir_ui_view"
2020-06-23 22:07:41.471 UTC [2846] DETAIL:  Key (id)=(1098) is still referenced from table "ir_ui_view".
2020-06-23 22:07:41.471 UTC [2846] STATEMENT:  DELETE FROM ir_ui_view WHERE id IN (1098)
2020-06-23 22:07:41,471 2842 ERROR template_fcb38c0104df_49376_13.0 odoo.sql_db: bad query: DELETE FROM ir_ui_view WHERE id IN (1098)
ERROR: update or delete on table "ir_ui_view" violates foreign key constraint "ir_ui_view_inherit_id_fkey" on table "ir_ui_view"
DETAIL:  Key (id)=(1098) is still referenced from table "ir_ui_view".

2020-06-23 22:07:41,477 2842 WARNING template_fcb38c0104df_49376_13.0 odoo.modules.loading: Transient module states were reset
2020-06-23 22:07:41,477 2842 ERROR template_fcb38c0104df_49376_13.0 odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/src/odoo/13.0/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/src/odoo/13.0/odoo/modules/loading.py", line 472, in load_modules
    env['ir.model.data']._process_end(processed_modules)
  File "/src/odoo/13.0/odoo/addons/base/models/ir_model.py", line 1990, in _process_end
    record.unlink()
  File "/src/odoo/13.0/addons/website/models/ir_ui_view.py", line 172, in unlink
    result = super(View, self + specific_views).unlink()
  File "/src/odoo/13.0/odoo/addons/base/models/ir_ui_view.py", line 512, in unlink
    return super(View, self).unlink()
  File "/src/odoo/13.0/odoo/models.py", line 3348, in unlink
    cr.execute(query, (sub_ids,))
  File "/src/odoo/13.0/odoo/sql_db.py", line 168, in wrapper
    return f(self, *args, **kwargs)
  File "/src/odoo/13.0/odoo/sql_db.py", line 245, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.ForeignKeyViolation: update or delete on table "ir_ui_view" violates foreign key constraint "ir_ui_view_inherit_id_fkey" on table "ir_ui_view"
DETAIL:  Key (id)=(1098) is still referenced from table "ir_ui_view".
```

Request 49376

closes odoo/upgrade#1393

Signed-off-by: Denis Ledoux (dle) <dle@odoo.com>