[FIX] helpdesk@saas~12.5: set `helpdesk_ticket` related `company_id`
In odoo/enterprise@f41ecec8e36b78a4956ab0c99aa9c7c493f0b04a

`company_id` of `helpdesk.team` became required.

On upgrade, the orm will set the the column values to the default
`self.env.company` thanks to `update_db_notnull`.

Therefore, `company_id` on `helpdesk.team` is set after upgrade.
However, the related `company_id` on `helpdesk.ticket`
is not set through the above mecanism,
because the above mecanism use plain sql, to update massively the column,
and therefore the recomputation of the related field is not done.

We therefore need to do it during upgrade,
otherwise this might lead to access exception
when reading a ticket (without company) having a team
from another company.

```
2021-03-01 09:07:12,837 9731 INFO db_8504 odoo.addons.base.maintenance.migrations.base.testsodoo.upgrade.base.tests.test_mock_crawl: Mocking view form: helpdesk.ticket.form
2021-03-01 09:07:12,840 9731 INFO db_8504 odoo.addons.base.maintenance.migrations.base.testsodoo.upgrade.base.tests.test_mock_crawl: view_form, helpdesk.ticket(1700, 1671, 1603), [('stage_id.is_close', '=', False)]
2021-03-01 09:07:12,857 9731 INFO db_8504 odoo.addons.base.models.ir_rule: Access Denied by record rules for operation: read on record ids: [5], uid: 2, model: helpdesk.team
2021-03-01 09:07:12,867 9731 INFO db_8504 odoo.addons.base.models.ir_rule: Access Denied by record rules for operation: read on record ids: [5], uid: 2, model: helpdesk.team
2021-03-01 09:07:12,873 9731 INFO db_8504 odoo.addons.base.models.ir_rule: Access Denied by record rules for operation: read on record ids: [5], uid: 2, model: helpdesk.team
2021-03-01 09:07:12,880 9731 INFO db_8504 odoo.addons.base.models.ir_rule: Access Denied by record rules for operation: read on record ids: [5], uid: 2, model: helpdesk.team
2021-03-01 09:07:12,890 9731 ERROR db_8504 odoo.addons.base.maintenance.migrations.base.testsodoo.upgrade.base.tests.test_mock_crawl: Adding menu ('helpdesk.helpdesk_ticket_menu_main', 554, 'Helpdesk > Tickets', 677) to the failing
Traceback (most recent call last):
  File "/tmp/tmpdwyefh1z/migrations/base/tests/test_mock_crawl.py", line 155, in crawl_menu
    self.mock_action(action_vals)
  File "/tmp/tmpdwyefh1z/migrations/base/tests/test_mock_crawl.py", line 234, in mock_action
    mock_method(model, view, fields_list, domain, group_by)
  File "/tmp/tmpdwyefh1z/migrations/base/tests/test_mock_crawl.py", line 260, in mock_view_form
    [data] = record.read(fields_list)
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 3023, in read
    return self._read_format(fnames=fields, load=load)
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 3043, in _read_format
    vals[name] = convert(record[name], record, use_name_get)
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 5664, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/odoo/src/odoo/14.0/odoo/fields.py", line 2483, in __get__
    return super().__get__(records, owner)
  File "/home/odoo/src/odoo/14.0/odoo/fields.py", line 1021, in __get__
    self.compute_value(record)
  File "/home/odoo/src/odoo/14.0/odoo/fields.py", line 1175, in compute_value
    records._compute_field_value(self)
  File "/home/odoo/src/odoo/14.0/addons/mail/models/mail_thread.py", line 410, in _compute_field_value
    return super()._compute_field_value(field)
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 4059, in _compute_field_value
    getattr(self, field.compute)()
  File "/home/odoo/src/enterprise/14.0/helpdesk/models/helpdesk_ticket.py", line 303, in _compute_domain_user_ids
    if task.team_id and task.team_id.visibility_member_ids:
  File "/home/odoo/src/odoo/14.0/odoo/fields.py", line 2483, in __get__
    return super().__get__(records, owner)
  File "/home/odoo/src/odoo/14.0/odoo/fields.py", line 998, in __get__
    record._fetch_field(self)
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 3072, in _fetch_field
    self._read(fnames)
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 3142, in _read
    self.check_access_rule('read')
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 3356, in check_access_rule
    raise self.env['ir.rule']._make_access_error(operation, forbidden)
odoo.exceptions.AccessError: Due to security restrictions, you are not allowed to access 'Helpdesk Team' (helpdesk.team) records.
```

In addition, the default `company_id` for `helpdesk.team`,
`self.env.company`, is not enough accurate for a multi company environment,
as this will always set the company of the admin user,
while the team might be from other companies.
We therefore guess the team company from the last writer or creator.

upg-8504