[FIX] website_sale/17.0: fixed website_sale.product cowed view
Summary of changes:
remove pricelist argument from `_get_combination_info` function
in `website_sale.product` qweb cowed view.

Description:
From version 17.0, there was change on `_get_combination_info`
function. that function called in `website_sale.product` view
template. so upto saas-16.4, we have argumet `pricelist` in
`_get_combination_info` which was removed in 17.0

so this changes has been updated in standard `website_sale.product`
view but it will not be updated in cowed view of `website_sale.product`

so we got the traceback when we click on shop product .

changes are here:
https://github.com/odoo/odoo/commit/4069158c96bbf2a6357622d5c0b0a91d722dd4cb#diff-635040c730ccbb8e4f6f2bf6472cf48a0cc9b8a3d488289dabdfce8096811915R951

UNICORN: 3890900

```
Error while render the template
TypeError: ProductTemplate._get_combination_info() got an unexpected keyword argument 'pricelist'
Template: website_sale.product
Path: /t/t[2]/t[3]
Node: <t t-set="product_variant" t-value="product.env[\'product.product\'].browse(combination_info[\'product_id\'])"/>
The error occurred while rendering the template website_sale.product și evaluarea următoarei expresii: <t t-set="product_variant" t-value="product.env[\'product.product\'].browse(combination_info[\'product_id\'])"/>
```

closes odoo/upgrade#5947

Signed-off-by: Christophe Simonis (chs) <chs@odoo.com>