[FIX] base/saas~18.2: fix syntax error
There is missing usage of `cr` in `util.module_installed`.
It is targeting to  `saas~18.2` that is why we do not have
failing db yet.

Steps to reproduce:
1. Install `pos_six` in 18.0
2. Upgrade to saas~18.2

You will see similar issue to this:

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/saas-18.2/odoo/service/server.py", line 1343, in preload_registries
    registry = Registry.new(dbname, update_module=update_module, install_modules=config['init'], upgrade_modules=config['update'])
  File "<decorator-gen-14>", line 2, in new
  File "/home/odoo/src/odoo/saas-18.2/odoo/tools/func.py", line 98, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/saas-18.2/odoo/orm/registry.py", line 165, in new
    load_modules(
  File "/home/odoo/src/odoo/saas-18.2/odoo/modules/loading.py", line 402, in load_modules
    load_module_graph(
  File "/home/odoo/src/odoo/saas-18.2/odoo/modules/loading.py", line 188, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/home/odoo/src/odoo/saas-18.2/odoo/modules/migration.py", line 261, in migrate_module
    mod.migrate(self.cr, installed_version)
  File "/home/odoo/src/upgrade/migrations/base/saas~18.2.1.3/pre-10-modules.py", line 34, in migrate
    if util.module_installed(cr, "pos_six") and not util.module_installed("pos_iot"):
TypeError: module_installed() missing 1 required positional argument: 'module'

```

closes odoo/upgrade#7291

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>