[FIX] acccount_asset/15.0: unlinked draft asset(s)
When Vendor Bills are reset to draft  that already has one or more
draft asset(s) related, those were left and not updated after re-posting
the Vendor Bills. Now they will be unlinked a created again.

also when customer invoice are reset to draft that already has
one or more draft `deferred revenue`, those were left and not updated
after re-posting the customer invoice. so need to unlinked a that
deferred revenue too.

otherwise we got user Error:
`All the lines should be posted`

see: https://github.com/odoo/enterprise/commit/f7cc7e10f01ccba03e7f733aa93f40bb0263e8b9#diff-a6560c3c87c9fd2bca4f17ad0e8383d3e80d5833c85ab335182526000eb44f5eR92

TGB : https://upgrade.odoo.com/web#id=724&action=178&model=upgrade.request.traceback.group&view_type=form&cids=1&menu_id=107

8 upgrade request failed by this traceback

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/15.0/odoo/service/server.py", line 1260, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/odoo/src/odoo/15.0/odoo/modules/registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/15.0/odoo/modules/loading.py", line 470, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/home/odoo/src/odoo/15.0/odoo/modules/loading.py", line 363, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/odoo/src/odoo/15.0/odoo/modules/loading.py", line 227, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/home/odoo/src/odoo/15.0/odoo/modules/migration.py", line 186, in migrate_module
    migrate(self.cr, installed_version)
  File "/tmp/tmp5urrdcun/migrations/account_asset_ndt/15.0.1.0/post-recompute.py", line 6, in migrate
    util.recompute_fields(cr, "account.asset", ["non_deductible_tax_val"])
  File "/tmp/tmp5urrdcun/migrations/util/orm.py", line 210, in wrapper
    return f(*args, **kwargs)
  File "/tmp/tmp5urrdcun/migrations/util/orm.py", line 247, in recompute_fields
    flush(records)
  File "/tmp/tmp5urrdcun/migrations/util/orm.py", line 180, in flush
    ((hasattr(records, "env") and getattr(records.env, "flush_all", None)) or getattr(records, "flush", lambda: None))()
  File "/home/odoo/src/odoo/15.0/odoo/models.py", line 5655, in flush
    self.recompute()
  File "/home/odoo/src/odoo/15.0/odoo/models.py", line 6128, in recompute
    process(field)
  File "/home/odoo/src/odoo/15.0/odoo/models.py", line 6112, in process
    field.recompute(recs)
  File "/home/odoo/src/odoo/15.0/odoo/fields.py", line 1268, in recompute
    self.compute_value(recs)
  File "/home/odoo/src/odoo/15.0/odoo/fields.py", line 1290, in compute_value
    records._compute_field_value(self)
  File "/home/odoo/src/odoo/15.0/addons/mail/models/mail_thread.py", line 411, in _compute_field_value
    return super()._compute_field_value(field)
  File "/home/odoo/src/odoo/15.0/odoo/models.py", line 4263, in _compute_field_value
    fields.determine(field.compute, self)
  File "/home/odoo/src/odoo/15.0/odoo/fields.py", line 87, in determine
    return needle(*args)
  File "/home/odoo/src/enterprise/15.0/account_asset_ndt/models/account_asset.py", line 26, in _compute_value
    super()._compute_value()
  File "/home/odoo/src/enterprise/15.0/account_asset/models/account_asset.py", line 128, in _compute_value
    raise UserError(_("All the lines should be posted"))
odoo.exceptions.UserError: All the lines should be posted
```

closes odoo/upgrade#4842

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>