[FIX] account/saas~14.1: journal code collision
When the journal codes being reused is a number we may fail to find a
corresponding new code.

Here we avoid removing the digits and add a sepparator to highligh the
extra digit(s) we add.

There is also an issue with the counter used to try multiple codes. If
there was only one journal code and it was in conflict the counter was
ending in 2 which then raised the error.

Improved the error message to quickly highlight the problematic code.

Example traceback
```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/15.0/odoo/service/server.py", line 1246, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/odoo/src/odoo/15.0/odoo/modules/registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/15.0/odoo/modules/loading.py", line 470, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/home/odoo/src/odoo/15.0/odoo/modules/loading.py", line 363, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/odoo/src/odoo/15.0/odoo/modules/loading.py", line 174, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/home/odoo/src/odoo/15.0/odoo/modules/migration.py", line 180, in migrate_module
    migrate(self.cr, installed_version)
  File "/tmp/tmpp0_dhd30/migrations/account/saas~14.1.1.1/pre-migrate.py", line 75, in migrate
    raise util.MigrationError("Could not create a new short code automatically for journal %s." % to_fix_id)
odoo.upgrade.util.exceptions.MigrationError: Could not create a new short code automatically for journal 33.
```

Example situation pre-upgrade
```
53937_afu=> SELECT trim(code), company_id, array_agg(id ORDER BY id) FROM account_journal GROUP BY trim(code), company_id HAVING count(*) > 1
+---------+--------------+------------------------------+
| btrim   | company_id   | array_agg                    |
|---------+--------------+------------------------------|
| 10      | 2            | [27, 28, 29, 30, 31, 32, 33] |
| INV     | 1            | [1, 36]                      |
+---------+--------------+------------------------------+
```
The script fails for 10, because it creates codes 1,2,3,..7 but there
are other journals called 5,6,7,9
Example situation post-upgrade with this fix
```
53937_afu_15.0=> select id,code,company_id from account_journal where company_id=2 order by company_id,code
+------+--------+--------------+
| id   | code   | company_id   |
|------+--------+--------------|
| 27   | 10     | 2            |
| 28   | 10N1   | 2            |
| 29   | 10N2   | 2            |
| 30   | 10N3   | 2            |
| 31   | 10N4   | 2            |
| 32   | 10N5   | 2            |
| 33   | 10N6   | 2            |
| 19   | 1118   | 2            |
| 23   | 5      | 2            |
| 24   | 6      | 2            |
| 25   | 7      | 2            |
| 26   | 9      | 2            |
+------+--------+--------------+
```

upg-53937
upg-54071
upg-52638 (quiet)
upg-49217
upg-44478

closes odoo/upgrade#3090

Signed-off-by: Nicolas Seinlet (nse) <nse@odoo.com>