[FIX] project_forecast/saas~17.1: decode byte string to string
Here, due to the use of `cr.mogrify`, the result is a byte string.
When converting in SQL, there's a check in `__init__` of `sql.py` to verify if
the input is an instance of str. Since it's a byte string, the following
traceback is raised.

To fix this, I’m decoding the byte string to convert it into a regular string.

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/saas-17.4/odoo/service/server.py", line 1302, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "<decorator-gen-16>", line 2, in new
  File "/home/odoo/src/odoo/saas-17.4/odoo/tools/func.py", line 84, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/saas-17.4/odoo/modules/registry.py", line 124, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/saas-17.4/odoo/modules/loading.py", line 476, in load_modules
    processed_modules += load_marked_modules(env, graph,
  File "/home/odoo/src/odoo/saas-17.4/odoo/modules/loading.py", line 364, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/odoo/src/odoo/saas-17.4/odoo/modules/loading.py", line 181, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/home/odoo/src/odoo/saas-17.4/odoo/modules/migration.py", line 240, in migrate_module
    migrate(self.cr, installed_version)
  File "/tmp/tmpurrbowh3/migrations/project_forecast/saas~17.1.1.0/pre-upgrade.py", line 64, in migrate
    company_filter=sql.SQL(company_filter),
  File "/home/odoo/.odoo-venvs/17.0/lib/python3.10/site-packages/psycopg2/sql.py", line 183, in __init__
    raise TypeError("SQL values must be strings")
TypeError: SQL values must be strings
```

UPG - 2184940
OPW - 4323220

closes odoo/upgrade#6745

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>