[FIX] website_sale/saas~18.4: Set inherit_id null for view
During the commit
https://github.com/odoo/odoo/commit/bbb2d98d9ab97ce729d59b9858b63daccf5434e2#diff-635040c730ccbb8e4f6f2bf6472cf48a0cc9b8a3d488289dabdfce8096811915L2193,
the view "website_sale.product_terms_and_conditions" was updated
to primary mode by setting `inherit_id` to NULL.
However, during migration, the view is updated without
resetting the `inherit_id`, which leads to a traceback due
to a conflicting inheritance state.
To fix this, the `inherit_id` is explicitly set to NULL, and the
The view mode is updated to `primary` to align with the standard.

Traceback:
ValueError: The element "<t name="Terms and Conditions" active="True"
priority="21" t-name="website_sale.product_terms_and_conditions">"
cannot be located in the main view.
Template: website_sale.product_terms_and_conditions

upg-3056076
opw-4997396

closes odoo/upgrade#8180

Signed-off-by: Christophe Simonis (chs) <chs@odoo.com>