[FIX] uom@0.0.0: ensure reference uoms
There can only be one reference uom per category.

If the user deleted the reference uom and created it back manually,
Odoo will try to create again the reference uom of the category
from the data, and the unique constraint will be raised.

```
2021-03-13 15:13:57,325 30 INFO db_9739 odoo.modules.loading: loading uom/data/uom_data.xml
2021-03-13 15:13:57,346 30 WARNING db_9739 odoo.modules.loading: Transient module states were reset
2021-03-13 15:13:57,346 30 ERROR db_9739 odoo.modules.registry: Failed to load registry
2021-03-13 15:13:57,346 30 CRITICAL db_9739 odoo.service.server: Failed to initialize database `db_9739`.
Traceback (most recent call last):
  File "/home/odoo/src/odoo/14.0/odoo/tools/convert.py", line 677, in _tag_root
    f(rec)
  File "/home/odoo/src/odoo/14.0/odoo/tools/convert.py", line 580, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 4214, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 4143, in _load_records_create
    return self.create(values)
  File "/tmp/tmp09qxlq6n/migrations/uom/0.0.0/pre-models-match_uniq.py", line 26, in create
    return super(UoM, self).create(values)
  File "<decorator-gen-113>", line 2, in create
  File "/home/odoo/src/odoo/14.0/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/14.0/addons/uom/models/uom_uom.py", line 102, in create
    return super(UoM, self).create(vals_list)
  File "<decorator-gen-112>", line 2, in create
  File "/home/odoo/src/odoo/14.0/odoo/api.py", line 326, in _model_create_single
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/home/odoo/src/odoo/14.0/odoo/api.py", line 326, in <genexpr>
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/tmp/tmp09qxlq6n/migrations/base/0.0.0/pre-models-match_uniq.py", line 22, in create
    return super(Base, self).create(values)
  File "<decorator-gen-65>", line 2, in create
  File "/home/odoo/src/odoo/14.0/odoo/api.py", line 344, in _model_create_multi
    return create(self, [arg])
  File "/home/odoo/src/odoo/14.0/odoo/addons/base/models/ir_fields.py", line 533, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "/home/odoo/src/odoo/14.0/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 3871, in create
    records = self._create(data_list)
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 4044, in _create
    records._validate_fields(name for data in data_list for name in data['stored'])
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 1256, in _validate_fields
    check(self)
  File "/home/odoo/src/odoo/14.0/addons/uom/models/uom_uom.py", line 94, in _validate_uom_category
    raise ValidationError(_("UoM category %s should only have one reference unit of measure.") % (self.category_id.name))
odoo.exceptions.ValidationError: UoM category Volume should only have one reference unit of measure.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/14.0/odoo/service/server.py", line 1198, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/odoo/src/odoo/14.0/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/src/odoo/14.0/odoo/modules/loading.py", line 451, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/home/odoo/src/odoo/14.0/odoo/modules/loading.py", line 348, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/odoo/src/odoo/14.0/odoo/modules/loading.py", line 221, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/home/odoo/src/odoo/14.0/odoo/modules/loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/home/odoo/src/odoo/14.0/odoo/tools/convert.py", line 733, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/home/odoo/src/odoo/14.0/odoo/tools/convert.py", line 799, in convert_xml_import
    obj.parse(doc.getroot())
  File "/home/odoo/src/odoo/14.0/odoo/tools/convert.py", line 719, in parse
    self._tag_root(de)
  File "/home/odoo/src/odoo/14.0/odoo/tools/convert.py", line 677, in _tag_root
    f(rec)
  File "/home/odoo/src/odoo/14.0/odoo/tools/convert.py", line 685, in _tag_root
    )) from e
odoo.tools.convert.ParseError: while parsing /home/odoo/src/odoo/14.0/addons/uom/data/uom_data.xml:89, near
<record id="product_uom_litre" model="uom.uom">
            <field name="name">L</field>
            <field name="category_id" ref="product_uom_categ_vol"/>
            <field name="factor">1.0</field>
            <field name="uom_type">reference</field>
        </record>
```

upg-2767
upg-3525
upg-5770
upg-6346
upg-7914
upg-9739
upg-10060

closes odoo/upgrade#2284

Signed-off-by: Christophe Simonis <chs@odoo.com>