[FIX] hr_holidays/18.0: fix 'actual_lastcall' being false
During upgrade test mock failed, facing the error
A fix about actual_lastcall=False was merged 2
weeks ago https://github.com/odoo/odoo/pull/209215
```
('hr_holidays.hr_holidays_status_menu_configuration', 513, 'Time Off > Configuration > Time Off Types', 790):
 Traceback (most recent call last):
   File "/tmp/tmps7tstgl1/migrations/base/tests/test_mock_crawl.py", line 261, in crawl_menu
    self.mock_action(action_vals)
   File "/tmp/tmps7tstgl1/migrations/base/tests/test_mock_crawl.py", line 274, in mock_action
    return self.mock_act_window(action)
   File "/tmp/tmps7tstgl1/migrations/base/tests/test_mock_crawl.py", line 434, in mock_act_window
    mock_method(model, view, fields_list, domain, group_by)
   File "/tmp/tmps7tstgl1/migrations/base/tests/test_mock_crawl.py", line 559, in mock_view_list
   File "/home/odoo/src/odoo/18.0/addons/hr_holidays/models/hr_leave_type.py", line 28, in _model_sorting_key
    remaining = leave_type.virtual_remaining_leaves > 0
   File "/home/odoo/src/odoo/18.0/addons/hr_holidays/models/hr_leave_type.py", line 289, in _compute_leaves
    data_days = self.get_allocation_data(employee, target_date)[employee]
   File "/home/odoo/src/odoo/18.0/addons/hr_holidays_attendance/models/hr_leave_type.py", line 36, in get_allocation_data
    res = super().get_allocation_data(employees, date)
   File "/home/odoo/src/odoo/18.0/addons/hr_holidays/models/hr_leave_type.py", line 548, in get_allocation_data
    closest_expiration_date, closest_allocation_remaining = self._get_closest_expiring_leaves_date_and_count(
   File "/home/odoo/src/odoo/18.0/addons/hr_holidays/models/hr_leave_type.py", line 598, in _get_closest_expiring_leaves_date_and_count
    carried_over_days_expiration_data = self._get_carried_over_days_expiration_data(allocations, target_date)
   File "/home/odoo/src/odoo/18.0/addons/hr_holidays/models/hr_leave_type.py", line 649, in _get_carried_over_days_expiration_data
    fake_allocations.sudo().with_context(default_date_from=target_date)._process_accrual_plans(target_date, log=False)
   File "/home/odoo/src/odoo/18.0/addons/hr_holidays/models/hr_leave_allocation.py", line 581, in _process_accrual_plans
    period_start = current_level._get_previous_date(allocation.actual_lastcall)
   File "/home/odoo/src/odoo/18.0/addons/hr_holidays/models/hr_leave_accrual_plan_level.py", line 308, in _get_previous_date
    date = last_call + relativedelta(day=self.first_day)
 TypeError: unsupported operand type(s) for +: 'bool' and 'relativedelta'
```

closes odoo/upgrade#7751

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>