[FIX] base/tests: allow to craw views with a restricted admin
If we set the admin user to only have `Access Rights` group (not
`Settings`), the fetching of `ir.actions` data is blocked by Access
Error.
```
2024-10-31 11:06:08,094 673178 ERROR test_17.4_18 odoo.addons.base.maintenance.migrations.base.testsodoo.upgrade.base.tests.test_mock_crawl: Adding menu ('mail.menu_root_discuss', 71, 'Discuss', 108) to the failing menus
Traceback (most recent call last):
  File "/home/odoo/src/upgrade/migrations/base/tests/test_mock_crawl.py", line 255, in crawl_menu
    [action_vals] = action_typed.read(self.action_type_fields[action.type])
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/saas-17.4/odoo/models.py", line 3684, in read
    self._origin.fetch(fields)
  File "/home/odoo/src/odoo/saas-17.4/odoo/models.py", line 3978, in fetch
    query = self.with_context(active_test=False)._search([('id', 'in', self.ids)])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/saas-17.4/odoo/models.py", line 5520, in _search
    self.check_access_rights('read')
  File "/home/odoo/src/odoo/saas-17.4/odoo/models.py", line 4257, in check_access_rights
    return self.env['ir.model.access'].check(self._name, operation, raise_exception)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/odoo/src/odoo/saas-17.4/odoo/addons/base/models/ir_model.py", line 2123, in check
    raise AccessError(msg) from None
odoo.exceptions.AccessError: You are not allowed to access 'Client Action' (ir.actions.client) records.

This operation is allowed for the following groups:
        - Administration/Settings
```

This causes all menus to fail which defeats the purpose of the test.
OTOH the admin is perfectly allowed to open many menus in the frontend.
The discrepancy comes from the way actions information is fetched. In
standard this is done in a sudo environment.

https://github.com/odoo/odoo/blob/33703769641d9f934409fb8d83dc67cda1654c00/odoo/addons/base/models/ir_ui_menu.py#L82

Steps to reproduce:
1. Install in a local DB any module (Discuss would do) in 17.4
2. Switch the admin to `Access Rights` group
3. Prepare upgrade tests.

We get errors on every menu.

closes odoo/upgrade#6702

Signed-off-by: Christophe Simonis (chs) <chs@odoo.com>