[FIX] base/saas~16.5: ensure update actions have a target field
For `object_write` actions after conversion from former server action
lines, we need to set the `update_path` otherwise the action fails.
```
...
   File "/home/odoo/src/odoo/17.0/odoo/fields.py", line 1389, in compute_value
    records._compute_field_value(self)
   File "/home/odoo/src/odoo/17.0/addons/base_automation/models/base_automation.py", line 764, in _compute_field_value
    automation._process(records, domain_post=domain_post)
   File "/home/odoo/src/odoo/17.0/addons/base_automation/models/base_automation.py", line 653, in _process
    action.with_context(**ctx).run()
   File "/home/odoo/src/odoo/17.0/odoo/addons/base/models/ir_actions.py", line 950, in run
    res = runner(run_self, eval_context=eval_context)
   File "/home/odoo/src/odoo/17.0/odoo/addons/base/models/ir_actions.py", line 790, in _run_action_object_write
    _, _, target_records = self._traverse_path(record=starting_record)
   File "/home/odoo/src/odoo/17.0/odoo/addons/base/models/ir_actions.py", line 646, in _traverse_path
    path = self.update_path.split('.')
 AttributeError: 'bool' object has no attribute 'split'
```

It seems that `object_write` actions expect this field to be set. It's
highlighted at the fronted view by the field selector widget.

tbg-1110
tested: upg-1389660 upg-1389651

Some pointers to the code in standard:
https://github.com/odoo/odoo/blob/b238770e5a3760d51e2d6c4786dd46648de87815/odoo/addons/base/models/ir_actions.py#L656-L659
https://github.com/odoo/odoo/blob/35535ce1129e4844f952d9d6cf5f75bc6a2da63f/odoo/addons/base/models/ir_actions.py#L666

closes odoo/upgrade#5782

Signed-off-by: Christophe Simonis (chs) <chs@odoo.com>