[FIX] mail/saas~17.3: Fix migration error for mail channel
Before this [commit]
https://github.com/odoo/upgrade-util/commit/afa3e94bb04e600babf56f987c048d7a42067719#diff-e83e04eeae2ce53657ba28fd8de2126f5f3ef6422a73066af36dcf9191de1278R86
many customer have upgraded production database
and those database contain this [administrator]
https://github.com/odoo/upgrade-util/commit/12dbc1d99308d2db772d7975d86661b6f4d1438f#diff-e83e04eeae2ce53657ba28fd8de2126f5f3ef6422a73066af36dcf9191de1278R69
channel.

From this commit [channel_admin]
https://github.com/odoo/upgrade-util/commit/afa3e94bb04e600babf56f987c048d7a42067719#diff-e83e04eeae2ce53657ba28fd8de2126f5f3ef6422a73066af36dcf9191de1278R86
entry creating and due to this many request blocked.

```py
Traceback (most recent call last):
  File "/home/odoo/src/odoo/saas-17.4/odoo/service/server.py", line 1302, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "<decorator-gen-16>", line 2, in new
  File "/home/odoo/src/odoo/saas-17.4/odoo/tools/func.py", line 84, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/saas-17.4/odoo/modules/registry.py", line 123, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/saas-17.4/odoo/modules/loading.py", line 476, in load_modules
    processed_modules += load_marked_modules(env, graph,
  File "/home/odoo/src/odoo/saas-17.4/odoo/modules/loading.py", line 364, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/odoo/src/odoo/saas-17.4/odoo/modules/loading.py", line 181, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/home/odoo/src/odoo/saas-17.4/odoo/modules/migration.py", line 240, in migrate_module
    migrate(self.cr, installed_version)
  File "/tmp/tmpfbake_h_/migrations/mail/saas~17.3.1.17/pre-migrate.py", line 16, in migrate
    util.rename_xmlid(cr, "__upgrade__.channel_administrators", "mail.channel_admin", noupdate=True)
  File "/tmp/tmpfbake_h_/migrations/util/records.py", line 720, in rename_xmlid
    raise MigrationError("Can't rename {} to {} as it already exists".format(old, new))
odoo.upgrade.util.exceptions.UpgradeError: Can't rename __upgrade__.channel_administrators to mail.channel_admin as it already exists
```
UPG-1878670

closes odoo/upgrade#6364

Related: odoo/upgrade-util#128
Signed-off-by: Christophe Simonis (chs) <chs@odoo.com>