[FIX] l10n_us_reports/saas~18.{2,3}: remove model
The model `l10n_us.tax.report.handler` was added here:
odoo/enterprise@1e8f79bd0a5e53f34cd8dfaea0a4d3e199aca0c7
and removed here: odoo/enterprise@f229fce6981b576f651163d922b4b8ceda995bde

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/saas-18.3/odoo/service/server.py", line 1396, in preload_registries
    registry = Registry.new(dbname, update_module=update_module, install_modules=config['init'], upgrade_modules=config['update'])
  File "<decorator-gen-6>", line 2, in new
  File "/home/odoo/src/odoo/saas-18.3/odoo/tools/func.py", line 83, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/saas-18.3/odoo/orm/registry.py", line 167, in new
    load_modules(
  File "/home/odoo/src/odoo/saas-18.3/odoo/modules/loading.py", line 509, in load_modules
    env['ir.model.data']._process_end(registry.updated_modules)
  File "/tmp/tmpaab90r3u/migrations/base/0.0.0/pre-models-no-model-data-delete.py", line 108, in _process_end
    return super(IrModelData, self)._process_end(modules)
  File "/home/odoo/src/odoo/saas-18.3/odoo/addons/base/models/ir_model.py", line 2589, in _process_end
    self._process_end_unlink_record(record)
  File "/home/odoo/src/odoo/saas-18.3/odoo/addons/base/models/ir_model.py", line 2518, in _process_end_unlink_record
    record.unlink()
  File "/home/odoo/src/odoo/saas-18.3/addons/mail/models/ir_model_fields.py", line 59, in unlink
    return super().unlink()
  File "/tmp/tmpaab90r3u/migrations/base/0.0.0/pre-models-ir_model.py", line 210, in unlink
    raise util.MigrationError(message)
odoo.upgrade.util.exceptions.UpgradeError: 💥 It looks like you forgot to call `util.remove_field` on the following fields: l10n_us.tax.report.handler.id
```

closes odoo/upgrade#7917

Signed-off-by: Christophe Simonis (chs) <chs@odoo.com>