[FIX] base/saas~16.1: index name may contain uppercase
For security we also need to quote it.

Note how the query was run with uppercase:
```
2023-03-17 09:09:38,730 30 ERROR ? odoo.sql_db: bad query: ALTER INDEX sale_order_line_x_studio_float_field_dCjOQ_index RENAME TO sale_order_line__x_studio_float_field_dCjOQ_index
ERROR: relation "sale_order_line_x_studio_float_field_dcjoq_index" does not exist
```
upg-623860

closes odoo/upgrade#4446

Signed-off-by: Christophe Simonis <chs@odoo.com>