[FIX] base/0.0.0: ensure having `sms` for `hr_recruitment`
The module `sms` is getting installed when we install `hr_recruitment`
because of **auto_install=TRUE**. But we can uninstall `sms`
independently.

There were 2 action windows in `hr_recruitment` which were depending on
module `sms` but it gets problematic when client uninstalls `sms`.
1. `hr_recruitment.action_hr_applicant_mass_sms`[^1] was introduced
   in `saas~16.4`
2. `hr_recruitment.action_hr_candidate_mass_sms`[^2] was introduced
   in `18.0`.

For solving the dependency issue between `hr_recruitment` and `sms`, bridge
module `hr_recruitment_sms` was introduced in `saas~18.2`[^3] and the
action windows were moved to this module. But renaming
xmlids from `hr_recruitment` --> `hr_recruitment_sms` is missing.

When we do these steps:
1. Install `hr_recruitment` in version `17.0`
2. Uninstall `sms` manually
3. Upgrade to `18.0`

Becayse we do not have bridge module yet, and there are actions in
`hr_recruitment` depending on presence of `sms`, when it loads the
actions we will have issue like this :

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/18.0/odoo/service/server.py", line 1318, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "<decorator-gen-13>", line 2, in new
  File "/home/odoo/src/odoo/18.0/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/18.0/odoo/modules/registry.py", line 127, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/18.0/odoo/modules/loading.py", line 476, in load_modules
    processed_modules += load_marked_modules(env, graph,
  File "/home/odoo/src/odoo/18.0/odoo/modules/loading.py", line 364, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/odoo/src/odoo/18.0/odoo/modules/loading.py", line 227, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "/home/odoo/src/odoo/18.0/odoo/modules/loading.py", line 71, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "/home/odoo/src/odoo/18.0/odoo/tools/convert.py", line 608, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "/home/odoo/src/odoo/18.0/odoo/tools/convert.py", line 679, in convert_xml_import
    obj.parse(doc.getroot())
  File "/home/odoo/src/odoo/18.0/odoo/tools/convert.py", line 594, in parse
    self._tag_root(de)
  File "/home/odoo/src/odoo/18.0/odoo/tools/convert.py", line 548, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
odoo.tools.convert.ParseError: while parsing /home/odoo/src/odoo/18.0/addons/hr_recruitment/views/hr_candidate_views.xml:220
Invalid model name “sms.composer” in action definition.

View error context:
'-no context-'
```

Actually the problem occurs for all dbs which :
1. Source version between `saas~16.4` and `18.0`
2. `hr_recruitment` installed but not `sms`
3. Target version between `17.0` and `saas~18.1`

For fixing the issue, I have force_installed `sms` for
the dbs which are falling to the condition's above

[^1]: odoo/odoo@5da9a87
[^2]: https://github.com/odoo/odoo/blob/e5b2a1744ff2d2ab4fec8b79256519107e561bcd/addons/hr_recruitment/views/hr_candidate_views.xml#L220-L232
[^3]: odoo/odoo#194647

closes odoo/upgrade#7317

Signed-off-by: Christophe Simonis (chs) <chs@odoo.com>