[FIX] base/saas~17.5: Replace tree with list in server action code
As in version 18.0, tree view has been replaced with list view. We have
incorporated that change in views and window action, but if there is any
reference to a tree in existing server action code like this,
It will throw an error.
```
ValueError: Wrong value for ir.ui.view.type: tree
```
To resolve this issue we can replace patterns like <tree>, </tree>,
"view_mode": "tree", "type": "tree", which were mostly occurring.

opw-4813876

closes odoo/upgrade#7772

Signed-off-by: Christophe Simonis (chs) <chs@odoo.com>