[FIX] base@13.0: force update record rule `base.res_users_rule`
The domain of the rule `base.res_users_rule`
changed in odoo/odoo@ebc8d85d383643c1d4d2aa6723bc7a589c7d1c68

It's is a `noupdate="1"` block so it doesn't get updated
on upgrade.

The field `gamification.badge.unique_owner_ids`
kinda rely on it, as it will display all employee users
having the badge in the kanban view,
accross companies.
See the raw sql in `_get_owners_info`

Without that rule,
users can only read users from their own/current company,
and then when opening the badge kanban view,
an access error is raised.

```
2021-03-01 09:08:20,325 9731 INFO db_8504 odoo.addons.base.maintenance.migrations.base.testsodoo.upgrade.base.tests.test_mock_crawl: Mocking view kanban: Badge Kanban View
2021-03-01 09:08:20,326 9731 INFO db_8504 odoo.addons.base.maintenance.migrations.base.testsodoo.upgrade.base.tests.test_mock_crawl: search_read, gamification.badge(), [[]]
2021-03-01 09:08:20,338 9731 INFO db_8504 odoo.addons.base.models.ir_rule: Access Denied by record rules for operation: read on record ids: [313], uid: 2, model: res.users
2021-03-01 09:08:20,352 9731 INFO db_8504 odoo.addons.base.models.ir_rule: Access Denied by record rules for operation: read on record ids: [313], uid: 2, model: res.users
2021-03-01 09:08:20,364 9731 ERROR db_8504 odoo.addons.base.maintenance.migrations.base.testsodoo.upgrade.base.tests.test_mock_crawl: Adding menu ('hr_gamification.gamification_badge_menu_hr', 601, 'Employees > Configuration > Challenges > Badges', 723) to the failing menus
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/tmpdwyefh1z/migrations/base/tests/test_mock_crawl.py", line 155, in crawl_menu
    self.mock_action(action_vals)
  File "/tmp/tmpdwyefh1z/migrations/base/tests/test_mock_crawl.py", line 234, in mock_action
    mock_method(model, view, fields_list, domain, group_by)
  File "/tmp/tmpdwyefh1z/migrations/base/tests/test_mock_crawl.py", line 324, in mock_view_kanban
    self.mock_web_search_read(model, view, [domain], fields_list)
  File "/tmp/tmpdwyefh1z/migrations/base/tests/test_mock_crawl.py", line 383, in mock_web_search_read
    data = model.search_read(domain=domain, fields=fields_list, limit=80)
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 4837, in search_read
    result = records.read(fields)
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 3023, in read
    return self._read_format(fnames=fields, load=load)
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 3043, in _read_format
    vals[name] = convert(record[name], record, use_name_get)
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 5664, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/odoo/src/odoo/14.0/odoo/fields.py", line 2483, in __get__
    return super().__get__(records, owner)
  File "/home/odoo/src/odoo/14.0/odoo/fields.py", line 1060, in __get__
    return self.convert_to_record(value, record)
  File "/home/odoo/src/odoo/14.0/odoo/fields.py", line 2956, in convert_to_record
    corecords = corecords.filtered(Comodel._active_name).with_prefetch(prefetch_ids)
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 5278, in filtered
    self.mapped(name)
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 5240, in mapped
    recs = recs._fields[name].mapped(recs)
  File "/home/odoo/src/odoo/14.0/odoo/fields.py", line 1086, in mapped
    self.__get__(first(remaining), type(remaining))
  File "/home/odoo/src/odoo/14.0/odoo/fields.py", line 998, in __get__
    record._fetch_field(self)
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 3072, in _fetch_field
    self._read(fnames)
  File "/home/odoo/src/odoo/14.0/odoo/addons/base/models/res_users.py", line 447, in _read
    super(Users, self)._read(fields)
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 3183, in _read
    raise self.env['ir.rule']._make_access_error('read', forbidden)
odoo.exceptions.AccessError: Due to security restrictions, you are not allowed to access 'Users' (res.users) records.

Records: Baptiste Le Poittevin  (id=313)
User: Admin user DO NOT MODIFY NOR DELETE (id=2)

This restriction is due to the following rules:
- user rule
```

This domain update happened in 13.0,
but as users already upgraded to 13.0 and 14.0 without having that rule
updated, we also apply it when upgrading to 14.0 and in the future 15.0
with the use of a symlink.

upg-8504

closes odoo/upgrade#2224

Signed-off-by: Christophe Simonis <chs@odoo.com>