[FIX] base/0.0.0: cleanup empty ir_default
The customer has added default for categ_id field of product_template model
as 'false',which overrides the standard default value for it, hence during
upgrade,categ_id is evaluated as NULL, which raises error, as categ_id
should cannot be NULL

```
2024-08-29 11:12:54,400 25 INFO db_2012130 odoo.modules.loading: loading loyalty/report/loyalty_report.xml
2024-08-29 11:12:54,405 25 INFO db_2012130 odoo.modules.loading: loading loyalty/data/mail_template_data.xml
2024-08-29 11:12:54,416 25 INFO db_2012130 odoo.modules.loading: loading loyalty/data/loyalty_data.xml
2024-08-29 11:12:54,437 25 INFO db_2012130 odoo.addons.base.models.ir_attachment: _read_file reading /home/odoo/.local/share/Odoo/filestore/db_2012130/3c/3c7f05adc81e30077c3010317a2de3a233123f54
Traceback (most recent call last):
  File "/home/odoo/src/odoo/17.0/odoo/addons/base/models/ir_attachment.py", line 123, in _file_read
    with open(full_path, 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/home/odoo/.local/share/Odoo/filestore/db_2012130/3c/3c7f05adc81e30077c3010317a2de3a233123f54'
2024-08-29 11:12:54,497 25 ERROR db_2012130 odoo.sql_db: bad query: INSERT INTO "product_template" ("active", "categ_id", "company_id", "create_date", "create_uid", "detailed_type", "list_price", "name", "priority", "product_properties", "purchase_ok", "sale_ok", "sequence", "type", "uom_id", "uom_po_id", "write_date", "write_uid") VALUES (true, NULL, 1, '2024-08-29 11:12:53.858407', 1, 'service', '1.00', '{"en_US": "Gift Card"}', '0', NULL, false, false, 1, 'service', 1, 1, '2024-08-29 11:12:53.858407', 1) RETURNING "id"
ERROR: null value in column "categ_id" of relation "product_template" violates not-null constraint
DETAIL:  Failing row contains (51591, {"en_US": "Gift Card"}, 1, null, null, null, service, null, 1.00, null, null, f, f, 1, 1, 1, t, null, null, null, null, 1, 2024-08-29 11:12:53.858407, 1, 2024-08-29 11:12:53.858407, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, service, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null).

2024-08-29 11:12:54,507 25 WARNING db_2012130 odoo.modules.loading: Transient module states were reset
2024-08-29 11:12:54,507 25 ERROR db_2012130 odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/home/odoo/src/odoo/17.0/odoo/tools/convert.py", line 556, in _tag_root
    f(rec)
  File "/home/odoo/src/odoo/17.0/odoo/tools/convert.py", line 456, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/home/odoo/src/odoo/17.0/odoo/models.py", line 5087, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/home/odoo/src/odoo/17.0/odoo/models.py", line 4998, in _load_records_create
    return self.create(values)
  File "<decorator-gen-205>", line 2, in create
  File "/home/odoo/src/odoo/17.0/odoo/api.py", line 415, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/17.0/addons/loyalty/models/loyalty_reward.py", line 258, in create
    res._create_missing_discount_line_products()
  File "/home/odoo/src/odoo/17.0/addons/loyalty/models/loyalty_reward.py", line 251, in _create_missing_discount_line_products
    products = self.env['product.product'].create(rewards._get_discount_product_values())
  File "<decorator-gen-175>", line 2, in create
  File "/home/odoo/src/odoo/17.0/odoo/api.py", line 415, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/17.0/addons/product/models/product_product.py", line 362, in create
    products = super(ProductProduct, self.with_context(create_product_product=False)).create(vals_list)
  File "<decorator-gen-140>", line 2, in create
  File "/home/odoo/src/odoo/17.0/odoo/api.py", line 415, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/17.0/addons/mail/models/mail_thread.py", line 259, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-123>", line 2, in create
  File "/home/odoo/src/odoo/17.0/odoo/api.py", line 415, in _model_create_multi
    return create(self, arg)
  File "/tmp/tmpk4puc8v2/migrations/util/orm.py", line 244, in wrapper
    return f(*args, **kwargs)
  File "/tmp/tmpk4puc8v2/migrations/base/0.0.0/pre-models-match_uniq.py", line 25, in create
    return super().create(vals_list)
  File "<decorator-gen-12>", line 2, in create
  File "/home/odoo/src/odoo/17.0/odoo/api.py", line 415, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/17.0/odoo/models.py", line 4618, in create
    parents = self.env[model_name].create([
  File "<decorator-gen-172>", line 2, in create
  File "/home/odoo/src/odoo/17.0/odoo/api.py", line 415, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/17.0/addons/product/models/product_template.py", line 487, in create
    templates = super(ProductTemplate, self).create(vals_list)
  File "<decorator-gen-140>", line 2, in create
  File "/home/odoo/src/odoo/17.0/odoo/api.py", line 415, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/17.0/addons/mail/models/mail_thread.py", line 259, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-123>", line 2, in create
  File "/home/odoo/src/odoo/17.0/odoo/api.py", line 415, in _model_create_multi
    return create(self, arg)
  File "/tmp/tmpk4puc8v2/migrations/util/orm.py", line 244, in wrapper
    return f(*args, **kwargs)
  File "/tmp/tmpk4puc8v2/migrations/base/0.0.0/pre-models-match_uniq.py", line 25, in create
    return super().create(vals_list)
  File "<decorator-gen-12>", line 2, in create
  File "/home/odoo/src/odoo/17.0/odoo/api.py", line 415, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/17.0/odoo/models.py", line 4626, in create
    records = self._create(data_list)
  File "/home/odoo/src/odoo/17.0/odoo/models.py", line 4814, in _create
    cr.execute(SQL(
  File "/home/odoo/src/odoo/17.0/odoo/sql_db.py", line 332, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.NotNullViolation: null value in column "categ_id" of relation "product_template" violates not-null constraint
DETAIL:  Failing row contains (51591, {"en_US": "Gift Card"}, 1, null, null, null, service, null, 1.00, null, null, f, f, 1, 1, 1, t, null, null, null, null, 1, 2024-08-29 11:12:53.858407, 1, 2024-08-29 11:12:53.858407, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, 0, service, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null).

upg-2012130
tbg-998
```

closes odoo/upgrade#6442

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>