[FIX] base_automation@saas~13.1: actions with multiple times the same field in onchange
In the observed case,
the database has an action with multiple times the same field in its onchange fields:

```
WITH ocf AS (
    SELECT a.id, s.model_id, trim(regexp_split_to_table(a.on_change_fields, ',')) as name
      FROM base_automation a
      JOIN ir_act_server s ON s.id = a.action_server_id
)
  SELECT id, name, COUNT(*)
    FROM ocf o
GROUP BY id, name
  HAVING COUNT(*) > 1;
 id |                name                | count
----+------------------------------------+-------
 55 | impression_bache_format_ids.height |     2
 56 | impression_bache_format_ids        |     2
 57 | impression_bache_format_ids        |     2
```

Therefore leading to the below unique cosntraint exception:

```
2021-03-16 12:00:45,874 29 INFO dle_4717_13.0_14.0 odoo.modules.migration: module base_automation: Running migration [>saas~13.1.1.0] pre-migrate
2021-03-16 12:00:45,896 29 ERROR dle_4717_13.0_14.0 odoo.sql_db: bad query:
        WITH ocf AS (
            SELECT a.id, s.model_id, trim(regexp_split_to_table(a.on_change_fields, ',')) as name
              FROM base_automation a
              JOIN ir_act_server s ON s.id = a.action_server_id
        )
        INSERT INTO base_automation_onchange_fields_rel(base_automation_id, ir_model_fields_id)
             SELECT o.id, f.id
               FROM ocf o
               JOIN ir_model_fields f USING (model_id, name)

ERROR: duplicate key value violates unique constraint "base_automation_onchange_fields_rel_pkey"
DETAIL:  Key (base_automation_id, ir_model_fields_id)=(56, 6022) already exists.

2021-03-16 12:00:45,902 29 WARNING dle_4717_13.0_14.0 odoo.modules.loading: Transient module states were reset
2021-03-16 12:00:45,906 29 ERROR dle_4717_13.0_14.0 odoo.modules.registry: Failed to load registry
2021-03-16 12:00:45,906 29 CRITICAL dle_4717_13.0_14.0 odoo.service.server: Failed to initialize database `dle_4717_13.0_14.0`.
Traceback (most recent call last):
  File "/home/odoo/src/odoo/14.0/odoo/service/server.py", line 1198, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/odoo/src/odoo/14.0/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/src/odoo/14.0/odoo/modules/loading.py", line 451, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/home/odoo/src/odoo/14.0/odoo/modules/loading.py", line 348, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/odoo/src/odoo/14.0/odoo/modules/loading.py", line 173, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/home/odoo/src/odoo/14.0/odoo/modules/migration.py", line 180, in migrate_module
    migrate(self.cr, installed_version)
  File "/tmp/tmpg4_8v53m/migrations/base_automation/saas~13.1.1.0/pre-migrate.py", line 17, in migrate
    """)
  File "<decorator-gen-3>", line 2, in execute
  File "/home/odoo/src/odoo/14.0/odoo/sql_db.py", line 101, in check
    return f(self, *args, **kwargs)
  File "/home/odoo/src/odoo/14.0/odoo/sql_db.py", line 298, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "base_automation_onchange_fields_rel_pkey"
DETAIL:  Key (base_automation_id, ir_model_fields_id)=(56, 6022) already exists.
```

upg-4717

closes odoo/upgrade#2278

Signed-off-by: Denis Ledoux (dle) <dle@odoo.com>