[FIX] sale_subscription/saas~15.3.1.1: fix domain
1. As 'sale.subscription' model merged with 'sale.order'
related field reference has been updated too.
like 'template_id' field renmated to 'sale_order_template_id'
but for custom base automated action, 'template_id'
 reference has not been updated, model changed from
 'sale.subscription' to 'sale.order' for that base automation.
 so It raised this traceback.
 so we need to correct filter_domain with updating
 'sale_order_template_id' in place of 'template_id'.

related upgrade request :

upg-422112
upg-437729
upg-420721
upg-424213

```
File "/home/odoo/src/odoo/16.0/odoo/models.py", line 4188, in _compute_field_value
    getattr(self, field.compute)()
   File "/home/odoo/src/enterprise/16.0/sale_subscription/models/sale_order_alert.py", line 68, in _compute_subscription_count
    alert.subscription_count = self.env['sale.order'].search_count(domain)
   File "/home/odoo/src/odoo/16.0/odoo/models.py", line 1514, in search_count
    res = self.search(domain, limit=limit, count=True)
   File "/home/odoo/src/odoo/16.0/odoo/models.py", line 1536, in search
    res = self._search(domain, offset=offset, limit=limit, order=order, count=count)
   File "/home/odoo/src/odoo/16.0/odoo/models.py", line 4620, in _search
    query = self._where_calc(domain)
   File "/home/odoo/src/odoo/16.0/odoo/models.py", line 4388, in _where_calc
    return expression.expression(domain, self).query
   File "/home/odoo/src/odoo/16.0/odoo/osv/expression.py", line 447, in __init__
    self.parse()
   File "/home/odoo/src/odoo/16.0/odoo/osv/expression.py", line 672, in parse
    raise ValueError("Invalid field %s.%s in leaf %s" % (model._name, path[0], str(leaf)))
 ValueError: Invalid field sale.order.template_id in leaf ('template_id', 'in', [1, 2, 3, 4, 5, 6])
```

2. 'recurring_invoice_line_ids' field also changed to
'order_line' but for custom base automation action,
'recurring_invoice_line_ids' field has not been updated
on filter domain.so we need to correct filter domain
with replacing 'recurring_invoice_line_ids' by 'order_line'

see : https://github.com/odoo/enterprise/commit/c35b17f3efeaf38592aa94dd76668dd3642fc6ba

```
  File "/home/odoo/src/odoo/16.0/odoo/models.py", line 4188, in _compute_field_value
    getattr(self, field.compute)()
   File "/home/odoo/src/enterprise/16.0/sale_subscription/models/sale_order_alert.py", line 69, in _compute_subscription_count
    k = self.env['sale.order'].search_count(domain)
   File "/home/odoo/src/odoo/16.0/odoo/models.py", line 1514, in search_count
    res = self.search(domain, limit=limit, count=True)
   File "/home/odoo/src/odoo/16.0/odoo/models.py", line 1536, in search
    res = self._search(domain, offset=offset, limit=limit, order=order, count=count)
   File "/home/odoo/src/odoo/16.0/odoo/models.py", line 4620, in _search
    query = self._where_calc(domain)
   File "/home/odoo/src/odoo/16.0/odoo/models.py", line 4388, in _where_calc
    return expression.expression(domain, self).query
   File "/home/odoo/src/odoo/16.0/odoo/osv/expression.py", line 447, in __init__
    self.parse()
   File "/home/odoo/src/odoo/16.0/odoo/osv/expression.py", line 672, in parse
    raise ValueError("Invalid field %s.%s in leaf %s" % (model._name, path[0], str(leaf)))
 ValueError: Invalid field sale.order.recurring_invoice_line_ids in leaf ('recurring_invoice_line_ids.product_id', 'in', [118, 13, 137, 145, 159, 160, 175])

````

upg-422112

closes odoo/upgrade#4170

Signed-off-by: Christophe Simonis <chs@odoo.com>