[FIX] account/saas~12.4.1.1: fix null price_{*}
The move lines created in https://github.com/odoo/upgrade/blob/9ffeba897060fcbac1a35ea3261e3c83ec190088/migrations/account/saas%7E12.4.1.1/end-09-account-pocalypse.py#L1700
have null price_{unit,total,subtotal}. Those values are still set
even if the lines are section/notes (display_type not null). Here we
get the value previously set on the invoice line, otherwise the null
values cause an exception later on the menu KPI.
```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/14.0/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/home/odoo/src/odoo/14.0/odoo/http.py", line 683, in dispatch
    result = self._call_function(**self.params)
  File "/home/odoo/src/odoo/14.0/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/odoo/src/odoo/14.0/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/odoo/src/odoo/14.0/odoo/http.py", line 347, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/odoo/src/odoo/14.0/odoo/http.py", line 912, in __call__
    return self.method(*args, **kw)
  File "/home/odoo/src/odoo/14.0/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/enterprise/14.0/sale_subscription_dashboard/controllers/revenue_kpis_dashboard.py", line 182, in compute_graph_and_stats
    graph = self.compute_graph(stat_type, start_date, end_date, filters, points_limit=points_limit)
  File "/home/odoo/src/odoo/14.0/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/enterprise/14.0/sale_subscription_dashboard/controllers/revenue_kpis_dashboard.py", line 203, in compute_graph
    value = self.compute_stat(stat_type, date, date, filters)
  File "/home/odoo/src/odoo/14.0/odoo/http.py", line 531, in response_wrap
    response = f(*args, **kw)
  File "/home/odoo/src/enterprise/14.0/sale_subscription_dashboard/controllers/revenue_kpis_dashboard.py", line 238, in compute_stat
    return STAT_TYPES[stat_type]['compute'](start_date, end_date, filters)
  File "/home/odoo/src/enterprise/14.0/sale_subscription_dashboard/controllers/stat_types.py", line 105, in compute_net_revenue
    return currency_normalisation(sql_results, 'price_subtotal')
  File "/home/odoo/src/enterprise/14.0/sale_subscription_dashboard/controllers/stat_types.py", line 28, in currency_normalisation
    company=company_id, date=datetime.utcnow().date())
  File "/home/odoo/src/odoo/14.0/odoo/addons/base/models/res_currency.py", line 200, in _convert
    return to_currency.round(to_amount) if round else to_amount
  File "/home/odoo/src/odoo/14.0/odoo/addons/base/models/res_currency.py", line 134, in round
    return tools.float_round(amount, precision_rounding=self.rounding)
  File "/home/odoo/src/odoo/14.0/odoo/tools/float_utils.py", line 72, in float_round
    normalized_value = value / rounding_factor # normalize
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/14.0/odoo/http.py", line 639, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/odoo/src/odoo/14.0/odoo/http.py", line 315, in _handle_exception
    raise exception.with_traceback(None) from new_cause
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'
```

Before
```
14988_afu_14.0_orig=> select count(*) from account_move_line where price_subtotal is null and display_type is not null;
+---------+
| count   |
|---------|
| 6187    |
+---------+
```
After
```
14988_afu_14.0=> select count(*) from account_move_line where price_subtotal is null and display_type is not null;
+---------+
| count   |
|---------|
| 0       |
+---------+

```

upg-14988
opw-2557522

closes odoo/upgrade#2520

Signed-off-by: Christophe Simonis <chs@odoo.com>