[FIX] account_followup/16.0: Fix unique constraint
The data file for the record `account_followup.demo_followup_line1`
has the flag `force_create` unset, but in this script, while updating
from xml the flag is not specified, creating the record from the data file
and potentially triggering the constraint.

upg-1298790
upg-1298777
upg-1298285
upg-1273463
upg-1246537
upg-1224171

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/16.0/odoo/tools/convert.py", line 698, in _tag_root
    f(rec)
  File "/home/odoo/src/odoo/16.0/odoo/tools/convert.py", line 599, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/home/odoo/src/odoo/16.0/odoo/models.py", line 4408, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/home/odoo/src/odoo/16.0/odoo/models.py", line 4319, in _load_records_create
    return self.create(values)
  File "<decorator-gen-123>", line 2, in create
  File "/home/odoo/src/odoo/16.0/odoo/api.py", line 415, in _model_create_multi
    return create(self, arg)
  File "/tmp/tmpcbk05i10/migrations/util/orm.py", line 212, in wrapper
    return f(*args, **kwargs)
  File "/tmp/tmpcbk05i10/migrations/base/0.0.0/pre-models-match_uniq.py", line 25, in create
    return super().create(vals_list)
  File "<decorator-gen-68>", line 2, in create
  File "/home/odoo/src/odoo/16.0/odoo/api.py", line 415, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/16.0/odoo/addons/base/models/ir_fields.py", line 670, in create
    recs = super().create(vals_list)
  File "<decorator-gen-15>", line 2, in create
  File "/home/odoo/src/odoo/16.0/odoo/api.py", line 415, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/16.0/odoo/models.py", line 3975, in create
    records = self._create(data_list)
  File "/home/odoo/src/odoo/16.0/odoo/models.py", line 4156, in _create
    cr.execute(
  File "/home/odoo/src/odoo/16.0/odoo/sql_db.py", line 321, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "account_followup_followup_line_days_uniq"
DETAIL:  Key (company_id, delay)=(1, 15) already exists.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/16.0/odoo/service/server.py", line 1299, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "<decorator-gen-16>", line 2, in new
  File "/home/odoo/src/odoo/16.0/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/16.0/odoo/modules/registry.py", line 90, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/16.0/odoo/modules/loading.py", line 523, in load_modules
    migrations.migrate_module(package, 'end')
  File "/home/odoo/src/odoo/16.0/odoo/modules/migration.py", line 189, in migrate_module
    migrate(self.cr, installed_version)
  File "/tmp/tmpcbk05i10/migrations/account_followup/16.0.1.0/end-migrate.py", line 18, in migrate
    util.update_record_from_xml(cr, "account_followup.demo_followup_line1")
  File "/tmp/tmpcbk05i10/migrations/util/records.py", line 729, in update_record_from_xml
    __update_record_from_xml(
  File "/tmp/tmpcbk05i10/migrations/util/records.py", line 864, in __update_record_from_xml
    importer.parse(new_root, **kw)
  File "/home/odoo/src/odoo/16.0/odoo/tools/convert.py", line 749, in parse
    self._tag_root(de)
  File "/home/odoo/src/odoo/16.0/odoo/tools/convert.py", line 698, in _tag_root
    f(rec)
  File "/home/odoo/src/odoo/16.0/odoo/tools/convert.py", line 711, in _tag_root
    raise ParseError('while parsing %s:%s, somewhere inside\n%s' % (
odoo.tools.convert.ParseError: while parsing None:47, somewhere inside
<record id="demo_followup_line1" model="account_followup.followup.line" forcecreate="False">
            <field name="name">15 Days</field>
            <field name="delay">15</field>
            <field name="company_id" ref="base.main_company"/>
            <field name="send_email">True</field>
            <field name="mail_template_id" ref="email_template_followup_1"/>
        </record>
```

closes odoo/upgrade#5636

Signed-off-by: Christophe Simonis (chs) <chs@odoo.com>