[FIX] data_merge/{0.0.0, saas~14.4}: Ensure xmlid for merge rules
The fix applied in https://github.com/odoo/upgrade/pull/3073 can actually
be applied to all versions above v14 as some dbs fail while
upgrading to saas~15.x.

If the client deletes some record from `data_merge.rule` and creates it with
the the same data, when they are re-created during the upgrade a violation of
`data_merge_rule_uniq_model_id_field_id` will happen.

By remapping the xmlids we avoid that problem.

upg-213605

```
  File "/home/odoo/src/odoo/saas-15.2/odoo/tools/convert.py", line 692, in _tag_root
    f(rec)
  File "/home/odoo/src/odoo/saas-15.2/odoo/tools/convert.py", line 593, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/home/odoo/src/odoo/saas-15.2/odoo/models.py", line 4476, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/home/odoo/src/odoo/saas-15.2/odoo/models.py", line 4399, in _load_records_create
    return self.create(values)
  File "<decorator-gen-122>", line 2, in create
  File "/home/odoo/src/odoo/saas-15.2/odoo/api.py", line 410, in _model_create_multi
    return create(self, arg)
  File "/tmp/tmpwelckadr/migrations/base/0.0.0/pre-models-match_uniq.py", line 24, in create
    return super().create(vals_list)
  File "<decorator-gen-68>", line 2, in create
  File "/home/odoo/src/odoo/saas-15.2/odoo/api.py", line 410, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/saas-15.2/odoo/addons/base/models/ir_fields.py", line 613, in create
    recs = super().create(vals_list)
  File "<decorator-gen-16>", line 2, in create
  File "/home/odoo/src/odoo/saas-15.2/odoo/api.py", line 410, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/saas-15.2/odoo/models.py", line 4063, in create
    records = self._create(data_list)
  File "/home/odoo/src/odoo/saas-15.2/odoo/models.py", line 4225, in _create
    cr.execute(
  File "/home/odoo/src/odoo/saas-15.2/odoo/sql_db.py", line 353, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "data_merge_rule_uniq_model_id_field_id"
DETAIL:  Key (model_id, field_id)=(1, 935) already exists.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/saas-15.2/odoo/service/server.py", line 1246, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "<decorator-gen-12>", line 2, in new
  File "/home/odoo/src/odoo/saas-15.2/odoo/tools/func.py", line 69, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/saas-15.2/odoo/modules/registry.py", line 88, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/saas-15.2/odoo/modules/loading.py", line 478, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/home/odoo/src/odoo/saas-15.2/odoo/modules/loading.py", line 371, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/odoo/src/odoo/saas-15.2/odoo/modules/loading.py", line 230, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/home/odoo/src/odoo/saas-15.2/odoo/modules/loading.py", line 71, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/home/odoo/src/odoo/saas-15.2/odoo/tools/convert.py", line 757, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/home/odoo/src/odoo/saas-15.2/odoo/tools/convert.py", line 823, in convert_xml_import
    obj.parse(doc.getroot())
  File "/home/odoo/src/odoo/saas-15.2/odoo/tools/convert.py", line 743, in parse
    self._tag_root(de)
  File "/home/odoo/src/odoo/saas-15.2/odoo/tools/convert.py", line 692, in _tag_root
    f(rec)
  File "/home/odoo/src/odoo/saas-15.2/odoo/tools/convert.py", line 705, in _tag_root
    raise ParseError('while parsing %s:%s, somewhere inside\n%s' % (
odoo.tools.convert.ParseError: while parsing /home/odoo/src/enterprise/saas-15.2/data_merge/data/data_merge_data.xml:22, somewhere inside
<record model="data_merge.rule" id="data_merge_field_res_partner_email">
            <field name="model_id" ref="data_merge_model_res_partner"/>
            <field name="field_id" ref="base.field_res_partner__email"/>
            <field name="match_mode">accent</field>
        </record>
```

closes odoo/upgrade#3400

Signed-off-by: Christophe Simonis <chs@odoo.com>