[FIX] base@tests: crawler, name_get as sudo
This is the same than in 68f4f99b750e593b0c846a876444f299fd9ea480

```
2021-02-22 18:16:34,139 3821 ERROR db_7890 odoo.addons.base.maintenance.migrations.base.testsodoo.upgrade.base.tests.test_mock_crawl: Adding menu ('stock.product_product_menu', 441, 'Inventory > Master Data > Product Variants', 649) to the failing menus
Traceback (most recent call last):
  File "/tmp/tmpq2aodqch/migrations/base/tests/test_mock_crawl.py", line 155, in crawl_menu
    self.mock_action(action_vals)
  File "/tmp/tmpq2aodqch/migrations/base/tests/test_mock_crawl.py", line 234, in mock_action
    mock_method(model, view, fields_list, domain, group_by)
  File "/tmp/tmpq2aodqch/migrations/base/tests/test_mock_crawl.py", line 262, in mock_view_form
    model.env[model._fields[fname].comodel_name].browse(data[fname]).read(["display_name"])
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 3021, in read
    self._read(stored_fields)
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 3183, in _read
    raise self.env['ir.rule']._make_access_error('read', forbidden)
odoo.exceptions.AccessError: Due to security restrictions, you are not allowed to access 'Inventory Routes' (stock.location.route) records.
```

upg-7890

closes odoo/upgrade#2194

Signed-off-by: Denis Ledoux (dle) <dle@odoo.com>