[FIX] sales_team/saas~14.2: add only internal users as team members
Generally speaking we are not allowed to add portal users as team
members in sales teams _but_ when a user is moved from internal to
portal in 14.0 there is not issue. On 15.0, there is.

The details:
* Start with a clean DB with only `sale` installed
* Create a second company `Comp2`
* Create an internal user `Dummy` of `Comp2`
* Allow admin to both companies
* Create a sale team `Team2` without any company assigned
* Add both admin and `Dummy` to `Team2`
* Change user `Dummy` from internal to portal
  So far this won't raise any error while opening the sale teams, not even
for Team2.
* Migrate to 15.0
We'll get a traceback upon access to Team2.

The reason is that we add `Dummy` to crm_team_member even though it
should have been cleared from it. This maybe needs a fix in standard
(i.e. clear the `sale_team_id` for portal users) but for migration
purposes we could just leave them out of crm_team_member.

Example traceback:
```
 Traceback (most recent call last):
   File "/tmp/tmpwjc8b89y/migrations/base/tests/test_mock_crawl.py", line 182, in crawl_menu
    self.mock_action(action_vals)
   File "/tmp/tmpwjc8b89y/migrations/base/tests/test_mock_crawl.py", line 293, in mock_action
    mock_method(model, view, fields_list, domain, group_by)
   File "/tmp/tmpwjc8b89y/migrations/base/tests/test_mock_crawl.py", line 383, in mock_view_kanban
    self.mock_web_search_read(model, view, [domain], fields_list)
   File "/tmp/tmpwjc8b89y/migrations/base/tests/test_mock_crawl.py", line 442, in mock_web_search_read
    data = model.search_read(domain=domain, fields=fields_list, limit=80)
   File "/home/odoo/src/odoo/15.0/odoo/models.py", line 5036, in search_read
    result = records.read(fields, **read_kwargs)
   File "/home/odoo/src/odoo/15.0/odoo/models.py", line 3227, in read
    return self._read_format(fnames=fields, load=load)
   File "/home/odoo/src/odoo/15.0/odoo/models.py", line 3247, in _read_format
    vals[name] = convert(record[name], record, use_name_get)
   File "/home/odoo/src/odoo/15.0/odoo/models.py", line 5874, in __getitem__
    return self._fields[key].__get__(self, type(self))
   File "/home/odoo/src/odoo/15.0/odoo/fields.py", line 2603, in __get__
    return super().__get__(records, owner)
   File "/home/odoo/src/odoo/15.0/odoo/fields.py", line 1150, in __get__
    return self.convert_to_record(value, record)
   File "/home/odoo/src/odoo/15.0/odoo/fields.py", line 3200, in convert_to_record
    corecords = corecords.filtered(Comodel._active_name).with_prefetch(prefetch_ids)
   File "/home/odoo/src/odoo/15.0/odoo/models.py", line 5474, in filtered
    self.mapped(name)
   File "/home/odoo/src/odoo/15.0/odoo/models.py", line 5436, in mapped
    recs = recs._fields[name].mapped(recs)
   File "/home/odoo/src/odoo/15.0/odoo/fields.py", line 1176, in mapped
    self.__get__(first(remaining), type(remaining))
   File "/home/odoo/src/odoo/15.0/odoo/fields.py", line 1085, in __get__
    record._fetch_field(self)
   File "/home/odoo/src/odoo/15.0/odoo/models.py", line 3276, in _fetch_field
    self._read(fnames)
   File "/home/odoo/src/odoo/15.0/odoo/addons/base/models/res_users.py", line 449, in _read
    super(Users, self)._read(fields)
   File "/home/odoo/src/odoo/15.0/odoo/models.py", line 3387, in _read
    raise self.env['ir.rule']._make_access_error('read', forbidden)
 odoo.exceptions.AccessError: Due to security restrictions, you are not allowed to access 'Users' (res.users) records.
```
The field that raises the error is `member_ids`
https://github.com/odoo/odoo/blob/49c7bd39826b428430c08c5faedca51dde9e2359/addons/sales_team/models/crm_team.py#L95-L99
https://github.com/odoo/odoo/blob/49c7bd39826b428430c08c5faedca51dde9e2359/addons/sales_team/models/crm_team.py#L127-L129

From the db:
```
90103_afu=> select d.name from res_groups_users_rel r join ir_model_data d on d.res_id=r.gid and d.model='res.groups' and module in ('base') where r.uid=2
+--------------+
| name         |
|--------------|
| group_portal |
+--------------+
90103_afu=> select id,login,sale_team_id from res_users where id=2
+------+----------------------+----------------+
| id   | login                | sale_team_id   |
|------+----------------------+----------------|
| 2    | publishing@ovento.ch | 1              |
+------+----------------------+----------------+
```

upg-90103
upg-45684

closes odoo/upgrade#3145

Signed-off-by: Christophe Simonis <chs@odoo.com>