[FIX] base@0.0.0: remove custom view from window actions if disabled
Request #47373
After upgrade, a custom (primary) view is disabled because it uses a field
which is no longer there.

The view was referenced in the `view_id` fields in a window action,
to "override" the one loaded by default.
Even if the view is disabled, it still tried to load this view specifically,
and therefore the menu/action was failing after upgrade.

The issue has been detected by the crawler unit test:

```
2020-05-07 12:43:58,430 1855 INFO template_58020c8c0deb_47373_13.0 odoo.addons.base.maintenance.migrations.base.testsodoo.upgrade.base.tests.test_mock_crawl: Mocking menu Inventory > Reporting > Location
 Inventory Valuation
2020-05-07 12:43:58,440 1855 INFO template_58020c8c0deb_47373_13.0 odoo.addons.base.models.ir_ui_view: Field `compute_at_date` does not exist

Error context:
View `Location Valuation Report`
[view_id: 1748, xml_id: perso_ebike.view_stock_quantity_history, model: stock.quantity.history, parent_id: n/a]
2020-05-07 12:43:58,441 1855 ERROR template_58020c8c0deb_47373_13.0 odoo.addons.base.maintenance.migrations.base.testsodoo.upgrade.base.tests.test_mock_crawl: Adding menu ('perso_ebike.menu_location_valu
ation', 390, 'Inventory > Reporting > Location Inventory Valuation', 611) to the failing menus
Traceback (most recent call last):
  File "/src/odoo/13.0/odoo/addons/base/maintenance/migrations/base/tests/test_mock_crawl.py", line 126, in crawl_menu
    self.mock_action(action_vals)
  File "/src/odoo/13.0/odoo/addons/base/maintenance/migrations/base/tests/test_mock_crawl.py", line 170, in mock_action
    action["views"], options={"action_id": action.get("id"), "toolbar": True, "load_filters": True}
  File "/src/odoo/13.0/odoo/models.py", line 1441, in load_views
    for [v_id, v_type] in views
  File "/src/odoo/13.0/odoo/models.py", line 1441, in <dictcomp>
    for [v_id, v_type] in views
  File "/src/odoo/13.0/addons/web/models/models.py", line 206, in fields_view_get
    r = super().fields_view_get(view_id, view_type, toolbar, submenu)
  File "/src/odoo/13.0/odoo/models.py", line 1528, in fields_view_get
    xarch, xfields = View.postprocess_and_fields(self._name, etree.fromstring(result['arch']), view_id)
  File "/src/odoo/13.0/odoo/addons/base/models/ir_ui_view.py", line 987, in postprocess_and_fields
    self.raise_view_error(message, view_id)
  File "/src/odoo/13.0/odoo/addons/base/models/ir_ui_view.py", line 614, in raise_view_error
    raise ValueError(message)
ValueError: Field `compute_at_date` does not exist

Error context:
View `Location Valuation Report`
[view_id: 1748, xml_id: perso_ebike.view_stock_quantity_history, model: stock.quantity.history, parent_id: n/a]
```

closes odoo/upgrade#1166

Signed-off-by: Denis Ledoux (dle) <dle@odoo.com>