[FIX] stock/7.saas~5.1.1: remove forgotten view
This view was removed on odoo/odoo@cd543d96e01c74b05b762c9f5142a4264b5ae0f4

Observed on https://upgradeci.odoo.com/upgradeci/run/10723
```
2021-05-18 13:44:32,707 80 ERROR matt-stock openerp.addons.base.ir.ir_ui_view: Field `product_uom` does not exist

Error context:
View `stock.inventory.line.form`
[view_id: 481, xml_id: stock.view_inventory_line_form, model: stock.inventory.line, parent_id: n/a]
2021-05-18 13:44:32,707 80 ERROR matt-stock openerp.tools.yaml_import: Field `product_uom` does not exist

Error context:
View `stock.inventory.line.form`
[view_id: 481, xml_id: stock.view_inventory_line_form, model: stock.inventory.line, parent_id: n/a]
Traceback (most recent call last):
  File "/tmp/tmp642aaags/odoo/8.0/openerp/tools/yaml_import.py", line 901, in process
    self._process_node(node)
  File "/tmp/tmp642aaags/odoo/8.0/openerp/tools/yaml_import.py", line 912, in _process_node
    self.process_record(node)
  File "/tmp/tmp642aaags/odoo/8.0/openerp/tools/yaml_import.py", line 327, in process_record
    view_info = model.fields_view_get(self.cr, SUPERUSER_ID, varg, 'form', context)
  File "/tmp/tmp642aaags/odoo/8.0/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/tmp/tmp642aaags/odoo/8.0/openerp/models.py", line 1549, in fields_view_get
    xarch, xfields = View.postprocess_and_fields(cr, uid, self._name, etree.fromstring(result['arch']), view_id, context=ctx)
  File "/tmp/tmp642aaags/odoo/8.0/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/tmp/tmp642aaags/odoo/8.0/openerp/addons/base/ir/ir_ui_view.py", line 845, in postprocess_and_fields
    self.raise_view_error(cr, user, message, view_id, context)
  File "/tmp/tmp642aaags/odoo/8.0/openerp/api.py", line 268, in wrapper
    return old_api(self, *args, **kwargs)
  File "/tmp/tmp642aaags/odoo/8.0/openerp/addons/base/ir/ir_ui_view.py", line 368, in raise_view_error
    raise AttributeError(message)
AttributeError: Field `product_uom` does not exist
```

upg-14143
opw-2526962