[FIX] util/modules: remove records in order
The optimization done in b80536ae has an unexpected side effect. We need
to remove the records in reverse order as they were added. This is
needed to avoid dependencies between them.
https://github.com/odoo/upgrade/blob/568b6822edb4194b1f2be3dc2268d218664e0182/migrations/util/modules.py#L124

For example in upg-368735 with the approach in b80536ae we will try to
remove a view _before_ removing a record that uses it with
`required=True` (and that subsequently must have been added _after_).
https://github.com/odoo/odoo/blob/f48b754cef9e778423c51ee69dd19ee3e8611eb6/addons/planner/models/planner.py#L25

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/9.0/openerp/service/server.py", line 894, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/home/odoo/src/odoo/9.0/openerp/modules/registry.py", line 386, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/src/odoo/9.0/openerp/modules/loading.py", line 318, in load_modules
    report=report, models_to_check=models_to_check
  File "/home/odoo/src/odoo/9.0/openerp/modules/loading.py", line 136, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/home/odoo/src/odoo/9.0/openerp/modules/migration.py", line 160, in migrate_module
    migrate(self.cr, installed_version)
  File "/home/odoo/src/odoo/9.0/openerp/addons/base/maintenance/migrations/base/9.0.1.3/pre-10-module-changes.py", line 262, in migrate
    util.remove_module(cr, m)
  File "/home/odoo/src/odoo/9.0/openerp/addons/base/maintenance/migrations/util/modules.py", line 215, in remove_module
    uninstall_module(cr, module)
  File "/home/odoo/src/odoo/9.0/openerp/addons/base/maintenance/migrations/util/modules.py", line 136, in uninstall_module
    remove_view(cr, view_id=res_id, silent=True)
  File "/home/odoo/src/odoo/9.0/openerp/addons/base/maintenance/migrations/util/records.py", line 132, in remove_view
    remove_records(cr, "ir.ui.view", [view_id])
  File "/home/odoo/src/odoo/9.0/openerp/addons/base/maintenance/migrations/util/records.py", line 309, in remove_records
    cr.execute('DELETE FROM "{}" WHERE id IN %s'.format(table), [ids])
  File "/home/odoo/src/odoo/9.0/openerp/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/home/odoo/src/odoo/9.0/openerp/sql_db.py", line 233, in execute
    res = self._obj.execute(query, params)
IntegrityError: null value in column "view_id" violates not-null constraint
DETAIL:  Failing row contains (1, 67, 1, 2015-06-27 12:12:46.335393, Sales strategy planner, planner_crm, null, 1, 2015-06-27 12:12:46.335393, 5, null, <p>Plan your sales strategy: objectives, leads, KPIs, and much m...).
CONTEXT:  SQL statement "UPDATE ONLY "public"."planner_planner" SET "view_id" = NULL WHERE $1 OPERATOR(pg_catalog.=) "view_id""
```

We can avoid the issue by removing records in the order they are fetched
by the query. While still grouping consecutive records that can be
batched together.

upg-368735

closes odoo/upgrade#3742

Signed-off-by: Christophe Simonis <chs@odoo.com>