[FIX] documents@saas-12.1: force to noupdate `documents.document_action`
In odoo/odoo@3e4ef5054822672e6b7f735556afe1efc8f229e4
The `documents.document_action` record changes
of `res_model` from `ir.attachement` to `documents.document`
and its domain is removed.

There are numerous cases where this action is set
to `noupdate` in user databases.
I am not 100% sure why, but that might be due to
Studio customization passing this menu to noupdate as soon
as you touch it, or even attempt to touch it.

If the action does not get updated,
the `res_model` is not changed as expected,
and you simply can't open the `Documents` menu.

 - odoo/migration-scripts@a929a0b29031cecab92c3357033fd7eff1856b98
 - odoo/migration-scripts@c3cb49f168353e33e2263dd36747c5b819bc331d
 - odoo/migration-scripts@5076038efda8e84054e4ef43c5264fb05db5d0d4
 - odoo/migration-scripts@175b92a62be6c79e69865912451155bcbcdd7b6a
 - odoo/migration-scripts@367fe44c7a0753a4cd8f04b248d50b4a52203648
 - odoo/migration-scripts@68d64e7f3df6dbddf5981f06377533192836015a
 - odoo/migration-scripts@bbd6e3ee8cc5a2086f0df50f88316851929edcfc
 - odoo/migration-scripts@8ef99dd1c60a83ae8621914e0274eb306c973482

There is no need to handle manually the domain removal thanks to
odoo/odoo@7ba8b45b625005e080db61ca70466d4057b8782e

I came open this thanks to the crawler unit tests:
```
2020-05-12 15:45:50,012 1580 INFO template_TvGh_13.0 odoo.addons.base.maintenance.migrations.base.testsodoo.upgrade.base.tests.test_mock_crawl: Mocking menu Documents > Documents
2020-05-12 15:45:50,047 1580 INFO template_TvGh_13.0 odoo.addons.base.models.ir_ui_view: Field `favorited_ids` does not exist

Error context:
View `documents.document kanban`
[view_id: 1843, xml_id: documents.document_view_kanban, model: documents.document, parent_id: n/a]
2020-05-12 15:45:50,049 1580 ERROR template_TvGh_13.0 odoo.addons.base.maintenance.migrations.base.testsodoo.upgrade.base.tests.test_mock_crawl: Adding menu ('documents.dashboard', 421, 'Documents > Documents', 595) to the failing menus
Traceback (most recent call last):
  File "/mnt/odoo_src/13.0/odoo/addons/base/maintenance/migrations/base/tests/test_mock_crawl.py", line 126, in crawl_menu
    self.mock_action(action_vals)
  File "/mnt/odoo_src/13.0/odoo/addons/base/maintenance/migrations/base/tests/test_mock_crawl.py", line 170, in mock_action
    action["views"], options={"action_id": action.get("id"), "toolbar": True, "load_filters": True}
  File "/mnt/odoo_src/13.0/odoo/models.py", line 1441, in load_views
    for [v_id, v_type] in views
  File "/mnt/odoo_src/13.0/odoo/models.py", line 1441, in <dictcomp>
    for [v_id, v_type] in views
  File "/mnt/odoo_src/13.0/addons/web/models/models.py", line 206, in fields_view_get
    r = super().fields_view_get(view_id, view_type, toolbar, submenu)
  File "/mnt/odoo_src/13.0/odoo/models.py", line 1528, in fields_view_get
    xarch, xfields = View.postprocess_and_fields(self._name, etree.fromstring(result['arch']), view_id)
  File "/mnt/odoo_src/13.0/odoo/addons/base/models/ir_ui_view.py", line 987, in postprocess_and_fields
    self.raise_view_error(message, view_id)
  File "/mnt/odoo_src/13.0/odoo/addons/base/models/ir_ui_view.py", line 614, in raise_view_error
    raise ValueError(message)
ValueError: Field `favorited_ids` does not exist

Error context:
View `documents.document kanban`
[view_id: 1843, xml_id: documents.document_view_kanban, model: documents.document, parent_id: n/a]
```

closes odoo/upgrade#1183

Signed-off-by: Denis Ledoux (dle) <dle@odoo.com>