[FIX] util.remove_field: check column exists
```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/8.0/openerp/service/server.py", line 941, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/home/odoo/src/odoo/8.0/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/src/odoo/8.0/openerp/modules/loading.py", line 297, in load_modules
    loaded_modules, processed_modules = load_module_graph(cr, graph, status, perform_checks=update_module, report=report)
  File "/home/odoo/src/odoo/8.0/openerp/modules/loading.py", line 142, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/home/odoo/src/odoo/8.0/openerp/modules/migration.py", line 171, in migrate_module
    migrate(self.cr, pkg.installed_version)
  File "/home/odoo/src/odoo/8.0/openerp/addons/base/maintenance/migrations/base/7.saas~3.1.3/pre-10-change-modules.py", line 15, in migrate
    util.remove_module(cr, 'portal_hr_employees')
  File "/home/odoo/src/odoo/8.0/openerp/addons/base/maintenance/migrations/util/modules.py", line 195, in remove_module
    uninstall_module(cr, module)
  File "/home/odoo/src/odoo/8.0/openerp/addons/base/maintenance/migrations/util/modules.py", line 153, in uninstall_module
    remove_field(cr, model, name)
  File "/home/odoo/src/odoo/8.0/openerp/addons/base/maintenance/migrations/util/fields.py", line 170, in remove_field
    [r"\m{}\M".format(fieldname)],
  File "/home/odoo/src/odoo/8.0/openerp/sql_db.py", line 171, in wrapper
    return f(self, *args, **kwargs)
  File "/home/odoo/src/odoo/8.0/openerp/sql_db.py", line 247, in execute
    res = self._obj.execute(query, params)
ProgrammingError: column "depends" does not exist
LINE 1: SELECT id,model,depends FROM ir_model_fields WHERE state='ma...
```

upg-22690

closes odoo/upgrade#2761

Signed-off-by: Christophe Simonis <chs@odoo.com>