[FIX] sale_timesheet/saas~14.5: removed action qweb
In v15 the qweb view for project.project is removed.
we removed standard action with view mode qweb
but custom actions defined with qweb mode no longer work
since qweb view for project.project removed,
It doesn't support a default qweb view.

upg-419623

see : https://github.com/odoo/odoo/commit/2f77c86275657f8a96aa63a1a5948bf38a2bf1b3

we have other request specific fix:
https://github.com/odoo/upgrade-specific/pull/4250
https://github.com/odoo/upgrade-specific/pull/1891
https://github.com/odoo/upgrade-specific/pull/3551

```
('studio_customization.chantiers_tableau_de_e13c1f49-8f79-4749-9ce9-34ff10b3680c', 1229, 'Project > Chantier > Tableau de bord chantier', 1851):
 Traceback (most recent call last):
   File "/home/odoo/src/odoo/15.0/odoo/models.py", line 1684, in _fields_view_get
    arch_etree = getattr(self, '_get_default_%s_view' % view_type)()
 AttributeError: 'project.project' object has no attribute '_get_default_qweb_view'

During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "/tmp/tmpd2nt89u5/migrations/base/tests/test_mock_crawl.py", line 220, in crawl_menu
    self.mock_action(action_vals)
   File "/tmp/tmpd2nt89u5/migrations/base/tests/test_mock_crawl.py", line 290, in mock_action
    views = get_views(
   File "/home/odoo/src/odoo/15.0/odoo/models.py", line 1629, in load_views
    result['fields_views'] = {
   File "/home/odoo/src/odoo/15.0/odoo/models.py", line 1630, in <dictcomp>
    v_type: self.fields_view_get(v_id, v_type if v_type != 'list' else 'tree',
   File "/home/odoo/src/odoo/15.0/addons/web/models/models.py", line 249, in fields_view_get
    r = super().fields_view_get(view_id, view_type, toolbar, submenu)
   File "/home/odoo/src/odoo/15.0/odoo/models.py", line 1713, in fields_view_get
    result = self._fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
   File "/home/odoo/src/odoo/15.0/odoo/models.py", line 1689, in _fields_view_get
    raise UserError(_("No default view of type '%s' could be found !", view_type))
 odoo.exceptions.UserError: Aucune vue par défaut de type "qweb" n'a pu être trouvée!
```

closes odoo/upgrade#4100

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>