[FIX] l10n_ec_reports_ats/saas~16.2: removed deprecated model
After saas-16.2, `l10n_ec.tax.report.ats.handler` model
has been deprecated so need to remove it by script.

see:
https://github.com/odoo/enterprise/commit/3ba27f9fd61e453f7df269a8ab2b68cdbdd5f788#diff-5afc47564cea79968373247084d3771bd723b739f2bda8d9723d674433500458R23

TGB: https://upgrade.odoo.com/web#id=1050&cids=1&menu_id=107&action=178&model=upgrade.request.traceback.group&view_type=form

12 Upgrade Requests failed.

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/17.0/odoo/service/server.py", line 1302, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "<decorator-gen-16>", line 2, in new
  File "/home/odoo/src/odoo/17.0/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/17.0/odoo/modules/registry.py", line 113, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/17.0/odoo/modules/loading.py", line 536, in load_modules
    env['ir.model.data']._process_end(processed_modules)
  File "/tmp/tmpnuaitlgj/migrations/base/0.0.0/pre-models-no-model-data-delete.py", line 103, in _process_end
    return super(IrModelData, self)._process_end(modules)
  File "/home/odoo/src/odoo/17.0/odoo/addons/base/models/ir_model.py", line 2562, in _process_end
    self._process_end_unlink_record(record)
  File "/home/odoo/src/odoo/17.0/odoo/addons/base/models/ir_model.py", line 2491, in _process_end_unlink_record
    record.unlink()
  File "/home/odoo/src/odoo/17.0/addons/mail/models/ir_model.py", line 70, in unlink
    return super(IrModel, self).unlink()
  File "/tmp/tmpnuaitlgj/migrations/base/0.0.0/pre-models-ir_model.py", line 38, in unlink
    raise util.MigrationError(message)
odoo.upgrade.util.exceptions.UpgradeError: 💥 It looks like you forgot to call `util.remove_model` on the following models: l10n_ec.tax.report.ats.handler
```

closes odoo/upgrade#5661

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>