[FIX] website_sale/16.0: Resetting cowed views
Summary of changes:

Add class in website_sale js_sale o_wsale_product_page

Clear Description:

In version 16.0 changed the class from js_sale to
"js_sale o_wsale_product_page so changed the class
for all the website_salecowed views.

Below is the reference to the PR in which
the class "js_sale" is changed:
https://github.com/odoo/odoo/blob/saas-15.2
/addons/website_sale/views/templates.xml#L602

Here is the link to the view where the class
"js_sale o_wsale_product_page" has been changed :
https://github.com/odoo/odoo/blob/16.0/addons
/website_sale/views/templates.xml#L1078

Here is the link reference that adds one view in
standard and add the class in this view
https://github.com/odoo/odoo/blob/16.0
/addons/website_sale/views/templates.xml#L1078

Traceback

  Traceback (most recent call last):
  File "/home/odoo/src/odoo/16.0/odoo/http.py", line 1583, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/home/odoo/src/odoo/16.0/odoo/service/model.py", line 134, in retrying
    result = func()
  File "/home/odoo/src/odoo/16.0/odoo/http.py", line 1612, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/home/odoo/src/odoo/16.0/odoo/http.py", line 1725, in dispatch
    return self.request.registry['ir.http']._dispatch(endpoint)
  File "/home/odoo/src/odoo/16.0/addons/website/models/ir_http.py",
  line 235, in _dispatch
    response = super()._dispatch(endpoint)
  File "/home/odoo/src/odoo/16.0/odoo/addons/base/models/ir_http.py",
  line 146, in _dispatch
    result.flatten()
  File "/home/odoo/src/odoo/16.0/odoo/http.py", line 1098, in flatten
    self.response.append(self.render())
  File "/home/odoo/src/odoo/16.0/odoo/http.py", line 1090, in render
    return request.env["ir.ui.view"]._render_template
  (self.template, self.qcontext)
  File "/home/odoo/src/odoo/16.0/addons/website/models/ir_ui_view.py",
  line 418, in _render_template
    return super()._render_template(template, values=values)
  File "/home/odoo/src/odoo/16.0/odoo/addons/base/models/ir_ui_view.py",
  line 2119, in _render_template
    return self.env['ir.qweb']._render(template, values)
  File "/home/odoo/src/odoo/16.0/odoo/tools/profiler.py",
  line 292, in _tracked_method_render
    return method_render(self, template, values, **options)
  File "/home/odoo/src/odoo/16.0/odoo/addons/base/models/ir_qweb.py",
  line 567, in _render
    rendering = render_template(irQweb, values)
  File "<3766>", line 5, in not_found_template
  ValueError: Element '<xpath expr="//div[hasclass
  (&#34;o_wsale_product_page&#34;)]">'
  cannot be located in parent view

Reference:

Link to the task - opw 3168556
Link to request - upg 507723

closes odoo/upgrade#4311

Signed-off-by: Christophe Simonis <chs@odoo.com>