[FIX] point_of_sale@saas~11.5: use an existing column
Fixes this issue:
File "/src/odoo/12.0/odoo/addons/base/maintenance/migrations/point_of_sale/saas~11.5.1.0.1/post-migrate.py", line 114, in migrate
  """)
psycopg2.ProgrammingError: column "agg" does not exist