[FIX] account/saas~13.{1,4}: Change custom payment types
This is a similar fix than https://github.com/odoo/upgrade/pull/1398

During the payment refactoring to v14, the dbs that contain custom payment types
will rise a `MigrationError` in
https://github.com/odoo/upgrade/blob/c59dcaf38246ae54be68bb544d632ad980d3dc89/migrations/account/saas~13.3.1.1/end-migrate.py#L4-L11
Even if the error was not raised, another error would happen during the
recomputation of the fields.

The payments are temporarily changed to the default standard values to allow
clients to keep their custom data.

upg-281741
upg-280018
upg-163532
upg-163519

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/14.0/odoo/service/server.py", line 1199, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/odoo/src/odoo/14.0/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/src/odoo/14.0/odoo/modules/loading.py", line 475, in load_modules
    migrations.migrate_module(package, 'end')
  File "/home/odoo/src/odoo/14.0/odoo/modules/migration.py", line 180, in migrate_module
    migrate(self.cr, installed_version)
  File "/tmp/tmp1_j7qzqg/migrations/account/saas~13.3.1.1/end-migrate.py", line 11, in migrate
    raise util.MigrationError("Only 'inbound' and 'outbound' are valid values for payment_type on account_payment.")
odoo.upgrade.util.exceptions.MigrationError: Only 'inbound' and 'outbound' are valid values for payment_type on account_payment.
```

closes odoo/upgrade#3483

Signed-off-by: Christophe Simonis <chs@odoo.com>