[FIX] l10n_ch_reports: 311a/b have been renamed 312a/b in stable
The financial report lines
 - `financial_report_line_chtax_311a`
 - `financial_report_line_chtax_311b`
have been renamed
 - `financial_report_line_chtax_312a`
 - `financial_report_line_chtax_312b`

in stable with the commit odoo/enterprise@67ee525a480e056fbb7c872dfa774b504cddefbb

The database of the observed case is in 12.0,
and we can see the report line is still
named "311a",
```
5828=> SELECT name, code FROM account_financial_html_report_line WHERE code = 'CHTAX_312a';
-[ RECORD 1 ]---------------------------------------
name | 311a Chiffre d'affaires imposable a 2.5% (TR)
```
has still as ir.model.data "311a"
```
5828=> SELECT module, name FROM ir_model_data WHERE model = 'account.financial.html.report.line' and res_id = 78;
-[ RECORD 1 ]----------------------------
module | l10n_ch_reports
name   | financial_report_line_chtax_311a
```
but has the 312a code:
```
5828=> SELECT code FROM account_financial_html_report_line WHERE code = 'CHTAX_312a';
-[ RECORD 1 ]----
code | CHTAX_312a
```
Therefore leading to the below exception on upgrade:
```
  File "/home/odoo/src/odoo/12.0/odoo/models.py", line 3822, in _load_records_create
    return self.create(values)
  File "<decorator-gen-3>", line 2, in create
  File "/home/odoo/src/odoo/12.0/odoo/api.py", line 462, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/12.0/odoo/models.py", line 3603, in create
    records = self._create(data_list)
  File "/home/odoo/src/odoo/12.0/odoo/models.py", line 3703, in _create
    cr.execute(query, params)
  File "/home/odoo/src/odoo/12.0/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/home/odoo/src/odoo/12.0/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
odoo.tools.convert.ParseError: "duplicate key value violates unique constraint "account_financial_html_report_line_code_uniq"
DETAIL:  Key (code)=(CHTAX_312a) already exists.
" while parsing /home/odoo/src/enterprise/12.0/l10n_ch_reports/data/account_financial_html_report_data.xml:158, near
<record id="financial_report_line_chtax_312a" model="account.financial.html.report.line">
        <field name="name">312a Chiffre d'affaires imposable a 2.5% (TR)</field>
        <field name="code">CHTAX_312a</field>
        <field name="sequence" eval="5"/>
        <field name="level" eval="3"/>
        <field name="domain" eval="[('tax_ids.tag_ids', 'in', [ref('l10n_ch.vat_tag_311_a')])]"/>
        <field name="formulas">balance = - sum.balance</field>
        <field name="parent_id" ref="financial_report_line_chtax_CAI"/>
        <field name="show_domain">foldable</field>
        <field name="groupby">account_id</field>
        <field name="special_date_changer">strict_range</field>
    </record>
```

Having the name "311a" while having the code "312a" is not something which could have happen automatically,
with a "-u", but this is probably the result of the user trying to solve his report
manually because of the fact this change/rename of xmlid in stable
should never have occurred in the first placeand leaded to issues.

Nevertheless, despite this is the result of a manual intervention,
we had multiple times the case during upgrades, solved in specific scripts:
- odoo/migration-scripts@5ce975d2701a38aec9a8f4bdf500fc11ea150d27
- odoo/migration-scripts@18b0705a6b154ee3b35dfc1ddec9bb36eb46880e
- odoo/migration-scripts@dd4974dec448ccff3d4c02467c9136871a71656a

Hence the hereby suggestion to solve this issue in generic scripts.

It has to be done in an `init-` script, because the script
needs to be ran before the upgrade platform perform the "-u" of the `l10n` report
module within the current database version.
In other words, if the customer attempted to upgrade the `l10n_ch_reports`
in its production, he would have had the same issue as well :).

upg-5828

closes odoo/upgrade#2131

Signed-off-by: Christophe Simonis <chs@odoo.com>