[IMP] mock_crawler: include tracebacks of failing views
Failing views at the very end of an upgrade is a common cause of
failure for upgrade requests. The last traceback for those cases is not
useful to identify the causes since it just prints a summary of the
failing menus.

Here we add the traceback information from every failing view on the
diff between before/after list of failing menus.

This has the advantage that we can search on last traceback, user the
traceback groups, and rapidly check causes of failure while looking
into the request. The downside is longer text on the last traceback.

Below an example of the info that gets printed. To shorten commit
message some tracebacks were manually edited to show `...`. Still all
tracebacks are printed to convey a sense of the final message size.
```
Traceback (most recent call last):
  File "/tmp/tmpg1ao7go4/migrations/testing.py", line 218, in test_check
    self.check(value)
  File "/tmp/tmpg1ao7go4/migrations/base/tests/test_mock_crawl.py", line 86, in check
    self.assertFalse(trim(diff), msg)
AssertionError: [('account.menu_account_supplier', 202, 'Accounting > Vendors > Vendors', 53), ('account.menu_account_customer', 199, 'Accounting > Customers > Customers', 52), ('account.menu_action_invoice_tree2', 206, 'Accounting > Vendors > Bills', 338), ('account.product_product_menu_purchasable', 201, 'Accounting > Vendors > Products', 319), ('account_reports.customer_statements_menu', 297, 'Accounting > Customers > Follow-up Reports', 474), ('account.menu_action_account_bank_journal_form', 191, 'Accounting > Configuration > Accounting > Add a Bank Account', 566), ('account.menu_action_tax_adjustment', 215, 'Accounting > Accounting > Actions > Tax Adjustments', 347), ('account.product_product_menu_sellable', 200, 'Accounting > Customers > Products', 318)] is not false : At least one menu or view working before upgrade is not working after upgrade.

('account.menu_account_supplier', 202, 'Accounting > Vendors > Vendors', 53):
 Traceback (most recent call last):
   File "/home/odoo/src/odoo/13.0/odoo/api.py", line 745, in get
    value = self._data[field][record._ids[0]]
 KeyError: 53

During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "/home/odoo/src/odoo/13.0/odoo/fields.py", line 1037, in __get__
    value = env.cache.get(record, self)
   File "/home/odoo/src/odoo/13.0/odoo/api.py", line 751, in get
    raise CacheMiss(record, field)
 odoo.exceptions.CacheMiss: ('ir.actions.act_window(53,).search_view', None)

During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "/home/odoo/src/odoo/13.0/odoo/addons/base/models/ir_ui_view.py", line 671, in apply_inheritance_specs
    pre_locate=pre_locate)
   File "/home/odoo/src/odoo/13.0/odoo/tools/template_inheritance.py", line 230, in apply_inheritance_specs
    _("Element '%s' cannot be located in parent view") % tag
 ValueError: Element '<filter name="supplier">' cannot be located in parent view

During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "/tmp/tmpg1ao7go4/migrations/base/tests/test_mock_crawl.py", line 162, in crawl_menu
    [action_vals] = action_typed.read(self.action_type_fields[action.type])
   ...
   File "/home/odoo/src/odoo/13.0/odoo/addons/base/models/ir_ui_view.py", line 614, in raise_view_error
    raise ValueError(message)
 ValueError: Element '<filter name="supplier">' cannot be located in parent view

Error context:
View `customer.statements.search`
[view_id: 1193, xml_id: account_reports.customer_statements_search_view, model: res.partner, parent_id: 115]

('account.menu_account_customer', 199, 'Accounting > Customers > Customers', 52):
 Traceback (most recent call last):
   File "/home/odoo/src/odoo/13.0/odoo/api.py", line 745, in get
    value = self._data[field][record._ids[0]]
 KeyError: 52

During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "/home/odoo/src/odoo/13.0/odoo/fields.py", line 1037, in __get__
    value = env.cache.get(record, self)
   File "/home/odoo/src/odoo/13.0/odoo/api.py", line 751, in get
    raise CacheMiss(record, field)
 odoo.exceptions.CacheMiss: ('ir.actions.act_window(52,).search_view', None)

During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "/home/odoo/src/odoo/13.0/odoo/addons/base/models/ir_ui_view.py", line 671, in apply_inheritance_specs
    pre_locate=pre_locate)
   File "/home/odoo/src/odoo/13.0/odoo/tools/template_inheritance.py", line 230, in apply_inheritance_specs
    _("Element '%s' cannot be located in parent view") % tag
 ValueError: Element '<filter name="supplier">' cannot be located in parent view

During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "/tmp/tmpg1ao7go4/migrations/base/tests/test_mock_crawl.py", line 162, in crawl_menu
    [action_vals] = action_typed.read(self.action_type_fields[action.type])
    ...
   File "/home/odoo/src/odoo/13.0/odoo/addons/base/models/ir_ui_view.py", line 614, in raise_view_error
    raise ValueError(message)
 ValueError: Element '<filter name="supplier">' cannot be located in parent view

Error context:
View `customer.statements.search`
[view_id: 1193, xml_id: account_reports.customer_statements_search_view, model: res.partner, parent_id: 115]

('account.menu_action_invoice_tree2', 206, 'Accounting > Vendors > Bills', 338):
 Traceback (most recent call last):
   File "/home/odoo/src/odoo/13.0/odoo/tools/safe_eval.py", line 354, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
   File "", line 2, in <module>
 AttributeError: 'account.invoice' object has no attribute 'complete_empty_list_help'

During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "/tmp/tmpg1ao7go4/migrations/base/tests/test_mock_crawl.py", line 163, in crawl_menu
    self.mock_action(action_vals)
    ...
   File "/home/odoo/src/odoo/13.0/odoo/tools/safe_eval.py", line 354, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
   File "", line 2, in <module>
 ValueError: <class 'AttributeError'>: "'account.invoice' object has no attribute 'complete_empty_list_help'" while evaluating
"action_values = env.ref('account.action_vendor_bill_template').read()[0]\nnew_help = model.complete_empty_list_help()\naction_values.update({'help': action_values.get('help', '') + new_help})\naction = action_values"

('account.product_product_menu_purchasable', 201, 'Accounting > Vendors > Products', 319):
 Traceback (most recent call last):
   File "/tmp/tmpg1ao7go4/migrations/base/tests/test_mock_crawl.py", line 163, in crawl_menu
    self.mock_action(action_vals)
    ...
   File "/home/odoo/src/odoo/13.0/odoo/addons/base/models/ir_ui_view.py", line 614, in raise_view_error
    raise ValueError(message)
 ValueError: Field `attribute_value_ids` does not exist

Error context:
View `product.product.tree`
[view_id: 807, xml_id: account.product_product_view_tree, model: product.product, parent_id: n/a]

('account_reports.customer_statements_menu', 297, 'Accounting > Customers > Follow-up Reports', 474):
 Traceback (most recent call last):
   File "/home/odoo/src/odoo/13.0/odoo/api.py", line 745, in get
    value = self._data[field][record._ids[0]]
 KeyError: 474

During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "/home/odoo/src/odoo/13.0/odoo/fields.py", line 1037, in __get__
    value = env.cache.get(record, self)
   File "/home/odoo/src/odoo/13.0/odoo/api.py", line 751, in get
    raise CacheMiss(record, field)
 odoo.exceptions.CacheMiss: ('ir.actions.act_window(474,).search_view', None)

During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "/home/odoo/src/odoo/13.0/odoo/addons/base/models/ir_ui_view.py", line 671, in apply_inheritance_specs
    pre_locate=pre_locate)
   File "/home/odoo/src/odoo/13.0/odoo/tools/template_inheritance.py", line 230, in apply_inheritance_specs
    _("Element '%s' cannot be located in parent view") % tag
 ValueError: Element '<filter name="supplier">' cannot be located in parent view

During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "/tmp/tmpg1ao7go4/migrations/base/tests/test_mock_crawl.py", line 162, in crawl_menu
    [action_vals] = action_typed.read(self.action_type_fields[action.type])
    ...
   File "/home/odoo/src/odoo/13.0/odoo/addons/base/models/ir_ui_view.py", line 614, in raise_view_error
    raise ValueError(message)
 ValueError: Element '<filter name="supplier">' cannot be located in parent view

Error context:
View `customer.statements.search`
[view_id: 1193, xml_id: account_reports.customer_statements_search_view, model: res.partner, parent_id: 115]

('account.menu_action_account_bank_journal_form', 191, 'Accounting > Configuration > Accounting > Add a Bank Account', 566):
 Traceback (most recent call last):
   File "/home/odoo/src/odoo/13.0/odoo/tools/safe_eval.py", line 354, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
   File "", line 1, in <module>
 AttributeError: 'res.company' object has no attribute 'setting_init_bank_account_action'

During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "/tmp/tmpg1ao7go4/migrations/base/tests/test_mock_crawl.py", line 163, in crawl_menu
    self.mock_action(action_vals)
    ...
   File "", line 1, in <module>
 ValueError: <class 'AttributeError'>: "'res.company' object has no attribute 'setting_init_bank_account_action'" while evaluating
'action = model.setting_init_bank_account_action()'

('account.menu_action_tax_adjustment', 215, 'Accounting > Accounting > Actions > Tax Adjustments', 347):
 Traceback (most recent call last):
   File "/tmp/tmpg1ao7go4/migrations/base/tests/test_mock_crawl.py", line 163, in crawl_menu
    self.mock_action(action_vals)
   ...
   File "/home/odoo/src/odoo/13.0/odoo/addons/base/models/ir_ui_view.py", line 614, in raise_view_error
    raise ValueError(message)
 ValueError: Field `amount` does not exist

Error context:
View `n/a`
[view_id: n/a, xml_id: n/a, model: n/a, parent_id: n/a]

('account.product_product_menu_sellable', 200, 'Accounting > Customers > Products', 318):
 Traceback (most recent call last):
   File "/tmp/tmpg1ao7go4/migrations/base/tests/test_mock_crawl.py", line 163, in crawl_menu
    self.mock_action(action_vals)
   ...
   File "/home/odoo/src/odoo/13.0/odoo/addons/base/models/ir_ui_view.py", line 614, in raise_view_error
    raise ValueError(message)
 ValueError: Field `attribute_value_ids` does not exist

Error context:
View `product.product.tree`
[view_id: 807, xml_id: account.product_product_view_tree, model: product.product, parent_id: n/a]

```

closes odoo/upgrade#2510

Signed-off-by: Denis Ledoux (dle) <dle@odoo.com>