[FIX] stock/0.0.0: fix pre-check_uom_consistency
When we fix the UoM inconsistencies on stock move _lines_ we also need
to ensure the stock _move_ has the correct UoM. Otherwise we may get
issues on other places that use the UoM from the move:
https://github.com/odoo/odoo/blob/b350058e6cb70bbf4767fb6af66418be0d45680b/addons/stock/models/stock_move.py#L345-L349

We update all the moves that have inconsistencies. We need to take into
account the active flag otherwise a move line for an inactive product
that is not updated may get in conflict with the update on the move.
This would cause the same error we are trying to prevent here.

Example traceback:
```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/14.0/odoo/service/server.py", line 1199, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/odoo/src/odoo/14.0/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/src/odoo/14.0/odoo/modules/loading.py", line 469, in load_modules
    migrations.migrate_module(package, 'end')
  File "/home/odoo/src/odoo/14.0/odoo/modules/migration.py", line 180, in migrate_module
    migrate(self.cr, installed_version)
  File "/tmp/tmp7t756r09/migrations/mrp/saas~13.4.2.0/end-migrate.py", line 363, in migrate
    util.recompute_fields(cr, "mrp.production", ["state", "production_location_id"])
  File "/tmp/tmp7t756r09/migrations/util/orm.py", line 113, in recompute_fields
    records.recompute()
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 5889, in recompute
    process(field)
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 5873, in process
    field.recompute(recs)
  File "/home/odoo/src/odoo/14.0/odoo/fields.py", line 1153, in recompute
    self.compute_value(recs)
  File "/home/odoo/src/odoo/14.0/odoo/fields.py", line 1175, in compute_value
    records._compute_field_value(self)
  File "/home/odoo/src/odoo/14.0/addons/mail/models/mail_thread.py", line 410, in _compute_field_value
    return super()._compute_field_value(field)
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 4055, in _compute_field_value
    getattr(self, field.compute)()
  File "/home/odoo/src/odoo/14.0/addons/mrp/models/mrp_production.py", line 485, in _compute_state
    elif any(not float_is_zero(move.quantity_done, precision_rounding=move.product_uom.rounding or move.product_id.uom_id.rounding) for move in production.move_raw_ids):
  File "/home/odoo/src/odoo/14.0/addons/mrp/models/mrp_production.py", line 485, in <genexpr>
    elif any(not float_is_zero(move.quantity_done, precision_rounding=move.product_uom.rounding or move.product_id.uom_id.rounding) for move in production.move_raw_ids):
  File "/home/odoo/src/odoo/14.0/odoo/fields.py", line 1019, in __get__
    self.compute_value(recs)
  File "/home/odoo/src/odoo/14.0/odoo/fields.py", line 1175, in compute_value
    records._compute_field_value(self)
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 4055, in _compute_field_value
    getattr(self, field.compute)()
  File "/home/odoo/src/odoo/14.0/addons/stock/models/stock_move.py", line 348, in _quantity_done_compute
    for line_uom_id, qty in rec.get(move.ids[0] if move.ids else move.id, [])
  File "/home/odoo/src/odoo/14.0/addons/stock/models/stock_move.py", line 348, in <genexpr>
    for line_uom_id, qty in rec.get(move.ids[0] if move.ids else move.id, [])
  File "/home/odoo/src/odoo/14.0/addons/uom/models/uom_uom.py", line 157, in _compute_quantity
    raise UserError(_('The unit of measure %s defined on the order line doesn\'t belong to the same category as the unit of measure %s defined on the product. Please correct the unit of measure defined on the order line or on the product, they should belong to the same category.') % (self.name, to_unit.name))
odoo.exceptions.UserError: The unit of measure kg defined on the order line doesn't belong to the same category as the unit of measure St. defined on the product. Please correct the unit of measure defined on the order line or on the product, they should belong to the same category.
```

The move in error
```
18793_afu=> select m.id mid,m.product_uom,m.product_id,l.id lid,l.product_uom_id,l.product_id from stock_move m join stock_move_line l on l.move_id=m.id where m.id=1183 order by l.id
+-------+---------------+--------------+-------+------------------+--------------+
| mid   | product_uom   | product_id   | lid   | product_uom_id   | product_id   |
|-------+---------------+--------------+-------+------------------+--------------|
| 1183  | 1             | 4274         | 7605  | 1                | 4274         |
+-------+---------------+--------------+-------+------------------+--------------+
```
The UoM from the product
```
18793_afu=> select t.uom_id from product_template t join product_product p on p.product_tmpl_id = t.id and p.id=4274
+----------+
| uom_id   |
|----------|
| 21       |
+----------+
```
does not have the same category as the UoM on the move (line):
```
18793_afu=> select id,category_id from uom_uom where id in (1,21)
+------+---------------+
| id   | category_id   |
|------+---------------|
| 1    | 1             |
| 21   | 2             |
+------+---------------+
```

upg-18793
opw-2608034

closes odoo/upgrade#2663

Signed-off-by: Christophe Simonis <chs@odoo.com>