[FIX] sale_stock_renting/0.0.0: fixed quant inconsistency for demo data
inconsistency on quant raised only when there is database with demo
data with product `rental_stock_product_1`. so need to check
condition if there is demo flag then and then will call
_ensure_rental_stock_moves_consistency.

https://upgrade.odoo.com/web?debug=1#id=736&action=178&model=upgrade.request.traceback.group&view_type=form&cids=1&menu_id=107

upgrade request 13 has been fixed.

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/14.0/odoo/service/server.py", line 1201, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/odoo/src/odoo/14.0/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/src/odoo/14.0/odoo/modules/loading.py", line 457, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/home/odoo/src/odoo/14.0/odoo/modules/loading.py", line 349, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/odoo/src/odoo/14.0/odoo/modules/loading.py", line 227, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/home/odoo/src/odoo/14.0/odoo/modules/migration.py", line 186, in migrate_module
    migrate(self.cr, installed_version)
  File "/tmp/tmpxsqra550/migrations/sale_stock_renting/0.0.0/post-migrate.py", line 14, in migrate
    _ensure_rental_stock_moves_consistency(cr, False)
  File "/home/odoo/src/enterprise/14.0/sale_stock_renting/__init__.py", line 26, in _ensure_rental_stock_moves_consistency
    line._move_qty(line.qty_delivered - line.qty_returned, line.order_id.warehouse_id.lot_stock_id, line.company_id.rental_loc_id)
  File "/home/odoo/src/enterprise/14.0/sale_stock_renting/models/sale_rental.py", line 196, in _move_qty
    rental_stock_move._action_done()
  File "/home/odoo/src/odoo/14.0/addons/stock_account/models/stock_move.py", line 265, in _action_done
    res = super(StockMove, self)._action_done(cancel_backorder=cancel_backorder)
  File "/home/odoo/src/odoo/14.0/addons/stock/models/stock_move.py", line 1563, in _action_done
    moves_todo.mapped('move_line_ids').sorted()._action_done()
  File "/home/odoo/src/odoo/14.0/addons/stock/models/stock_move_line.py", line 481, in _action_done
    '\n - '.join(mls_tracked_without_lot.mapped('product_id.display_name')))
odoo.exceptions.UserError: You need to supply a Lot/Serial Number for product:
 - [02003906] SCALE-X CARBO CONTROLLER   (50 Hz, Type G, 220 V)
```

closes odoo/upgrade#4806

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>