[FIX] gamification/0.0.0: no email sent on karma rank creation
During the upgrade, if the karma ranks don't exist, they are created
and after creation they send e-mails to the qualifying users.

The solution is to override the `_rank_changed` method on res_users
to avoid the emails to be sent when the ranks are created.

Moreover during the upgrade to saas~14.5, the email templates are not
converted to qweb yet, failing the rendering.

Closes #2966
upg-43129

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/15.0/odoo/tools/convert.py", line 680, in _tag_root
    f(rec)
  File "/home/odoo/src/odoo/15.0/odoo/tools/convert.py", line 583, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/home/odoo/src/odoo/15.0/odoo/models.py", line 4399, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/home/odoo/src/odoo/15.0/odoo/models.py", line 4328, in _load_records_create
    return self.create(values)
  File "<decorator-gen-155>", line 2, in create
  File "/home/odoo/src/odoo/15.0/odoo/api.py", line 410, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/15.0/addons/gamification/models/gamification_karma_rank.py", line 39, in create
    users._recompute_rank()
  File "/home/odoo/src/odoo/15.0/addons/gamification/models/res_users.py", line 203, in _recompute_rank
    self._recompute_rank_bulk()
  File "/home/odoo/src/odoo/15.0/addons/gamification/models/res_users.py", line 255, in _recompute_rank_bulk
    users_to_notify._rank_changed()
  File "/home/odoo/src/odoo/15.0/addons/gamification/models/res_users.py", line 187, in _rank_changed
    template.send_mail(u.id, force_send=False, notif_layout='mail.mail_notification_light')
  File "/home/odoo/src/odoo/15.0/addons/mail/models/mail_template.py", line 259, in send_mail
    values = self.generate_email(res_id, ['subject', 'body_html', 'email_from', 'email_to', 'partner_to', 'email_cc', 'reply_to', 'scheduled_date'])
  File "/home/odoo/src/odoo/15.0/addons/mail/models/mail_template.py", line 187, in generate_email
    results = template.generate_recipients(results, template_res_ids)
  File "/home/odoo/src/odoo/15.0/addons/mail/models/mail_template.py", line 154, in generate_recipients
    tpl_partner_ids = [int(pid) for pid in partner_to.split(',') if pid]
  File "/home/odoo/src/odoo/15.0/addons/mail/models/mail_template.py", line 154, in <listcomp>
    tpl_partner_ids = [int(pid) for pid in partner_to.split(',') if pid]
ValueError: invalid literal for int() with base 10: '${object.partner_id.id}'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/15.0/odoo/service/server.py", line 1246, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/odoo/src/odoo/15.0/odoo/modules/registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/15.0/odoo/modules/loading.py", line 472, in load_modules
    force, status, report, loaded_modules, update_module, modls_to_check)
  File "/home/odoo/src/odoo/15.0/odoo/modules/loading.py", line 365, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/odoo/src/odoo/15.0/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/home/odoo/src/odoo/15.0/odoo/modules/loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/home/odoo/src/odoo/15.0/odoo/tools/convert.py", line 745, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/home/odoo/src/odoo/15.0/odoo/tools/convert.py", line 811, in convert_xml_import
    obj.parse(doc.getroot())
  File "/home/odoo/src/odoo/15.0/odoo/tools/convert.py", line 731, in parse
    self._tag_root(de)
  File "/home/odoo/src/odoo/15.0/odoo/tools/convert.py", line 680, in _tag_root
    f(rec)
  File "/home/odoo/src/odoo/15.0/odoo/tools/convert.py", line 697, in _tag_root
    )) from e
odoo.tools.convert.ParseError: while parsing /home/odoo/src/odoo/15.0/addons/gamification/data/gamification_karma_rank_data.xml:12, somewhere inside
<record id="rank_newbie" model="gamification.karma.rank">
        <field name="name">Newbie</field>
        <field name="description" type="html"><p>You just began the adventure! Welcome!</p></field>
        <field name="description_motivational" type="html">
            <div class="media align-items-center">
                <div class="media-body">Earn your first points and join the adventure !</div>
                <img class="ml-3 img img-fluid" style="max-height: 72px;" src="/gamification/static/img/rank_newbie_badge.svg"/>
            </div>
        </field>
        <field name="karma_min">1</field>
        <field name="image_1920" type="base64" file="gamification/static/img/rank_newbie_badge.svg"/>
    </record>
```

closes odoo/upgrade#2970

Signed-off-by: Christophe Simonis <chs@odoo.com>