[FIX] l10n_co_edi/saas~14.5.0.1: obligation types duplicate error
as default obligation type(R-99-PN) is replaced for deprecated l10n co edi type
code, but in case customer had selected multiple type code in
'Obligaciones y Responsabilidades' at partner's form, then the replace of
deprecated type by default code type is raising issue for duplication,
because of unique constraint for partner_id and type_id.

Here is error log:-

ERROR: duplicate key value violates unique constraint
'partner_l10n_co_edi_obligation_types_pkey'
DETAIL:  Key (partner_id, type_id)=(111223, 50) already exists.

Traceback (most recent call last):
  File '/home/odoo/src/odoo/15.0/odoo/service/server.py',
    line 1246, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File '/home/odoo/src/odoo/15.0/odoo/modules/registry.py', line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File '/home/odoo/src/odoo/15.0/odoo/modules/loading.py',
    line 470, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File '/home/odoo/src/odoo/15.0/odoo/modules/loading.py',
    line 363, in load_marked_modules
    loaded, processed = load_module_graph(
  File '/home/odoo/src/odoo/15.0/odoo/modules/loading.py',
    line 174, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File '/home/odoo/src/odoo/15.0/odoo/modules/migration.py',
    line 180, in migrate_module
    migrate(self.cr, installed_version)
  File '/tmp/tmpms5nmqzw/migrations/l10n_co_edi/saas~14.5.0.1/pre-migrate.py',
    line 59, in migrate
    cr.execute(
  File '<decorator-gen-3>', line 2, in execute
  File '/home/odoo/src/odoo/15.0/odoo/sql_db.py', line 89, in check
    return f(self, *args, **kwargs)
  File '/home/odoo/src/odoo/15.0/odoo/sql_db.py', line 310, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique
    constraint 'partner_l10n_co_edi_obligation_types_pkey'
DETAIL:  Key (partner_id, type_id)=(111223, 50) already exists.

Here is output result from database:

SELECT p.partner_id, p.type_id, t.name
  FROM partner_l10n_co_edi_obligation_types p,
       l10n_co_edi_type_code t
 WHERE p.type_id = t.id
   AND t.name NOT IN ('O-47', 'R-99-PN', 'O-13', 'O-15', 'O-23')
   AND p.partner_id = 111223;

 partner_id | type_id | name
------------+---------+------
     111223 |      83 | A-42
     111223 |      88 | A-48

closes odoo/upgrade#3034

Signed-off-by: Nicolas Seinlet (nse) <nse@odoo.com>