[FIX] analytic/saas~16.5: added default analytic_plan_id
From Odoo 17 , account_analytic_plan demo record moved on
data file. but will add that analytic_plan in ir config parameter
but there are some database which does not have any record for
analytic plan , we already created default record but in version
 16.0 so this raised error when we have database > 16.

so need to create default plan id if there was no any record.

upg-1173290
upg-1173260

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/17.0/odoo/service/server.py", line 1302, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "<decorator-gen-16>", line 2, in new
  File "/home/odoo/src/odoo/17.0/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/17.0/odoo/modules/registry.py", line 113, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/17.0/odoo/modules/loading.py", line 476, in load_modules
    processed_modules += load_marked_modules(env, graph,
  File "/home/odoo/src/odoo/17.0/odoo/modules/loading.py", line 364, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/odoo/src/odoo/17.0/odoo/modules/loading.py", line 181, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/home/odoo/src/odoo/17.0/odoo/modules/migration.py", line 240, in migrate_module
    migrate(self.cr, installed_version)
  File "/tmp/tmphqcrrdxn/migrations/analytic/saas~16.5.1.1/pre-migrate.py", line 13, in migrate
    project_plan_id = all_project_plans[0] if all_project_plans else cr.fetchone()[0]
TypeError: 'NoneType' object is not subscriptable
```

closes odoo/upgrade#5381

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>