[FIX] base/tests: `self.env.company` doesn't exist before 13.0
This causes many errors in the `test_prepare` for upgrades coming from
<= odoo 12. `current_company_id` exists from 13.0 thus there is no need
to add it to the context in older versions.

Example error on a 12->12.3 upgrade only `base` installed:
```
2025-05-30 08:34:04,491 117694 ERROR test_12_saas~12.3 odoo.addons.base.maintenance.migrations.base.testsodoo.addons.base.maintenance.migrations.base.tests.test_mock_crawl: Adding menu ('base.menu_res_lang_act_win
dow', 55, 'Settings > Translations > Languages', 49) to the failing menus
Traceback (most recent call last):
  File "/home/odoo/src/odoo/12.0/odoo/addons/base/maintenance/migrations/base/tests/test_mock_crawl.py", line 269, in crawl_menu
    self.mock_action(action_vals)
  File "/home/odoo/src/odoo/12.0/odoo/addons/base/maintenance/migrations/base/tests/test_mock_crawl.py", line 282, in mock_action
    return self.mock_act_window(action)
  File "/home/odoo/src/odoo/12.0/odoo/addons/base/maintenance/migrations/base/tests/test_mock_crawl.py", line 315, in mock_act_window
    context = self._safe_eval(context) if context else {}
  File "/home/odoo/src/odoo/12.0/odoo/addons/base/maintenance/migrations/base/tests/test_mock_crawl.py", line 245, in _safe_eval
    "current_company_id": self.env.company.id,
AttributeError: 'Environment' object has no attribute 'company'
```

closes odoo/upgrade#7769

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>