[FIX] base/0.0.0: fix deleting inherited fields
When a field is defined in a custom module and added to a mixin (like
mail.thread) it will be added to many other models. For some reason
those fields will be marked as of Odoo authorship only in some models,
but not on the original one (mail.thread).

Those inherited fields should not be deleted, but to know from where
they come from we cannot use the field model _inherit attribute since
it returns the field model, and not the model from where it is coming.

In order to verify the actual model from which those fields come from we
need to check all abstract models.

```
2605_afu=> select f.id,f.model as field_model,f.name as field_name,d.module as field_module,m.author module_author from
ir_model_fields f join ir_model_data d on d.res_id=f.id join ir_module_module m on d.module=m.name where
d.model='ir.model.fields' and f.name='hide_messages';
  id   |                  field_model                   |  field_name   |         field_module          |    module_author
-------+------------------------------------------------+---------------+-------------------------------+----------------------
 19574 | mail.thread                                    | hide_messages | prt_mail_messages_pro         | Ivan Sokolov, Cetmix
 19577 | mail.thread.cc                                 | hide_messages | prt_mail_messages_pro         | Ivan Sokolov, Cetmix
 19579 | mail.blacklist                                 | hide_messages | prt_mail_messages_pro         | Ivan Sokolov, Cetmix
 19582 | mail.thread.blacklist                          | hide_messages | prt_mail_messages_pro         | Ivan Sokolov, Cetmix
 19584 | mail.channel                                   | hide_messages | prt_mail_messages_pro         | Ivan Sokolov, Cetmix
 19586 | account.analytic.account                       | hide_messages | prt_mail_messages_pro         | Ivan Sokolov, Cetmix
 19588 | calendar.event                                 | hide_messages | prt_mail_messages_pro         | Ivan Sokolov, Cetmix
 19590 | gamification.challenge                         | hide_messages | prt_mail_messages_pro         | Ivan Sokolov, Cetmix
 ... many more
 19629 | res.users                                      | hide_messages | prt_mail_messages_pro         | Ivan Sokolov, Cetmix
 19631 | project.task                                   | hide_messages | project                       | Odoo S.A.
 ...
 19666 | event.registration                             | hide_messages | event                         | Odoo S.A.
 ...
(46 rows)
```

```
(Pdb) p model._inherit
'event.registration'
```

```
  File "/tmp/tmp3ovf7hwn/migrations/base/0.0.0/pre-models-ir_model.py", line 127, in unlink
    "💥 It looks like you forgot to call `util.remove_field` on the following fields: %s" % ", ".join(fields)
odoo.upgrade.util.MigrationError: 💥 It looks like you forgot to call `util.remove_field` on the following fields: event.registration.hide_messages
```

upg-2605
cf. odoo/odoo#49354 odoo/odoo#53316

closes odoo/upgrade#2416

Signed-off-by: Christophe Simonis <chs@odoo.com>
Co-authored-by: Denis Ledoux (dle) <dle@odoo.com>