[FIX] base/0.0.0: match partner companies
TBG-1748

After this PR was merged:
https://github.com/odoo/odoo/pull/193981/commits/25cf037c1bcbdd298802fe758510c98c7b00f527
Some dbs fail to upgrade, it would seem that many DBs have
a `commercial_partner_id` that belongs to another company,

example:
```
	partner.company_id == NULL
	partner.commercial_partner_id.company_id == 2
```
This causes an access error here:
https://github.com/odoo/odoo/pull/193981/commits/25cf037c1bcbdd298802fe758510c98c7b00f527#diff-1db47cdbb145c8ab07b89c2288e239b8d2588881cf5917fcde02adcfcf87cb40R643

We can either set both to `null` or make the partner follow his
commercial partner, But I'm not sure if this should rather have
a fix in standard
(No idea what's the workflow here :D)

```
 File "/home/odoo/src/odoo/18.0/odoo/fields.py", line 1291, in __get__
    self.compute_value(recs)
   File "/home/odoo/src/odoo/18.0/odoo/fields.py", line 1473, in compute_value
    records._compute_field_value(self)
   File "/home/odoo/src/odoo/18.0/addons/mail/models/mail_thread.py", line 428, in _compute_field_value
    return super()._compute_field_value(field)
   File "/home/odoo/src/odoo/18.0/odoo/models.py", line 5238, in _compute_field_value
    fields.determine(field.compute, self)
   File "/home/odoo/src/odoo/18.0/odoo/fields.py", line 110, in determine
    return needle(*args)
   File "/home/odoo/src/odoo/18.0/addons/account_edi_ubl_cii/models/res_partner.py", line 190, in _compute_invoice_edi_format
    super()._compute_invoice_edi_format()
   File "/home/odoo/src/odoo/18.0/addons/account/models/partner.py", line 643, in _compute_invoice_edi_format
    if partner.commercial_partner_id.invoice_edi_format_store == 'none':
   File "/home/odoo/src/odoo/18.0/odoo/fields.py", line 1266, in __get__
    recs._fetch_field(self)
   File "/home/odoo/src/odoo/18.0/odoo/models.py", line 4058, in _fetch_field
    self.fetch(fnames)
   File "/home/odoo/src/odoo/18.0/odoo/models.py", line 4101, in fetch
    raise self.env['ir.rule']._make_access_error('read', forbidden)
 odoo.exceptions.AccessError: Oups ! On dirait que vous êtes tombé sur des enregistrements top secrets.

Désolé, Benoit BLANCHER (id=2) n'a pas d'accès 'lire' à :
- Contact (res.partner)
```

closes odoo/upgrade#7113

Signed-off-by: Christophe Simonis (chs) <chs@odoo.com>