[FIX] stock/0.0.0: fixed update of view location id
When there is standard entry for warehouse `warehouse0`
is missing in his original database, and there is record
in warehouse table with `WH` code, then
1. It's try to create `warehouse0` record from stock/data
file, so create method called in stock/warehouse file
and it will create `view_location_id` and other sub locations.
see:
https://github.com/odoo/odoo/blob/de8c95c455eb56bb221ec5406b2dd0e315af45b9/addons/stock/models/stock_warehouse.py#L116
but we override create method in our generic script :
https://github.com/odoo/upgrade/blob/2b1cc4529f9d47670074e51ef9889ad3ac0369da/migrations/base/0.0.0/pre-models-match_uniq.py#L75

there is unique constraing (code, company_id) in warehouse,
so it will try to find existing record in warehouse which has
code='WH' and company = 1 and if we find that record then
update all the values of `warehouse0` to this entry
and which create issue because it's try to update `view_location_id`
and before upgrade `view_location_id` is different then
after upgrade , create product mismatched on hand qty
because will fetch `Quant` record and `qty_available` from
view location and it's related stock internal location.
see:
https://github.com/odoo/odoo/blob/de8c95c455eb56bb221ec5406b2dd0e315af45b9/addons/stock/models/product.py#L297

so when we have no `warehouse0` entry and code='WH' entry
exist then avoid to update record use
`ensure_xmlid_match_record`

upg-1296874
upg-1267857

```
vals_list [{'partner_id': 1, 'code': 'WH', 'view_location_id': 71, 'lot_stock_id': 72, 'wh_input_stock_loc_id': 73, 'wh_qc_stock_loc_id': 74, 'wh_output_stock_loc_id': 75, 'wh_pack_stock_loc_id': 76}]

2024-02-05 07:10:34,688 32 ERROR atp_1296874_17.0 odoo.sql_db: bad query: UPDATE "stock_warehouse" SET "code" = 'WH', "company_id" = 1, "lot_stock_id" = 72, "partner_id" = 1, "view_location_id" = 71, "wh_input_stock_loc_id" = 73, "wh_output_stock_loc_id" = 75, "wh_pack_stock_loc_id" = 76, "wh_qc_stock_loc_id" = 74, "write_date" = '2024-02-05T07:10:28.789721'::timestamp, "write_uid" = 1 WHERE id IN (7)

Traceback (most recent call last):
  File "/tmp/tmpa_5hs9t7/migrations/testing.py", line 207, in test_check
    self.check(value)
  File "/tmp/tmpa_5hs9t7/migrations/stock/tests/test_on_hand_quantity.py", line 41, in check
    self.assertEqual(before_results, self.convert_check(after_results), self.message)
AssertionError: Lists differ: [[27599, '20'], [27600, '1'], [27601, '5'][22299 chars]65']] != []

First list contains 1511 additional elements.
First extra element 0:
[27599, '20']

Traceback (most recent call last):
  File "/tmp/tmpjr8vvogi/migrations/testing.py", line 207, in test_check
    self.check(value)
  File "/tmp/tmpjr8vvogi/migrations/stock/tests/test_on_hand_quantity.py", line 41, in check
    self.assertEqual(before_results, self.convert_check(after_results), self.message)
AssertionError: Lists differ: [[1337, '2'], [1339, '1'], [1340, '1'], [1[2198 chars]'2']] != []

First list contains 169 additional elements.
First extra element 0:
[1337, '2']

```

closes odoo/upgrade#5652

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>