[FIX] base/tests: skip mocking menus `menu_procurement_compute{,_mrp}`
Starting from `18.0` after this commit[^1] the action of
`mrp.menu_procurement_compute_mrp` and `stock.menu_procurement_compute`
menus is **ir_cron_scheduler_action_ir_actions_server**[^2], which
the code of action calls `run_scheduler()` with use_new_cursor=True.

This leads to commiting the cursor[^3], so during the mocking the menus
if we mock that menu we lose the savepoint `test_mock_crawl` on that
cursor commit. So if we face exception we gonna face problem on rolling
back here[^4].

That menus are not mocked by default becasue they have
groups=`base.group_no_one`, but if we manually add `base.group_system`
they will be mocked. Additionally during the mocking we will get
action=False here[^5], so we will call `self.mock_action(False)`[^6],
as result we will have exception so rollback issue.

For fixing the issue I have skipped those menus from mocking.

Steps to reproduce:
1. Install `stock` in 18.0
2. Add `base.group_system` to that menu
3. Upgrade to `saas~18.2`

You will see traceback like this

```
File "/tmp/tmp0gdhxbzc/migrations/base/tests/test_mock_crawl.py", line 271, in mock_action
    if action["type"] == "ir.actions.act_window":
TypeError: 'bool' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/tmp0gdhxbzc/migrations/testing.py", line 302, in test_prepare
    value = self.prepare()
  File "/tmp/tmp0gdhxbzc/migrations/testing.py", line 425, in prepare
    return self.invariant()
  File "/usr/lib/python3.10/unittest/mock.py", line 1379, in patched
    return func(*newargs, **newkeywargs)
  File "/tmp/tmp0gdhxbzc/migrations/base/tests/test_mock_crawl.py", line 222, in invariant
    failing.update(self.crawl_menu(get_menu(menu), get_menu))
  File "/tmp/tmp0gdhxbzc/migrations/base/tests/test_mock_crawl.py", line 267, in crawl_menu
    failing.update(self.crawl_menu(get_menu(child), get_menu, menu_name))
  File "/tmp/tmp0gdhxbzc/migrations/base/tests/test_mock_crawl.py", line 267, in crawl_menu
    failing.update(self.crawl_menu(get_menu(child), get_menu, menu_name))
  File "/tmp/tmp0gdhxbzc/migrations/base/tests/test_mock_crawl.py", line 261, in crawl_menu
    self.env.cr.execute("ROLLBACK TO SAVEPOINT test_mock_crawl")  # In case the cursor is broken
  File "/home/odoo/src/odoo/saas-18.1/odoo/sql_db.py", line 635, in execute
    return self._cursor.execute(*args, **kwargs)
  File "/home/odoo/src/odoo/saas-18.1/odoo/sql_db.py", line 421, in execute
    self._obj.execute(query, params)
psycopg2.errors.InvalidSavepointSpecification: savepoint "test_mock_crawl" does not exist

```

tbg-1991

[^1]: https://github.com/odoo/odoo/commit/7d72959ba2745095e3fb507a2ebeb44620ff03ec
[^2]: https://github.com/odoo/odoo/blob/0d63da167251f6c4bb727c7c24e249d04d36eea7/addons/stock/data/stock_sequence_data.xml#L56C40-L56C64
[^3]: https://github.com/odoo/odoo/blob/8f42171acbb2369fe2536b24928854dcdfb2aa86/addons/stock/models/stock_rule.py#L705
[^4]: https://github.com/odoo/upgrade/blob/75d74658f0d9a258792b249e1adb12e25a62a85c/migrations/base/tests/test_mock_crawl.py#L261
[^5]: https://github.com/odoo/upgrade/blob/75d74658f0d9a258792b249e1adb12e25a62a85c/migrations/base/tests/test_mock_crawl.py#L275
[^6]: https://github.com/odoo/upgrade/blob/75d74658f0d9a258792b249e1adb12e25a62a85c/migrations/base/tests/test_mock_crawl.py#L289

closes odoo/upgrade#7684

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>