[FIX] l10n_mx_edi_stock/saas~16.3: Fix user error
Step to reproduce

1. createdb in version 16.3 with installed module stock,l10n_mx_edi
installed
2. prepare the  test case

below traceback will raise
```
Traceback (most recent call last):
  File "/upgrade-util/src/testing.py", line 283, in test_prepare
    super(UpgradeCase, self).test_prepare()
  File "/upgrade-util/src/testing.py", line 186, in test_prepare
    value = self.prepare()
  File "/upgrade/migrations/l10n_mx_edi_stock/tests/test_16_4_refactoring_edi.py", line 204, in prepare
    results["tests"].append(("_check_stock_picking", self._prepare_test_stock_picking()))
  File "/home/upgradeci/.pyenv/versions/3.10/lib/python3.10/site-packages/freezegun/api.py", line 778, in wrapper
    result = func(*args, **kwargs)
  File "/upgrade/migrations/l10n_mx_edi_stock/tests/test_16_4_refactoring_edi.py", line 88, in _prepare_test_stock_picking
    picking.l10n_mx_edi_action_send_delivery_guide()
  File "/tmp/tmp7jw60cj2/enterprise/saas-16.3/l10n_mx_edi_stock/models/stock_picking.py", line 313, in l10n_mx_edi_action_send_delivery_guide
    self._l10n_mx_edi_check_required_data()
  File "/tmp/tmp7jw60cj2/enterprise/saas-16.3/l10n_mx_edi_stock_extended_30/models/stock_picking.py", line 40, in _l10n_mx_edi_check_required_data
    super()._l10n_mx_edi_check_required_data()
  File "/tmp/tmp7jw60cj2/enterprise/saas-16.3/l10n_mx_edi_stock_30/models/stock_picking.py", line 57, in _l10n_mx_edi_check_required_data
    raise UserError(_("Please define a gross vehicle weight."))
odoo.exceptions.UserError: Please define a gross vehicle weight.
```
The
[gross_vehicle_weight]
(https://github.com/odoo/enterprise/blob/e93a1e15fcbe689ae9be8314e8d033f88888522e/l10n_mx_edi_stock_30/models/l10n_mx_edi_vehicle.py#L9)
field is 0.0  while creating  a new record of ``l10n_mx_edi.vehicle``
model this is used
[here]
(https://github.com/odoo/upgrade/blob/6d9012ad37706334b46b6185536c6f24d655dc50/migrations/l10n_mx_edi_stock/tests/test_16_4_refactoring_edi.py#L62)
in ``stock.picking`` record if ``l10n_mx_edi_vehicle_id``
is their so this `` l10n_mx_edi_gross_vehicle_weight``
field should have ``gross_vehicle_weight``
which 0.0 and it is throwing user error
[here]
(https://github.com/odoo/enterprise/blob/e93a1e15fcbe689ae9be8314e8d033f88888522e/l10n_mx_edi_stock_30/models/stock_picking.py#L56)
according to condition

closes odoo/upgrade#6529

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>