[FIX] base/saas~16.5.1.3: fix typo in end-01-attrs-view
**-Description**

 when taking care of translation for translated arch the double quotes is adding
 in front and back of arch due to this
 ``data[vid] = f'"{etree.tostring(new_arch).decode()}"'``
 while parsing it's raising error during menu open in particular language for
 resolving the issue remove ``f-string`` because after removing
 ``etree.tostring(new_arch).decode()``
 still work as string
```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/17.0/odoo/http.py", line 2159, in __call__
    response = request._serve_db()
  File "/home/odoo/src/odoo/17.0/odoo/http.py", line 1734, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/home/odoo/src/odoo/17.0/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/home/odoo/src/odoo/17.0/odoo/http.py", line 1761, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/home/odoo/src/odoo/17.0/odoo/http.py", line 1962, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/home/odoo/src/odoo/17.0/odoo/addons/base/models/ir_http.py", line 207, in _dispatch
    result = endpoint(**request.params)
  File "/home/odoo/src/odoo/17.0/odoo/http.py", line 722, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/home/odoo/src/odoo/17.0/addons/web/controllers/dataset.py", line 24, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/17.0/addons/web/controllers/dataset.py", line 20, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/17.0/odoo/api.py", line 462, in call_kw
    result = _call_kw_model(method, model, args, kwargs)
  File "/home/odoo/src/odoo/17.0/odoo/api.py", line 435, in _call_kw_model
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/odoo/17.0/addons/hr/models/res_users.py", line 184, in get_views
    result = super().get_views(views, options)
  File "/home/odoo/src/enterprise/17.0/web_studio/models/ir_ui_view.py", line 53, in get_views
    return super().get_views(views, options)
  File "/home/odoo/src/odoo/17.0/odoo/addons/base/models/ir_ui_view.py", line 2440, in get_views
    result['views'] = {
  File "/home/odoo/src/odoo/17.0/odoo/addons/base/models/ir_ui_view.py", line 2441, in <dictcomp>
    v_type: self.get_view(
  File "/home/odoo/src/odoo/17.0/addons/hr/models/res_users.py", line 200, in get_view
    result = super(User, self).get_view(view_id, view_type, **options)
  File "/home/odoo/src/odoo/17.0/odoo/addons/base/models/ir_ui_view.py", line 2626, in get_view
    result = dict(self._get_view_cache(view_id, view_type, **options))
  File "<decorator-gen-51>", line 2, in _get_view_cache
  File "/home/odoo/src/odoo/17.0/odoo/tools/cache.py", line 104, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/odoo/src/odoo/17.0/odoo/addons/base/models/ir_ui_view.py", line 2582, in _get_view_cache
    arch, view = self._get_view(view_id, view_type, **options)
  File "/home/odoo/src/odoo/17.0/odoo/addons/base/models/ir_ui_view.py", line 2529, in _get_view
    arch = view._get_combined_arch()
  File "/home/odoo/src/odoo/17.0/odoo/addons/base/models/ir_ui_view.py", line 948, in _get_combined_arch
    arch = root.with_prefetch(tree_views._prefetch_ids)._combine(hierarchy)
  File "/home/odoo/src/odoo/17.0/odoo/addons/base/models/ir_ui_view.py", line 885, in _combine
    arch = etree.fromstring(view.arch)
  File "src/lxml/etree.pyx", line 3252, in lxml.etree.fromstring
  File "src/lxml/parser.pxi", line 1913, in lxml.etree._parseMemoryDocument
  File "src/lxml/parser.pxi", line 1793, in lxml.etree._parseDoc
  File "src/lxml/parser.pxi", line 1082, in lxml.etree._BaseParser._parseUnicodeDoc
  File "src/lxml/parser.pxi", line 615, in lxml.etree._ParserContext._handleParseResultDoc
  File "src/lxml/parser.pxi", line 725, in lxml.etree._handleParseResult
  File "src/lxml/parser.pxi", line 654, in lxml.etree._raiseParseError
  File "<string>", line 1
lxml.etree.XMLSyntaxError: Start tag expected, '<' not found, line 1, column 1
```
-**Step to reproduce the issue**
   1. First create database with base in ``saas-16.3`` and then install
      one another language like french and then migrate to 17.0
   2. then click on my profile you will have the same traceback as above

-**Before fix**
```
select arch_db->>'fr_BE' from ir_ui_view where id=231;
 "<group name="auth" position="after">
     - - - -
</group>"
```
-**After fix**
```
select arch_db->>'fr_BE' from ir_ui_view where id=231;
 <group name="auth" position="after">
    - - - - -
</group>
```
upg-1194553

closes odoo/upgrade#5480

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>