[FIX] stock@saas~12.5: update `stock_move_rule`, `stock_move_line_rule`
These rules have changed in
odoo/odoo@6ff34073153767d449804669f31e26c04de0a670
but they are in a `noupdate="1"` block,
therefore they are not updated by the ORM on upgrade.

Not updating them can lead to an AccessError
when accessing a `stock.move.line` associated to
a picking in another company.

```
2021-03-01 05:14:06,313 8191 INFO template_00633d7b76a4_59862_13.0 odoo.addons.base.maintenance.migrations.base.testsodoo.upgrade.base.tests.test_mock_crawl: Mocking view form: stock.production.lot.form
2021-03-01 05:14:06,314 8191 INFO template_00633d7b76a4_59862_13.0 odoo.addons.base.maintenance.migrations.base.testsodoo.upgrade.base.tests.test_mock_crawl: view_form, stock.production.lot(426, 429, 431), []
2021-03-01 05:14:06,654 8191 INFO template_00633d7b76a4_59862_13.0 odoo.addons.base.models.ir_rule: Access Denied by record rules for operation: read on record ids: [709, 250891], uid: 13, model: stock.picking
2021-03-01 05:14:06,665 8191 INFO template_00633d7b76a4_59862_13.0 odoo.addons.base.models.ir_rule: Access Denied by record rules for operation: read on record ids: [709], uid: 13, model: stock.picking
2021-03-01 05:14:06,998 8191 INFO template_00633d7b76a4_59862_13.0 odoo.addons.base.models.ir_rule: Access Denied by record rules for operation: read on record ids: [709, 250891], uid: 13, model: stock.picking
2021-03-01 05:14:07,009 8191 INFO template_00633d7b76a4_59862_13.0 odoo.addons.base.models.ir_rule: Access Denied by record rules for operation: read on record ids: [709], uid: 13, model: stock.picking
2021-03-01 05:14:07,026 8191 ERROR template_00633d7b76a4_59862_13.0 odoo.addons.base.maintenance.migrations.base.testsodoo.upgrade.base.tests.test_mock_crawl: Adding menu ('stock.menu_action_production_lot_form', 165, 'Inventory > Master Data > Lots/Serial Numbers', 246) to the failing menus
Traceback (most recent call last):
  File "/src/odoo/13.0/odoo/addons/base/maintenance/migrations/base/tests/test_mock_crawl.py", line 155, in crawl_menu
    self.mock_action(action_vals)
  File "/src/odoo/13.0/odoo/addons/base/maintenance/migrations/base/tests/test_mock_crawl.py", line 234, in mock_action
    mock_method(model, view, fields_list, domain, group_by)
  File "/src/odoo/13.0/odoo/addons/base/maintenance/migrations/base/tests/test_mock_crawl.py", line 260, in mock_view_form
    [data] = record.read(fields_list)
  File "/src/odoo/13.0/odoo/models.py", line 2965, in read
    vals[name] = convert(record[name], record, use_name_get)
  File "/src/odoo/13.0/odoo/models.py", line 5731, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/src/odoo/13.0/odoo/fields.py", line 2366, in __get__
    return super().__get__(records, owner)
  File "/src/odoo/13.0/odoo/fields.py", line 1063, in __get__
    self.compute_value(record)
  File "/src/odoo/13.0/odoo/fields.py", line 1146, in compute_value
    records._compute_field_value(self)
  File "/src/odoo/13.0/odoo/models.py", line 4003, in _compute_field_value
    getattr(self, field.compute)()
  File "/src/odoo/13.0/addons/purchase_stock/models/stock.py", line 201, in _compute_purchase_order_ids
    lambda move: move.picking_id.location_id.usage == 'supplier' and move.state == 'done')
  File "/src/odoo/13.0/odoo/models.py", line 5344, in filtered
    return self.browse([rec.id for rec in self if func(rec)])
  File "/src/odoo/13.0/odoo/models.py", line 5344, in <listcomp>
    return self.browse([rec.id for rec in self if func(rec)])
  File "/src/odoo/13.0/addons/purchase_stock/models/stock.py", line 201, in <lambda>
    lambda move: move.picking_id.location_id.usage == 'supplier' and move.state == 'done')
  File "/src/odoo/13.0/odoo/fields.py", line 2366, in __get__
    return super().__get__(records, owner)
  File "/src/odoo/13.0/odoo/fields.py", line 1046, in __get__
    record._fetch_field(self)
  File "/src/odoo/13.0/odoo/models.py", line 2994, in _fetch_field
    self._read(fnames)
  File "/src/odoo/13.0/odoo/models.py", line 3110, in _read
    raise self.env['ir.rule']._make_access_error('read', forbidden)
odoo.exceptions.AccessError: ('L\'opération demandée ("read" sur "Transfer" (stock.picking)) a été rejetée en raison des règles suivantes:\n- stock_picking multi-company\n\nNote : ce pourrait être un problème de multi-société.\n\n(Enregistrements: BPT/OUT/00229 (id=709), Utilisateur: Jean-Michel AWAD (id=13))\n\xa0', None)
```

request 59862

closes odoo/upgrade#2247

Signed-off-by: Christophe Simonis <chs@odoo.com>