[FIX] documents/saas~14.1: Check record dependencies before update
The records that get updated depend on other records for their domains:
```xml
        <record id="documents_rule_internal_legal" model="documents.workflow.rule" forcecreate="0">
            <field name="name">Send to Legal</field>
            <field name="sequence">2</field>
            <field name="condition_type">domain</field>
            <field name="domain" eval="[('tag_ids', 'in', [
                ref('documents.documents_internal_status_inbox'),
                ref('documents.documents_internal_status_validated')])]"/>
            <field name="domain_folder_id" ref="documents.documents_internal_folder"/>
            <field name="activity_option">True</field>
            <field name="activity_type_id" ref="documents.mail_documents_activity_data_tv"/>
        </record>
```
If those records had been deleted, since they've been marked as no forcecreate,
it fails to find the corresponding xmlid.

upg-322842

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/15.0/odoo/tools/cache.py", line 85, in lookup
    r = d[key]
  File "/home/odoo/src/odoo/15.0/odoo/tools/func.py", line 71, in wrapper
    return func(self, *args, **kwargs)
  File "/home/odoo/src/odoo/15.0/odoo/tools/lru.py", line 34, in __getitem__
    a = self.d[obj]
KeyError: ('ir.model.data', <function IrModelData._xmlid_lookup at 0x7f04e6e71670>, 'documents.documents_internal_status_inbox')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/15.0/odoo/tools/safe_eval.py", line 332, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
  File "", line 1, in <module>
  File "/home/odoo/src/odoo/15.0/odoo/tools/convert.py", line 663, in id_get
    res = self.model_id_get(id_str, raise_if_not_found)
  File "/home/odoo/src/odoo/15.0/odoo/tools/convert.py", line 669, in model_id_get
    return self.env['ir.model.data']._xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "/home/odoo/src/odoo/15.0/odoo/addons/base/models/ir_model.py", line 1935, in _xmlid_to_res_model_res_id
    return self._xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-35>", line 2, in _xmlid_lookup
  File "/home/odoo/src/odoo/15.0/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/odoo/src/odoo/15.0/odoo/addons/base/models/ir_model.py", line 1928, in _xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: documents.documents_internal_status_inbox

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/15.0/odoo/tools/convert.py", line 680, in _tag_root
    f(rec)
  File "/home/odoo/src/odoo/15.0/odoo/tools/convert.py", line 569, in _tag_record
    f_val = _eval_xml(self, field, env)
  File "/home/odoo/src/odoo/15.0/odoo/tools/convert.py", line 117, in _eval_xml
    return safe_eval(a_eval, idref2)
  File "/home/odoo/src/odoo/15.0/odoo/tools/convert.py", line 39, in <lambda>
    safe_eval = lambda expr, ctx={}: s_eval(expr, ctx, nocopy=True)
  File "/home/odoo/src/odoo/15.0/odoo/tools/safe_eval.py", line 348, in safe_eval
    raise ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr))
ValueError: <class 'ValueError'>: "External ID not found in the system: documents.documents_internal_status_inbox" while evaluating
"[('tag_ids', 'in', [                 ref('documents.documents_internal_status_inbox'),                 ref('documents.documents_internal_status_validated')])]"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/15.0/odoo/service/server.py", line 1260, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/odoo/src/odoo/15.0/odoo/modules/registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/15.0/odoo/modules/loading.py", line 470, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/home/odoo/src/odoo/15.0/odoo/modules/loading.py", line 363, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/odoo/src/odoo/15.0/odoo/modules/loading.py", line 227, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/home/odoo/src/odoo/15.0/odoo/modules/migration.py", line 180, in migrate_module
    migrate(self.cr, installed_version)
  File "/tmp/tmp8wf48wys/migrations/documents/saas~14.1.1.1/post-migrate.py", line 17, in migrate
    util.if_unchanged(cr, "documents.documents_rule_internal_legal", util.update_record_from_xml)
  File "/tmp/tmp8wf48wys/migrations/util/records.py", line 391, in if_unchanged
    callback(cr, xmlid, **kwargs)
  File "/tmp/tmp8wf48wys/migrations/util/records.py", line 612, in update_record_from_xml
    importer.parse(new_root, **kw)
  File "/home/odoo/src/odoo/15.0/odoo/tools/convert.py", line 731, in parse
    self._tag_root(de)
  File "/home/odoo/src/odoo/15.0/odoo/tools/convert.py", line 680, in _tag_root
    f(rec)
  File "/home/odoo/src/odoo/15.0/odoo/tools/convert.py", line 693, in _tag_root
    raise ParseError('while parsing %s:%s, somewhere inside\n%s' % (
odoo.tools.convert.ParseError: while parsing None:51, somewhere inside
<record id="documents_rule_internal_legal" model="documents.workflow.rule" forcecreate="0">
            <field name="name">Send to Legal</field>
            <field name="sequence">2</field>
            <field name="condition_type">domain</field>
            <field name="domain" eval="[('tag_ids', 'in', [                 ref('documents.documents_internal_status_inbox'),                 ref('documents.documents_internal_status_validated')])]"/>
            <field name="domain_folder_id" ref="documents.documents_internal_folder"/>
            <field name="activity_option">True</field>
            <field name="activity_type_id" ref="documents.mail_documents_activity_data_tv"/>
        </record>
```

closes odoo/upgrade#3605

Signed-off-by: Christophe Simonis <chs@odoo.com>