[FIX] payment/saas~14.4: add primary key to temp table
Postgres logical replication expects a primary key to exist for use as a
default for REPLICA IDENTITY when attempting insert/update statements.

```
ERROR: cannot update table "_upg_payment_acquirer_journal_mapping" because it does not have a replica identity and publishes updates
HINT:  To enable updating the table, set REPLICA IDENTITY using ALTER TABLE.
```

closes odoo/upgrade#6726

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>