[FIX] base/0.0.0: except AttributeError while removing parent
child:
<xpath expr="anything" position = 'anything'>
    <field name='removed_field'/>
</xpath>

After removing of field node we try to remove the parent if the parent
does not have any child. But while removing if the arch become empty then
we get AttributeError like
`AttributeError: 'NoneType' object has no attribute 'remove'`

closes odoo/upgrade#5406

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>