[FIX] industry_fsm_sale@saas~13.1: do not update `industry_fsm.field_service_product`
The data product `industry_fsm.field_service_product` is marked as `noupdate="1"`
in its origin module `industry_fsm`.

In saas~13.1, a new module `industry_fsm_sale` has been
created, in which this product has been moved,
its xmlid therefore becoming `industry_fsm_sale.field_service_product`.

As `industry_fsm_sale` gets installed during the upgrade,
it's a `init` (`-i`) and not an `upgrade` (`-u`),
even if the data is marked as `noupdate`,
it gets loaded anyway.

If the user changed things in this product which breaks
constraints, attempting to load the product will raise an exception.

```
2021-03-19 06:54:41,072 30 INFO db_10130 odoo.modules.loading: loading industry_fsm_sale/data/industry_fsm_data.xml
2021-03-19 06:54:41,160 30 WARNING db_10130 odoo.modules.loading: Transient module states were reset
2021-03-19 06:54:41,161 30 ERROR db_10130 odoo.modules.registry: Failed to load registry
2021-03-19 06:54:41,161 30 CRITICAL db_10130 odoo.service.server: Failed to initialize database `db_10130`.
Traceback (most recent call last):
  File "/home/odoo/src/odoo/14.0/odoo/tools/convert.py", line 677, in _tag_root
    f(rec)
  File "/home/odoo/src/odoo/14.0/odoo/tools/convert.py", line 580, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 4200, in _load_records
    data['record']._load_records_write(data['values'])
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 4137, in _load_records_write
    self.write(values)
  File "/home/odoo/src/odoo/14.0/addons/sale_timesheet/models/product.py", line 108, in write
    return super(ProductProduct, self).write(vals)
  File "/home/odoo/src/odoo/14.0/addons/stock_account/models/product.py", line 105, in write
    return super(ProductProduct, self).write(vals)
  File "/home/odoo/src/odoo/14.0/addons/stock/models/product.py", line 527, in write
    return super().write(values)
  File "/home/odoo/src/odoo/14.0/addons/product/models/product.py", line 335, in write
    res = super(ProductProduct, self).write(values)
  File "/home/odoo/src/odoo/14.0/addons/mail/models/mail_thread.py", line 322, in write
    result = super(MailThread, self).write(values)
  File "/home/odoo/src/odoo/14.0/addons/mail/models/mail_activity.py", line 766, in write
    return super(MailActivityMixin, self).write(vals)
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 3695, in write
    fields[0].determine_inverse(real_recs)
  File "/home/odoo/src/odoo/14.0/odoo/fields.py", line 1187, in determine_inverse
    self.inverse(records)
  File "/home/odoo/src/odoo/14.0/odoo/fields.py", line 568, in _inverse_related
    target[field.name] = record_value[record]
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 5675, in __setitem__
    return self._fields[key].__set__(self, value)
  File "/home/odoo/src/odoo/14.0/odoo/fields.py", line 1127, in __set__
    records.write({self.name: write_value})
  File "/home/odoo/src/odoo/14.0/addons/sale_timesheet/models/product.py", line 84, in write
    return super(ProductTemplate, self).write(vals)
  File "/home/odoo/src/odoo/14.0/addons/stock_account/models/product.py", line 50, in write
    res = super(ProductTemplate, self).write(vals)
  File "/home/odoo/src/odoo/14.0/addons/stock/models/product.py", line 750, in write
    return super(ProductTemplate, self).write(vals)
  File "/home/odoo/src/odoo/14.0/addons/product/models/product_template.py", line 427, in write
    res = super(ProductTemplate, self).write(vals)
  File "/home/odoo/src/odoo/14.0/addons/mail/models/mail_thread.py", line 322, in write
    result = super(MailThread, self).write(values)
  File "/home/odoo/src/odoo/14.0/addons/mail/models/mail_activity.py", line 766, in write
    return super(MailActivityMixin, self).write(vals)
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 3709, in write
    real_recs._validate_fields(inverse_fields)
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 1260, in _validate_fields
    check(self)
  File "/home/odoo/src/odoo/14.0/addons/sale_project/models/product.py", line 40, in _check_project_and_template
    raise ValidationError(_('The product %s should not have a global project since it will generate a project.') % (product.name,))
odoo.exceptions.ValidationError: Le produit Field Service ne devrait pas avoir de projet global car il va générer un projet.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/14.0/odoo/service/server.py", line 1198, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/odoo/src/odoo/14.0/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/src/odoo/14.0/odoo/modules/loading.py", line 455, in load_modules
    loaded_modules, update_module, models_to_check)
  File "/home/odoo/src/odoo/14.0/odoo/modules/loading.py", line 348, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/odoo/src/odoo/14.0/odoo/modules/loading.py", line 221, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/home/odoo/src/odoo/14.0/odoo/modules/loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/home/odoo/src/odoo/14.0/odoo/tools/convert.py", line 733, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/home/odoo/src/odoo/14.0/odoo/tools/convert.py", line 799, in convert_xml_import
    obj.parse(doc.getroot())
  File "/home/odoo/src/odoo/14.0/odoo/tools/convert.py", line 719, in parse
    self._tag_root(de)
  File "/home/odoo/src/odoo/14.0/odoo/tools/convert.py", line 677, in _tag_root
    f(rec)
  File "/home/odoo/src/odoo/14.0/odoo/tools/convert.py", line 685, in _tag_root
    )) from e
odoo.tools.convert.ParseError: while parsing /home/odoo/src/enterprise/14.0/industry_fsm_sale/data/industry_fsm_data.xml:11, near
<record id="field_service_product" model="product.product">
            <field name="name">Field Service</field>
            <field name="project_id" ref="industry_fsm.fsm_project"/>
            <field name="service_tracking">task_global_project</field>
            <field name="type">service</field>
            <field name="list_price">100</field>
            <field name="uom_id" ref="uom.product_uom_hour"/>
            <field name="uom_po_id" ref="uom.product_uom_hour"/>
            <field name="service_policy">delivered_timesheet</field>
            <field name="image_1920" type="base64" file="sale_timesheet/static/img/product_product_time_product.png"/>
        </record>
```

To avoid the problem, we let the ORM create the new product, which shouldn't raise
any constraint ats its a brand new module, and
then afterwards we remove the product newly created,
and rename the xmlid of the former product from `industry_fsm` to `industry_fsm_sale`

upg-10130
upg-9339
upg-8241
upg-2886

closes odoo/upgrade#2292

Signed-off-by: Denis Ledoux (dle) <dle@odoo.com>