[FIX] {product,sale,website_sale}/12.0: fix demo loading
`function` tags in XML data are skipped if they are in a noupdate block.
This leads to errors in these modules because the function is supposed
to create some records[^1] with xmlids that are later updated[^2]. But
if the records are not created by the function then they are by the
"update" part which leads to a create with missing values. Later if the
records are missing the update from other modules could fail as well.

Example errors below.

Product:
```
2025-06-03 13:42:39,819 415242 INFO test_11_ssa_12 odoo.modules.loading: loading product/data/product_demo.xml
2025-06-03 13:42:39,899 415242 ERROR test_11_ssa_12 odoo.sql_db: bad query: INSERT INTO "product_template_attribute_value" ("id", "create_uid", "create_date", "write_uid", "write_date", "price_extra") VALUES (next
val('product_template_attribute_value_id_seq'), 1, (now() at time zone 'UTC'), 1, (now() at time zone 'UTC'), '50.40') RETURNING id
ERROR: null value in column "product_attribute_value_id" of relation "product_template_attribute_value" violates not-null constraint
DETAIL:  Failing row contains (8, 1, 2025-06-03 13:42:38.833743, 1, 2025-06-03 13:42:38.833743, null, null, 50.40).
```

Sale:
```
2025-06-03 13:43:51,941 416426 ERROR test_11_ssa_12 odoo.tools.convert.init: Could not eval([(6,0,[ref('sale.product_template_attribute_value_5')])]) for value_ids in {}
2025-06-03 13:43:51,941 416426 WARNING test_11_ssa_12 odoo.modules.loading: Module sale demo data failed to install, installed without demo data
Traceback (most recent call last):
  File "/home/odoo/src/odoo/12.0/odoo/tools/cache.py", line 88, in lookup
    r = d[key]
  File "/home/odoo/src/odoo/12.0/odoo/tools/func.py", line 69, in wrapper
    return func(self, *args, **kwargs)
  File "/home/odoo/src/odoo/12.0/odoo/tools/lru.py", line 44, in __getitem__
    a = self.d[obj].me
KeyError: ('ir.model.data', <function IrModelData.xmlid_lookup at 0x7300e4daa940>, 'sale.product_template_attribute_value_5')
```

Website Sale:
```
2025-06-03 13:45:31,812 418305 INFO test_11_ssa_12 odoo.modules.loading: loading website_sale/data/demo.xml
2025-06-03 13:45:32,076 418305 ERROR test_11_ssa_12 odoo.sql_db: bad query: INSERT INTO "product_template_attribute_value" ("id", "create_uid", "create_date", "write_uid", "write_date", "price_extra") VALUES (next
val('product_template_attribute_value_id_seq'), 1, (now() at time zone 'UTC'), 1, (now() at time zone 'UTC'), '18.00') RETURNING id
ERROR: null value in column "product_attribute_value_id" of relation "product_template_attribute_value" violates not-null constraint
DETAIL:  Failing row contains (10, 1, 2025-06-03 13:45:30.116975, 1, 2025-06-03 13:45:30.116975, null, null, 18.00).
```

[^1]: https://github.com/odoo/odoo/blob/ba1ba88874e2ae9716e59ec199eb739d58c3f771/addons/product/data/product_demo.xml#L334-L344
      https://github.com/odoo/odoo/blob/ba1ba88874e2ae9716e59ec199eb739d58c3f771/addons/sale/data/sale_demo.xml#L784-L798
      https://github.com/odoo/odoo/blob/ba1ba88874e2ae9716e59ec199eb739d58c3f771/addons/website_sale/data/demo.xml#L670-L676

[^2]: https://github.com/odoo/odoo/blob/ba1ba88874e2ae9716e59ec199eb739d58c3f771/addons/product/data/product_demo.xml#L346-L352
      https://github.com/odoo/odoo/blob/ba1ba88874e2ae9716e59ec199eb739d58c3f771/addons/sale/data/sale_demo.xml#L828-L830
      https://github.com/odoo/odoo/blob/ba1ba88874e2ae9716e59ec199eb739d58c3f771/addons/website_sale/data/demo.xml#L678-L680

Part-of: odoo/upgrade#7970
Signed-off-by: Christophe Simonis (chs) <chs@odoo.com>