[FIX] product/saas~13.5.1.2: fix typo
```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/14.0/odoo/service/server.py", line 1199, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/odoo/src/odoo/14.0/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/src/odoo/14.0/odoo/modules/loading.py", line 503, in load_modules
    env['ir.model.data']._process_end(processed_modules)
  File "/tmp/tmpz6goiws3/migrations/base/0.0.0/pre-models-no-model-data-delete.py", line 102, in _process_end
    return super(IrModelData, self)._process_end(modules)
  File "/home/odoo/src/odoo/14.0/odoo/addons/base/models/ir_model.py", line 2296, in _process_end
    record.unlink()
  File "/tmp/tmpz6goiws3/migrations/base/0.0.0/pre-models-ir_model.py", line 160, in unlink
    "💥 It looks like you forgot to call `util.remove_field` on the following fields: %s" % ", ".join(fields)
odoo.upgrade.util.exceptions.MigrationError: 💥 It looks like you forgot to call `util.remove_field` on the following fields: product.attribute.custom.value.sale_order_line_id
```
Because sale_order_line_id gets moved to product, but it's not moved
back due to the typo.
This DB also has `sale` module uninstalled, which _should_ have removed
this field, but it didn't.

upg-40682

closes odoo/upgrade#2950

Signed-off-by: Christophe Simonis <chs@odoo.com>