[FIX] documents/saas~17.5: Fix Query Error
This fix aims to resolve the syntax error due to the script in documents module.

Steps to produce the blocking point:

-> Install 'Documents' in v17.4 in fresh database.
-> Migrate to v18
-> Following traceback will occur.

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/18.0/odoo/service/server.py", line 1305,
in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "<decorator-gen-13>", line 2, in new
  File "/home/odoo/src/odoo/18.0/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/18.0/odoo/modules/registry.py", line 131, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/18.0/odoo/modules/loading.py", line 513, in
load_modules
    migrations.migrate_module(package, 'end')
  File "/home/odoo/src/odoo/18.0/odoo/modules/migration.py", line 254, in
migrate_module
    mod.migrate(self.cr, installed_version)
  File "/tmp/tmpe_vclws9/migrations/documents/saas~17.5.1.4/end-migrate.py",
 line 105, in migrate
    queries_steps = migrate_workflow_rule(
  File "/tmp/tmpe_vclws9/migrations/documents/saas~17.5.1.4/end-migrate.py",
line 405, in migrate_workflow_rule
    cr.execute(
  File "/home/odoo/src/odoo/18.0/odoo/sql_db.py", line 354, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.SyntaxError: syntax error at or near ")"
LINE 11:          WHERE wr.id IN ()

```
So,i added return case if no values found in workflow_rules to avoid further
redundant checks.

closes odoo/upgrade#6762

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>