[FIX] base/saas~16.2: fix dependency issue for stock_delivery
If delivery module is not installed and website_sale installed
on Odoo 16 or saas~16.1, then it will load demo data
of stock_delivery module and which break the test on hand qty
as we had mismatch on hand qty because from demo data
it will create picking and stock move which effect
on hand qty after upgrade.

upg-696340
upg-763859

```
Traceback (most recent call last):
  File "/tmp/tmplfw81dyx/migrations/testing.py", line 211, in test_check
    self.check(value)
  File "/tmp/tmplfw81dyx/migrations/stock/tests/test_on_hand_quantity.py", line 41, in check
    self.assertEqual(before_results, self.convert_check(after_results), self.message)
AssertionError: Lists differ: [[6, [68 chars]8, '460'], [19, '18'], [20, '-1'], [21, '22'],[553 chars]10']] != [[6, [68 chars]8, '459'], [19, '18'], [20, '-1'], [21, '22'],[553 chars]10']]

First differing element 6:
[18, '460']
[18, '459']

```

closes odoo/upgrade#4650

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>