[FIX] base@0.0.0: missing `@api.model` on create
Without adding the `@api.model` on `def create`,
the upgrade works well,
but if you try to create a record, without restarting
the server without the upgrade path,
it raises when creating a record (e.g. a crm tag).
See the traceback below.

```
Traceback (most recent call last):
  File "/home/dle/src/odoo/master/odoo/addons/base/models/ir_http.py", line 229, in _dispatch
    result = request.dispatch()
  File "/home/dle/src/odoo/master/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/home/dle/src/odoo/master/odoo/http.py", line 353, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/home/dle/src/odoo/master/odoo/service/model.py", line 93, in wrapper
    return f(dbname, *args, **kwargs)
  File "/home/dle/src/odoo/master/odoo/http.py", line 346, in checked_call
    result = self.endpoint(*a, **kw)
  File "/home/dle/src/odoo/master/odoo/http.py", line 919, in __call__
    return self.method(*args, **kw)
  File "/home/dle/src/odoo/master/odoo/http.py", line 523, in response_wrap
    response = f(*args, **kw)
  File "/home/dle/src/odoo/master/addons/web/controllers/main.py", line 1320, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/dle/src/odoo/master/addons/web/controllers/main.py", line 1312, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/dle/src/odoo/master/odoo/api.py", line 385, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/dle/src/odoo/master/odoo/api.py", line 372, in _call_kw_multi
    result = method(recs, *args, **kwargs)
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/dle/src/odoo/master/odoo/http.py", line 631, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/home/dle/src/odoo/master/odoo/http.py", line 317, in _handle_exception
    raise exception.with_traceback(None) from new_cause
TypeError: create() missing 1 required positional argument: 'values'
```