Revert "[IMP] stock/16.0: recompute fields with query"
This reverts commit de796a8e5370164615d8993ecfc26351e219bb42.

Because of:
upg-3133791

```
Traceback (most recent call last):
[...]
  File "/tmp/tmpedjm7eqk/migrations/stock/16.0.1.1/post-migrate.py", line 9, in migrate
    util.recompute_fields(cr, "stock.move", ["quantity_done"], strategy="commit")
[...]
psycopg2.DatabaseError: out of memory for query result
```

Note that this is the second place where we need to revert the same thing for
this DB. So it may be better to improve
https://github.com/odoo/upgrade-util/pull/317 right now.

closes odoo/upgrade#8474

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>