[FIX] documents@0.0.0: `_match_uniq` `documents.facet`
```
2021-03-17 08:59:13,663 33 INFO db_9964 odoo.modules.loading: loading documents/data/documents_data.xml
2021-03-17 08:59:13,670 33 ERROR db_9964 odoo.sql_db: bad query: INSERT INTO "documents_facet" ("id", "create_uid", "create_date", "write_uid", "write_date", "folder_id", "name", "sequence") VALUES (nextval('documents_facet_id_seq'), 1, (now() at time zone 'UTC'), 1, (now() at time zone 'UTC'), 2, 'Status', 1) RETURNING id
ERROR: duplicate key value violates unique constraint "documents_facet_name_unique"
DETAIL:  Key (folder_id, name)=(2, Status) already exists.

2021-03-17 08:59:13,683 33 WARNING db_9964 odoo.modules.loading: Transient module states were reset
2021-03-17 08:59:13,683 33 ERROR db_9964 odoo.modules.registry: Failed to load registry
2021-03-17 08:59:13,683 33 CRITICAL db_9964 odoo.service.server: Failed to initialize database `db_9964`.
Traceback (most recent call last):
  File "/home/odoo/src/odoo/14.0/odoo/tools/convert.py", line 677, in _tag_root
    f(rec)
  File "/home/odoo/src/odoo/14.0/odoo/tools/convert.py", line 580, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 4214, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 4143, in _load_records_create
    return self.create(values)
  File "<decorator-gen-112>", line 2, in create
  File "/home/odoo/src/odoo/14.0/odoo/api.py", line 326, in _model_create_single
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/home/odoo/src/odoo/14.0/odoo/api.py", line 326, in <genexpr>
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/tmp/tmpu2dq518n/migrations/base/0.0.0/pre-models-match_uniq.py", line 22, in create
    return super(Base, self).create(values)
  File "<decorator-gen-64>", line 2, in create
  File "/home/odoo/src/odoo/14.0/odoo/api.py", line 344, in _model_create_multi
    return create(self, [arg])
  File "/home/odoo/src/odoo/14.0/odoo/addons/base/models/ir_fields.py", line 533, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "/home/odoo/src/odoo/14.0/odoo/api.py", line 345, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 3871, in create
    records = self._create(data_list)
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 3977, in _create
    cr.execute(query, params)
  File "<decorator-gen-3>", line 2, in execute
  File "/home/odoo/src/odoo/14.0/odoo/sql_db.py", line 101, in check
    return f(self, *args, **kwargs)
  File "/home/odoo/src/odoo/14.0/odoo/sql_db.py", line 298, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "documents_facet_name_unique"
DETAIL:  Key (folder_id, name)=(2, Status) already exists.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/14.0/odoo/service/server.py", line 1198, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/odoo/src/odoo/14.0/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/src/odoo/14.0/odoo/modules/loading.py", line 451, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/home/odoo/src/odoo/14.0/odoo/modules/loading.py", line 348, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/odoo/src/odoo/14.0/odoo/modules/loading.py", line 221, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/home/odoo/src/odoo/14.0/odoo/modules/loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/home/odoo/src/odoo/14.0/odoo/tools/convert.py", line 733, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/home/odoo/src/odoo/14.0/odoo/tools/convert.py", line 799, in convert_xml_import
    obj.parse(doc.getroot())
  File "/home/odoo/src/odoo/14.0/odoo/tools/convert.py", line 719, in parse
    self._tag_root(de)
  File "/home/odoo/src/odoo/14.0/odoo/tools/convert.py", line 677, in _tag_root
    f(rec)
  File "/home/odoo/src/odoo/14.0/odoo/tools/convert.py", line 685, in _tag_root
    )) from e
odoo.tools.convert.ParseError: while parsing /home/odoo/src/enterprise/14.0/documents/data/documents_data.xml:71, near
<record id="documents_finance_status" model="documents.facet">
            <field name="name">Status</field>
            <field name="sequence">1</field>
            <field name="folder_id" ref="documents_finance_folder"/>
        </record>
```

upg-9964

closes odoo/upgrade#2283

Signed-off-by: Denis Ledoux (dle) <dle@odoo.com>