[FIX] industry_fsm/saas~17.5: change fsm action context
PR odoo/enterprise#58375, changed the context, default_user_ids
are not valid for literal_val, and can cause malformed errors. The
context from actions was changed accordingly, but if one of those
actions gets modified through Studio, it won't be updated when the
module is loaded. This triggers an error when the action is used
by a menu.

```
Traceback (most recent call last):
   File "/home/odoo/src/odoo/18.0/odoo/tools/safe_eval.py", line 390, in safe_eval
    return unsafe_eval(c, globals_dict, locals_dict)
   File "ir.actions.server(1455,)", line 1, in <module>
   File "/home/odoo/src/enterprise/18.0/industry_fsm/models/project_task.py", line 370, in _server_action_project_task_fsm
    context = literal_eval(action.get('context', '{}'))
   File "/home/odoo/src/odoo/18.0/odoo/_monkeypatches/literal_eval.py", line 28, in literal_eval
    return orig_literal_eval(expr)
   File "/usr/lib/python3.10/ast.py", line 110, in literal_eval
    return _convert(node_or_string)
   File "/usr/lib/python3.10/ast.py", line 99, in _convert
    return dict(zip(map(_convert, node.keys),
   File "/usr/lib/python3.10/ast.py", line 90, in _convert
    return list(map(_convert, node.elts))
   File "/usr/lib/python3.10/ast.py", line 88, in _convert
    return tuple(map(_convert, node.elts))
   File "/usr/lib/python3.10/ast.py", line 109, in _convert
    return _convert_signed_num(node)
   File "/usr/lib/python3.10/ast.py", line 83, in _convert_signed_num
    return _convert_num(node)
   File "/usr/lib/python3.10/ast.py", line 74, in _convert_num
    _raise_malformed_node(node)
   File "/usr/lib/python3.10/ast.py", line 71, in _raise_malformed_node
    raise ValueError(msg + f': {node!r}')
 ValueError: malformed node or string on line 11: <ast.Name object at 0x7f1634e4a7d0>
```

closes odoo/upgrade#7129

Signed-off-by: Christophe Simonis (chs) <chs@odoo.com>