[FIX] base/tests: fix multi-level child companies
When we have a multilevel hierarchy on companies the crawler because it
takes into account only one level of children companies.
In this patch we get all the descendant companies, walking down the
hierarchy.

```
Traceback (most recent call last):
   File "/home/odoo/src/odoo/14.0/odoo/fields.py", line 1019, in __get__
    self.compute_value(recs)
   File "/home/odoo/src/odoo/14.0/odoo/fields.py", line 1175, in compute_value
    records._compute_field_value(self)
   File "/home/odoo/src/odoo/14.0/addons/mail/models/mail_thread.py", line 410, in _compute_field_value
    return super()._compute_field_value(field)
   File "/home/odoo/src/odoo/14.0/odoo/models.py", line 4057, in _compute_field_value
    getattr(self, field.compute)()
   File "/home/odoo/src/odoo/14.0/addons/payment/models/account_payment.py", line 35, in _compute_related_partners
    | p.partner_id.commercial_partner_id.child_ids
   File "/home/odoo/src/odoo/14.0/odoo/fields.py", line 3147, in __get__
    return super().__get__(records, owner)
   File "/home/odoo/src/odoo/14.0/odoo/fields.py", line 2483, in __get__
    return super().__get__(records, owner)
   File "/home/odoo/src/odoo/14.0/odoo/fields.py", line 998, in __get__
    record._fetch_field(self)
   File "/home/odoo/src/odoo/14.0/odoo/models.py", line 3065, in _fetch_field
    self._read(fnames)
   File "/home/odoo/src/odoo/14.0/odoo/models.py", line 3135, in _read
    self.check_access_rule('read')
   File "/home/odoo/src/odoo/14.0/odoo/models.py", line 3349, in check_access_rule
    raise self.env['ir.rule']._make_access_error(operation, forbidden)
 odoo.exceptions.AccessError: Due to security restrictions, you are not allowed to access 'Contact' (res.partner) records.
```
This example TB is due to (breadcrums):
`Payments > SUPP.OUT/2021/0611 > James Briggs > OmniAnts LLC > Gaatu, Inc. > Gaatu Consolidated`
The payment SUPP.OUT/2021/0611 is using a Contact (James Briggs) from a
company (OmniAnts LLC) that is a second level child of the admin company
(Gaatu Consolidated).

upg-22794

closes odoo/upgrade#2779

Signed-off-by: Christophe Simonis <chs@odoo.com>