[FIX] tests: fix crawler non-deterministic errors
The fields_list, as gotten from the arch, is non-deterministic.
Concretely, the list is different on each run. This makes tests less
reliable since they load/fetch fields in a different order each time.

On this commit we keep the order of the fields as on the arch. We
choose to do so, first to have reproducible runs, and second because it
seems that's the way the webclient behaves?[^3]

That being said the real details of the need for this change are below.

Running tests with a different order in the fields list has a very nasty
effect: sometimes the test fails, sometimes it does not. In particular,
recently we have a set of failing upgrades that seemed to be fixed just
by rerunning them. The recurring traceback was:
```
 Traceback (most recent call last):
   File "/tmp/tmpxfawxzel/migrations/base/tests/test_mock_crawl.py", line 193, in crawl_menu
    self.mock_action(action_vals)
   File "/tmp/tmpxfawxzel/migrations/base/tests/test_mock_crawl.py", line 307, in mock_action
    mock_method(model, view, fields_list, domain, group_by)
   File "/tmp/tmpxfawxzel/migrations/base/tests/test_mock_crawl.py", line 335, in mock_view_form
    [data] = record.read(fields_list)
   File "/home/odoo/src/odoo/15.0/odoo/models.py", line 3227, in read
    return self._read_format(fnames=fields, load=load)
   File "/home/odoo/src/odoo/15.0/odoo/models.py", line 3247, in _read_format
    vals[name] = convert(record[name], record, use_name_get)
   File "/home/odoo/src/odoo/15.0/odoo/models.py", line 5885, in __getitem__
    return self._fields[key].__get__(self, type(self))
   File "/home/odoo/src/odoo/15.0/odoo/fields.py", line 1108, in __get__
    self.compute_value(record)
   File "/home/odoo/src/odoo/15.0/odoo/fields.py", line 1265, in compute_value
    records._compute_field_value(self)
   File "/home/odoo/src/odoo/15.0/odoo/models.py", line 4255, in _compute_field_value
    getattr(self, field.compute)()
   File "/home/odoo/src/enterprise/15.0/sale_purchase_inter_company_rules/models/res_company.py", line 52, in _compute_intercompany_transaction_message
    record.intercompany_transaction_message = record._intercompany_transaction_message_so_and_po(record.rule_type, record.auto_validation, record.warehouse_id)
   File "/home/odoo/src/enterprise/15.0/sale_purchase_inter_company_rules/models/res_company.py", line 36, in _intercompany_transaction_message_so_and_po
    'warehouse': warehouse_id.display_name,
   File "/home/odoo/src/odoo/15.0/odoo/fields.py", line 1108, in __get__
    self.compute_value(record)
   File "/home/odoo/src/odoo/15.0/odoo/fields.py", line 1265, in compute_value
    records._compute_field_value(self)
   File "/home/odoo/src/odoo/15.0/odoo/models.py", line 4255, in _compute_field_value
    getattr(self, field.compute)()
   File "/home/odoo/src/odoo/15.0/odoo/models.py", line 1830, in _compute_display_name
    names = dict(self.name_get())
   File "/home/odoo/src/odoo/15.0/odoo/models.py", line 1848, in name_get
    result.append((record.id, convert(record[name], record)))
   File "/home/odoo/src/odoo/15.0/odoo/models.py", line 5885, in __getitem__
    return self._fields[key].__get__(self, type(self))
   File "/home/odoo/src/odoo/15.0/odoo/fields.py", line 1085, in __get__
    record._fetch_field(self)
   File "/home/odoo/src/odoo/15.0/odoo/models.py", line 3276, in _fetch_field
    self._read(fnames)
   File "/home/odoo/src/odoo/15.0/odoo/models.py", line 3387, in _read
    raise self.env['ir.rule']._make_access_error('read', forbidden)
 odoo.exceptions.AccessError: Due to security restrictions, you are not allowed to access 'Warehouse' (stock.warehouse) records.
```
The reason why it fails is because the order of the fields for this view
matters! If we read first `warehouse_id` then `intercompany_transaction_message` all goes fine.
Below an example fields list that does not fail:
```py
['city', 'name', 'sequence', 'message_ids', 'state_id', 'street', 'street2', 'company_registry', 'account_enabled_tax_country_ids', 'warehouse_id', 'message_follower_ids', 'favicon', 'email', 'account_tax_unit_ids', 'mobile', 'auto_validation', 'country_code', 'intercompany_user_id', 'currency_id', 'rule_type', 'iap_enrich_auto_done', 'country_id', 'intercompany_transaction_message', 'account_display_representative_field', 'zip', 'account_representative_id', 'partner_id', 'partner_gid', 'vat', 'phone', 'website', 'logo', 'parent_id'],
```
Here an example that fails:
```py
['partner_gid', 'website', 'name', 'account_enabled_tax_country_ids', 'message_follower_ids', 'parent_id', 'logo', 'currency_id', 'sequence', 'account_representative_id', 'rule_type', 'intercompany_transaction_message', 'city', 'street2', 'company_registry', 'account_tax_unit_ids', 'email', 'message_ids', 'zip', 'street', 'phone', 'partner_id', 'state_id', 'vat', 'auto_validation', 'favicon', 'iap_enrich_auto_done', 'mobile', 'warehouse_id', 'intercompany_user_id', 'country_code', 'country_id', 'account_display_representative_field']
```
After some debugging and many good/bad fields lists it became clear that
what makes generating `intercompany_transaction_message` fail is whether
`warehouse_id`[^1] is read before or after this field. If read before
the record will be in cache when `intercompany_transaction_message`
needs it, if read after the compute may fail since we are trying to
fetch information from a different company.

Note that for this test to fail it _must_ read the fields with the
_right_ order on the `test_prepare` then with the _bad_ order on the
`test_check`. Since the fields list has a random order this does not
happen always! That's what makes this bug so difficult to detect: it
does not happen often and when it happens it's not simple to reproduce!
Upg-293541 seems to be one of the rare cases that makes this bug appear
more often on `test_prepare`.

This issue is reproducible in standard[^2]. If we create a new form view for
res.company with just the field `intercompany_transaction_message` this
view will fail if we try to show the details of a company that is not on
the cids list (still with admin user). The standard view does not fail
because of the above mentioned caching, which is avoided by the
webclient[^3] somehow (in spite that it seems to requests the fields
ordered by name AFAICT).

The reason why reading `warehouse_id.display_name` first is OK becomes
apparent once we look at what happens when it is read directly (i.e. as
part of the crawler call[^4], highlighted below the relevant line):
```
  /tmp/tmpxiwxg_7n/migrations/base/tests/test_mock_crawl.py(160)invariant()
-> failing.update(self.crawl_menu(get_menu(menu), get_menu))
  /tmp/tmpxiwxg_7n/migrations/base/tests/test_mock_crawl.py(209)crawl_menu()
-> failing.update(self.crawl_menu(get_menu(child), get_menu, menu_name))
  /tmp/tmpxiwxg_7n/migrations/base/tests/test_mock_crawl.py(209)crawl_menu()
-> failing.update(self.crawl_menu(get_menu(child), get_menu, menu_name))
  /tmp/tmpxiwxg_7n/migrations/base/tests/test_mock_crawl.py(201)crawl_menu()
-> self.mock_action(action_vals)
  /tmp/tmpxiwxg_7n/migrations/base/tests/test_mock_crawl.py(319)mock_action()
-> mock_method(model, view, fields_list, domain, group_by)
  /tmp/tmpxiwxg_7n/migrations/base/tests/test_mock_crawl.py(351)mock_view_form()
-> [data] = record.read(fields_list)
  /home/odoo/src/odoo/saas-15.1/odoo/models.py(3243)read()
-> return self._read_format(fnames=fields, load=load)
  /home/odoo/src/odoo/saas-15.1/odoo/models.py(3263)_read_format()
-> vals[name] = convert(record[name], record, use_name_get)
  /home/odoo/src/odoo/saas-15.1/odoo/fields.py(2858)convert_to_read()
-> return (value.id, value.sudo().display_name)   *********
  /home/odoo/src/odoo/saas-15.1/odoo/fields.py(1150)__get__()
-> self.compute_value(recs)
  /home/odoo/src/odoo/saas-15.1/odoo/fields.py(1309)compute_value()
-> records._compute_field_value(self)
  /home/odoo/src/odoo/saas-15.1/odoo/models.py(4343)_compute_field_value()
-> getattr(self, field.compute)()
  /home/odoo/src/odoo/saas-15.1/odoo/models.py(1830)_compute_display_name()
-> names = dict(self.name_get())
  /home/odoo/src/odoo/saas-15.1/odoo/models.py(1853)name_get()
-> result.append((record.id, convert(record[name], record)))
  /home/odoo/src/odoo/saas-15.1/odoo/models.py(5975)__getitem__()
-> return self._fields[key].__get__(self, type(self))
  /home/odoo/src/odoo/saas-15.1/odoo/fields.py(1127)__get__()
-> recs._fetch_field(self)
  /home/odoo/src/odoo/saas-15.1/odoo/models.py(3292)_fetch_field()
-> self._read(fnames)
  /home/odoo/src/odoo/saas-15.1/odoo/models.py(3342)_read()
-> self._apply_ir_rules(query, 'read')
```

In summary: having a fixed order for the fields list will make tests
more reproducible and will avoid headaches as this one. On the cons side
it was _this non-determinism_ what perhaps uncovered an issue in
standard, at the cost of multiple failing requests, among which several
production rolling release ones. The cost is probably not worth it.

[^1]: https://github.com/odoo/enterprise/blob/bea5408d5071302bf819f0471ad9e55ebfc10a7b/sale_purchase_inter_company_rules/models/res_company.py#L36
[^2]: I will propose a fix in standard, still this does not invalidate
the reproducible-tests argument at the core of this PR.
[^3]: Following the details of how fields are fetched by the webclient
in both `read` and `search_read`.
[^4]: https://github.com/odoo/upgrade/blob/4ed088f0dc4d4baba8c5a78a1f8cf832bf01ebb9/migrations/base/tests/test_mock_crawl.py#L335

upg-293541

closes odoo/upgrade#3518

Signed-off-by: Christophe Simonis <chs@odoo.com>