[FIX] hr_expense/saas~18.2.2.0: correct module name
Steps to reproduce:
- Create a DB in saas-18.1 with the 'Expense' module
- Give Marc Demo as 'Team Approver' rights in the expense
- Upgrade to saas-18.2 and log in with Marc Demo
- Open 'Expense' >> Error

Traceback:
ValueError: Invalid field hr.expense.user_id in condition ('user_id', '=', 21)

At [1], the module name was incorrectly written as 'hr.expense' instead of the
correct 'hr_expense'.

[1]- https://github.com/odoo/upgrade/pull/6990/files#diff-10f788108069a9e33d32f9362e648020828ff21e65b44fdba5bd248d1acc30beR8-R12

sentry-6542662358, 6585778452

closes odoo/upgrade#7665

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>