[FIX] data-merge/saas~14.1.1.3: fix `data-merge-rule` constraint
If the client deletes some record from `data_merge.rule` and creates it with
the the same data, when they are re-created during the upgrade a violation of
`data_merge_rule_uniq_model_id_field_id` will happen.

By remapping the xmlids we avoid that problem.

upg-47986

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/15.0/odoo/tools/convert.py", line 680, in _tag_root
    f(rec)
  File "/home/odoo/src/odoo/15.0/odoo/tools/convert.py", line 583, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/home/odoo/src/odoo/15.0/odoo/models.py", line 4398, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/home/odoo/src/odoo/15.0/odoo/models.py", line 4327, in _load_records_create
    return self.create(values)
  File "<decorator-gen-119>", line 2, in create
  File "/home/odoo/src/odoo/15.0/odoo/api.py", line 394, in _model_create_single
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/home/odoo/src/odoo/15.0/odoo/api.py", line 394, in <genexpr>
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/tmp/tmpegyq5h7k/migrations/base/0.0.0/pre-models-match_uniq.py", line 22, in create
    return super(Base, self).create(values)
  File "<decorator-gen-67>", line 2, in create
  File "/home/odoo/src/odoo/15.0/odoo/api.py", line 412, in _model_create_multi
    return create(self, [arg])
  File "/home/odoo/src/odoo/15.0/odoo/addons/base/models/ir_fields.py", line 613, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "/home/odoo/src/odoo/15.0/odoo/api.py", line 413, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/15.0/odoo/models.py", line 4063, in create
    records = self._create(data_list)
  File "/home/odoo/src/odoo/15.0/odoo/models.py", line 4161, in _create
    cr.execute(query, params)
  File "<decorator-gen-3>", line 2, in execute
  File "/home/odoo/src/odoo/15.0/odoo/sql_db.py", line 89, in check
    return f(self, *args, **kwargs)
  File "/home/odoo/src/odoo/15.0/odoo/sql_db.py", line 310, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "data_merge_rule_uniq_model_id_field_id"
DETAIL:  Key (model_id, field_id)=(2, 892) already exists.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/15.0/odoo/service/server.py", line 1246, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/odoo/src/odoo/15.0/odoo/modules/registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/15.0/odoo/modules/loading.py", line 470, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/home/odoo/src/odoo/15.0/odoo/modules/loading.py", line 363, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/odoo/src/odoo/15.0/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/home/odoo/src/odoo/15.0/odoo/modules/loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/home/odoo/src/odoo/15.0/odoo/tools/convert.py", line 745, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/home/odoo/src/odoo/15.0/odoo/tools/convert.py", line 811, in convert_xml_import
    obj.parse(doc.getroot())
  File "/home/odoo/src/odoo/15.0/odoo/tools/convert.py", line 731, in parse
    self._tag_root(de)
  File "/home/odoo/src/odoo/15.0/odoo/tools/convert.py", line 680, in _tag_root
    f(rec)
  File "/home/odoo/src/odoo/15.0/odoo/tools/convert.py", line 693, in _tag_root
    raise ParseError('while parsing %s:%s, somewhere inside\n%s' % (
odoo.tools.convert.ParseError: while parsing /home/odoo/src/enterprise/15.0/data_merge/data/data_merge_data.xml:40, somewhere inside
<record model="data_merge.rule" id="data_merge_field_res_partner_category_name">
            <field name="model_id" ref="data_merge_model_res_partner_category"/>
            <field name="field_id" ref="base.field_res_partner_category__name"/>
            <field name="match_mode">accent</field>
        </record>
```

closes odoo/upgrade#3073

Signed-off-by: Nicolas Seinlet (nse) <nse@odoo.com>