[FIX] sale/saas~16.2: Assign correct company product
``sale.default_deposit_product_id`` product related
product template belongs to one company but here
while creating column ``sale_down_payment_product_id``
it's assigning to that product every company
which is wrong due to that below traceback raised.

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/17.0/odoo/service/server.py", line 1314, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "<decorator-gen-16>", line 2, in new
  File "/home/odoo/src/odoo/17.0/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/17.0/odoo/modules/registry.py", line 110, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/17.0/odoo/modules/loading.py", line 515, in load_modules
    migrations.migrate_module(package, 'end')
  File "/home/odoo/src/odoo/17.0/odoo/modules/migration.py", line 240, in migrate_module
    migrate(self.cr, installed_version)
  File "/home/odoo/src/odoo/17.0/addons/l10n_es/migrations/5.4/end-migrate.py", line 7, in migrate
    env['account.chart.template'].try_loading(company.chart_template, company)
  File "/home/odoo/src/odoo/17.0/addons/account/models/chart_template.py", line 155, in try_loading
    return self._load(template_code, company, install_demo)
  File "/home/odoo/src/odoo/17.0/addons/account/models/chart_template.py", line 213, in _load
    self._load_data(data)
  File "/tmp/tmp2shuvhzc/migrations/account/0.0.0/pre-ensure-deferred-accounts.py", line 36, in _load_data
    return super()._load_data(data, *args, **kwargs)
  File "/home/odoo/src/odoo/17.0/addons/account/models/chart_template.py", line 615, in _load_data
    created_records[model] = self.with_context(lang='en_US').env[model]._load_records(all_records_vals)
  File "/home/odoo/src/odoo/17.0/odoo/models.py", line 5065, in _load_records
    data['record']._load_records_write(data['values'])
  File "/home/odoo/src/odoo/17.0/odoo/models.py", line 4996, in _load_records_write
    self.write(values)
  File "/home/odoo/src/enterprise/17.0/timesheet_grid/models/res_company.py", line 41, in write
    result = super(Company, self).write(values)
  File "/home/odoo/src/enterprise/17.0/account_reports/models/res_company.py", line 75, in write
    res = super().write(values)
  File "/home/odoo/src/enterprise/17.0/account_accountant/models/res_company.py", line 64, in write
    rslt = super(ResCompany, self).write(vals)
  File "/home/odoo/src/odoo/17.0/addons/hr_holidays_attendance/models/res_company.py", line 24, in write
    res = super().write(vals)
  File "/home/odoo/src/odoo/17.0/addons/account/models/company.py", line 409, in write
    return super(ResCompany, self).write(values)
  File "/home/odoo/src/odoo/17.0/addons/hr_attendance/models/res_company.py", line 105, in write
    res = super().write(vals)
  File "/home/odoo/src/odoo/17.0/addons/product/models/res_company.py", line 60, in write
    return super().write(vals)
  File "/home/odoo/src/odoo/17.0/addons/web/models/models.py", line 1132, in write
    res = super().write(values)
  File "/home/odoo/src/odoo/17.0/odoo/addons/base/models/res_company.py", line 310, in write
    res = super(Company, self).write(values)
  File "/home/odoo/src/odoo/17.0/addons/mail/models/mail_thread.py", line 311, in write
    return super(MailThread, self).write(values)
  File "/home/odoo/src/odoo/17.0/odoo/models.py", line 4473, in write
    self._check_company()
  File "/home/odoo/src/odoo/17.0/odoo/models.py", line 4107, in _check_company
    raise UserError("\n".join(lines))
odoo.exceptions.UserError: Empresas incompatibles con los registros:
- Informe es de la compañía 'Luminescence S.L.' y 'Deposit Product' (sale_down_payment_product_id: 'Anticipo') pertenece a otra compañía.
```

for resolving this assigning correct company to that record

upg-2390902
opw-4351292

closes odoo/upgrade#6913

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>