[FIX] hr: oversight in 5e4c550ec45be6c1fd03c4cab9a7b8f5259253c4
`user_id` is stored only in Odoo >= 12.0

```
  File "/src/odoo/10.0/odoo/addons/base/maintenance/migrations/hr/0.0.0/pre-ensure-admin-employee.py", line 17, in migrate
    util.ensure_xmlid_match_record(cr, xml_id_employee, "hr.employee", {"user_id": util.ref(cr, xml_id_user)})
  File "/src/odoo/10.0/odoo/addons/base/maintenance/migrations/util.py", line 947, in ensure_xmlid_match_record
    cr.execute(query, data)
  File "/src/odoo/10.0/odoo/sql_db.py", line 154, in wrapper
    return f(self, *args, **kwargs)
  File "/src/odoo/10.0/odoo/sql_db.py", line 231, in execute
    res = self._obj.execute(query, params)
psycopg2.ProgrammingError: column "user_id" does not exist
```

Request 52739, 52734, 52729, 52715, 52701, 52638, 52515

closes odoo/upgrade#1630

Signed-off-by: Denis Ledoux (dle) <dle@odoo.com>