[FIX] l10n_be/saas~18.3: Prevent tax duplication on child companies
This commit c248e68  was creating taxes and accounts for child companies
with chart templates, causing duplicate tax records, blocking the migration.

Issue:
-------
A ValidationError was raised due to duplicate tax names during migration:

    File "/home/odoo/src/odoo/saas-18.3/addons/account/models/account_tax.py",
line 249, in _constrains_name
        raise ValidationError(
    odoo.exceptions.ValidationError: Tax names must be unique!
    - 21% EU Car in ITC MULTIMEDIA SRL
    - 21% S ND in ITC MULTIMEDIA SRL
    - 21% IG ND in ITC MULTIMEDIA SRL

Cause of the issue:
--------------------
Child companies were also included in the loop, leading to the creation of
taxes for both parent companies and child companies
and resulting in duplicates.

As per the `_load()` logic in account.chart.template._load():
https://github.com/odoo/odoo/blob/de21d07d0f4b9b5b070a86132a340d07beb3a79d/addons/account/models/chart_template.py#L224-L227

When a company has a parent (`company.parent_id`), only the res.company
data should be loaded, avoiding creation of duplicate taxes for child
companies.

Steps to reproduce:
--------------------
- Install `l10n_be` on 18.0.
- Create a child company (branch).
- Migrate to saas~18.3.
- The migration fails with a duplicate tax name error.

opw - 4909852
upg-3011618
tgb-1718

closes odoo/upgrade#8024

Signed-off-by: Christophe Simonis (chs) <chs@odoo.com>