[FIX] maintenance/17.0: update close_date for maintenance
`close_Date` for `Maintenance request` was not required field
and will use that field on compute maintenance request
specially for MTTR calculation.
during write, close_Date was updated with current date if
stage_id is in done and close_date is NULL.
so we need to handle that in upgrade script too.
so
we consider requests to be 'done' by their current stage (having the done flag)
so update close_date to consider the last stage change as the true closing date
and if there was no stage change subtype in mail message for some
maintenance request then will use write_date of request.

see: https://github.com/odoo/odoo/commit/c2688e45f318629cc44d445cec65c67e1ccdc3f2
upg-1180862

```
 Traceback (most recent call last):
   File "/tmp/tmp9ygckkc5/migrations/base/tests/test_mock_crawl.py", line 238, in crawl_menu
    self.mock_action(action_vals)
   File "/tmp/tmp9ygckkc5/migrations/base/tests/test_mock_crawl.py", line 394, in mock_action
    mock_method(model, view, fields_list, domain, group_by)
   File "/tmp/tmp9ygckkc5/migrations/base/tests/test_mock_crawl.py", line 423, in mock_view_form
    [data] = record.read(fields_list)
   File "/home/odoo/src/odoo/17.0/odoo/models.py", line 3531, in read
    return self._read_format(fnames=fields, load=load)
   File "/home/odoo/src/odoo/17.0/odoo/models.py", line 3742, in _read_format
    vals[name] = convert(record[name], record, use_display_name)
   File "/home/odoo/src/odoo/17.0/odoo/models.py", line 6584, in __getitem__
    return self._fields[key].__get__(self, type(self))
   File "/home/odoo/src/odoo/17.0/odoo/fields.py", line 1206, in __get__
    self.compute_value(recs)
   File "/home/odoo/src/odoo/17.0/odoo/fields.py", line 1388, in compute_value
    records._compute_field_value(self)
   File "/home/odoo/src/odoo/17.0/addons/mail/models/mail_thread.py", line 424, in _compute_field_value
    return super()._compute_field_value(field)
   File "/home/odoo/src/odoo/17.0/odoo/models.py", line 4858, in _compute_field_value
    fields.determine(field.compute, self)
   File "/home/odoo/src/odoo/17.0/odoo/fields.py", line 101, in determine
    return needle(*args)
   File "/home/odoo/src/odoo/17.0/addons/maintenance/models/maintenance.py", line 109, in _compute_maintenance_request
    record.mttr = len(maintenance_requests) and (sum(int((request.close_date - request.request_date).days) for request in maintenance_requests) / len(maintenance_requests)) or 0
   File "/home/odoo/src/odoo/17.0/addons/maintenance/models/maintenance.py", line 109, in <genexpr>
    record.mttr = len(maintenance_requests) and (sum(int((request.close_date - request.request_date).days) for request in maintenance_requests) / len(maintenance_requests)) or 0
 TypeError: unsupported operand type(s) for -: 'bool' and 'datetime.date'
```

closes odoo/upgrade#5412

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>