[FIX] account_asset@saas~12.3: no migration journal when no asset
Oversight in 3cb2b056576ceef2dabd01bb8112e770222ab1aa

When the table `account_asset` is empty,
no migration journal were created.

Then, the SQL queries doing `journal_id IN ()`
were failing.

This is the shortest fix possible:
 - a global `if` condition checking the table was empty
   would have required a re-indentation, messing up the code authorship,
 - changing the requests to remove `journal_id IN %s` would have been
   painful and ugly,
 - besides, this is not impossible also the table is not empty,
   but `company_id` is NULL for all all records (even if normally it's
   required)

```
Traceback (most recent call last):
  File "/src/odoo/saas-12.3/odoo/service/server.py", line 1167, in
preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/src/odoo/saas-12.3/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status,
update_module)
  File "/src/odoo/saas-12.3/odoo/modules/loading.py", line 417, in
load_modules
    force, status, report, loaded_modules, update_module,
models_to_check)
  File "/src/odoo/saas-12.3/odoo/modules/loading.py", line 313, in
load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/src/odoo/saas-12.3/odoo/modules/loading.py", line 177, in
load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/src/odoo/saas-12.3/odoo/modules/migration.py", line 167, in
migrate_module
    migrate(self.cr, installed_version)
  File
"/src/odoo/saas-12.3/odoo/addons/base/maintenance/migrations/account_asset/saas~12.3.1.0/pre-10-models.py",
line 188, in migrate
    'journal_ids': tuple(migration_journals.ids),
  File "/src/odoo/saas-12.3/odoo/sql_db.py", line 146, in wrapper
    return f(self, *args, **kwargs)
  File "/src/odoo/saas-12.3/odoo/sql_db.py", line 223, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.SyntaxError: syntax error at or near ")"
LINE 76: ...                                        AND journal.id IN ()
```

Request 55496
M1804067200244

closes odoo/upgrade#1859

Signed-off-by: Denis Ledoux (dle) <dle@odoo.com>