[FIX] test_xlsx_export/saas~14.1.0.1: Removed deprecated model
before version saas-14.1, the model 'export.computed.binary' must get removed
but persisted and caused the upgrade error while upgrading to 15.0
```
 File "/home/odoo/src/odoo/15.0/odoo/service/server.py", line 1246, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/odoo/src/odoo/15.0/odoo/modules/registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/15.0/odoo/modules/loading.py", line 513, in load_modules
    env['ir.model.data']._process_end(processed_modules)
  File "/home/odoo/src/upgrade/migrations/base/0.0.0/pre-models-no-model-data-delete.py", line 104, in _process_end
    return super(IrModelData, self)._process_end(modules)
  File "/home/odoo/src/odoo/15.0/odoo/addons/base/models/ir_model.py", line 2275, in _process_end
    self._process_end_unlink_record(record)
  File "/home/odoo/src/odoo/15.0/odoo/addons/base/models/ir_model.py", line 2199, in _process_end_unlink_record
    record.unlink()
  File "/home/odoo/src/upgrade/migrations/base/0.0.0/pre-models-ir_model.py", line 161, in unlink
    raise util.MigrationError(
odoo.upgrade.util.exceptions.MigrationError: 💥 It looks like you forgot to call `util.remove_field` on the
following fields: export.computed.binary.write_date
```

closes odoo/upgrade#3310

Signed-off-by: Christophe Simonis <chs@odoo.com>