[FIX] base/0.0.0: fix bad translation states
When there is an invalid value on ir_translation.state the mechanism
that synchronizes terms fails on write.
Example for 'false' state:
```
Traceback (most recent call last):
  ...
  File "/home/odoo/src/odoo/15.0/odoo/fields.py", line 1641, in write
    records.env['ir.translation']._sync_terms_translations(self, real_recs)
  File "/home/odoo/src/odoo/15.0/odoo/addons/base/models/ir_translation.py", line 439, in _sync_terms_translations
    translation.write(vals)
  File "/home/odoo/src/odoo/15.0/odoo/addons/base/models/ir_translation.py", line 559, in write
    result = super(IrTranslation, self.sudo()).write(vals)
  File "/home/odoo/src/odoo/15.0/odoo/models.py", line 3852, in write
    field.write(self, value)
  File "/home/odoo/src/odoo/15.0/odoo/fields.py", line 1015, in write
    cache_value = self.convert_to_cache(value, records)
  File "/home/odoo/src/odoo/15.0/odoo/fields.py", line 2534, in convert_to_cache
    raise ValueError("Wrong value for %s: %r" % (self, value))
ValueError: Wrong value for ir.translation.state: 'false'
```
Triggered on upgrade to 15.0 while parsing:
https://github.com/odoo/odoo/blob/784a5a3178d1b7f3eba592461dd06a98fc896e9c/addons/website/views/website_navbar_templates.xml#L37
due to the extra `mr-2` w.r.t 14.0

Here we clean all invalid states to avoid the issue. This could happen
on any version therefore the 0.0.0 script.

upg-44116
upg-43272
upg-42602
upg-42527
upg-43614

closes odoo/upgrade#2982

Signed-off-by: Christophe Simonis <chs@odoo.com>