[FIX] base@saas~12.5: `res.company`.`font` existed in 10.0
The field `font` on `res.company` existed in Odoo 10.0
and has been removed in odoo/odoo@3425752eaca236c1e4b4d616aa49b3faa6cfd957 (10~saas.17).

It has never been correctly removed in any upgrade script

```
2020-09-14 09:22:49,850 1474 INFO template_3gNC_13.0 odoo.modules.migration: module base: Running migration [>saas~12.5.1.3] pre-20-models
2020-09-14 09:22:50,450 1474 ERROR template_3gNC_13.0 odoo.upgrade.util: res_company.font already exists but is 'int4' instead of 'varchar'
2020-09-14 09:22:50,456 1474 ERROR template_3gNC_13.0 odoo.sql_db: bad query: UPDATE res_company SET font = 'Lato'
ERROR: invalid input syntax for integer: "Lato"
LINE 1: UPDATE res_company SET font = 'Lato'
```

Request 52118
M20062317095699

closes odoo/upgrade#1759

Signed-off-by: Denis Ledoux (dle) <dle@odoo.com>