[FIX] website_sale/saas~14.5.1.1: fix 'old_order'
Fixes an error introduced by a previous fix:
`UnboundLocalError: local variable 'old_order' referenced before assignment`

upg-43240

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/15.0/odoo/service/server.py", line 1246, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/odoo/src/odoo/15.0/odoo/modules/registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/15.0/odoo/modules/loading.py", line 472, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/home/odoo/src/odoo/15.0/odoo/modules/loading.py", line 365, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/odoo/src/odoo/15.0/odoo/modules/loading.py", line 227, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/home/odoo/src/odoo/15.0/odoo/modules/migration.py", line 180, in migrate_module
    migrate(self.cr, installed_version)
  File "/tmp/tmpuyi01owt/migrations/website_sale/saas~14.5.1.1/post-products-searchbar.py", line 13, in migrate
    migrate_products_searchbar_snippet(cr, "ir_ui_view", "arch_db")
  File "/tmp/tmpuyi01owt/migrations/website_sale/saas~14.5.1.1/post-products-searchbar.py", line 100, in migrate_products_searchbar_snippet
    search_input.set("data-order-by", old_order)
UnboundLocalError: local variable 'old_order' referenced before assignment
```

closes odoo/upgrade#2977

Signed-off-by: Christophe Simonis <chs@odoo.com>