[FIX] hr/saas~18.4.1.1: prevent error on running cronjob
Currently an error occurs when the `HR Contract: update state` scheduled action
runs after upgrading to version 18.4.

Steps to replicate:
* Install `hr_contract`
* Upgrade to version 18.4
* Scheduled Action > `HR Contract: update state` > Run Manually

Error:
`ValueError:AttributeError(''hr.version' object has no attribute 'update_state''
) while evaluating 'model.with_context(from_cron=True).update_state()'`

Root cause:
* After the changes described in [1], the contracts were merged into the
  versioned employee model. Additionally, the contracts model was changed to
  versions, as shown in [2]. As part of this update, the `update_state()` method
  was removed, equivalent functionality was moved to `hr_versions` [3] or
  `hr_employee`[4].
* As a result, the scheduled action `HR Contract: update state` is now
  deprecated but is not removed during the upgrade process.

Solution:
* Remove the scheduled action.

[1]:
https://github.com/odoo/odoo/pull/202869
[2]:
https://github.com/odoo/upgrade/blob/84c69dc5533bd59ed30f7bd16bfd392acbc401ac/migrations/hr/saas~18.4.1.1/pre-migrate.py#L29
[3]:
https://github.com/odoo/odoo/blob/saas-18.4/addons/hr/models/hr_version.py
[4]:
https://github.com/odoo/odoo/blob/f6874befe64daf78dc59fa09a349cad305717bed/addons/hr/models/hr_employee.py#L942-L974

sentry-6837268503

closes odoo/upgrade#8345

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>