[FIX] util/tools: avoid error if init file doesn't exist
When adding a new test file if the `tests` folder is new the
`__init__.py` file may be missing. Avoid raising an exception and
correctly report the problem.

Before:
```
Traceback (most recent call last):
  File "/home/odoo/src/upgrade/tools/check-filenames.py", line 44, in <module>
    for node in ast.walk(ast.parse(init.read_text())):
                                   ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/pathlib.py", line 1029, in read_text
    with self.open(mode='r', encoding=encoding, errors=errors) as f:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/pathlib.py", line 1015, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/odoo/src/upgrade/migrations/account_accountant/tests/__init__.py'
```

After:
```
❌ Missing init file `migrations/account_accountant/tests/__init__.py`. It should import 'test_dummy'.
```

closes odoo/upgrade#6632

Signed-off-by: Christophe Simonis (chs) <chs@odoo.com>