[FIX] base@tests: mock crawler, allow all company childs
In the case of `res.partner`,
the multi company rule was formely
`['|','|',('company_id.child_ids','child_of',[user.company_id.id]),('company_id','child_of',[user.company_id.id]),('company_id','=',False)]`
which has been replaced in Odoo 13.0 with
`['|', '|', ('partner_share', '=', False), ('company_id', 'in', company_ids), ('company_id', '=', False)]`

`company_ids` coming from the context key `allowed_company_ids`

In the case of the two below upgrade requests,
payments were created in the child company (e.g. id #3)
using a partner from the parent company (e.g. id #1)

In Odoo 12.0, it was possible to read the partner of the payment
thanks to the 12.0 multi-company rule which took care to include the child companies.
In Odoo 13.0, it will be possible only if you check both the parent and its childs
in the multi-company dropdown selector, which mimics the former multi-company rule from 12.0.

In order to have the same multi-company behavior than formely, in Odoo >= 12.0,
set in the context `allowed_company_ids` all the company childs,
in order to overcome these multi-company access errors.

```
dle_20249=> SELECT id, parent_id, name FROM res_company ORDER BY id;
 id | parent_id |                   name
----+-----------+-------------------------------------------
  1 |           | JFL-Media
  3 |         1 | JFL MÉDIA FORMATION 9360-4288 QUÉBEC INC.
  4 |           | Betzy Style Makeup & Hairstyle
(3 rows)
```

```
dle_20249=> SELECT j.company_id as payment_company, par.company_id as partner_company
              FROM account_payment pay
              JOIN account_journal j ON j.id = pay.journal_id
              JOIN res_partner par ON par.id = pay.partner_id
             WHERE pay.id = 1855;
 payment_company | partner_company
-----------------+-----------------
               3 |               1
(1 row)
```

```
 Traceback (most recent call last):
   File "/tmp/tmpz9jiy2fo/migrations/base/tests/test_mock_crawl.py", line 176, in crawl_menu
    self.mock_action(action_vals)
   File "/tmp/tmpz9jiy2fo/migrations/base/tests/test_mock_crawl.py", line 267, in mock_action
    mock_method(model, view, fields_list, domain, group_by)
   File "/tmp/tmpz9jiy2fo/migrations/base/tests/test_mock_crawl.py", line 293, in mock_view_form
    [data] = record.read(fields_list)
   File "/home/odoo/src/odoo/14.0/odoo/models.py", line 3016, in read
    return self._read_format(fnames=fields, load=load)
   File "/home/odoo/src/odoo/14.0/odoo/models.py", line 3036, in _read_format
    vals[name] = convert(record[name], record, use_name_get)
   File "/home/odoo/src/odoo/14.0/odoo/models.py", line 5662, in __getitem__
    return self._fields[key].__get__(self, type(self))
   File "/home/odoo/src/odoo/14.0/odoo/fields.py", line 2483, in __get__
    return super().__get__(records, owner)
   File "/home/odoo/src/odoo/14.0/odoo/fields.py", line 1021, in __get__
    self.compute_value(record)
   File "/home/odoo/src/odoo/14.0/odoo/fields.py", line 1175, in compute_value
    records._compute_field_value(self)
   File "/home/odoo/src/odoo/14.0/addons/mail/models/mail_thread.py", line 410, in _compute_field_value
    return super()._compute_field_value(field)
   File "/home/odoo/src/odoo/14.0/odoo/models.py", line 4057, in _compute_field_value
    getattr(self, field.compute)()
   File "/home/odoo/src/odoo/14.0/addons/payment/models/account_payment.py", line 35, in _compute_related_partners
    | p.partner_id.commercial_partner_id.child_ids
   File "/home/odoo/src/odoo/14.0/odoo/fields.py", line 2483, in __get__
    return super().__get__(records, owner)
   File "/home/odoo/src/odoo/14.0/odoo/fields.py", line 998, in __get__
    record._fetch_field(self)
   File "/home/odoo/src/odoo/14.0/odoo/models.py", line 3065, in _fetch_field
    self._read(fnames)
   File "/home/odoo/src/odoo/14.0/odoo/models.py", line 3176, in _read
    raise self.env['ir.rule']._make_access_error('read', forbidden)
 odoo.exceptions.AccessError: En raison de restrictions de sécurité, vous n'êtes pas autorisé à accéder aux enregistrements 'Contact' (res.partner).

Records: Laura Romero (id=30694)
Utilisateur : Stephen Labrosse (id=2)

Cette restriction est due aux règles suivantes:
- res.partner company

Note : ce pourrait être un problème de multi-société.

Contactez votre administrateur pour demander l'accès si nécessaire.
```

upg-20249
upg-17335

closes odoo/upgrade#2692

Signed-off-by: Christophe Simonis <chs@odoo.com>