[FIX] event@saas~15: cast int to bool
'ir_values' named 'auto_confirmation' (model 'event.config.settings') is
defined as an integer in Odoo but 'auto_confirm' column in posqtgresql
is defined as a boolean.

In order to not get a:
  ProgrammingError: column "auto_confirm" is of type boolean but
  expression is of type integer
we need to cast that value as a bool.