[FIX] account/16.0: ignore unexpected types in internal adapter
tbg-885

The `account_internal_adapter` fails to update domains whose values
are extracted from context.
Since we don't have a safe way to update those domains (to my knowledge)
and in order to respect the chance that some custom types were used.
We limit the function to only make changes on the types and values we expect
without raising errors otherwise.

Types in a DB that has the issue before and after the upgrade:
```
yaih_1146044_15.0> select distinct(internal_type) from account_account;
+---------------+
| internal_type |
|---------------|
| receivable    |
| payable       |
| other         |
| liquidity     |
+---------------+
```

```
yaih_1146044_15.0_16.0> select distinct(account_type) from account_account;
+-----------------------+
| account_type          |
|-----------------------|
| asset_cash            |
| expense               |
| equity                |
| liability_payable     |
| liability_non_current |
| asset_receivable      |
| asset_fixed           |
| expense_depreciation  |
| income_other          |
| equity_unaffected     |
| liability_current     |
| asset_current         |
| income                |
+-----------------------+

```

TB example:
```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/16.0/odoo/service/server.py", line 1299, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "<decorator-gen-14>", line 2, in new
  File "/home/odoo/src/odoo/16.0/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/16.0/odoo/modules/registry.py", line 90, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/16.0/odoo/modules/loading.py", line 484, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/home/odoo/src/odoo/16.0/odoo/modules/loading.py", line 372, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/odoo/src/odoo/16.0/odoo/modules/loading.py", line 183, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/home/odoo/src/odoo/16.0/odoo/modules/migration.py", line 189, in migrate_module
    migrate(self.cr, installed_version)
  File "/tmp/tmpboowqp1_/migrations/account/16.0.1.1/pre-migrate.py", line 134, in migrate
    util.update_field_usage(
  File "/tmp/tmpboowqp1_/migrations/util/fields.py", line 785, in update_field_usage
    return _update_field_usage_multi(cr, [model], old, new, domain_adapter=domain_adapter, skip_inherit=skip_inherit)
  File "/tmp/tmpboowqp1_/migrations/util/fields.py", line 971, in _update_field_usage_multi
    adapt_domains(cr, model, old, new, adapter=domain_adapter, skip_inherit="*", force_adapt=True)
  File "/tmp/tmpboowqp1_/migrations/util/domains.py", line 333, in adapt_domains
    domain = _adapt_one_domain(
  File "/tmp/tmpboowqp1_/migrations/util/domains.py", line 246, in _adapt_one_domain
    dom = [clean_term(term) for term in adapter(leaf, is_or, neg)]
  File "/tmp/tmpboowqp1_/migrations/account/16.0.1.1/pre-migrate.py", line 105, in internal_type_adapter
    right = flatten(mapping[r] for r in right) if isinstance(right, (tuple, list)) else mapping[right]
KeyError: account_internal_type
```

closes odoo/upgrade#5189

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>