[FIX] util/records.py: remove_view compatible for older than V8.0
On execution of
[File](https://github.com/odoo/upgrade/blob/master/migrations/base/7.saas~5.1.3/pre-30-cleanup.py#L6)

remove_view is raising an error as in 7.0 there is lack of
active field in 'ir.ui.view' object.

Ref: https://github.com/odoo/odoo/blob/7.0/openerp/addons/base/ir/ir_ui_view.py#L63-L84

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/8.0/openerp/service/server.py", line 941, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/home/odoo/src/odoo/8.0/openerp/modules/registry.py", line 370, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/src/odoo/8.0/openerp/modules/loading.py", line 297, in load_modules
    loaded_modules, processed_modules = load_module_graph(cr, graph, status, perform_checks=update_module, report=report)
  File "/home/odoo/src/odoo/8.0/openerp/modules/loading.py", line 142, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/home/odoo/src/odoo/8.0/openerp/modules/migration.py", line 171, in migrate_module
    migrate(self.cr, pkg.installed_version)
  File "/home/odoo/src/odoo/8.0/openerp/addons/base/maintenance/migrations/base/7.saas~5.1.3/pre-30-cleanup.py", line 6, in migrate
    util.remove_view(cr, 'base.user_groups_view')
  File "/home/odoo/src/odoo/8.0/openerp/addons/base/maintenance/migrations/util/records.py", line 133, in remove_view
    cr.execute(disable_view_query, (key or xml_id, child_id))
  File "/home/odoo/src/odoo/8.0/openerp/sql_db.py", line 171, in wrapper
    return f(self, *args, **kwargs)
  File "/home/odoo/src/odoo/8.0/openerp/sql_db.py", line 247, in execute
    res = self._obj.execute(query, params)
ProgrammingError: column "active" of relation "ir_ui_view" does not exist
LINE 5:                     active = false
```

upg-926120

closes odoo/upgrade#4898

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>