[FIX] product/0.0.0: TypeError generator object is not subscriptable
Their is typo in placing for loop due to that issue is rasied so
fixing that changes done in this commit
https://github.com/odoo/upgrade/commit/e786bde08656340e4887d77a0ef37c6a3e91513d
```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/14.0/odoo/service/server.py", line 1201, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/odoo/src/odoo/14.0/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/src/odoo/14.0/odoo/modules/loading.py", line 457, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/home/odoo/src/odoo/14.0/odoo/modules/loading.py", line 349, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/odoo/src/odoo/14.0/odoo/modules/loading.py", line 174, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/home/odoo/src/odoo/14.0/odoo/modules/migration.py", line 186, in migrate_module
    migrate(self.cr, installed_version)
  File "/tmp/tmp3nrebzc8/migrations/product/0.0.0/pre-sanitize-pricelists.py", line 173, in migrate
    for row in deleted
TypeError: 'generator' object is not subscriptable
```
upg-2049158

closes odoo/upgrade#6553

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>