[FIX] account@saas~13.4: only cancel just created payment moves
This piece of code is all about
creating `account.move` records for draft/cancel payments.

The point here is to mark as cancelled payment
that were cancelled before upgrade.

Before this revision,
it was attempting to cancel all payments marked as cancelled before
upgrade, not just the ones that just has been created.

In addition to unnecessary processing and possible performance issues,
this could lead to an error being raised if, before upgrade,
a cancelled payment was linked to a posted move
(which is unusual, but should prevent the upgrade)

``
2020-10-17 22:16:25,050 25 INFO db_798 odoo.modules.migration: module account: Running migration [saas~13.4.1.1>] post-10-payment-refactoring
2020-10-17 22:16:30,669 25 WARNING db_798 odoo.modules.loading: Transient module states were reset
2020-10-17 22:16:30,671 25 ERROR db_798 odoo.modules.registry: Failed to load registry
2020-10-17 22:16:30,671 25 CRITICAL db_798 odoo.service.server: Failed to initialize database `db_798`.
Traceback (most recent call last):
  File "/home/odoo/src/odoo/14.0/odoo/service/server.py", line 1198, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/odoo/src/odoo/14.0/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/src/odoo/14.0/odoo/modules/loading.py", line 449, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/home/odoo/src/odoo/14.0/odoo/modules/loading.py", line 346, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/odoo/src/odoo/14.0/odoo/modules/loading.py", line 226, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/home/odoo/src/odoo/14.0/odoo/modules/migration.py", line 180, in migrate_module
    migrate(self.cr, installed_version)
  File "/tmp/tmpf429qien/migrations/account/saas~13.4.1.1/post-10-payment-refactoring.py", line 390, in migrate
    env["account.payment"].browse(res_ids).action_cancel()
  File "/home/odoo/src/odoo/14.0/addons/account/models/account_payment.py", line 740, in action_cancel
    self.move_id.button_cancel()
  File "/home/odoo/src/odoo/14.0/addons/account/models/account_move.py", line 2527, in button_cancel
    self.write({'auto_post': False, 'state': 'cancel'})
  File "/home/odoo/src/odoo/14.0/addons/account/models/account_move.py", line 1825, in write
    self._synchronize_business_models(set(vals.keys()))
  File "/home/odoo/src/odoo/14.0/addons/account/models/account_move.py", line 1532, in _synchronize_business_models
    self_sudo.statement_line_id._synchronize_from_moves(changed_fields)
  File "/home/odoo/src/odoo/14.0/addons/account/models/account_bank_statement.py", line 890, in _synchronize_from_moves
    raise UserError(_(
odoo.exceptions.UserError: You can't manually change the state of journal entry BNK1/2020/0302, as it has been created by bank statement Synchronisation en ligne.`
```

Request 773, 798 (new upgrade platform)

closes odoo/upgrade#1858

Signed-off-by: Denis Ledoux (dle) <dle@odoo.com>