[FIX] account/saas~14.3.1.1: fix regex errors
When a `res_country.name` starts by `+`, `*`, or `?` the regular expression
becomes invalid:

```
ayad_408847=> INSERT INTO res_country (name) VALUES ('?aaabbb');
INSERT 0 1
ayad_408847=> SELECT res_country.id, res_country.name
                FROM res_country,res_company
               WHERE res_company.name ~* ANY(ARRAY[res_country.name])
                 AND res_company.id=28
            ORDER BY LENGTH(res_country.name) DESC;
ERROR:  invalid regular expression: quantifier operand invalid
```

When it contains `(` or `[`, the regular expression becomes also invalid (for
another reason):

```
ayad_408847=> INSERT INTO res_country (name) VALUES ('a[aabbb');
INSERT 0 1
ayad_408847=> SELECT res_country.id, res_country.name
                FROM res_country,res_company
               WHERE res_company.name ~* ANY(ARRAY[res_country.name])
                 AND res_company.id=28
            ORDER BY LENGTH(res_country.name) DESC;
ERROR:  invalid regular expression: brackets [] not balanced
```

When it starts with `|`, it will _always_ be returned even if there is no
matching country:
```
ayad_408847=> INSERT INTO res_country (name) VALUES ('|aaaaaa');
INSERT 0 1
ayad_408847=> INSERT INTO res_country (name) VALUES ('|zzzzzz');
INSERT 0 1
ayad_408847=> SELECT res_country.id, res_country.name
                FROM res_country,res_company
               WHERE res_company.name ~* ANY(ARRAY[res_country.name])
                 AND res_company.id=28
            ORDER BY LENGTH(res_country.name) DESC;
 id  |  name
-----+---------
 294 | |aaaaaa
 295 | |zzzzzz
(2 rows)
```

Since we want to check if a company name contains a country name. We can use
`POSITION()` function and `LOWER()` function (since `~*` is case-insensitive).

upg-408847

closes odoo/upgrade#4022

Signed-off-by: Christophe Simonis <chs@odoo.com>