[FIX] stock/saas~17.3: skip location check
To reproduce this error:

1) make database in 17.0
2) Archive manufacturing operation type.
3) change the type of destination location to scrap location.
   Clients can unarchive it as well.
4) upgrade to 17.4 or 18.0.

During the upgrade here: c188f65, when we call this method:
`warehouse._create_or_update_sequences_and_picking_types`, it
tries to update all the picking_types including their values. Since
manufacturing operation types with destination location was ok
pre-upgrade, we can skip the check for upgrade.

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/18.0/odoo/service/server.py", line 1318, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "<decorator-gen-13>", line 2, in new
  File "/home/odoo/src/odoo/18.0/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/18.0/odoo/modules/registry.py", line 127, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/18.0/odoo/modules/loading.py", line 514, in load_modules
    migrations.migrate_module(package, 'end')
  File "/home/odoo/src/odoo/18.0/odoo/modules/migration.py", line 254, in migrate_module
    mod.migrate(self.cr, installed_version)
  File "/tmp/tmp_loj8ynx/migrations/stock/saas~17.3.1.1/end-migrate.py", line 16, in migrate
    new_types_vals = warehouse._create_or_update_sequences_and_picking_types()
  File "/home/odoo/src/odoo/18.0/addons/stock/models/stock_warehouse.py", line 379, in _create_or_update_sequences_and_picking_types
    self[picking_type].write(values)
  File "/home/odoo/src/odoo/18.0/addons/stock/models/stock_picking.py", line 217, in write
    return super(PickingType, self).write(vals)
  File "/home/odoo/src/odoo/18.0/odoo/models.py", line 4771, in write
    real_recs._validate_fields(vals, inverse_fields)
  File "/home/odoo/src/odoo/18.0/odoo/models.py", line 1599, in _validate_fields
    check(self)
  File "/home/odoo/src/odoo/18.0/addons/stock/models/stock_picking.py", line 411, in _check_default_location
    raise ValidationError(_("You cannot set a scrap location as the destination location for a manufacturing type operation."))
odoo.exceptions.ValidationError: You cannot set a scrap location as the destination location for a manufacturing type operation.
```

closes odoo/upgrade#7385

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>