[FIX] industry_fsm/saas~17.5.1.0 : update worksheet custom reports
Steps to reproduce the issue:
1. Create a fresh database in any version below 18.0.
2. Install the `industry_fsm_report` module.
3. Open any task in the Project module.
4. Use Studio to duplicate the "Field Service Report".
5. Migrate the database into 18 and open any task which have
   work sheet is created and try print the custom report
The following traceback was encountered:

```
Traceback (most recent call last):
  File "<4168>", line 583, in template_4168
  File "<4168>", line 467, in template_4168_content
KeyError: 'worksheet_map'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/18.0/addons/web/controllers/report.py", line 120, in report_download
    response = self.report_routes(reportname, docids=docids, converter=converter, context=context)
  File "/home/odoo/src/odoo/18.0/odoo/http.py", line 727, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/home/odoo/src/odoo/18.0/addons/web/controllers/report.py", line 42, in report_routes
    pdf = report.with_context(context)._render_qweb_pdf(reportname, docids, data=data)[0]
  File "/home/odoo/src/enterprise/18.0/industry_fsm/models/ir_actions_report.py", line 15, in _render_qweb_pdf
    return super()._render_qweb_pdf(report_ref, res_ids=res_ids, data=data)
  File "/home/odoo/src/odoo/18.0/odoo/addons/base/models/ir_actions_report.py", line 1007, in _render_qweb_pdf
    collected_streams, report_type = self._pre_render_qweb_pdf(report_ref, res_ids=res_ids, data=data)
  File "/home/odoo/src/odoo/18.0/addons/account/models/ir_actions_report.py", line 74, in _pre_render_qweb_pdf
    return super()._pre_render_qweb_pdf(report_ref, res_ids=res_ids, data=data)
  File "/home/odoo/src/odoo/18.0/odoo/addons/base/models/ir_actions_report.py", line 998, in _pre_render_qweb_pdf
    return self._render_qweb_pdf_prepare_streams(report_ref, data, res_ids=res_ids), 'pdf'
  File "/home/odoo/src/odoo/18.0/addons/sale_pdf_quote_builder/models/ir_actions_report.py", line 17, in _render_qweb_pdf_prepare_streams
    result = super()._render_qweb_pdf_prepare_streams(report_ref, data, res_ids=res_ids)
  File "/home/odoo/src/enterprise/18.0/account_followup/models/ir_actions_report.py", line 12, in _render_qweb_pdf_prepare_streams
    res = super()._render_qweb_pdf_prepare_streams(report_ref, data, res_ids)
  File "/home/odoo/src/odoo/18.0/addons/purchase/models/ir_actions_report.py", line 12, in _render_qweb_pdf_prepare_streams
    collected_streams = super()._render_qweb_pdf_prepare_streams(report_ref, data, res_ids=res_ids)
  File "/home/odoo/src/odoo/18.0/addons/hr_expense/models/ir_actions_report.py", line 12, in _render_qweb_pdf_prepare_streams
    res = super()._render_qweb_pdf_prepare_streams(report_ref, data, res_ids)
  File "/home/odoo/src/odoo/18.0/addons/account/models/ir_actions_report.py", line 22, in _render_qweb_pdf_prepare_streams
    return super()._render_qweb_pdf_prepare_streams(report_ref, data, res_ids=res_ids)
  File "/home/odoo/src/odoo/18.0/odoo/addons/base/models/ir_actions_report.py", line 848, in _render_qweb_pdf_prepare_streams
    html = self.with_context(**additional_context)._render_qweb_html(report_ref, all_res_ids_wo_stream, data=data)[0]
  File "/home/odoo/src/enterprise/18.0/web_studio/models/ir_actions_report.py", line 24, in _render_qweb_html
    return super(IrActionsReport, self)._render_qweb_html(report_ref, docids, data)
  File "/home/odoo/src/odoo/18.0/odoo/addons/base/models/ir_actions_report.py", line 1086, in _render_qweb_html
    return self._render_template(report.report_name, data), 'html'
  File "/home/odoo/src/odoo/18.0/odoo/addons/base/models/ir_actions_report.py", line 765, in _render_template
    return view_obj._render_template(template, values).encode()
  File "/home/odoo/src/enterprise/18.0/web_studio/models/ir_ui_view.py", line 1319, in _render_template
    return super(View, self)._render_template(template, values)
  File "/home/odoo/src/odoo/18.0/addons/website/models/ir_ui_view.py", line 449, in _render_template
    return super()._render_template(template, values=values)
  File "/home/odoo/src/odoo/18.0/odoo/addons/base/models/ir_ui_view.py", line 2191, in _render_template
    return self.env['ir.qweb']._render(template, values)
  File "/home/odoo/src/odoo/18.0/odoo/tools/profiler.py", line 306, in _tracked_method_render
    return method_render(self, template, values, **options)
  File "/home/odoo/src/odoo/18.0/odoo/addons/base/models/ir_qweb.py", line 601, in _render
    result = ''.join(rendering)
  File "<4167>", line 95, in template_4167
  File "<4167>", line 77, in template_4167_content
  File "<4167>", line 59, in template_4167_t_call_0
  File "<4167>", line 23, in template_4167_t_call_1
  File "<4168>", line 591, in template_4168
odoo.addons.base.models.ir_qweb.QWebException: Error while render the template
KeyError: 'worksheet_map'
Template: industry_fsm_report.worksheet_custom_page_copy_2
Path: /t/div/t[2]/div/t[1]
Node: <t t-set="worksheet" t-value="worksheet_map.get(doc.id)"/>

The above server error caused the following client error:
RPC_ERROR: Odoo Server Error
    RPC_ERROR
        at makeErrorFromResponse (https://41.test.upgrade.odoo.com/web/assets/2beb38b/web.assets_web.min.js:3099:163)
        at decoder.onload (https://41.test.upgrade.odoo.com/web/assets/2beb38b/web.assets_web.min.js:3085:7)
```

- This issue arises because the custom report was not updated according
  to the standard.  `worksheet_map` was present in "industry_fsm" , But in
  custom report  key as  "industry_fsm_report.worksheet_%%"
- The key 'industry_fsm_report.worksheet_%%' needs to be
  updated to 'industry_fsm.worksheet__%%' to match the standard. We also
  need to update the arch_db and report_name to resolve the issue.

OPW - 4408234
UPG - 2395173

closes odoo/upgrade#6939

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>