[FIX] documents/saas~17.5: handle negative activity_date_deadline_range
The field `activity_date_deadline_range` is non-negative
in model _**ir.act.server**_[^1] while not in _**documents.workflow.rule**_.
So during the upgrade when it migrates workflow rules and creates
related action servers, it will set negative value on
`activity_date_deadline_range`[^2] if there is workflow rule
with negative value on that column. So it will fail on that
constraint when it recomoutes that field later.

For fixing the issue I have set to 0 if it is negative.

Steps to reproduce:
1. Install `documents` in version `17.0`
2. Go to `Documents -> Configuration -> Actions`
3. Create entry by setting `Due Date In` negative value
   and set acitivity to `Activity type`
4. Upgrade to `18.0`

You will get traceback like this:

```
2025-04-09 11:40:55,357 3723674 CRITICAL test_db_09042025 odoo.service.server: Failed to initialize database `test_db_09042025`.
Traceback (most recent call last):
  File "/home/odoo/src/odoo/18.0/odoo/service/server.py", line 1328, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "<decorator-gen-13>", line 2, in new
  File "/home/odoo/src/odoo/18.0/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/18.0/odoo/modules/registry.py", line 127, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/18.0/odoo/modules/loading.py", line 518, in load_modules
    migrations.migrate_module(package, 'end')
  File "/home/odoo/src/odoo/18.0/odoo/modules/migration.py", line 222, in migrate_module
    exec_script(self.cr, installed_version, pyfile, pkg.name, stage, stageformat[stage] % version)
  File "/home/odoo/src/odoo/18.0/odoo/modules/migration.py", line 259, in exec_script
    mod.migrate(cr, installed_version)
  File "/home/odoo/src/upgrade/migrations/documents/saas~17.5.1.4/end-migrate.py", line 122, in migrate
    util.recompute_fields(
  File "/home/odoo/src/upgrade-util/src/util/orm.py", line 248, in wrapper
    return f(*args, **kwargs)
  File "/home/odoo/src/upgrade-util/src/util/orm.py", line 304, in recompute_fields
    recompute(records)
  File "/home/odoo/src/upgrade-util/src/util/orm.py", line 218, in recompute
    (
  File "/home/odoo/src/odoo/18.0/odoo/api.py", line 843, in _recompute_all
    self[field.model_name]._recompute_field(field)
  File "/home/odoo/src/odoo/18.0/odoo/models.py", line 7343, in _recompute_field
    field.recompute(records)
  File "/home/odoo/src/odoo/18.0/odoo/fields.py", line 1463, in recompute
    apply_except_missing(self.compute_value, recs)
  File "/home/odoo/src/odoo/18.0/odoo/fields.py", line 1436, in apply_except_missing
    func(records)
  File "/home/odoo/src/odoo/18.0/odoo/fields.py", line 1485, in compute_value
    records._compute_field_value(self)
  File "/home/odoo/src/odoo/18.0/odoo/models.py", line 5288, in _compute_field_value
    self.filtered('id')._validate_fields(fnames)
  File "/home/odoo/src/odoo/18.0/odoo/models.py", line 1631, in _validate_fields
    check(self)
  File "/home/odoo/src/odoo/18.0/addons/mail/models/ir_actions_server.py", line 161, in _check_activity_date_deadline_range
    raise ValidationError(_("The 'Due Date In' value can't be negative."))
odoo.exceptions.ValidationError: The 'Due Date In' value can't be negative.

tbg-1961

```

[^1]: https://github.com/odoo/odoo/blob/56905a72f1586b2508910675e9bd00a3f0720439/addons/mail/models/ir_actions_server.py#L159-L161
[^2]: https://github.com/odoo/upgrade/blob/bf0fa8e574702a48a79b39ac6f0bc4d7a4cbb0eb/migrations/documents/saas~17.5.1.4/end-migrate.py#L515

closes odoo/upgrade#7530

Signed-off-by: Jinane Maksoud (maji) <maji@odoo.com>