[FIX] stock/saas~17.4: correct path for server action of inventory
There is a constraint that the path shown in the URL must be unique.
However, in the server action for Inventory, there is a path named
"inventory" that conflicts with the window action for the Inventory Overview.
Here is the latest server action path that has been changed before 6 months
on standard code
[here](https://github.com/odoo/odoo/pull/159711/files#diff-01bfabf3ea8ec659ba45d8677ebdb199d5a3e93b5d505d1363b2fa3bf2da9e94R7)
The action's path didn't get updated because of this
[here](https://github.com/odoo/upgrade/blob/c46d0f45afcebc104c30833b621cc6a834f85724/migrations/base/0.0.0/pre-models-ir_actions.py#L19)

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/saas-17.4/odoo/service/server.py", line 1302, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "<decorator-gen-16>", line 2, in new
  File "/home/odoo/src/odoo/saas-17.4/odoo/tools/func.py", line 84, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/saas-17.4/odoo/modules/registry.py", line 123, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/saas-17.4/odoo/modules/loading.py", line 476, in load_modules
    processed_modules += load_marked_modules(env, graph,
  File "/home/odoo/src/odoo/saas-17.4/odoo/modules/loading.py", line 364, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/odoo/src/odoo/saas-17.4/odoo/modules/loading.py", line 227, in load_module_graph
    load_data(env, idref, mode, kind='data', package=package)
  File "/home/odoo/src/odoo/saas-17.4/odoo/modules/loading.py", line 71, in load_data
    tools.convert_file(env, package.name, filename, idref, mode, noupdate, kind)
  File "/home/odoo/src/odoo/saas-17.4/odoo/tools/convert.py", line 630, in convert_file
    convert_xml_import(env, module, fp, idref, mode, noupdate)
  File "/home/odoo/src/odoo/saas-17.4/odoo/tools/convert.py", line 701, in convert_xml_import
    obj.parse(doc.getroot())
  File "/home/odoo/src/odoo/saas-17.4/odoo/tools/convert.py", line 616, in parse
    self._tag_root(de)
  File "/home/odoo/src/odoo/saas-17.4/odoo/tools/convert.py", line 570, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
odoo.tools.convert.ParseError: while parsing /home/odoo/src/odoo/saas-17.4/addons/stock/views/stock_picking_type_views.xml:16
Path to show in the URL must be unique! Please choose another one.

View error context:
'-no context-'

bda@(none):bda_1880120> select * from ir_actions where path = 'inventory';
-[ RECORD 1 ]-------------------------
id                 | 587
binding_model_id   | <null>
create_uid         | 1
write_uid          | 1
type               | ir.actions.server
path               | inventory
binding_type       | action
binding_view_types | list,form
name               | {"en_US": "Inventory"}
help               | <null>
create_date        | 2024-04-05 12:23:02.480938
write_date         | 2024-04-05 12:23:02.480938
-[ RECORD 2 ]-------------------------
id                 | 616
binding_model_id   | <null>
create_uid         | 1
write_uid          | 1
type               | ir.actions.act_window
path               | inventory
binding_type       | action
binding_view_types | list,form
name               | {"en_US": "Inventory Overview"}
help               | {"en_US": "<p class=\"o_view_nocontent_smiling_face\">\n            Create a new operation type\n            </p><p>\n            The operation type system allows you to assign each>
create_date        | 2024-04-05 12:23:02.480938
write_date         | 2024-04-05 12:23:02.480938
SELECT 2
Time: 0.002s
bda@(none):bda_1880120>  select * from ir_act_window where id=587;

bda@(none):bda_1880120> select id,name,noupdate,module,model,res_id,create_date from ir_model_data where res_id in (587,616) and model='ir.actions.server';
+-------+----------------------------+----------+--------+-------------------+--------+----------------------------+
| id    | name                       | noupdate | module | model             | res_id | create_date                |
|-------+----------------------------+----------+--------+-------------------+--------+----------------------------|
| 38547 | action_view_inventory_tree | False    | stock  | ir.actions.server | 587    | 2024-04-05 12:23:02.480938 |
+-------+----------------------------+----------+--------+-------------------+--------+----------------------------+
SELECT 1
Time: 0.008s

opw-4111869
upg-1880120
tbg-1414
```

closes odoo/upgrade#6392

Signed-off-by: Christophe Simonis (chs) <chs@odoo.com>