[FIX] website/saas~16.5: update cowed views of website.header_call_to_action
View `website.header_call_to_action` is often customized
by clients by creating cowed views of it. Since 17.0 there's a new
class added to one of its elements. This element is sometimes used
as an anchor to apply xpath, such as for example here:
https://github.com/odoo/odoo/blob/f1654683b68276955b55372aeee6139cbb75de1f/addons/website/views/website_templates.xml#L2196

Element in 16.4:
https://github.com/odoo/odoo/blob/75720063356b4c6d8b68c98ad432fe99d5096bd7/addons/website/views/website_templates.xml#L2090

Element in 17.0:
https://github.com/odoo/odoo/blob/ad35458e8bfc30602f927944031a0bf87a92f82d/addons/website/views/website_templates.xml#L2187

Cowed views would otherwise fail if the new class is not present.

```
Error while render the template
ValueError: Element '<xpath expr="//a[hasclass(&#39;oe_unremovable&#39;)]">' cannot be located in parent view
Template: website.template_header_mobile
Path: /t/t/div/div/div[2]/ul[2]/t[4]
Node: <t t-call="website.header_call_to_action_large"/>

The error occurred while rendering the template website.template_header_mobile and evaluating the following expression: <t t-call="website.header_call_to_action_large"/>
```

upg-1190134
opw-3644220

Part-of: odoo/upgrade#5466