[FIX] {base,l10n_fr_hr_holidays}/saas~16.3.1.{3,5}: Assign default value
Starting from saas~16.3, module `l10n_hr_fr_holidays` add new field
`l10n_fr_reference_leave_type` in `res.company` model. The module is
automatically installed in dbs with french accounting module
(`l10n_fr`) and Time Off (`hr_holidays`) installed. This new field
represent the type of Paid Time Off used for part-time worker used in
leave computation.

When mocking all view at the end of upgrade, the number of leave days
is computed. The new added field is then used to get this number of
days. As no default value is set in Odoo, the error is raised.

For all (french) companies, we need to add a default value during the
upgrade.

(The choice of using `hr_holidays.holiday_status_cl` has been discussed
with vidange team: this xmlid reference the Odoo `hr.leave.type`
'Paid Time Off')

See Odoo: odoo/odoo#82637

tbg-798

```
Traceback (most recent call last):
  File "/tmp/tmp0m1xh0mn/migrations/testing.py", line 211, in test_check
    self.check(value)
  File "/tmp/tmp0m1xh0mn/migrations/base/tests/test_mock_crawl.py", line 132, in check
    self.assertFalse(diff, msg)
AssertionError: [('hr_holidays.menu_hr_available_holidays_report_tree', 827, 'Time Off > Reporting > by Employee', 1194)] is not false : At least one menu or view working before upgrade is not working after upgrade.

('hr_holidays.menu_hr_available_holidays_report_tree', 827, 'Time Off > Reporting > by Employee', 1194):
 Traceback (most recent call last):
   File "/home/odoo/src/odoo/saas-16.3/odoo/api.py", line 959, in get
    cache_value = field_cache[record._ids[0]]
 KeyError: 2

During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "/home/odoo/src/odoo/saas-16.3/odoo/fields.py", line 1158, in __get__
    value = env.cache.get(record, self)
   File "/home/odoo/src/odoo/saas-16.3/odoo/api.py", line 966, in get
    raise CacheMiss(record, field)
 odoo.exceptions.CacheMiss: 'hr.leave(2,).number_of_hours_text'

During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "/home/odoo/src/odoo/saas-16.3/odoo/api.py", line 959, in get
    cache_value = field_cache[record._ids[0]]
 KeyError: 2

During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "/home/odoo/src/odoo/saas-16.3/odoo/fields.py", line 1158, in __get__
    value = env.cache.get(record, self)
   File "/home/odoo/src/odoo/saas-16.3/odoo/api.py", line 966, in get
    raise CacheMiss(record, field)
 odoo.exceptions.CacheMiss: 'hr.leave(2,).number_of_hours_display'

During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "/tmp/tmp0m1xh0mn/migrations/base/tests/test_mock_crawl.py", line 231, in crawl_menu
    self.mock_action(action_vals)
   File "/tmp/tmp0m1xh0mn/migrations/base/tests/test_mock_crawl.py", line 385, in mock_action
    mock_method(model, view, fields_list, domain, group_by)
   File "/tmp/tmp0m1xh0mn/migrations/base/tests/test_mock_crawl.py", line 413, in mock_view_form
    [data] = record.read(fields_list)
   File "/home/odoo/src/odoo/saas-16.3/odoo/models.py", line 3177, in read
    return self._read_format(fnames=fields, load=load)
   File "/home/odoo/src/odoo/saas-16.3/odoo/models.py", line 3369, in _read_format
    vals[name] = convert(record[name], record, use_name_get)
   File "/home/odoo/src/odoo/saas-16.3/odoo/models.py", line 6131, in __getitem__
    return self._fields[key].__get__(self, type(self))
   File "/home/odoo/src/odoo/saas-16.3/odoo/fields.py", line 1209, in __get__
    self.compute_value(recs)
   File "/home/odoo/src/odoo/saas-16.3/odoo/fields.py", line 1387, in compute_value
    records._compute_field_value(self)
   File "/home/odoo/src/odoo/saas-16.3/addons/mail/models/mail_thread.py", line 396, in _compute_field_value
    return super()._compute_field_value(field)
   File "/home/odoo/src/odoo/saas-16.3/odoo/models.py", line 4491, in _compute_field_value
    fields.determine(field.compute, self)
   File "/home/odoo/src/odoo/saas-16.3/odoo/fields.py", line 99, in determine
    return needle(*args)
   File "/home/odoo/src/odoo/saas-16.3/addons/hr_holidays/models/hr_leave.py", line 587, in _compute_number_of_hours_text
    float_round(leave.number_of_hours_display, precision_digits=2),
   File "/home/odoo/src/odoo/saas-16.3/odoo/fields.py", line 1209, in __get__
    self.compute_value(recs)
   File "/home/odoo/src/odoo/saas-16.3/odoo/fields.py", line 1387, in compute_value
    records._compute_field_value(self)
   File "/home/odoo/src/odoo/saas-16.3/addons/mail/models/mail_thread.py", line 396, in _compute_field_value
    return super()._compute_field_value(field)
   File "/home/odoo/src/odoo/saas-16.3/odoo/models.py", line 4491, in _compute_field_value
    fields.determine(field.compute, self)
   File "/home/odoo/src/odoo/saas-16.3/odoo/fields.py", line 99, in determine
    return needle(*args)
   File "/home/odoo/src/odoo/saas-16.3/addons/hr_holidays/models/hr_leave.py", line 567, in _compute_number_of_hours_display
    number_of_hours = holiday._get_number_of_days(holiday.date_from, holiday.date_to, holiday.employee_id)['hours']
   File "/home/odoo/src/odoo/saas-16.3/addons/l10n_fr_hr_holidays/models/hr_leave.py", line 131, in _get_number_of_days
    if self.holiday_status_id != employee.company_id._get_fr_reference_leave_type():
   File "/home/odoo/src/odoo/saas-16.3/addons/l10n_fr_hr_holidays/models/res_company.py", line 18, in _get_fr_reference_leave_type
    raise ValidationError(_("You must first define a reference time off type for the company."))
 odoo.exceptions.ValidationError: You must first define a reference time off type for the company.
```

closes odoo/upgrade#5087

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>