[FIX] mail/0.0.0: Ensure `channel_partner_general_channel_for_admin`
It's the same fix as https://github.com/odoo/upgrade/pull/3253 but moved to
0.0.0 since the issue it's also happening in saas~15.2 and it will
continue to be recurrent.

```
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "mail_channel_partner_partner_unique"
DETAIL:  Key (channel_id, partner_id)=(1, 2) already exists.

raise ParseError('while parsing %s:%s, somewhere inside\n%s' % (
odoo.tools.convert.ParseError: while parsing /home/odoo/src/odoo/saas-15.2/addons/mail/data/mail_channel_data.xml:21, somewhere inside
<record model="mail.channel.partner" id="channel_partner_general_channel_for_admin">
            <field name="partner_id" ref="base.partner_admin"/>
            <field name="channel_id" ref="mail.channel_all_employees"/>
            <field name="fetched_message_id" ref="mail.module_install_notification"/>
            <field name="seen_message_id" ref="mail.module_install_notification"/>
        </record>
```

closes odoo/upgrade#3472

Signed-off-by: Christophe Simonis <chs@odoo.com>