[FIX] base/saas~16.5: arch variable reference before assignment
minor typo, variable name is new_arch used by mistake
arch. so need to use new_arch

upg-1175570

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/17.0/odoo/service/server.py", line 1302, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "<decorator-gen-16>", line 2, in new
  File "/home/odoo/src/odoo/17.0/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/17.0/odoo/modules/registry.py", line 113, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/17.0/odoo/modules/loading.py", line 514, in load_modules
    migrations.migrate_module(package, 'end')
  File "/home/odoo/src/odoo/17.0/odoo/modules/migration.py", line 240, in migrate_module
    migrate(self.cr, installed_version)
  File "/tmp/tmppk_9kt0y/migrations/base/saas~16.5.1.3/end-01-attrs-views.py", line 567, in migrate
    check_arch(vid, arch, lang, error=True)
UnboundLocalError: local variable 'arch' referenced before assignment
```

closes odoo/upgrade#5390

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>