[FIX] l10n_br_avatax/saas~17.4: create column of stored compute field
tbg-1435

The `_compute_l10n_br_goods_operation_type_id` is being triggered before the
records it needs ([introduced in standard alongside the
field](https://github.com/odoo/enterprise/pull/65942)) are even loaded.

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/saas-17.4/odoo/tools/cache.py", line 103, in lookup
    r = d[key]
  File "<decorator-gen-5>", line 2, in __getitem__
  File "/home/odoo/src/odoo/saas-17.4/odoo/tools/func.py", line 84, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/saas-17.4/odoo/tools/lru.py", line 34, in __getitem__
    a = self.d[obj]
KeyError: ('ir.model.data', <function IrModelData._xmlid_lookup at 0x7f38556f1c60>, 'l10n_br_avatax.operation_type_1')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/saas-17.4/odoo/service/server.py", line 1302, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "<decorator-gen-16>", line 2, in new
  File "/home/odoo/src/odoo/saas-17.4/odoo/tools/func.py", line 84, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/saas-17.4/odoo/modules/registry.py", line 124, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/saas-17.4/odoo/modules/loading.py", line 476, in load_modules
    processed_modules += load_marked_modules(env, graph,
  File "/home/odoo/src/odoo/saas-17.4/odoo/modules/loading.py", line 364, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/odoo/src/odoo/saas-17.4/odoo/modules/loading.py", line 205, in load_module_graph
    registry.init_models(env.cr, model_names, {'module': package.name}, new_install)
  File "/home/odoo/src/odoo/saas-17.4/odoo/modules/registry.py", line 603, in init_models
    func()
  File "/home/odoo/src/odoo/saas-17.4/odoo/addons/base/models/ir_model.py", line 1953, in _reflect_relation
    self.env.invalidate_all()
  File "/home/odoo/src/odoo/saas-17.4/odoo/api.py", line 727, in invalidate_all
    self.flush_all()
  File "/home/odoo/src/odoo/saas-17.4/odoo/api.py", line 737, in flush_all
    self._recompute_all()
  File "/home/odoo/src/odoo/saas-17.4/odoo/api.py", line 733, in _recompute_all
    self[field.model_name]._recompute_field(field)
  File "/home/odoo/src/odoo/saas-17.4/odoo/models.py", line 7021, in _recompute_field
    field.recompute(records)
  File "/home/odoo/src/odoo/saas-17.4/odoo/fields.py", line 1423, in recompute
    apply_except_missing(self.compute_value, recs)
  File "/home/odoo/src/odoo/saas-17.4/odoo/fields.py", line 1396, in apply_except_missing
    func(records)
  File "/home/odoo/src/odoo/saas-17.4/odoo/fields.py", line 1445, in compute_value
    records._compute_field_value(self)
  File "/home/odoo/src/odoo/saas-17.4/addons/mail/models/mail_thread.py", line 428, in _compute_field_value
    return super()._compute_field_value(field)
  File "/home/odoo/src/odoo/saas-17.4/odoo/models.py", line 5051, in _compute_field_value
    fields.determine(field.compute, self)
  File "/home/odoo/src/odoo/saas-17.4/odoo/fields.py", line 101, in determine
    return needle(*args)
  File "/home/odoo/src/enterprise/saas-17.4/l10n_br_avatax/models/account_move.py", line 11, in _compute_l10n_br_goods_operation_type_id
    super()._compute_l10n_br_goods_operation_type_id()
  File "/home/odoo/src/enterprise/saas-17.4/l10n_br_avatax/models/account_external_tax_mixin.py", line 67, in _compute_l10n_br_goods_operation_type_id
    record.l10n_br_goods_operation_type_id = self.env.ref("l10n_br_avatax.operation_type_1") if record.l10n_br_is_avatax else False
  File "/home/odoo/src/odoo/saas-17.4/odoo/api.py", line 584, in ref
    res_model, res_id = self['ir.model.data']._xmlid_to_res_model_res_id(
  File "/home/odoo/src/odoo/saas-17.4/odoo/addons/base/models/ir_model.py", line 2229, in _xmlid_to_res_model_res_id
    return self._xmlid_lookup(xmlid)
  File "<decorator-gen-44>", line 2, in _xmlid_lookup
  File "/home/odoo/src/odoo/saas-17.4/odoo/tools/cache.py", line 110, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/odoo/src/odoo/saas-17.4/odoo/addons/base/models/ir_model.py", line 2222, in _xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: l10n_br_avatax.operation_type_1
```

closes odoo/upgrade#6439

Signed-off-by: Christophe Simonis (chs) <chs@odoo.com>