[FIX] mass_mailing/15.0.2.5: Ensure compatibility for editing templates
Description:
Resolves an issue where email templates created in version 14 or older
could not be edited after upgrading to version 15 in the mass mailing
module.

Steps to reproduce:
 - Create a mail template in version 14.
 - Upgrade the database to version 15.
 - Attempt to edit the previously created template.

Fix:
Adds the `o_editable` class to the template element, restoring editing
functionality.

Traceback:
```
TypeError: Cannot read properties of undefined (reading 'droppable')
    at jQuery.fn.init.stop (https://72.test.upgrade.odoo.com/web/assets/264-d578d37/web_editor.assets_wysiwyg.min.js:1571:12)
    at Class._onSmoothDragStop (https://72.test.upgrade.odoo.com/web/assets/258-1001e36/web.assets_common.min.js:5155:1050)
    at HTMLDivElement.stop (https://72.test.upgrade.odoo.com/web/assets/258-1001e36/web.assets_common.min.js:5135:6)
    at $.<computed>.<computed>._trigger (https://72.test.upgrade.odoo.com/web/assets/258-1001e36/web.assets_common.min.js:2168:75)
    at $.<computed>.<computed>._trigger (https://72.test.upgrade.odoo.com/web/assets/258-1001e36/web.assets_common.min.js:2307:36)
    at $.<computed>.<computed>._trigger (https://72.test.upgrade.odoo.com/web/assets/258-1001e36/web.assets_common.min.js:2138:159)
    at $.<computed>.<computed>._mouseStop (https://72.test.upgrade.odoo.com/web/assets/258-1001e36/web.assets_common.min.js:2240:373)
    at $.<computed>.<computed>._mouseStop (https://72.test.upgrade.odoo.com/web/assets/258-1001e36/web.assets_common.min.js:2138:159)
    at $.<computed>.<computed>._mouseUp (https://72.test.upgrade.odoo.com/web/assets/258-1001e36/web.assets_common.min.js:2217:6)
    at $.<computed>.<computed>._mouseUp (https://72.test.upgrade.odoo.com/web/assets/258-1001e36/web.assets_common.min.js:2138:159)
```

References:
 - UPG-1218886
 - OPW-3682222
 - Community PR - https://github.com/odoo/odoo/pull/107288
 - Specific PR - https://github.com/odoo/upgrade-specific/pull/5449
 - Specific PR - https://github.com/odoo/upgrade-specific/pull/5515

closes odoo/upgrade#5568

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>