[FIX] util.remove_model: set unknown for relation fields
When a model is removed, we need to update the fields that point to it
via it's related column.

```
 Traceback (most recent call last):
   File "/tmp/tmp_ywlrvub/migrations/base/tests/test_mock_crawl.py", line 175, in crawl_menu
    self.mock_action(action_vals)
   File "/tmp/tmp_ywlrvub/migrations/base/tests/test_mock_crawl.py", line 239, in mock_action
    action["views"], options={"action_id": action.get("id"), "toolbar": True, "load_filters": True}
   File "/home/odoo/src/odoo/14.0/odoo/models.py", line 1530, in load_views
    for [v_id, v_type] in views
   File "/home/odoo/src/odoo/14.0/odoo/models.py", line 1530, in <dictcomp>
    for [v_id, v_type] in views
   File "/home/odoo/src/odoo/14.0/addons/web/models/models.py", line 220, in fields_view_get
    r = super().fields_view_get(view_id, view_type, toolbar, submenu)
   File "/home/odoo/src/odoo/14.0/odoo/models.py", line 1618, in fields_view_get
    xarch, xfields = view.postprocess_and_fields(etree.fromstring(result['arch']), model=self._name)
   File "/home/odoo/src/odoo/14.0/odoo/addons/base/models/ir_ui_view.py", line 852, in postprocess_and_fields
    arch, name_manager = self._postprocess_view(node, model, validate=validate)
   File "/home/odoo/src/odoo/14.0/odoo/addons/base/models/ir_ui_view.py", line 861, in _postprocess_view
    self._postprocess_on_change(model, node)
   File "/home/odoo/src/odoo/14.0/odoo/addons/base/models/ir_ui_view.py", line 890, in _postprocess_on_change
    collect(arch, self.env[model_name])
   File "/home/odoo/src/odoo/14.0/odoo/addons/base/models/ir_ui_view.py", line 888, in collect
    collect(child, model)
   File "/home/odoo/src/odoo/14.0/odoo/addons/base/models/ir_ui_view.py", line 888, in collect
    collect(child, model)
   File "/home/odoo/src/odoo/14.0/odoo/addons/base/models/ir_ui_view.py", line 888, in collect
    collect(child, model)
   File "/home/odoo/src/odoo/14.0/odoo/addons/base/models/ir_ui_view.py", line 886, in collect
    model = self.env[field.comodel_name]
   File "/home/odoo/src/odoo/14.0/odoo/api.py", line 473, in __getitem__
    return self.registry[model_name]._browse(self, (), ())
   File "/home/odoo/src/odoo/14.0/odoo/modules/registry.py", line 177, in __getitem__
    return self.models[model_name]
 KeyError: 'hr.contribution.register'
```

Before
```
17153_afu_14.0=> select id,name,model,relation from ir_model_fields where relation='hr.contribution.register'
+-------+-------------+--------------+--------------------------+
| id    | name        | model        | relation                 |
|-------+-------------+--------------+--------------------------|
| 10124 | register_id | hr.loan.line | hr.contribution.register |
| 8305  | register_id | hr.loan      | hr.contribution.register |
+-------+-------------+--------------+--------------------------+
```
after
```
17153_afu_14.0=> select id,name,model,relation from ir_model_fields where id in (10124,8305)
+-------+-------------+--------------+------------+
| id    | name        | model        | relation   |
|-------+-------------+--------------+------------|
| 8305  | register_id | hr.loan      | _unknown   |
| 10124 | register_id | hr.loan.line | _unknown   |
+-------+-------------+--------------+------------+
```
Ref:
https://github.com/odoo/upgrade/blob/0beca5fe7c221ccc00daa0634be07aa543140150/migrations/hr_payroll/saas%7E12.3.1.0/pre-30-fieldsremoval.py#L19

upg-17153
opw-2583085

closes odoo/upgrade#2603

Signed-off-by: Christophe Simonis <chs@odoo.com>