[FIX] fleet/saas~1{2.5, 3.4, 4.5}: Fix multi-company odometer
The multi-company rules were added by https://github.com/odoo/odoo/pull/73608

If the company of `fleet.vehicle.log.services` (or `fleet.vehicle.cost` in v13)
is empty or different than the company of the associated `fleet.vehicle`,
it can make it so that some logs can be seen although the user has no access
to the corresponding vehicles.

It can also make the test mock crawl fail for the same reason if the db doesn't
have the multi-company rules before the upgrade.

upg-155952
upg-154262
upg-106079
upg-165858

ticket-2800443

```
Traceback (most recent call last):
  File "/tmp/tmp3baegn6l/migrations/testing.py", line 204, in test_check
    self.check(value)
  File "/tmp/tmp3baegn6l/migrations/base/tests/test_mock_crawl.py", line 85, in check
    self.assertFalse(diff, msg)
AssertionError: [('fleet.fleet_vehicle_log_services_menu', 487, 'Fleet > Fleet > Services', 643)] is not false : At least one menu or view working before upgrade is not working after upgrade.

('fleet.fleet_vehicle_log_services_menu', 487, 'Fleet > Fleet > Services', 643):
 Traceback (most recent call last):
   File "/home/odoo/src/odoo/15.0/odoo/api.py", line 886, in get
    return field_cache[record._ids[0]]
 KeyError: 1

During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "/home/odoo/src/odoo/15.0/odoo/fields.py", line 1057, in __get__
    value = env.cache.get(record, self)
   File "/home/odoo/src/odoo/15.0/odoo/api.py", line 889, in get
    raise CacheMiss(record, field)
 odoo.exceptions.CacheMiss: 'fleet.vehicle.log.services(1,).odometer'

During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "/home/odoo/src/odoo/15.0/odoo/api.py", line 886, in get
    return field_cache[record._ids[0]]
 KeyError: 10

During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "/home/odoo/src/odoo/15.0/odoo/fields.py", line 1057, in __get__
    value = env.cache.get(record, self)
   File "/home/odoo/src/odoo/15.0/odoo/api.py", line 889, in get
    raise CacheMiss(record, field)
 odoo.exceptions.CacheMiss: 'fleet.vehicle.odometer(10,).value'

During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "/home/odoo/src/odoo/15.0/odoo/fields.py", line 1083, in __get__
    recs._fetch_field(self)
   File "/home/odoo/src/odoo/15.0/odoo/models.py", line 3276, in _fetch_field
    self._read(fnames)
   File "/home/odoo/src/odoo/15.0/odoo/models.py", line 3387, in _read
    raise self.env['ir.rule']._make_access_error('read', forbidden)
 odoo.exceptions.AccessError: Due to security restrictions, you are not allowed to access 'Odometer log for a vehicle' (fleet.vehicle.odometer) records.

Records: FORD/1992/WJ92760 / 2017-11-20 (id=10)
User: Raul Gonzalez (id=2)

This restriction is due to the following rules:
- User can only see his/her vehicle's odometer
- Manager has all rights on vehicle's vehicle's odometer
- Fleet odometer: Multi Company

Note: this might be a multi-company issue.

Contact your administrator to request access if necessary.
```

closes odoo/upgrade#3389

Signed-off-by: Christophe Simonis <chs@odoo.com>