[FIX] util/models: remove m2m tables on remove_model
When removing a model, we should remove the tables associated to its
m2m fields.

Not removing those tables may cause issues like
```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/13.0/odoo/service/server.py", line 1192, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/odoo/src/odoo/13.0/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/src/odoo/13.0/odoo/modules/loading.py", line 424, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/home/odoo/src/odoo/13.0/odoo/modules/loading.py", line 315, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/odoo/src/odoo/13.0/odoo/modules/loading.py", line 177, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/home/odoo/src/odoo/13.0/odoo/modules/migration.py", line 180, in migrate_module
    migrate(self.cr, installed_version)
  File "/tmp/tmpjsu0__re/migrations/l10n_bo/saas~12.5.2.0/pre-migrate.py", line 10, in migrate
    replace_xmlid=False,
  File "/tmp/tmpjsu0__re/migrations/util/records.py", line 756, in replace_record_references_batch
    if target_of(cr, table, col2)[:2] == target_of(cr, table, fk)[:2]:
TypeError: 'NoneType' object is not subscriptable
```
In particular, this error is raised on
https://github.com/odoo/upgrade/blob/8cd0ff0bfdc504111cbddddb79ac5e8244ef4d8b/migrations/l10n_bo/saas%7E12.5.2.0/pre-migrate.py#L6-L11
while updating the references to account.account.type on the m2m table
account_account_financial_report_type which has missing a FK constraint.
That constraint is dropped wen removing the model
accoun.financial.report on
https://github.com/odoo/upgrade/blob/bb4079227651871184d3e289655fce367f16a2e4/migrations/account/saas%7E11.5.1.1/pre-10-models.py#L30
more specifically when removing the model's table
https://github.com/odoo/upgrade/blob/bb4079227651871184d3e289655fce367f16a2e4/migrations/util/models.py#L135

Orignal DB
```
21609_afu=> \d account_account_financial_report_type
+-----------------+---------+-------------+
| Column          | Type    | Modifiers   |
|-----------------+---------+-------------|
| report_id       | integer |  not null   |
| account_type_id | integer |  not null   |
+-----------------+---------+-------------+
Indexes:
    "account_account_financial_report__report_id_account_type_id_key" UNIQUE CONSTRAINT, btree (report_id, account_type_id)
    "account_account_financial_report_type_account_type_id_idx" btree (account_type_id)
    "account_account_financial_report_type_report_id_idx" btree (report_id)
Foreign-key constraints:
    "account_account_financial_report_type_account_type_id_fkey" FOREIGN KEY (account_type_id) REFERENCES account_account_type(id) ON DELETE CASCADE
    "account_account_financial_report_type_report_id_fkey" FOREIGN KEY (report_id) REFERENCES account_financial_report(id) ON DELETE CASCADE
```
After removing the model account.financial.report the table loses the FK
constraint `account_account_financial_report_type_report_id_fkey`
```
21609_afu_12.0=> \d account_account_financial_report_type
+-----------------+---------+-------------+
| Column          | Type    | Modifiers   |
|-----------------+---------+-------------|
| report_id       | integer |  not null   |
| account_type_id | integer |  not null   |
+-----------------+---------+-------------+
Indexes:
    "account_account_financial_report_type_pkey" PRIMARY KEY, btree (account_type_id, report_id)
    "account_account_financial_report__report_id_account_type_id_idx" btree (report_id, account_type_id)
Foreign-key constraints:
    "account_account_financial_report_type_account_type_id_fkey" FOREIGN KEY (account_type_id) REFERENCES account_account_type(id) ON DELETE CASCADE
```

upg-19975
upg-21523
upg-21609 opw-2618513

closes odoo/upgrade#2717

Signed-off-by: Christophe Simonis <chs@odoo.com>