[FIX] base@0.0.0: custom transients can still have references to them
As explained in the comment of this method,
odoo/odoo@f8e573db2350b025afec8407eeb5849c7a31afa4
ensures no model can reference a transient model.

However, if a custom module adds a reference from a regular model
to a transient model,
and the custom module is not updated with the ORM(`-u`),
(which is the case for custom modules during upgrades)
the reference to the transient model remains,
and `TRUNCATE ... CASCADE` deletes cascadely all records
of the model, as well as other tables referencing it.

For instance, for the request 47475:
```sql
SELECT model,transient FROM ir_model WHERE transient AND model = 'account.move.china.payment';
           model            | transient
----------------------------+-----------
 account.move.china.payment | t
(1 row)

\d account_move_china_payment;
                                           Table "public.account_move_china_payment"
     Column      |            Type             | Collation | Nullable |                        Default
-----------------+-----------------------------+-----------+----------+--------------------------------------------------------
 id              | integer                     |           | not null | nextval('account_move_china_payment_id_seq'::regclass)
 create_uid      | integer                     |           |          |
 create_date     | timestamp without time zone |           |          |
 name            | character varying           |           |          |
 bank_account_id | integer                     |           |          |
 currency_id     | integer                     |           |          |
 company_id      | integer                     |           |          |
 write_uid       | integer                     |           |          |
 write_date      | timestamp without time zone |           |          |
 partner_id      | integer                     |           |          |
Indexes:
    "account_move_china_payment_pkey" PRIMARY KEY, btree (id)
    "account_move_china_payment_name_index" btree (name)
    "account_move_china_payment_partner_id_index" btree (partner_id)
Foreign-key constraints:
    "account_move_china_payment_bank_account_id_fkey" FOREIGN KEY (bank_account_id) REFERENCES res_partner_bank(id) ON DELETE SET NULL
    "account_move_china_payment_company_id_fkey" FOREIGN KEY (company_id) REFERENCES res_company(id) ON DELETE SET NULL
    "account_move_china_payment_create_uid_fkey" FOREIGN KEY (create_uid) REFERENCES res_users(id) ON DELETE SET NULL
    "account_move_china_payment_currency_id_fkey" FOREIGN KEY (currency_id) REFERENCES res_currency(id) ON DELETE SET NULL
    "account_move_china_payment_partner_id_fkey" FOREIGN KEY (partner_id) REFERENCES res_partner(id) ON DELETE SET NULL
    "account_move_china_payment_write_uid_fkey" FOREIGN KEY (write_uid) REFERENCES res_users(id) ON DELETE SET NULL
Referenced by:
    TABLE "account_move" CONSTRAINT "account_move_china_payment_id_fkey" FOREIGN KEY (china_payment_id) REFERENCES account_move_china_payment(id) ON DELETE SET NULL
```

The reference `china_payment_id` on `account_move` has as effect
to delete allmost everything when truncating the transient:
accounting moves, partners, companies, even modules.

And this is the reason why the request upgrade is failing with the error:
```
  File "/src/odoo/12.0/odoo/addons/base/maintenance/migrations/base/saas~11.1.1.3/pre-10-modules.py", line 15, in migrate
    util.new_module_dep(cr, 'l10n_mx', 'account_cancel')
  File "/src/odoo/12.0/odoo/addons/base/maintenance/migrations/util.py", line 1686, in new_module_dep
    _assert_modules_exists(cr, module, new_dep)
  File "/src/odoo/12.0/odoo/addons/base/maintenance/migrations/util.py", line 1681, in _assert_modules_exists
    raise AssertionError("Unexisting modules: {}".format(", ".join(unexisting_modules)))
AssertionError: Unexisting modules: l10n_mx, account_cancel
```

`migrations/base/0.0.0/pre-clean-transients.py` ran before `maintenance/migrations/base/saas~11.1.1.3/pre-10-modules.py`
and emptied the `ir_module_module` table because of this bug.

Request 47475
M120330524-bzfsmrzs

closes odoo/upgrade#1514

Signed-off-by: Christophe Simonis <chs@odoo.com>