[FIX] stock/tests: removed trailing whitespace
As we introduced a `priority` field for products
we use it in orderning and we inherit the
`_generate_order_by_iner` method now that method
has been changed in saas~16.3
see: https://github.com/odoo/odoo/blob/f8452b2eb8f9243402984d78184ed494384a187c/odoo/models.py#L4783

so when before upgrade for order by it was giving this element
`mrp_bom__product_id__product_tmpl_id"."priority" DESC`
but after upgrade it is giving this :

`mrp_bom__product_id__product_tmpl_id"."priority" DESC `
a trailing space which create difference between
original and after upgrade on hand qty.

upg-942575

```
>>> m = 'mrp_bom__product_id__product_tmpl_id.priority DESC'
>>> m.rpartition(" ")
('mrp_bom__product_id__product_tmpl_id.priority', ' ', 'DESC')
>>> z = 'mrp_bom__product_id__product_tmpl_id.priority DESC '
>>> z.rpartition(" ")
('mrp_bom__product_id__product_tmpl_id.priority DESC', ' ', '')
```

```
Traceback (most recent call last):
  File "/tmp/tmpwcc_8dj8/migrations/testing.py", line 211, in test_check
    self.check(value)
  File "/tmp/tmpwcc_8dj8/migrations/stock/tests/test_on_hand_quantity.py", line 41, in check
    self.assertEqual(before_results, self.convert_check(after_results), self.message)
AssertionError: Lists differ: [[8, [1632 chars]51, '20'], [652, '6'], [653, '10'], [654, '2'][2375 chars]'5']] != [[8, [1632 chars]51, '12'], [652, '12'], [653, '12'], [654, '12[2379 chars]'5']]

First differing element 128:
[651, '20']
[651, '12']

Diff is 5228 characters long. Set self.maxDiff to None to see it. : Invariant check fail
```

closes odoo/upgrade#4924

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>