[FIX] base/0.0.0: remove phantom dependencies
Due to a bug in `base_import_module` we could install a data module with
totally known dependencies, i.e dependencies that are not present in
`ir_module_module`. Since imported modules are marked as `to upgrade`
the ORM tries to fetch the missing dependency and fails.

```
  File "/home/odoo/src/odoo/saas-17.4/odoo/addons/base/models/ir_module.py", line 716, in button_upgrade
    raise UserError(_('You try to upgrade the module %(module)s that depends on the module: %(dependency)s.\nBut this module is not available in your system.', module=module.name, dependency=dep.name))
odoo.exceptions.UserError: Vous tentez de mettre à niveau le module tk_imprimeur qui dépend du module : .
Mais ce dernier n'est pas disponible sur votre système.
```

```
afu_2189915=> select id,name,latest_version,state,imported from ir_module_module where name in ('base','tk_imprimeur')
+------+--------------+----------------+-----------+----------+
| id   | name         | latest_version | state     | imported |
|------+--------------+----------------+-----------+----------|
| 77   | base         | saas~17.2.1.3  | installed | <null>   |
| 1148 | tk_imprimeur | saas~17.2.0.1  | installed | True     |
+------+--------------+----------------+-----------+----------+
afu_2189915=> select * from ir_module_module_dependency where module_id=1148
+------+------+-----------+-----------------------+
| id   | name | module_id | auto_install_required |
|------+------+-----------+-----------------------|
| 2482 |      | 1148      | False                 |
+------+------+-----------+-----------------------+
```

upg-2189915

There are many more archived upgrades with a similar issue.

closes odoo/upgrade#6770

Signed-off-by: Christophe Simonis (chs) <chs@odoo.com>