[FIX] base/saas~17.5: rename oca module
OCA module `sale_commission` from 17.0 comes in conflict with the
newly introduced module `sale_commission` in standard.
OCA module:https://github.com/OCA/commission/tree/17.0/sale_commission

```
asno_2432913> select author,latest_version from ir_module_module where name='sale_commission'
+---------------------------------------------+----------------+
| author                                      | latest_version |
|---------------------------------------------+----------------|
| Tecnativa, Odoo Community Association (OCA) | 15.0.2.1.0     |
+---------------------------------------------+----------------+

```
traceback

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/18.0/odoo/service/server.py", line 1306, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "<decorator-gen-13>", line 2, in new
  File "/home/odoo/src/odoo/18.0/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/18.0/odoo/modules/registry.py", line 127, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/18.0/odoo/modules/loading.py", line 536, in load_modules
    env['ir.model.data']._process_end(processed_modules)
  File "/tmp/tmpmoooi6nn/migrations/base/0.0.0/pre-models-no-model-data-delete.py", line 108, in _process_end
    return super(IrModelData, self)._process_end(modules)
  File "/home/odoo/src/odoo/18.0/odoo/addons/base/models/ir_model.py", line 2643, in _process_end
    self._process_end_unlink_record(record)
  File "/home/odoo/src/odoo/18.0/addons/website/models/ir_model_data.py", line 35, in _process_end_unlink_record
    return super()._process_end_unlink_record(record)
  File "/home/odoo/src/odoo/18.0/odoo/addons/base/models/ir_model.py", line 2572, in _process_end_unlink_record
    record.unlink()
  File "/home/odoo/src/odoo/18.0/addons/mail/models/ir_model_fields.py", line 56, in unlink
    return super().unlink()
  File "/tmp/tmpmoooi6nn/migrations/base/0.0.0/pre-models-ir_model.py", line 210, in unlink
    raise util.MigrationError(message)
odoo.upgrade.util.exceptions.UpgradeError: 💥 It looks like you forgot to call `util.remove_field` on the following fields: sale.order.line.agent.write_date
```

closes odoo/upgrade#7059

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>