[FIX] base/16.0.1.3: UPDATE query syntax error
Missing field in UPDATE query.

```
2023-02-14 11:16:22,006 5461 ERROR pied_421325_wc_16.0 odoo.sql_db: bad query:
            UPDATE ir_act_window
               SET 'tree,form'
             WHERE view_mode = ''
               AND id IN (1518, 1517)

ERROR: syntax error at or near "'tree,form'"
LINE 3:                SET 'tree,form'
                           ^

2023-02-14 11:16:22,012 5461 WARNING pied_421325_wc_16.0 odoo.modules.loading: Transient module states were reset
2023-02-14 11:16:22,013 5461 ERROR pied_421325_wc_16.0 odoo.modules.registry: Failed to load registry
2023-02-14 11:16:22,013 5461 CRITICAL pied_421325_wc_16.0 odoo.service.server: Failed to initialize database `pied_421325_wc_16.0`.
Traceback (most recent call last):
  File "/home/odoo/src/odoo/16.0/odoo/service/server.py", line 1297, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "<decorator-gen-14>", line 2, in new
  File "/home/odoo/src/odoo/16.0/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/16.0/odoo/modules/registry.py", line 90, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/16.0/odoo/modules/loading.py", line 522, in load_modules
    migrations.migrate_module(package, 'end')
  File "/home/odoo/src/odoo/16.0/odoo/modules/migration.py", line 177, in migrate_module
    migrate(self.cr, installed_version)
  File "/tmp/tmpr5kms03p/migrations/base/16.0.1.3/end-remove-dashboard.py", line 41, in migrate
    cr.execute(
  File "/home/odoo/src/odoo/16.0/odoo/sql_db.py", line 315, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.SyntaxError: syntax error at or near "'tree,form'"
LINE 3:                SET 'tree,form'
```

closes odoo/upgrade#4338

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>