[FIX] point_of_sale/saas~17.{1,2}: fixed to remove used pos demo data
When the database is uploaded without demo data and there are no
valid POS products in the point of sale, customers using the "load demo data"
feature from the frontend screen inadvertently create demo records from a file
defined in point_of_sale/data/point_of_sale_onboarding_main_config.xml
with noupdate=False.
These XML IDs were created from a Python file using load samples,
hence having noupdate=False.

During an upgrade from version 17.0 to saas-17.1, It will,
remove entries with noupdate=f that could not found in
the source, resulting in issues.
Specifically, POS sessions linked with account bank statement lines,
which are in turn linked to journal entries, may be affected.
This can lead to attempted removal of
partially reconciled journal entries.

To address this issue, set noupdate=True in both the XML file
(point_of_sale/data/point_of_sale_onboarding_main_config.xml) and
the corresponding Python function.

This need to fixed in standard xml file to with noupdate="1"
true tag.
see:
https://github.com/odoo/odoo/pull/162080

TGB:
https://upgrade.odoo.com/web?debug=1#id=1184&cids=1&menu_id=107&action=178&model=upgrade.request.traceback.group&view_type=form
13 requests failed

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/saas-17.1/odoo/service/server.py", line 1286, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "<decorator-gen-14>", line 2, in new
  File "/home/odoo/src/odoo/saas-17.1/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/saas-17.1/odoo/modules/registry.py", line 119, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/saas-17.1/odoo/modules/loading.py", line 536, in load_modules
    env['ir.model.data']._process_end(processed_modules)
  File "/tmp/tmpklsxctuy/migrations/base/0.0.0/pre-models-no-model-data-delete.py", line 103, in _process_end
    return super(IrModelData, self)._process_end(modules)
  File "/home/odoo/src/odoo/saas-17.1/odoo/addons/base/models/ir_model.py", line 2561, in _process_end
    self._process_end_unlink_record(record)
  File "/home/odoo/src/odoo/saas-17.1/odoo/addons/base/models/ir_model.py", line 2490, in _process_end_unlink_record
    record.unlink()
  File "/home/odoo/src/odoo/saas-17.1/addons/point_of_sale/models/pos_session.py", line 517, in unlink
    self.statement_line_ids.unlink()
  File "/home/odoo/src/odoo/saas-17.1/addons/account/models/account_bank_statement_line.py", line 395, in unlink
    moves.unlink()
  File "/home/odoo/src/odoo/saas-17.1/addons/sale/models/account_move.py", line 30, in unlink
    res = super(AccountMove, self).unlink()
  File "/home/odoo/src/odoo/saas-17.1/addons/account/models/account_move.py", line 2770, in unlink
    self.line_ids.unlink()
  File "/home/odoo/src/odoo/saas-17.1/addons/account/models/account_move_line.py", line 1672, in unlink
    self._check_reconciliation()
  File "/home/odoo/src/odoo/saas-17.1/addons/account/models/account_move_line.py", line 1322, in _check_reconciliation
    raise UserError(_("You cannot do this modification on a reconciled journal entry. "
odoo.exceptions.UserError: No puede hacer esta modificación en un asiento conciliado. Puede cambiar algunos campos no legales, o romper antes la conciliación.
```

closes odoo/upgrade#5927

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>