[FIX] sale_subscription/saas~15.3: Fix syntax error
When all products with both `recurring_invoice` and `rent_ok` set to True that
are used in a subscription are linked to a template that has
`product_variant_count` > 1, `case_str` (and `template_mapping`) is not filled,
resulting in an invalid SQL syntax:

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/16.0/odoo/service/server.py", line 1299, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "<decorator-gen-16>", line 2, in new
  File "/home/odoo/src/odoo/16.0/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/16.0/odoo/modules/registry.py", line 90, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/16.0/odoo/modules/loading.py", line 484, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/home/odoo/src/odoo/16.0/odoo/modules/loading.py", line 372, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/odoo/src/odoo/16.0/odoo/modules/loading.py", line 183, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/home/odoo/src/odoo/16.0/odoo/modules/migration.py", line 189, in migrate_module
    migrate(self.cr, installed_version)
  File "/tmp/tmp9qe7hp04/migrations/sale_subscription/saas~15.3.1.1/pre-migrate.py", line 157, in migrate
    _handle_recurring_renting_products(cr)
  File "/tmp/tmp9qe7hp04/migrations/sale_subscription/saas~15.3.1.1/pre-migrate.py", line 953, in _handle_recurring_renting_products
    cr.execute(query)
  File "/home/odoo/src/odoo/16.0/odoo/sql_db.py", line 321, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.SyntaxError: syntax error at or near "ELSE"
LINE 4:                ELSE product_id
                       ^
```

closes odoo/upgrade#5745

Signed-off-by: Christophe Simonis (chs) <chs@odoo.com>