[FIX] base/0.0.0: remove unused FK
This could cause issues if the UNIQUE constraint in `res_lang` is
removed or edited.

```
2024-11-21 14:47:49,695 23 ERROR afu_2192105_18.0 odoo.sql_db: bad query: b'ALTER TABLE "res_lang" DROP CONSTRAINT "res_lang_code_uniq"'
ERROR: cannot drop constraint res_lang_code_uniq on table res_lang because other objects depend on it
DETAIL:  constraint ir_translation_lang_fkey_res_lang on table _ir_translation depends on index res_lang_code_uniq
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
```

closes odoo/upgrade#6827

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>