[FIX] l10n_de_skr04@{10.0,11.0,12.0}: l10n_de_skr04.account_3800
In odoo/odoo@a3bc08d9d8aa40e8d41f99e5b102997c6990396a:
 - Account templates xml ids are renamed from account_% to chart_skr04_%
 - The account and refund account of some tax templates is unset:
     - tax_eu_sale_skr04
     - tax_export_skr04
     - tax_not_taxable_skr04

As it was done during the lifetime of the 10.0 version,
and forward ported to 10.0, 11.0 and 12.0,
this script needs to run in these three major versions.

Without this, the upgrade of a database with `l10n_de_skr04`
installed fails with the below exception:

```
Deleting 1700@account.account.template (l10n_de_skr04.account_3800)
bad query: DELETE FROM account_account_template WHERE id IN (1700)
ERROR: update or delete on table "account_account_template" violates foreign key constraint "account_tax_template_account_id_fkey" on table "account_tax_template"
DETAIL:  Key (id)=(1700) is still referenced from table "account_tax_template".
```

This has been solved (wrongly) multiple times in unique customer migration scripts:
 - odoo/migration-scripts@5250f1970f492d5d77fd08faefd111f9b7f24494
 - odoo/migration-scripts@2c71b01cefb71eb27a4a3415bd4ee9976ac9c199
 - odoo/migration-scripts@981d1a824d6cbbaafd5ea16df53bd8eeee19f5da
 - odoo/migration-scripts@f78882bdbff9f365076d403484e0a6522e4238a3
 - odoo/migration-scripts@4d036cfeb45c6fe058c3fdee0fcbbf75d2c11422
 - odoo/migration-scripts@b916f943465daae18862d5a1b018c9144b79a8e7
 - odoo/migration-scripts@d3a79f69cc16a8cbf48b2e02b6c7e2608ec7797c
 - odoo/migration-scripts@b96b40572ad12ed27b141e5c3093e01b5cecd1dd
 - odoo/migration-scripts@ef6f5fd5972155b2d3be7de3d67414ab4396aec7
 - odoo/migration-scripts@9ae5d4c7768b3e386341f54ec8f5f76586159c50
 - odoo/migration-scripts@3dc822c6738b3793df60fbd64994feba7dc92d37
 - odoo/migration-scripts@78b6e20535b9174b52fceaa7841cd671d72a7f17
 - odoo/migration-scripts@32b8ddd6fe5673c2a1ab6e91cd13d098b758ef0d
 - odoo/migration-scripts@794a8e07991cb79b25b639da4cec8ce1f85b8f45
 - odoo/migration-scripts@723d92a3e60768cf06d11602222512290d464d76
 - odoo/migration-scripts@b9d891fea9f3d5a88e11eaeb0fb5b68f4925c67d
 - odoo/migration-scripts@7907f02114978d424aadef2297507d172407765d
 - odoo/migration-scripts@6122adfe3f9ea227d99b311e227a9fb2a6b8bb48
 - odoo/migration-scripts@2112b1a3b3d7b0905b908b183845287d57e13071
 - odoo/migration-scripts@cbb872ff09474eca641e084e7d3aebd216103096
 - odoo/migration-scripts@229d80f4c1e44275efa06e5a4c36506996783271
 - odoo/migration-scripts@04cd40f3f1052a7f91014f6b05c267a2bc5471d8

closes odoo/upgrade#767

Signed-off-by: Christophe Simonis <chs@odoo.com>