[FIX] base@tests: only user and active companies in `allowed_company_ids`
There were two issues:
 - If a custom module added an `active` field on `res.company`,
   inactive companies might have been added to `allowed_company_ids`,
   and once `custom_module_field_as_manual` called,
   the inactive companies are considerd as invalid companies.
   Hence, move the computation of the `allowed_company_ids`
   once the custom fields loaded
 - When adding all the children of the parent company,
   it's possible companies the user doesn't have access to
   were added to `allowed_company_ids`,
   and then it raised the `Access to unauthorized or invalid companies`
   exception.

```
 Traceback (most recent call last):
   File "/tmp/tmpamck8lv_/migrations/base/tests/test_mock_crawl.py", line 179, in crawl_menu
    self.mock_action(action_vals)
   File "/tmp/tmpamck8lv_/migrations/base/tests/test_mock_crawl.py", line 253, in mock_action
    action["views"], options={"action_id": action.get("id"), "toolbar": True, "load_filters": True}
   File "/home/odoo/src/odoo/14.0/odoo/models.py", line 1529, in load_views
    result['filters'] = self.env['ir.filters'].get_filters(self._name, options.get('action_id'))
   File "/home/odoo/src/odoo/14.0/odoo/addons/base/models/ir_filters.py", line 71, in get_filters
    filters = self.search(action_domain + [('model_id', '=', model), ('user_id', 'in', [self._uid, False])])
   File "/home/odoo/src/odoo/14.0/odoo/models.py", line 1702, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
   File "/home/odoo/src/odoo/14.0/odoo/models.py", line 4488, in _search
    self._flush_search(args, order=order)
   File "/home/odoo/src/odoo/14.0/odoo/models.py", line 4406, in _flush_search
    domain = list(domain) + (self.env['ir.rule']._compute_domain(self._name, 'read') or [])
   File "<decorator-gen-60>", line 2, in _compute_domain
   File "/home/odoo/src/odoo/14.0/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
   File "/home/odoo/src/odoo/14.0/odoo/addons/base/models/ir_rule.py", line 142, in _compute_domain
    eval_context = self._eval_context()
   File "/home/odoo/src/odoo/14.0/addons/website/models/ir_rule.py", line 11, in _eval_context
    res = super(IrRule, self)._eval_context()
   File "/home/odoo/src/odoo/14.0/odoo/addons/base/models/ir_rule.py", line 56, in _eval_context
    'company_ids': self.env.companies.ids,
   File "/home/odoo/src/odoo/14.0/odoo/tools/func.py", line 26, in __get__
    value = self.fget(obj)
   File "/home/odoo/src/odoo/14.0/odoo/api.py", line 590, in companies
    raise AccessError(_("Access to unauthorized or invalid companies."))
 odoo.exceptions.AccessError: Access to unauthorized or invalid companies.
```

request 62566
upg-22623
upg-22607
upg-22233
upg-21909
upg-21426
upg-20500
upg-19649
upg-2440

closes odoo/upgrade#2754

Signed-off-by: Christophe Simonis <chs@odoo.com>