[FIX] industry_fsm/saas~16.3: fixed test case for personal stages
When Database is upgraded from saas~16.2 to 17.0,
and `industry_fsm`, `industry_fsm_sale` and
`note` modules are installed with demo data in saas-16.2
then, The <function> tag is not called during update in the noupdate block
defined in `industry_fsm` demo file which remove the
some stages. so as these stages are not removed during upgrade
it will make test case failed.

and as per this commit we need to remove it from
generic script to make runbot green.

see:
https://github.com/odoo/enterprise/commit/d7830587748d92c0dbc43c2365f5eaf6861ba4e4

and `note` module is renamed to `project_todo` from
saas-16.3.

```
FAIL: TestMigrateNoteInTodo.test_check
Traceback (most recent call last):
  File "/data/build/upgrade-util/src/testing.py", line 208, in test_check
    self.check(value)
  File "/data/build/upgrade/migrations/project_todo/tests/test_migrate_note_in_todo.py", line 73, in check
    self.assertEqual(
AssertionError: 11 != 7 : No personal stages should be generated for the current user since he have already got`
```

closes odoo/upgrade#5617

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>