[FIX] account_asset@saas~12.3: do not round counter balance moves
In the observed case, the rounding of the currency
has been changed from `0.01` to `1.0` after
some move lines have already been created.

On creation of the move counter-balancing
the journals, as the ORM is used, the debit/credit
were rounded while the origin move lines were not,
therefore leading to the error
```
  File "/src/odoo/saas-12.3/addons/account/models/account_move.py", line
505, in assert_balanced
    "\n\n{}{}".format(_('Difference debit - credit: '), res[1])
odoo.exceptions.UserError: ('Cannot create unbalanced journal
entry.\n\nDifference debit - credit: 1.0', '')
```

In addition, the `assert_balanced` constraint also rounds
the debit/credit according to the currency rounding:
```sql
HAVING ROUND(SUM(line.debit - line.credit), currency.decimal_places) != 0.0;
```

So even if plain SQL was used to create the counter balance moves,
it would have caused the issue as well.

For instance, in this database, the currency is the Vietnamese Dong,
rounded to 1.0:

```sql
SELECT name, rounding FROM res_currency WHERE id = 24;
 name | rounding
------+----------
 VND  | 1.000000

SELECT aml.debit, aml.credit, am.currency_id
  FROM account_asset_depreciation_line dl
  JOIN account_move am ON  dl.move_id = am.id
  JOIN account_move_line aml ON aml.move_id = am.id
 WHERE dl.move_id IS NOT NULL
   AND SPLIT_PART(aml.debit::text, '.', 2) != '0';
       debit        | credit | currency_id
--------------------+--------+-------------
         9695653.53 |    0.0 |          24
         6809001.93 |    0.0 |          24
           38436.38 |    0.0 |          24
         3349095.81 |    0.0 |          24
            11308.5 |    0.0 |          24
         6436485.45 |    0.0 |          24
         3349095.81 |    0.0 |          24
         6436485.45 |    0.0 |          24
          523494.38 |    0.0 |          24
          523494.38 |    0.0 |          24
          523494.38 |    0.0 |          24
           38436.38 |    0.0 |          24
```

Request 55782

closes odoo/upgrade#1893

Signed-off-by: Christophe Simonis <chs@odoo.com>