[FIX] hr_contract/saas~14.3: remove menu
`hr_contract.hr_menu_contract` was removed in odoo/odoo#66247. Then
there is a menu being renamed back to `hr_contract.hr_menu_contract`

https://github.com/odoo/upgrade/blob/fb0db8d300db4b94d0793956665311bb9bbc298a/migrations/hr_contract/saas~16.5.1.0/pre-migrate.py#L10

This fails for some DBs:
```
UpgradeError: Can't rename hr_work_entry_contract_enterprise.hr_menu_contract to hr_contract.hr_menu_contract as it already exists
```

To solve the issue we 1. remove the old menu, and 2. use a merge
strategy.

See also #2197
tbg-1004

closes odoo/upgrade#5732

Signed-off-by: Christophe Simonis (chs) <chs@odoo.com>