[FIX] website/saas~18.4: Set blockquote view to primary mode
During the commit odoo/odoo@b3083dad6cb641901afb36c1b0cc892d9f17589a,
the view `website.s_blockquote_options` was updated
to primary mode by setting `inherit_id` to NULL.
However, during migration, the view is updated without
resetting the `inherit_id`, which leads to a traceback due
to conflicting inheritance state.
To fix this, the `inherit_id` is explicitly set to NULL and the
view mode is updated to `primary` to align with the standard.

Traceback:
ValueError: Element '<t t-name="website.s_blockquote_options">'
cannot be located in parent view
Template: website.s_blockquote_options

upg-3054997
opw-4992245

closes odoo/upgrade#8166

Signed-off-by: Christophe Simonis (chs) <chs@odoo.com>