[FIX] base/0.0.0: Skip test modules
Test modules are not meant to be installed on user databases, so we remove them
in the beginning of the upgrade in base/0.0.0/pre-uninstall-test-modules.py.
However, before the upgrade even starts, Odoo is parsing the tests from all
installed modules in order to construct test suites.
Just parsing the test suites (without even executing them) can lead to
unnecessary errors, for example if one of the imports cannot be found.

In order to avoid the test modules being consulted for the test suites to
begin with, we set the test modules' state to something else. This is enough
to exclude them from being included in the graph (and therefore in the test
suite); the actual removal of the test module is done in
pre-uninstall-test-modules as before.

So far the only culprit appears to be the test_lint module, so we can restrict
the state change to that one.

Example traceback:
```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/17.0/odoo/service/server.py", line 1302, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "<decorator-gen-16>", line 2, in new
  File "/home/odoo/src/odoo/17.0/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/17.0/odoo/modules/registry.py", line 113, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/17.0/odoo/modules/loading.py", line 476, in load_modules
    processed_modules += load_marked_modules(env, graph,
  File "/home/odoo/src/odoo/17.0/odoo/modules/loading.py", line 364, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/odoo/src/odoo/17.0/odoo/modules/loading.py", line 277, in load_module_graph
    suite = loader.make_suite([module_name], 'at_install')
  File "/home/odoo/src/odoo/17.0/odoo/tests/loader.py", line 76, in make_suite
    return OdooSuite(sorted(tests, key=lambda t: t.test_sequence))
  File "/home/odoo/src/odoo/17.0/odoo/tests/loader.py", line 72, in <genexpr>
    for m in get_test_modules(module_name)
  File "/home/odoo/src/odoo/17.0/odoo/tests/loader.py", line 19, in get_test_modules
    results = _get_tests_modules(importlib.util.find_spec(f'odoo.addons.{module}'))
  File "/home/odoo/src/odoo/17.0/odoo/tests/loader.py", line 30, in _get_tests_modules
    tests_mod = importlib.import_module(spec.name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/odoo/src/odoo/17.0/odoo/addons/test_lint/tests/__init__.py", line 2, in <module>
    from . import test_checkers
  File "/home/odoo/src/odoo/17.0/odoo/addons/test_lint/tests/test_checkers.py", line 13, in <module>
    from . import _odoo_checker_sql_injection
  File "/home/odoo/src/odoo/17.0/odoo/addons/test_lint/tests/_odoo_checker_sql_injection.py", line 8, in <module>
    import astroid
ModuleNotFoundError: No module named 'astroid'
```

closes odoo/upgrade#5865

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>