[FIX] base/saas~17.5: fixed TypeError for NoneType object
The error you're encountering happens
because cr.fetchone() is returning None,
which means there is no row to fetch from the database.
When None is returned, trying to access cr.fetchone()[0] causes a TypeError.

TypeError: 'NoneType' object is not iterable

when `property_valuation` in property field contain
value with company_id Null get this error.
upg-2182217

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/18.0/odoo/service/server.py", line 1305, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "<decorator-gen-13>", line 2, in new
  File "/home/odoo/src/odoo/18.0/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/18.0/odoo/modules/registry.py", line 131, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/18.0/odoo/modules/loading.py", line 421, in load_modules
    loaded_modules, processed_modules = load_module_graph(
  File "/home/odoo/src/odoo/18.0/odoo/modules/loading.py", line 180, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/home/odoo/src/odoo/18.0/odoo/modules/migration.py", line 254, in migrate_module
    mod.migrate(self.cr, installed_version)
  File "/tmp/tmpt50xhyg8/migrations/base/saas~17.5.1.3/pre-company-dependent-jsonb.py", line 35, in migrate
    cleanup_stock_account_property(cr)
  File "/tmp/tmpt50xhyg8/migrations/base/saas~17.5.1.3/pre-company-dependent-jsonb.py", line 138, in cleanup_stock_account_property
    non_real_time_fallback_company_ids = tuple(cr.fetchone()[0]) if cr.rowcount else ()
TypeError: 'NoneType' object is not iterable
```

closes odoo/upgrade#6750

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>