[FIX] website_helpdesk/saas~15.2: fixed cowed view for helpdesk team
From Odoo 16 version, there are changes on `website_helpdesk.team`
view.
now following things has been changed.
1. ```<t t-set="many_teams" t-value="len(teams)>1"/>``` this whole div has
been removed. now we cannot directly fetch `teams` and that's error
if it was not updated.
2. ```<div id="website_helpdesk_form">``` has been replaced by
   ```<div t-if="team.use_website_helpdesk_form">
          <t t-set="template_xmlid" t-value="team.website_form_view_id.xml_id"/>
          <t t-call="#{template_xmlid}"/>
     </div>
   ```
3. It has been removed.
```
<t t-if="team.use_website_helpdesk_form">
    <a class="mb-5" id="submit-ticket" t-attf-href="/my/tickets">
        <button t-attf-class="btn btn-primary #{'col-md-10' if multi_type else 'col-md-12'} mb-2">View my Tickets</button>
    </a>
</t>
<div class="oe_structure" id="oe_structure_website_helpdesk_links">
    <t t-if="team.portal_show_rating">
        <a t-attf-href="/helpdesk/rating/#{team.id}">
            <button t-attf-class="btn btn-primary #{'col-md-10' if multi_type else 'col-md-12'} mt-2 mb-2">Our team's ratings</button>
        </a>
    </t>
</div>
```
see: https://github.com/odoo/enterprise/commit/b191f16abb5913893a228ccc4eedb8a2242a0298
but when there is multi-website then this view has been not
updated and will get this traceback for cowed views.

```
Error while render the template
TypeError: object of type 'NoneType' has no len()
Template: website_helpdesk.team
Path: /t/t/div[1]/div
Node: <div t-if="many_teams" class="navbar navbar-expand-md navbar-light bg-light pb-0"/>
The error occurred while rendering the template website_helpdesk.team and evaluating the following expression: <div t-if="many_teams" class="navbar navbar-expand-md navbar-light bg-light pb-0"/>
```
Unicorn task:
https://www.odoo.com/web#id=3428333&menu_id=4720&cids=21&action=333&active_id=6443&model=project.task&view_type=form

upg-647620
https://upgrade.odoo.com/web#cids=1&id=647620&menu_id=&model=upgrade.request&view_type=form

closes odoo/upgrade#5003

Signed-off-by: Christophe Simonis (chs) <chs@odoo.com>