[FIX] account/saas~13.4: remove deprecated flag
Due to odoo/odoo@c2519747 bank statements cannot be posted if one of the
move lines is for a deprecated account.

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/14.0/odoo/service/server.py", line 1201, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/odoo/src/odoo/14.0/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/src/odoo/14.0/odoo/modules/loading.py", line 477, in load_modules
    migrations.migrate_module(package, 'end')
  File "/home/odoo/src/odoo/14.0/odoo/modules/migration.py", line 180, in migrate_module
    migrate(self.cr, installed_version)
  File "/tmp/tmpify__4bp/migrations/account/saas~13.4.1.1/end-09-payment-refactoring.py", line 607, in migrate
    bs.button_post()
  File "/home/odoo/src/odoo/14.0/addons/account/models/account_bank_statement.py", line 431, in button_post
    lines_of_moves_to_post.move_id._post(soft=False)
  File "/home/odoo/src/enterprise/14.0/account_asset/models/account_move.py", line 38, in _post
    posted = super()._post(soft)
  File "/home/odoo/src/odoo/14.0/addons/sale/models/account_invoice.py", line 75, in _post
    posted = super()._post(soft)
  File "/home/odoo/src/enterprise/14.0/account_reports/models/account_activity.py", line 75, in _post
    return super()._post(soft)
  File "/home/odoo/src/enterprise/14.0/account_invoice_extract/models/account_invoice.py", line 334, in _post
    posted = super()._post(soft)
  File "/home/odoo/src/odoo/14.0/addons/account_edi/models/account_move.py", line 337, in _post
    posted = super()._post(soft=soft)
  File "/home/odoo/src/odoo/14.0/addons/account/models/account_move.py", line 2689, in _post
    raise UserError(_("A line of this move is using a deprecated account, you cannot post it."))
odoo.exceptions.UserError: A line of this move is using a deprecated account, you cannot post it.
```

upg-422728
(at least 6 more, tbg-459)

closes odoo/upgrade#4117

Signed-off-by: Christophe Simonis <chs@odoo.com>