[FIX] documents_project/saas~17.5: remove missed draft tag
tbg-1908
The tag `documents_tag_draft` needed by
`documents_project.ir_actions_server_tag_remove_draft`
was not added to the tags that need to be created when
`documents_project` is installed.

Although the tag is forcecreate=0 noupdate=1,
we need to create it if documents_project is installed as done
for `documents_tag_deprecated`.

https://github.com/odoo/upgrade/blob/7bcda2765d197c0e8e9b79119ce23efffa34f070/migrations/documents_project/saas~17.5.1.0/post-migrate.py#L9

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/18.0/odoo/tools/cache.py", line 103, in lookup
    r = d[key]
  File "<decorator-gen-6>", line 2, in __getitem__
  File "/home/odoo/src/odoo/18.0/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/18.0/odoo/tools/lru.py", line 33, in __getitem__
    a = self.d[obj]
KeyError: ('ir.model.data', <function IrModelData._xmlid_lookup at 0x72bc812f7250>, 'documents.documents_tag_draft')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/18.0/odoo/tools/convert.py", line 537, in _tag_root
    f(rec)
  File "/home/odoo/src/odoo/18.0/odoo/tools/convert.py", line 397, in _tag_record
    val = self.model_id_get(f_ref)
  File "/home/odoo/src/odoo/18.0/odoo/tools/convert.py", line 525, in model_id_get
    return self.env['ir.model.data']._xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "/home/odoo/src/odoo/18.0/odoo/addons/base/models/ir_model.py", line 2245, in _xmlid_to_res_model_res_id
    return self._xmlid_lookup(xmlid)
  File "<decorator-gen-44>", line 2, in _xmlid_lookup
  File "/home/odoo/src/odoo/18.0/odoo/tools/cache.py", line 110, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/odoo/src/odoo/18.0/odoo/addons/base/models/ir_model.py", line 2238, in _xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: documents.documents_tag_draft

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/18.0/odoo/service/server.py", line 1318, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "<decorator-gen-13>", line 2, in new
  File "/home/odoo/src/odoo/18.0/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/18.0/odoo/modules/registry.py", line 127, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/18.0/odoo/modules/loading.py", line 476, in load_modules
    processed_modules += load_marked_modules(env, graph,
  File "/home/odoo/src/odoo/18.0/odoo/modules/loading.py", line 364, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/odoo/src/odoo/18.0/odoo/modules/loading.py", line 232, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/home/odoo/src/odoo/18.0/odoo/modules/migration.py", line 254, in migrate_module
    mod.migrate(self.cr, installed_version)
  File "/tmp/tmpbv0txwap/migrations/documents_project/saas~17.5.1.0/post-migrate.py", line 29, in migrate
    util.update_record_from_xml(cr, f"documents_project.ir_actions_server_{server_action}")
  File "/tmp/tmpbv0txwap/migrations/util/records.py", line 1050, in update_record_from_xml
    __update_record_from_xml(
  File "/tmp/tmpbv0txwap/migrations/util/records.py", line 1196, in __update_record_from_xml
    importer.parse(new_root, **kw)
  File "/home/odoo/src/odoo/18.0/odoo/tools/convert.py", line 594, in parse
    self._tag_root(de)
  File "/home/odoo/src/odoo/18.0/odoo/tools/convert.py", line 537, in _tag_root
    f(rec)
  File "/home/odoo/src/odoo/18.0/odoo/tools/convert.py", line 550, in _tag_root
    raise ParseError('while parsing %s:%s, somewhere inside\n%s' % (
odoo.tools.convert.ParseError: while parsing None:6, somewhere inside
<record id="ir_actions_server_tag_remove_draft" model="ir.actions.server" forcecreate="0">
            <field name="name">Remove Tag Draft</field>
            <field name="model_id" ref="documents.model_documents_document"/>
            <field name="groups_id" eval="[Command.link(ref('base.group_user'))]"/>
            <field name="sequence">7</field> <!-- Higher than the sequence of "_code" checks -->
            <field name="state">object_write</field>
            <field name="update_m2m_operation">remove</field>
            <field name="update_path">tag_ids</field>
            <field name="resource_ref" ref="documents.documents_tag_draft"/>
        </record>Traceback (most recent call last):
  File "/home/odoo/src/odoo/18.0/odoo/tools/cache.py", line 103, in lookup
    r = d[key]
  File "<decorator-gen-6>", line 2, in __getitem__
  File "/home/odoo/src/odoo/18.0/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/18.0/odoo/tools/lru.py", line 33, in __getitem__
    a = self.d[obj]
KeyError: ('ir.model.data', <function IrModelData._xmlid_lookup at 0x72bc812f7250>, 'documents.documents_tag_draft')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/18.0/odoo/tools/convert.py", line 537, in _tag_root
    f(rec)
  File "/home/odoo/src/odoo/18.0/odoo/tools/convert.py", line 397, in _tag_record
    val = self.model_id_get(f_ref)
  File "/home/odoo/src/odoo/18.0/odoo/tools/convert.py", line 525, in model_id_get
    return self.env['ir.model.data']._xmlid_to_res_model_res_id(id_str, raise_if_not_found=raise_if_not_found)
  File "/home/odoo/src/odoo/18.0/odoo/addons/base/models/ir_model.py", line 2245, in _xmlid_to_res_model_res_id
    return self._xmlid_lookup(xmlid)
  File "<decorator-gen-44>", line 2, in _xmlid_lookup
  File "/home/odoo/src/odoo/18.0/odoo/tools/cache.py", line 110, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/odoo/src/odoo/18.0/odoo/addons/base/models/ir_model.py", line 2238, in _xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: documents.documents_tag_draft

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/18.0/odoo/service/server.py", line 1318, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "<decorator-gen-13>", line 2, in new
  File "/home/odoo/src/odoo/18.0/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/18.0/odoo/modules/registry.py", line 127, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/18.0/odoo/modules/loading.py", line 476, in load_modules
    processed_modules += load_marked_modules(env, graph,
  File "/home/odoo/src/odoo/18.0/odoo/modules/loading.py", line 364, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/odoo/src/odoo/18.0/odoo/modules/loading.py", line 232, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/home/odoo/src/odoo/18.0/odoo/modules/migration.py", line 254, in migrate_module
    mod.migrate(self.cr, installed_version)
  File "/tmp/tmpbv0txwap/migrations/documents_project/saas~17.5.1.0/post-migrate.py", line 29, in migrate
    util.update_record_from_xml(cr, f"documents_project.ir_actions_server_{server_action}")
  File "/tmp/tmpbv0txwap/migrations/util/records.py", line 1050, in update_record_from_xml
    __update_record_from_xml(
  File "/tmp/tmpbv0txwap/migrations/util/records.py", line 1196, in __update_record_from_xml
    importer.parse(new_root, **kw)
  File "/home/odoo/src/odoo/18.0/odoo/tools/convert.py", line 594, in parse
    self._tag_root(de)
  File "/home/odoo/src/odoo/18.0/odoo/tools/convert.py", line 537, in _tag_root
    f(rec)
  File "/home/odoo/src/odoo/18.0/odoo/tools/convert.py", line 550, in _tag_root
    raise ParseError('while parsing %s:%s, somewhere inside\n%s' % (
odoo.tools.convert.ParseError: while parsing None:6, somewhere inside
<record id="ir_actions_server_tag_remove_draft" model="ir.actions.server" forcecreate="0">
            <field name="name">Remove Tag Draft</field>
            <field name="model_id" ref="documents.model_documents_document"/>
            <field name="groups_id" eval="[Command.link(ref('base.group_user'))]"/>
            <field name="sequence">7</field> <!-- Higher than the sequence of "_code" checks -->
            <field name="state">object_write</field>
            <field name="update_m2m_operation">remove</field>
            <field name="update_path">tag_ids</field>
            <field name="resource_ref" ref="documents.documents_tag_draft"/>
        </record>
```

closes odoo/upgrade#7384

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>