[FIX] util/pg.py: rename_table compatible for relational table
As relational table haven't id so there is not possible to have sequence.

error log:
```
2023-06-08 13:33:44,924 32 ERROR db_816141 odoo.sql_db: bad query: ALTER SEQUENCE "hr_employee_planning_role_rel_id_seq" RENAME TO "hr_employee_planning_role_rel_custom_id_seq"
ERROR: relation "hr_employee_planning_role_rel_id_seq" does not exist

2023-06-08 13:33:44,928 32 WARNING db_816141 odoo.modules.loading: Transient module states were reset
2023-06-08 13:33:44,928 32 ERROR db_816141 odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/home/odoo/src/odoo/14.0/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/src/odoo/14.0/odoo/modules/loading.py", line 402, in load_modules
    report=report, models_to_check=models_to_check)
  File "/home/odoo/src/odoo/14.0/odoo/modules/loading.py", line 174, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/home/odoo/src/odoo/14.0/odoo/modules/migration.py", line 186, in migrate_module
    migrate(self.cr, installed_version)
  File "/tmp/tmpjds6nn6t/migrations/base/14.0.1.0/pre--rename_custom_table.py", line 10, in migrate
    custom_module="planning_cust",
  File "/tmp/tmpjds6nn6t/migrations/util/specific.py", line 50, in rename_custom_table
    rename_table(cr, table_name, new_table_name, remove_constraints=False)
  File "/tmp/tmpjds6nn6t/migrations/util/pg.py", line 647, in rename_table
    sql.Identifier(old_table + "_id_seq"), sql.Identifier(new_table + "_id_seq")
  File "<decorator-gen-3>", line 2, in execute
  File "/home/odoo/src/odoo/14.0/odoo/sql_db.py", line 101, in check
    return f(self, *args, **kwargs)
  File "/home/odoo/src/odoo/14.0/odoo/sql_db.py", line 301, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.UndefinedTable: relation "hr_employee_planning_role_rel_id_seq" does not exist
```

upg-816141
upg-838307

closes odoo/upgrade#4782

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>