[FIX] account/0.0.0: make repartition lines from 14.0
Databases upgrading from 13.0 to a higher will fail because `company_id`
was a required and not computed field.
Since the changes of this script are only relevant for saas~16.2 and higher,
we only apply the script when
upgrading to 15.0 and higher so that we're sure that company_id is a
computed field. else we get an error
because we're not filling the field in the query
(which is unnecessary starting from 14.0)

TBG:
https://upgrade.odoo.com/web#id=882&cids=1&menu_id=107&action=178&model=upgrade.request.traceback.group&view_type=form

`company_id` field in 13.0:

https://github.com/odoo/odoo/blob/13.0/addons/account/models/account.py#L1894

Tracebacks:
```
2023-09-18 08:06:07,421 29 INFO db_1145965 odoo.modules.migration: module account: Running migration [>0.0.0] pre-make-repartition-lines
2023-09-18 08:06:07,435 29 ERROR db_1145965 odoo.sql_db: bad query:
            WITH info AS (
                SELECT tax.type AS ttype,
                       doc.type AS dtype,
                       array_agg(
                           CASE doc.type
                               WHEN 'invoice' THEN rl.invoice_tax_id
                               ELSE rl.refund_tax_id
                           END
                       ) AS tax_ids
                  FROM (VALUES ('tax'), ('base')) AS tax(type)
            CROSS JOIN (VALUES ('invoice'), ('refund')) AS doc(type)
             LEFT JOIN account_tax_repartition_line rl
                    ON rl.repartition_type = tax.type
                 WHERE (doc.type = 'invoice' AND rl.invoice_tax_id IS NOT NULL)
                    OR (doc.type = 'refund' AND rl.refund_tax_id IS NOT NULL)
              GROUP BY tax.type, doc.type
            )
            INSERT INTO account_tax_repartition_line(
                            repartition_type,invoice_tax_id,refund_tax_id,factor_percent
                        )
                 SELECT info.ttype,
                        CASE
                            WHEN info.dtype = 'invoice' THEN t.id
                            ELSE NULL
                        END AS invoice_tax_id,
                        CASE
                            WHEN info.dtype = 'refund' THEN t.id
                            ELSE NULL
                        END AS refund_tax_id,
                        100.0
                   FROM info,
                        account_tax t
                  WHERE t.amount_type != 'group'
                    AND t.id != ALL(info.tax_ids)

ERROR: null value in column "company_id" of relation "account_tax_repartition_line" violates not-null constraint
DETAIL:  Failing row contains (10160, 100, tax, null, null, 2157, null, null, null, null, null, null).
```

closes odoo/upgrade#5165

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>