[FIX] base/tests: get right model for field
Some fields may be inside an embedded tree or form view. In such cases
we cannot assume the field comes from the model of the top-level view.

upg-472172
upg-472096
upg-471760
upg-471327

```
<form string="Analytic Account">
    <field name="company_id" on_change="1" modifiers="{&quot;invisible&quot;: true}" can_create="true" can_write="true"/>
    <sheet string="Analytic Account">
        <div class="oe_title">
	    <label for="name"/>
      	    <h1>
                <field name="name" class="oe_inline" placeholder="e.g.
Project XYZ"/>
	    </h1>
         </div>
	<field name="project_ids" on_change="1">
	    <tree decoration-muted="active == False" string="Projects" multi_edit="1" sample="1" default_order="sequence, name, id">
	        <field name="sequence" optional="show" widget="handle"/>
		<field name="x_last_update_status" optional="show" string="Estado de proyecto" widget="selection" modifiers="{&quot;required&quot;: true}"/>
	    </tree>
       </field>
  </sheet>
</form>

Traceback (most recent call last):
  File "/tmp/tmpzx0vp425/migrations/testing.py", line 211, in test_check
    self.check(value)
  File "/tmp/tmpzx0vp425/migrations/base/tests/test_mock_crawl.py", line 121, in check
    self.assertFalse(diff, msg)
AssertionError: [('account.account_analytic_def_account', 168, 'Accounting > Configuration > Analytic Accounting > Analytic Accounts', 132)] is not false : At least one menu or view working before upgrade is not working after upgrade.

('account.account_analytic_def_account', 168, 'Accounting > Configuration > Analytic Accounting > Analytic Accounts', 132):
 Traceback (most recent call last):
   File "/tmp/tmpzx0vp425/migrations/base/tests/test_mock_crawl.py", line 221, in crawl_menu
    self.mock_action(action_vals)
   File "/tmp/tmpzx0vp425/migrations/base/tests/test_mock_crawl.py", line 362, in mock_action
    mock_method(model, view, fields_list, domain, group_by)
   File "/tmp/tmpzx0vp425/migrations/base/tests/test_mock_crawl.py", line 423, in mock_view_form
    field = model._fields[fname]
 KeyError: 'x_last_update_status'

```

closes odoo/upgrade#4287

Signed-off-by: Christophe Simonis <chs@odoo.com>