[FIX] onboarding/saas~16.4: fix tests imports
This script is imported from tests but since odoo.upgrade cannot be
found in older versions it breaks tests from 12.0 up to 13.0

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/12.0/odoo/modules/module.py", line 446, in _get_tests_modules
    mod = importlib.import_module('.tests', modpath)
...
  File "/home/odoo/src/odoo/12.0/odoo/addons/base/maintenance/migrations/account/tests/__init__.py", line 3, in <module>
    from . import (
  File "/home/odoo/src/odoo/12.0/odoo/addons/base/maintenance/migrations/account/tests/test_16_4_onboarding.py", line 4, in <module>
    from odoo.addons.base.maintenance.migrations.onboarding.tests.test_common import UpgradeOnboardingCase
  File "/home/odoo/src/odoo/12.0/odoo/addons/base/maintenance/migrations/onboarding/tests/__init__.py", line 3, in <module>
    from . import test_16_4_onboarding, test_common
  File "/home/odoo/src/odoo/12.0/odoo/addons/base/maintenance/migrations/onboarding/tests/test_16_4_onboarding.py", line 3, in <module>
    from odoo.addons.base.maintenance.migrations.onboarding.tests.test_common import UpgradeOnboardingCase
  File "/home/odoo/src/odoo/12.0/odoo/addons/base/maintenance/migrations/onboarding/tests/test_common.py", line 6, in <module>
    onboarding_utils = util.import_script("onboarding/saas~16.4.1.2/pre-migrate.py")
  File "/home/odoo/src/odoo/12.0/odoo/addons/base/maintenance/migrations/util/misc.py", line 150, in import_script
    spec.loader.exec_module(module)
  File "/home/odoo/src/odoo/12.0/odoo/addons/base/maintenance/migrations/onboarding/saas~16.4.1.2/pre-migrate.py", line 3, in <module>
    from odoo.upgrade import util
ModuleNotFoundError: No module named 'odoo.upgrade'
```

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/12.0/odoo/modules/module.py", line 446, in _get_tests_modules
    mod = importlib.import_module('.tests', modpath)
...
  File "/home/odoo/src/odoo/12.0/odoo/addons/base/maintenance/migrations/account/tests/__init__.py", line 3, in <module>
    from . import (
  File "/home/odoo/src/odoo/12.0/odoo/addons/base/maintenance/migrations/account/tests/test_16_4_onboarding.py", line 7, in <module>
    post_migrate = util.import_script("account/saas~16.4.1.2/post-migrate.py")
  File "/home/odoo/src/odoo/12.0/odoo/addons/base/maintenance/migrations/util/misc.py", line 150, in import_script
    spec.loader.exec_module(module)
  File "/home/odoo/src/odoo/12.0/odoo/addons/base/maintenance/migrations/account/saas~16.4.1.2/post-migrate.py", line 3, in <module>
    from odoo.upgrade import util
ModuleNotFoundError: No module named 'odoo.upgrade'
```
```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/12.0/odoo/modules/module.py", line 446, in _get_tests_modules
    mod = importlib.import_module('.tests', modpath)
...
  File "/home/odoo/src/odoo/12.0/odoo/addons/base/maintenance/migrations/sale/tests/__init__.py", line 3, in <module>
    from . import test_16_4_onboarding
  File "/home/odoo/src/odoo/12.0/odoo/addons/base/maintenance/migrations/sale/tests/test_16_4_onboarding.py", line 7, in <module>
    post_migrate = util.import_script("sale/saas~16.4.1.2/post-migrate.py")
  File "/home/odoo/src/odoo/12.0/odoo/addons/base/maintenance/migrations/util/misc.py", line 150, in import_script
    spec.loader.exec_module(module)
  File "/home/odoo/src/odoo/12.0/odoo/addons/base/maintenance/migrations/sale/saas~16.4.1.2/post-migrate.py", line 3, in <module>
    from odoo.upgrade import util
ModuleNotFoundError: No module named 'odoo.upgrade'
```

closes odoo/upgrade#4933

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>