[FIX] stock@saas~12.3: create missing location
Normally, these methods to create the missing locations
should be called through the data file
`addons/stock/data/stock_data.xml`
https://github.com/odoo/odoo/blob/saas-12.3/addons/stock/data/stock_data.xml#L148-L152
but as it's in a `noupdate="1"`, they are not during an upgrade `-u`.

As some of these locations type might be missing in the 12.0 database,
they need to be called so the missing locations are correctly created.

```
Traceback (most recent call last):
  File "/data/build/odoo/odoo/modules/loading.py", line 84, in load_demo
    load_data(cr, idref, mode, kind='demo', package=package, report=report)
  File "/data/build/odoo/odoo/modules/loading.py", line 68, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind, report)
  File "/data/build/odoo/odoo/tools/convert.py", line 734, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate, report)
  File "/data/build/odoo/odoo/tools/convert.py", line 795, in convert_xml_import
    obj.parse(doc.getroot())
  File "/data/build/odoo/odoo/tools/convert.py", line 719, in parse
    exc_info[2]
  File "/data/build/odoo/odoo/tools/pycompat.py", line 13, in reraise
    raise value.with_traceback(tb)
  File "/data/build/odoo/odoo/tools/convert.py", line 710, in parse
    self._tag_root(de)
  File "/data/build/odoo/odoo/tools/convert.py", line 672, in _tag_root
    f(rec)
  File "/data/build/odoo/odoo/tools/convert.py", line 672, in _tag_root
    f(rec)
  File "/data/build/odoo/odoo/tools/convert.py", line 327, in _tag_function
    _eval_xml(self, rec, env)
  File "/data/build/odoo/odoo/tools/convert.py", line 199, in _eval_xml
    return odoo.api.call_kw(model, method_name, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 755, in call_kw
    return _call_kw_multi(method, model, args, kwargs)
  File "/data/build/odoo/odoo/api.py", line 742, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/data/build/odoo/addons/mrp/models/stock_warehouse.py", line 248, in write
    return super(StockWarehouse, self).write(vals)
  File "/data/build/odoo/addons/stock/models/stock_warehouse.py", line 163, in write
    global_rules = warehouse._get_global_route_rules_values()
  File "/data/build/odoo/addons/purchase_stock/models/stock.py", line 116, in _get_global_route_rules_values
    rules = super(StockWarehouse, self)._get_global_route_rules_values()
  File "/data/build/odoo/addons/mrp/models/stock_warehouse.py", line 103, in _get_global_route_rules_values
    rules = super(StockWarehouse, self)._get_global_route_rules_values()
  File "/data/build/odoo/addons/stock/models/stock_warehouse.py", line 327, in _get_global_route_rules_values
    rule = self.get_rules_dict()[self.id][self.delivery_steps]
  File "/data/build/odoo/addons/mrp/models/stock_warehouse.py", line 44, in get_rules_dict
    production_location_id = self._get_production_location()
  File "/data/build/odoo/addons/mrp/models/stock_warehouse.py", line 64, in _get_production_location
    raise UserError(_('Can\'t find any production location.'))
odoo.tools.convert.ParseError: "Can't find any production location.
" while parsing /data/build/odoo/addons/purchase_stock/data/purchase_stock_demo.xml:2, near
<odoo>
    <data noupdate="1">

    	<record id="stock.res_company_1" model="res.company">
            <field eval="1.0" name="po_lead"/>
        </record>

        <record id="product.product_delivery_01" model="product.product">
            <field name="route_ids" eval="[(4,ref('route_warehouse0_buy'))]"/>
        </record>

        <record id="product.product_delivery_02" model="product.product">
            <field name="route_ids" eval="[(4,ref('route_warehouse0_buy'))]"/>
        </record>

        <record id="product.product_product_20" model="product.product">
            <field name="route_ids" eval="[(4,ref('route_warehouse0_buy'))]"/>
        </record>

        <record id="product.product_product_9" model="product.product">
            <field name="route_ids" eval="[(4,ref('route_warehouse0_buy'))]"/>
        </record>
	</data>

    <data noupdate="0">

        <record id="stock.stock_warehouse_shop0" model="stock.warehouse">
            <field name="buy_to_resupply" eval="True"/>
        </record>

        <function model="stock.warehouse" name="write">
          <value model="stock.warehouse" search="[('partner_id', '=', ref('stock.res_partner_company_1'))]"/>
          <value eval="{'buy_to_resupply': True}"/>
        </function>

	</data>

</odoo>
```

closes odoo/upgrade#2296

Signed-off-by: Christophe Simonis <chs@odoo.com>