[FIX] mail/17.0: reset model of mail.mail_activity_data_todo
In Odoo `17.0` new model `mail.activity.plan.template` is introduced.
It has a field `activity_type` pointing to `mail.activity.type`
with default `mail.mail_activity_data_todo`. This field is ensured to match
the model linked to the plan template
commit-hash=5704cce223be189865c2c10363c7b6b08b750eaa
path-to-file=/addons/mail/models/mail_activity_plan_template.py#L38

Therefore when the model of `mail.mail_activity_data_todo` is set (not NULL) the
above check may fail.

Since `mail.mail_activity_data_todo` is a standard record used in many places
we clear any model that could have been manually set on it.

Steps to reproduce:
1. Install mail, hr , hr_fleet in `16.0`
2. Change the res_model of `mail.mail_acitivity_data_todo` (not to hr.employee)
3. Upgrade the db to `17.0`

Failing upgrades:
upg-1395156
upg-1385925 and other 4 upgrades

tbg-1105

```
  File "/home/odoo/src/odoo/17.0/odoo/tools/convert.py", line 556, in _tag_root
    f(rec)
  File "/home/odoo/src/odoo/17.0/odoo/tools/convert.py", line 567, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
odoo.tools.convert.ParseError: while parsing /home/odoo/src/odoo/17.0/addons/hr_fleet/data/hr_fleet_data.xml:5
El tipo de actividad "To Do" no es compatible con el plan "Offboarding" porque está limitado al modelo "discuss.channel".

View error context:
'-no context-'
```

closes odoo/upgrade#5768

Signed-off-by: Christophe Simonis (chs) <chs@odoo.com>