[FIX] base/saas~16.5.1.3: Fix ValueError in server actions
After this commit 773dcb1, when converting server actions to code actions,
fields with the `evaluation_type == reference` are returning the record like
`res.company(1)`(in this case) instead of the ID.

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/17.0/odoo/http.py", line 2206, in __call__
    response = request._serve_db()
  File "/home/odoo/src/odoo/17.0/odoo/http.py", line 1782, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/home/odoo/src/odoo/17.0/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/home/odoo/src/odoo/17.0/odoo/http.py", line 1809, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/home/odoo/src/odoo/17.0/odoo/http.py", line 2013, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/home/odoo/src/odoo/17.0/odoo/addons/base/models/ir_http.py", line 221, in _dispatch
    result = endpoint(**request.params)
  File "/home/odoo/src/odoo/17.0/odoo/http.py", line 757, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/home/odoo/src/odoo/17.0/addons/web/controllers/dataset.py", line 24, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/17.0/addons/web/controllers/dataset.py", line 20, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/17.0/odoo/api.py", line 468, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/17.0/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/odoo/17.0/addons/web/models/models.py", line 73, in web_save
    self = self.create(vals)
  File "<decorator-gen-502>", line 2, in create
  File "/home/odoo/src/odoo/17.0/odoo/api.py", line 414, in _model_create_multi
    return create(self, [arg])
  File "/home/odoo/src/odoo/17.0/addons/base_automation/models/base_automation.py", line 728, in create
    automation._process(automation._filter_post(records, feedback=True))
  File "/home/odoo/src/odoo/17.0/addons/base_automation/models/base_automation.py", line 679, in _process
    action.with_context(**ctx).run()
  File "/home/odoo/src/odoo/17.0/odoo/addons/base/models/ir_actions.py", line 939, in run
    res = runner(run_self, eval_context=eval_context)
  File "/home/odoo/src/odoo/17.0/odoo/addons/base/models/ir_actions.py", line 771, in _run_action_code_multi
    safe_eval(self.code.strip(), eval_context, mode="exec", nocopy=True, filename=str(self))  # nocopy allows to return 'action'
  File "/home/odoo/src/odoo/17.0/odoo/tools/safe_eval.py", line 405, in safe_eval
    raise ValueError('%s: "%s" while evaluating\n%r' % (ustr(type(e)), ustr(e), expr))
ValueError: <class 'psycopg2.ProgrammingError'>: "can't adapt type 'res.company'" while evaluating
'new_record = env["project.project"].create({"name": "[" + record.x_name + "] OPS", "company_id": env[\'res.company\'].browse(1), "privacy_visibility": \'followers\', "allow_timesheets": \'True\',
"x_studio_projet_chantier": record.id, "x_studio_type": \'OPS\'})\n# link the new record to the current record\nrecord.write({"x_studio_chantier_default_project": new_record.id})'
```
upg-2392496
opw-4372518

closes odoo/upgrade#6929

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>