[FIX] l10n_be_hr_contract_salary/saas~18.3: update record in post script
tbg-2035

Before this PR[^1], `l10n_be_hr_contract_salary_mobility_budget` was
dependent to `l10n_be_hr_contract_salary` and it was
auto_install=`TRUE`. After that PR they have been merged.

During this script[^2], if the mobility budget module
was uninstalled:
1. Because the module `l10n_be_hr_contract_salary` module was not
   loaded yet, so we will be missing the record
   `l10n_be_hr_contract_salary.l10n_be_mobility_budget_amount`
2. So when the script above tries to update the record
   `l10n_be_hr_contract_salary.hr_contract_salary_resume_monthly_cash`
   from xml, it will fail because the missing record above is a new
   benefit.

For fixing the issue I have moved that script to `post` script.

Steps to reproduce:
1. Install `l10n_be_hr_contract_salary` in `saas~18.2`
2. Uninstall `l10n_be_hr_contract_salary_mobility_budget`
3. Upgrade to `saas~18.3`

You will face similar issue to this:

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/saas-18.3/odoo/tools/convert.py", line 554, in _tag_root
    f(rec)
  File "/home/odoo/src/odoo/saas-18.3/odoo/tools/convert.py", line 422, in _tag_record
    f_val = _eval_xml(self, field, env)
  File "/home/odoo/src/odoo/saas-18.3/odoo/tools/convert.py", line 101, in _eval_xml
    return safe_eval(a_eval, idref2)
  File "/home/odoo/src/odoo/saas-18.3/odoo/tools/convert.py", line 35, in safe_eval
    return s_eval(expr, ctx, nocopy=True)
  File "/home/odoo/src/odoo/saas-18.3/odoo/tools/safe_eval.py", line 411, in safe_eval
    raise ValueError('%r while evaluating\n%r' % (e, expr))
ValueError: ValueError('External ID not found in the system: l10n_be_hr_contract_salary.l10n_be_mobility_budget_amount') while evaluating
"[             (4, ref('l10n_be_hr_contract_salary.l10n_be_fuel_card')),             (4, ref('l10n_be_hr_contract_salary.l10n_be_yearly_commission')),             (4, ref('l10n_be_hr_contract_salary.l10n_be_meal_vouchers')),             (4, ref('l10n_be_hr_contract_salary.l10n_be_mobility_budget_amount')),         ]"

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/saas-18.3/odoo/service/server.py", line 1396, in preload_registries
    registry = Registry.new(dbname, update_module=update_module, install_modules=config['init'], upgrade_modules=config['update'])
  File "<decorator-gen-6>", line 2, in new
  File "/home/odoo/src/odoo/saas-18.3/odoo/tools/func.py", line 83, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/saas-18.3/odoo/orm/registry.py", line 167, in new
    load_modules(
  File "/home/odoo/src/odoo/saas-18.3/odoo/modules/loading.py", line 450, in load_modules
    load_module_graph(
  File "/home/odoo/src/odoo/saas-18.3/odoo/modules/loading.py", line 181, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/home/odoo/src/odoo/saas-18.3/odoo/modules/migration.py", line 220, in migrate_module
    exec_script(self.cr, installed_version, pyfile, pkg.name, stage, stageformat[stage] % version)
  File "/home/odoo/src/odoo/saas-18.3/odoo/modules/migration.py", line 257, in exec_script
    mod.migrate(cr, installed_version)
  File "/tmp/tmpd1tq7_cw/migrations/l10n_be_hr_contract_salary/saas~18.3.1.0/pre-migrate.py", line 11, in migrate
    util.if_unchanged(
  File "/tmp/tmpd1tq7_cw/migrations/util/records.py", line 643, in if_unchanged
    callback(cr, xmlid, **kwargs)
  File "/tmp/tmpd1tq7_cw/migrations/util/records.py", line 1055, in update_record_from_xml
    __update_record_from_xml(
  File "/tmp/tmpd1tq7_cw/migrations/util/records.py", line 1204, in __update_record_from_xml
    importer.parse(new_root, **kw)
  File "/home/odoo/src/odoo/saas-18.3/odoo/tools/convert.py", line 611, in parse
    self._tag_root(de)
  File "/home/odoo/src/odoo/saas-18.3/odoo/tools/convert.py", line 554, in _tag_root
    f(rec)
  File "/home/odoo/src/odoo/saas-18.3/odoo/tools/convert.py", line 567, in _tag_root
    raise ParseError('while parsing %s:%s, somewhere inside\n%s' % (
odoo.tools.convert.ParseError: while parsing None:55, somewhere inside
<record id="hr_contract_salary_resume_monthly_cash" model="hr.contract.salary.resume">
        <field name="benefit_ids" eval="[             (4, ref('l10n_be_hr_contract_salary.l10n_be_fuel_card')),             (4, ref('l10n_be_hr_contract_salary.l10n_be_yearly_commission')),             (4, ref('l10n_be_hr_contract_salary.l10n_be_meal_vouchers')),             (4, ref('l10n_be_hr_contract_salary.l10n_be_mobility_budget_amount')),         ]"/>
        </record>
```
[^1]: https://github.com/odoo/enterprise/pull/81700
[^2]: https://github.com/odoo/upgrade/blob/8506f12279ad878de0a3821c8dd69065eb27d2c5/migrations/l10n_be_hr_contract_salary/saas~18.3.1.0/pre-migrate.py#L11
[^3]: https://github.com/odoo/enterprise/blob/b2b599340f0c48295e78d9136b2e08cdabf4ecf4/l10n_be_hr_contract_salary/data/hr_contract_salary_resume_data.xml#L63

closes odoo/upgrade#7802

Signed-off-by: Christophe Simonis (chs) <chs@odoo.com>