[FIX] base/saas~16.5: restore views for installed modules only
Blindly restoring any view may cause issues if the module was
uninstalled and some leftover views remain.

```
Traceback (most recent call last):
...
    new_archs = fix_archs(info)
  File "/tmp/tmp2s4i3c2w/migrations/base/saas~16.5.1.3/end-01-attrs-views.py", line 586, in fix_archs
    util.update_record_from_xml(cr, f"{md.module}.{md.name}")
  File "/tmp/tmp2s4i3c2w/migrations/util/records.py", line 721, in update_record_from_xml
    __update_record_from_xml(
  File "/tmp/tmp2s4i3c2w/migrations/util/records.py", line 845, in __update_record_from_xml
    importer.parse(new_root, **kw)
  File "/home/odoo/src/odoo/17.0/odoo/tools/convert.py", line 613, in parse
    self._tag_root(de)
  File "/home/odoo/src/odoo/17.0/odoo/tools/convert.py", line 556, in _tag_root
    f(rec)
  File "/home/odoo/src/odoo/17.0/odoo/tools/convert.py", line 569, in _tag_root
    raise ParseError('while parsing %s:%s, somewhere inside\n%s' % (
odoo.tools.convert.ParseError: while parsing None:260, somewhere inside
<record model="ir.ui.view" id="product_form_view_procurement_button">
...
2023-12-06 16:37:07,469 35 CRITICAL db_1180614 odoo.service.server: Failed to initialize database `db_1180614`.
...
  File "/home/odoo/src/odoo/17.0/odoo/addons/base/models/ir_model.py", line 2163, in _xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: stock.action_product_replenish
```

```
1180614_afu=> select id,name,latest_version,state,author from ir_module_module where name='stock'
+-----+-------+----------------+-------------+-----------+
| id  | name  | latest_version | state       | author    |
|-----+-------+----------------+-------------+-----------|
| 731 | stock | <null>         | uninstalled | Odoo S.A. |
+-----+-------+----------------+-------------+-----------+
1180614_afu=> select module,name,res_id from ir_model_data where name='product_form_view_procurement_button'
+--------+--------------------------------------+--------+
| module | name                                 | res_id |
|--------+--------------------------------------+--------|
| stock  | product_form_view_procurement_button | 1459   |
+--------+--------------------------------------+--------+
1180614_afu=> select id,name from ir_ui_view where id=1459
+------+-----------------------------+
| id   | name                        |
|------+-----------------------------|
| 1459 | product.product.procurement |
+------+-----------------------------+
```

upg-1180614

closes odoo/upgrade#5488

Signed-off-by: Christophe Simonis (chs) <chs@odoo.com>