[FIX] sale_stock_renting/0.0.0: avoid to create duplicate rental moves
as we are always trigger `post_init_hook` for demo rental product
during upgrade also, that will create duplicate moves for all
the ongoing rental sale orders that was risky and wrong.
so need to revert the code.

the purpose of the commit has been resolved by this :
https://github.com/odoo/upgrade/commit/f3c038f169bbd2087dd86cf5e46f781d8512b727
as we are skipping test case for demo data so no
more inconsistency for on hand qty.

upg-1215287

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/17.0/odoo/service/server.py", line 1302, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "<decorator-gen-16>", line 2, in new
  File "/home/odoo/src/odoo/17.0/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/17.0/odoo/modules/registry.py", line 113, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/17.0/odoo/modules/loading.py", line 476, in load_modules
    processed_modules += load_marked_modules(env, graph,
  File "/home/odoo/src/odoo/17.0/odoo/modules/loading.py", line 364, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/odoo/src/odoo/17.0/odoo/modules/loading.py", line 232, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/home/odoo/src/odoo/17.0/odoo/modules/migration.py", line 240, in migrate_module
    migrate(self.cr, installed_version)
  File "/tmp/tmpy4d5t7kc/migrations/sale_stock_renting/0.0.0/post-migrate.py", line 14, in migrate
    _ensure_rental_stock_moves_consistency(env)
  File "/home/odoo/src/enterprise/17.0/sale_stock_renting/__init__.py", line 23, in _ensure_rental_stock_moves_consistency
    line.with_company(line.company_id)._move_qty(
  File "/home/odoo/src/enterprise/17.0/sale_stock_renting/models/sale_order_line.py", line 232, in _move_qty
    rental_stock_move._action_done()
  File "/home/odoo/src/enterprise/17.0/sale_stock_renting/models/stock_move.py", line 52, in _action_done
    res = super()._action_done(cancel_backorder=cancel_backorder)
  File "/home/odoo/src/odoo/17.0/addons/stock_account/models/stock_move.py", line 262, in _action_done
    res = super(StockMove, self)._action_done(cancel_backorder=cancel_backorder)
  File "/home/odoo/src/odoo/17.0/addons/stock/models/stock_move.py", line 1848, in _action_done
    moves_todo.mapped('move_line_ids').sorted()._action_done()
  File "/home/odoo/src/odoo/17.0/addons/stock/models/stock_move_line.py", line 566, in _action_done
    raise UserError(_('You need to supply a Lot/Serial Number for product: \n - ') +
odoo.exceptions.UserError: Debe proporcionar un número de lote / serie para el producto:
 - test
```

closes odoo/upgrade#5527

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>