[FIX] base@0.0.0: do not copy translation when copying view source
When we override a view because its no longer valid and its a
standard view which has been manually modified by the customer,
we create a copy, so the user can look for what was changed.

In some cases, the copy of the translations crashed
the upgrade process:

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/11.0/odoo/addons/base/ir/ir_ui_view.py", line 1376, in _validate_module_views
    self.browse(vid)._check_xml()
  File "/home/odoo/src/odoo/11.0/odoo/addons/base/maintenance/migrations/base/0.0.0/pre-models-ir_ui_view.py", line 45, in _check_xml
    if self._migrate_fix_views():
  File "/home/odoo/src/odoo/11.0/odoo/addons/base/maintenance/migrations/base/0.0.0/pre-models-ir_ui_view.py", line 94, in _migrate_fix_views
    view_copy = view.copy({'active': False, 'name': '%s (Copy created during migration)' % view.name})
  File "/home/odoo/src/odoo/11.0/odoo/models.py", line 3993, in copy
    self.with_context(from_copy_translation=True).copy_translations(new)
  File "/home/odoo/src/odoo/11.0/odoo/models.py", line 3975, in copy_translations
    Translation.create(vals)
  File "/home/odoo/src/odoo/11.0/odoo/addons/base/ir/ir_translation.py", line 576, in create
    record = super(IrTranslation, self.sudo()).create(vals).with_env(self.env)
  File "/home/odoo/src/odoo/11.0/odoo/addons/base/maintenance/migrations/base/0.0.0/pre-models-match_uniq.py", line 21, in create
    return super(Base, self).create(values)
  File "/home/odoo/src/odoo/11.0/odoo/models.py", line 3418, in create
    record = self.browse(self._create(old_vals))
  File "/home/odoo/src/odoo/11.0/odoo/models.py", line 3571, in _create
    self._validate_fields(vals)
  File "/home/odoo/src/odoo/11.0/odoo/models.py", line 1038, in _validate_fields
    check(self)
  File "/home/odoo/src/odoo/11.0/odoo/addons/base/ir/ir_translation.py", line 572, in _check_value
    raise ValidationError(_("Translation is not valid:\n%s") % val)
odoo.exceptions.ValidationError: ('Translation is not valid:\n<strong></strong>', None)
```

We therefore avoid to copy the translations,
which are not relevant anyway.