[FIX] mail@saas~14.5: ensure `mail.channel_partner_general_channel_for_admin`
When upgrading a demo database from 13.0 to 15.0,
the sql constraint `mail_channel_partner_partner_unique`
on `mail_channel_partner` raises when attempting to load
`mail.channel_partner_general_channel_for_admin` because
the record to which it's linked gets deleted by
https://github.com/odoo/upgrade/blob/321431177298adb9b80b01a3640494bd1e177ba5/migrations/mail/saas~14.5.1.5/pre-migrate.py#L38-L47
and therefore as the xmlid is linked to a non-existing record,
the xmlid gets deleted automatically by the ORM:
`2021-10-01 14:06:12,412 50 INFO dle_13.0_15.0 odoo.models.unlink: User #1 deleted ir.model.data records with IDs: [14498]`
and then the ORM tries to create the record again when loading the given xml file,
and there is another record in the table with the same partner_id/channel_id pair:
```
dle_13.0_14.0=> select * from mail_channel_partner;
 id | custom_channel_name | partner_id | channel_id | fetched_message_id | seen_message_id | fold_state | is_minimized | is_pinned | create_uid |        create_date         | write_uid |         write_date
----+---------------------+------------+------------+--------------------+-----------------+------------+--------------+-----------+------------+----------------------------+-----------+----------------------------
  1 |                     |          2 |          1 |                    |                 |            |              |           |            |                            |           |
  2 |                     |          3 |          1 |                    |                 |            |              |           |            |                            |           |
  3 |                     |          3 |          1 |                  1 |               1 | open       |              | t         |          1 | 2021-10-01 14:15:19.216354 |         1 | 2021-10-01 14:15:19.216354
(3 rows)
```

```
2021-10-01 14:06:12,404 50 INFO dle_13.0_15.0 odoo.modules.loading: loading mail/data/mail_channel_data.xml
2021-10-01 14:06:12,412 50 INFO dle_13.0_15.0 odoo.models.unlink: User #1 deleted ir.model.data records with IDs: [14498]
2021-10-01 14:06:12,414 50 ERROR dle_13.0_15.0 odoo.sql_db: bad query: INSERT INTO "mail_channel_partner" ("id", "channel_id", "create_date", "create_uid", "fetched_message_id", "fold_state", "is_pinned", "last_interest_dt", "partner_id", "seen_message_id", "write_date", "write_uid") VALUES (nextval('mail_channel_partner_id_seq'), 1, '2021-10-01 14:06:11.972584', 1, 1, 'open', true, '2021-10-01 14:06:12', 3, 1, '2021-10-01 14:06:11.972584', 1) RETURNING id
ERROR: duplicate key value violates unique constraint "mail_channel_partner_partner_unique"
DETAIL:  Key (channel_id, partner_id)=(1, 3) already exists.

2021-10-01 14:06:12,419 50 WARNING dle_13.0_15.0 odoo.modules.loading: Transient module states were reset
2021-10-01 14:06:12,420 50 ERROR dle_13.0_15.0 odoo.modules.registry: Failed to load registry
2021-10-01 14:06:12,420 50 CRITICAL dle_13.0_15.0 odoo.service.server: Failed to initialize database `dle_13.0_15.0`.

Traceback (most recent call last):
  File "/home/odoo/src/odoo/15.0/odoo/tools/convert.py", line 680, in _tag_root
    f(rec)
  File "/home/odoo/src/odoo/15.0/odoo/tools/convert.py", line 583, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/home/odoo/src/odoo/15.0/odoo/models.py", line 4399, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/home/odoo/src/odoo/15.0/odoo/models.py", line 4328, in _load_records_create
    return self.create(values)
  File "<decorator-gen-140>", line 2, in create
  File "/home/odoo/src/odoo/15.0/odoo/api.py", line 410, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/15.0/addons/mail/models/mail_channel_partner.py", line 67, in create
    return super(ChannelPartner, self).create(vals_list)
  File "<decorator-gen-118>", line 2, in create
  File "/home/odoo/src/odoo/15.0/odoo/api.py", line 391, in _model_create_single
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/home/odoo/src/odoo/15.0/odoo/api.py", line 391, in <genexpr>
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/home/odoo/src/upgrade/migrations/base/0.0.0/pre-models-match_uniq.py", line 22, in create
    return super(Base, self).create(values)
  File "<decorator-gen-67>", line 2, in create
  File "/home/odoo/src/odoo/15.0/odoo/api.py", line 409, in _model_create_multi
    return create(self, [arg])
  File "/home/odoo/src/odoo/15.0/odoo/addons/base/models/ir_fields.py", line 613, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "/home/odoo/src/odoo/15.0/odoo/api.py", line 410, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/15.0/odoo/models.py", line 4064, in create
    records = self._create(data_list)
  File "/home/odoo/src/odoo/15.0/odoo/models.py", line 4162, in _create
    cr.execute(query, params)
  File "<decorator-gen-3>", line 2, in execute
  File "/home/odoo/src/odoo/15.0/odoo/sql_db.py", line 89, in check
    return f(self, *args, **kwargs)
  File "/home/odoo/src/odoo/15.0/odoo/sql_db.py", line 310, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "mail_channel_partner_partner_unique"
DETAIL:  Key (channel_id, partner_id)=(1, 3) already exists.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/15.0/odoo/service/server.py", line 1246, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/odoo/src/odoo/15.0/odoo/modules/registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/15.0/odoo/modules/loading.py", line 472, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/home/odoo/src/odoo/15.0/odoo/modules/loading.py", line 365, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/odoo/src/odoo/15.0/odoo/modules/loading.py", line 222, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/home/odoo/src/odoo/15.0/odoo/modules/loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/home/odoo/src/odoo/15.0/odoo/tools/convert.py", line 745, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/home/odoo/src/odoo/15.0/odoo/tools/convert.py", line 811, in convert_xml_import
    obj.parse(doc.getroot())
  File "/home/odoo/src/odoo/15.0/odoo/tools/convert.py", line 731, in parse
    self._tag_root(de)
  File "/home/odoo/src/odoo/15.0/odoo/tools/convert.py", line 680, in _tag_root
    f(rec)
  File "/home/odoo/src/odoo/15.0/odoo/tools/convert.py", line 697, in _tag_root
    )) from e
odoo.tools.convert.ParseError: while parsing /home/odoo/src/odoo/15.0/addons/mail/data/mail_channel_data.xml:21, somewhere inside
<record model="mail.channel.partner" id="channel_partner_general_channel_for_admin">
            <field name="partner_id" ref="base.partner_admin"/>
            <field name="channel_id" ref="mail.channel_all_employees"/>
            <field name="fetched_message_id" ref="mail.module_install_notification"/>
            <field name="seen_message_id" ref="mail.module_install_notification"/>
        </record>
```

closes odoo/upgrade#2885

Signed-off-by: Christophe Simonis <chs@odoo.com>