[FIX] hr_payroll_account/0.0.0: set up journals
In the customer database, the XML ID hr_payroll_account_journal is not present
During the upgrade process, when the module l10n_pk_hr_payroll_account is
loaded, the _load_payroll_accounts function attempts to load
{}_hr_payroll_account_journal. Since this XML ID doesn't exist in the customer
database, it sets up journals for the existing companies.

[here](https://github.com/odoo/enterprise/pull/62196/files#diff-d46c020e26a7d70c26eb61321bb74d204408ee10383c5c40adcfb91b736040a1R4)
[here](https://github.com/odoo/enterprise/blob/saas-17.4/hr_payroll_account/models/account_chart_template.py#L51)
[here](https://github.com/odoo/enterprise/blob/saas-17.4/hr_payroll_account/__init__.py#L11-L38)

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/saas-17.4/odoo/tools/cache.py", line 103, in lookup
    r = d[key]
  File "<decorator-gen-5>", line 2, in __getitem__
  File "/home/odoo/src/odoo/saas-17.4/odoo/tools/func.py", line 84, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/saas-17.4/odoo/tools/lru.py", line 34, in __getitem__
    a = self.d[obj]
KeyError: ('ir.model.data', <function IrModelData._xmlid_lookup at 0x7f936cce0280>, 'account.1_hr_payroll_account_journal')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/saas-17.4/odoo/tools/convert.py", line 559, in _tag_root
    f(rec)
  File "/home/odoo/src/odoo/saas-17.4/odoo/tools/convert.py", line 280, in _tag_function
    _eval_xml(self, rec, env)
  File "/home/odoo/src/odoo/saas-17.4/odoo/tools/convert.py", line 205, in _eval_xml
    return odoo.api.call_kw(model, method_name, args, kwargs)
  File "/home/odoo/src/odoo/saas-17.4/odoo/api.py", line 459, in call_kw
    result = getattr(recs, name)(*args, **kwargs)
  File "/home/odoo/src/enterprise/saas-17.4/hr_payroll_account/models/account_chart_template.py", line 23, in _load_payroll_accounts
    config_method(companies)
  File "/home/odoo/src/enterprise/saas-17.4/l10n_pk_hr_payroll_account/models/account_chart_template.py", line 21, in _configure_payroll_account_pk
    self._configure_payroll_account(
  File "/home/odoo/src/enterprise/saas-17.4/hr_payroll_account/models/account_chart_template.py", line 51, in _configure_payroll_account
    journal = self.ref('hr_payroll_account_journal')
  File "/home/odoo/src/odoo/saas-17.4/addons/account/models/chart_template.py", line 1051, in ref
    or self.env.ref(f"account.{self.env.company.parent_ids[0].id}_{xmlid}", raise_if_not_found)
  File "/home/odoo/src/odoo/saas-17.4/odoo/api.py", line 584, in ref
    res_model, res_id = self['ir.model.data']._xmlid_to_res_model_res_id(
  File "/home/odoo/src/odoo/saas-17.4/odoo/addons/base/models/ir_model.py", line 2229, in _xmlid_to_res_model_res_id
    return self._xmlid_lookup(xmlid)
  File "<decorator-gen-44>", line 2, in _xmlid_lookup
  File "/home/odoo/src/odoo/saas-17.4/odoo/tools/cache.py", line 110, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/odoo/src/odoo/saas-17.4/odoo/addons/base/models/ir_model.py", line 2222, in _xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: account.1_hr_payroll_account_journal

upg-2020742
tbg-1494
```

closes odoo/upgrade#6477

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>