[FIX] base/0.0.0: Fix validation error while checking account
From 16.4 super users also can have access
so according that while running during upgrade
super user won't rights to all companies those db are coming
from 16.0 and migrated already.So assigning according to
this commit
https://github.com/odoo/odoo/commit/c71b571b68933796e32329660ba55b2ec8721f2c
so while getting companies
https://github.com/odoo/odoo/blob/2bd88ca0adfe63fdbbf545777d51fc9a99c4ade6/addons/account/models/account_account.py#L166
ids for super user it would have all company rights.
So it can search records correctly during upgrade.

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/18.0/odoo/service/server.py", line 1305, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "<decorator-gen-13>", line 2, in new
  File "/home/odoo/src/odoo/18.0/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/18.0/odoo/modules/registry.py", line 131, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/18.0/odoo/modules/loading.py", line 513, in load_modules
    migrations.migrate_module(package, 'end')
  File "/home/odoo/src/odoo/18.0/odoo/modules/migration.py", line 254, in migrate_module
    mod.migrate(self.cr, installed_version)
  File "/home/odoo/src/odoo/18.0/addons/l10n_es/migrations/5.3/end-migrate_update_taxes.py", line 26, in migrate
    env['account.chart.template'].try_loading(company.chart_template, company)
  File "/home/odoo/src/odoo/18.0/addons/account/models/chart_template.py", line 160, in try_loading
    return self._load(template_code, company, install_demo)
  File "/home/odoo/src/odoo/18.0/addons/account/models/chart_template.py", line 221, in _load
    self._post_load_data(template_code, company, template_data)
  File "/home/odoo/src/enterprise/18.0/hr_payroll_account/models/account_chart_template.py", line 17, in _post_load_data
    super()._post_load_data(template_code, company, template_data)
  File "/home/odoo/src/enterprise/18.0/account_reports/models/chart_template.py", line 10, in _post_load_data
    super()._post_load_data(template_code, company, template_data)
  File "/home/odoo/src/odoo/18.0/addons/stock_account/models/account_chart_template.py", line 12, in _post_load_data
    super()._post_load_data(template_code, company, template_data)
  File "/home/odoo/src/odoo/18.0/addons/account/models/chart_template.py", line 637, in _post_load_data
    company.get_unaffected_earnings_account()
  File "/home/odoo/src/odoo/18.0/addons/account/models/company.py", line 738, in get_unaffected_earnings_account
    return self.env['account.account']._load_records([
  File "/home/odoo/src/odoo/18.0/odoo/models.py", line 5449, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/home/odoo/src/odoo/18.0/odoo/models.py", line 5353, in _load_records_create
    records = self.create(vals_list)
  File "<decorator-gen-237>", line 2, in create
  File "/home/odoo/src/odoo/18.0/odoo/api.py", line 480, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/18.0/addons/account/models/account_account.py", line 985, in create
    )).create(vals_list_for_company)
  File "<decorator-gen-139>", line 2, in create
  File "/home/odoo/src/odoo/18.0/odoo/api.py", line 480, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/18.0/addons/mail/models/mail_thread.py", line 263, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-119>", line 2, in create
  File "/home/odoo/src/odoo/18.0/odoo/api.py", line 480, in _model_create_multi
    return create(self, arg)
  File "/tmp/tmpjk1n7c98/migrations/util/orm.py", line 244, in wrapper
    return f(*args, **kwargs)
  File "/tmp/tmpjk1n7c98/migrations/base/0.0.0/pre-models-match_uniq.py", line 25, in create
    return super().create(vals_list)
  File "<decorator-gen-31>", line 2, in create
  File "/home/odoo/src/odoo/18.0/odoo/api.py", line 480, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/18.0/odoo/models.py", line 4957, in create
    records = self._create(data_list)
  File "/home/odoo/src/odoo/18.0/odoo/models.py", line 5215, in _create
    records._validate_fields(name for data in data_list for name in data['stored'])
  File "/home/odoo/src/odoo/18.0/odoo/models.py", line 1599, in _validate_fields
    check(self)
  File "/home/odoo/src/odoo/18.0/addons/account/models/account_account.py", line 42, in _check_account_type_unique_current_year_earning
    raise ValidationError(_('You cannot have more than one account with "Current Year Earnings" as type. (accounts: %s)', [a.code for a in account_unaffected_earnings]))
odoo.exceptions.ValidationError: You cannot have more than one account with "Current Year Earnings" as type. (accounts: ['129000', False])
```
opw-4371266
upg-2340112

Part-of: odoo/upgrade#6914
Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>