[FIX] account/saas~18.1: At least one invoice report
tbg-1783

The new compute method for invoice reports
https://github.com/odoo/odoo/blob/2efc9f0c24b1a7a7e5a72653181c8a491bf46207/addons/account/models/partner.py#L497
expects at least one available invoice report, however many DBs don't
have one mostly because the record was set to noupdate and the field
`is_invoice_report` was only added in 18.0.

We update the record `account.account_invoices`
https://github.com/odoo/odoo/blob/2efc9f0c24b1a7a7e5a72653181c8a491bf46207/addons/account/views/account_report.xml#L5
so that it can be used, since it was intended as the template.

```
('account.menu_account_customer', 122, 'Accounting > Customers > Customers', 261):
 Traceback (most recent call last):
   File "/tmp/tmpugwnt2rj/migrations/base/tests/test_mock_crawl.py", line 259, in crawl_menu
    self.mock_action(action_vals)
   File "/tmp/tmpugwnt2rj/migrations/base/tests/test_mock_crawl.py", line 272, in mock_action
    return self.mock_act_window(action)
   File "/tmp/tmpugwnt2rj/migrations/base/tests/test_mock_crawl.py", line 432, in mock_act_window
    mock_method(model, view, fields_list, domain, group_by)
   File "/tmp/tmpugwnt2rj/migrations/base/tests/test_mock_crawl.py", line 463, in mock_view_form
    [data] = record.read(fields_list)
   File "/home/odoo/src/odoo/saas-18.1/odoo/orm/models.py", line 3612, in read
    return self._read_format(fnames=fields, load=load)
   File "/home/odoo/src/odoo/saas-18.1/odoo/orm/models.py", line 3842, in _read_format
    vals[name] = convert(record[name], record, use_display_name)
   File "/home/odoo/src/odoo/saas-18.1/odoo/orm/models.py", line 6898, in __getitem__
    return self._fields[key].__get__(self)
   File "/home/odoo/src/odoo/saas-18.1/odoo/orm/fields_relational.py", line 813, in __get__
    return super().__get__(records, owner)
   File "/home/odoo/src/odoo/saas-18.1/odoo/orm/fields_relational.py", line 40, in __get__
    return super().__get__(records, owner)
   File "/home/odoo/src/odoo/saas-18.1/odoo/orm/fields.py", line 1441, in __get__
    self.compute_value(recs)
   File "/home/odoo/src/odoo/saas-18.1/odoo/orm/fields.py", line 1607, in compute_value
    records._compute_field_value(self)
   File "/home/odoo/src/odoo/saas-18.1/addons/mail/models/mail_thread.py", line 441, in _compute_field_value
    return super()._compute_field_value(field)
   File "/home/odoo/src/odoo/saas-18.1/odoo/orm/models.py", line 5056, in _compute_field_value
    determine(field.compute, self)
   File "/home/odoo/src/odoo/saas-18.1/odoo/orm/fields.py", line 70, in determine
    return needle(*args)
   File "/home/odoo/src/odoo/saas-18.1/addons/account/models/partner.py", line 506, in _compute_available_invoice_template_pdf_report_ids
    raise UserError(_("There is no template that applies to invoices."))
 odoo.exceptions.UserError: There is no template that applies to invoices.
```

closes odoo/upgrade#7419

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>