[FIX] l10n_ca/saas~16.4.1.0: update value of chart template 'l10n_ca'
The selection field named 'chart_template' value was not updated,
Therefore assigning value "ca_2023" instead of "ca".
For the Canada localization
https://github.com/odoo/odoo/commit/b88a846866a3b262d2417b5811110bce9451f8f6
Ref- addons/l10n_ca/demo/demo_company.xml

**Reproduce the error:**
Create a database with a base version of 16.3, install the Canada localization,
perform a migration to version 17.0 and then click on the settings.
```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/17.0/odoo/http.py", line 2150, in __call__
    response = request._serve_db()
  File "/home/odoo/src/odoo/17.0/odoo/http.py", line 1722, in _serve_db
    return service_model.retrying(self._serve_ir_http, self.env)
  File "/home/odoo/src/odoo/17.0/odoo/service/model.py", line 133, in retrying
    result = func()
  File "/home/odoo/src/odoo/17.0/odoo/http.py", line 1749, in _serve_ir_http
    response = self.dispatcher.dispatch(rule.endpoint, args)
  File "/home/odoo/src/odoo/17.0/odoo/http.py", line 1953, in dispatch
    result = self.request.registry['ir.http']._dispatch(endpoint)
  File "/home/odoo/src/odoo/17.0/odoo/addons/base/models/ir_http.py", line 222, in _dispatch
    result = endpoint(**request.params)
  File "/home/odoo/src/odoo/17.0/odoo/http.py", line 722, in route_wrapper
    result = endpoint(self, *args, **params_ok)
  File "/home/odoo/src/odoo/17.0/addons/web/controllers/dataset.py", line 24, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/home/odoo/src/odoo/17.0/addons/web/controllers/dataset.py", line 20, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/home/odoo/src/odoo/17.0/odoo/api.py", line 466, in call_kw
    result = _call_kw_multi(method, model, args, kwargs)
  File "/home/odoo/src/odoo/17.0/odoo/api.py", line 453, in _call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/odoo/17.0/addons/web/models/models.py", line 1029, in onchange
    record._update_cache(changed_values)
  File "/home/odoo/src/odoo/17.0/odoo/models.py", line 5982, in _update_cache
    value = field.convert_to_cache(value, self, validate)
  File "/home/odoo/src/odoo/17.0/odoo/fields.py", line 2817, in convert_to_cache
    raise ValueError("Wrong value for %s: %r" % (self, value))
ValueError: Wrong value for res.config.settings.chart_template: 'ca'
```
**Before fix:**
```
test_17.0=> select name,chart_template from res_company;
    name     | chart_template
-------------+----------------
 CA Company  | ca
(1 rows)
```
**After fix:**
```
test_17.0=> select name,chart_template from res_company;
    name     | chart_template
-------------+----------------
 CA Company  | ca_2023
(1 rows)
```
OPW- 3664328,3668689

closes odoo/upgrade#5525

Signed-off-by: Christophe Simonis (chs) <chs@odoo.com>