[FIX] tests: patch `_unknown` model to have `id` in >=15.0
The `_unknown` model lost its `id` field in 15.0:
```
In [1]: odoo.release.version
Out[1]: '15.0+e'

In [2]: type(self.env["_unknown"])._fields
Out[2]: {}
```
vs (in 14.0):
```
In [1]: odoo.release.version
Out[1]: '14.0+e'

In [2]: type(self.env["_unknown"])._fields
Out[2]:
OrderedDict([('id', _unknown.id),
             ('display_name', _unknown.display_name),
             ('__last_update', _unknown.__last_update)])
```

This may cause a traceback on
https://github.com/odoo/odoo/blob/14e9f3d5e83909d4a61aded0c125c6330379a756/odoo/fields.py#L3406
since `get_id` tries to access the `id` of `many2one` an `_unknown`
record. This makes the crawler fail during the test checks in 15.0 but
not on <15.0.

The `_unknown` relation seem to come from previous migrations
https://github.com/odoo/upgrade/blob/81e77ef281384b568bda001c2f46c4c0df77ac36/migrations/util/models.py#L159
for example on upg-166232
```
166232_afu=> select id,name,model,relation,ttype from ir_model_fields where model='shipping.label.document' and name='shipping_id'
+------+-------------+-------------------------+------------+----------+
| id   | name        | model                   | relation   | ttype    |
|------+-------------+-------------------------+------------+----------|
| 7601 | shipping_id | shipping.label.document | _unknown   | many2one |
+------+-------------+-------------------------+------------+----------+
```
Example traceback:
```
('printnode_base.menu_shipping_labels', 300, 'PrintNode > Shipping Labels', 553):
 Traceback (most recent call last):
   File "/tmp/tmp7f9lp9v6/migrations/base/tests/test_mock_crawl.py", line 182, in crawl_menu
    self.mock_action(action_vals)
   File "/tmp/tmp7f9lp9v6/migrations/base/tests/test_mock_crawl.py", line 293, in mock_action
    mock_method(model, view, fields_list, domain, group_by)
   File "/tmp/tmp7f9lp9v6/migrations/base/tests/test_mock_crawl.py", line 408, in mock_view_tree
    self.mock_web_search_read(model, view, [domain], fields_list)
   File "/tmp/tmp7f9lp9v6/migrations/base/tests/test_mock_crawl.py", line 442, in mock_web_search_read
    data = model.search_read(domain=domain, fields=fields_list, limit=80)
   File "/home/odoo/src/odoo/15.0/odoo/models.py", line 5047, in search_read
    result = records.read(fields, **read_kwargs)
   File "/home/odoo/src/odoo/15.0/odoo/models.py", line 3225, in read
    self._read(stored_fields)
   File "/home/odoo/src/odoo/15.0/odoo/models.py", line 3371, in _read
    field.read(fetched)
   File "/home/odoo/src/odoo/15.0/odoo/fields.py", line 3406, in read
    group[get_id(line[inverse])].append(line.id)
   File "/home/odoo/src/odoo/15.0/odoo/fields.py", line 3398, in <lambda>
    get_id = (lambda rec: rec.id) if inverse_field.type == 'many2one' else int
 AttributeError: '_unknown' object has no attribute 'id'
```

upg-166232
upg-105512

closes odoo/upgrade#3454

Signed-off-by: Christophe Simonis <chs@odoo.com>