[FIX] stock_enterprise/16.0: removed action grid
In v16 the grid view for report.stock.quantity is removed.
but custom actions defined with grid  mode no longer work
since grid view for report.stock.quantity removed,
It doesn't support a default grid view.

upg-516160

```
 select res_model,view_mode,view_id from ir_act_window where id=666;
       res_model       | view_mode  | view_id
-----------------------+------------+---------
 report.stock.quantity | graph,grid |
(1 row)
select name,module from ir_model_data where module='stock_enterprise' and res_id in (select id from ir_ui_view where type='grid' and model='report.stock.quantity');
          name          |      module
------------------------+------------------
 stock_report_view_grid | stock_enterprise
(1 row)

Traceback (most recent call last):
   File "/tmp/tmpqp6l3i9a/migrations/base/tests/test_mock_crawl.py", line 220, in crawl_menu
    self.mock_action(action_vals)
   File "/tmp/tmpqp6l3i9a/migrations/base/tests/test_mock_crawl.py", line 304, in mock_action
    views = get_views(
   File "/home/odoo/src/odoo/16.0/odoo/addons/base/models/ir_ui_view.py", line 2480, in get_views
    result['views'] = {
   File "/home/odoo/src/odoo/16.0/odoo/addons/base/models/ir_ui_view.py", line 2481, in <dictcomp>
    v_type: self.get_view(
   File "/home/odoo/src/odoo/16.0/odoo/addons/base/models/ir_ui_view.py", line 2665, in get_view
    result = dict(self._get_view_cache(view_id, view_type, **options))
   File "<decorator-gen-48>", line 2, in _get_view_cache
   File "/home/odoo/src/odoo/16.0/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
   File "/home/odoo/src/odoo/16.0/odoo/addons/base/models/ir_ui_view.py", line 2625, in _get_view_cache
    arch, view = self._get_view(view_id, view_type, **options)
   File "/home/odoo/src/odoo/16.0/addons/web/models/models.py", line 245, in _get_view
    arch, view = super()._get_view(view_id, view_type, **options)
   File "/home/odoo/src/odoo/16.0/odoo/addons/base/models/ir_ui_view.py", line 2579, in _get_view
    raise UserError(_("No default view of type '%s' could be found !", view_type))
 odoo.exceptions.UserError: لا يوجد إيجاد طريقة عرض افتراضية من النوع 'grid'!

```

closes odoo/upgrade#4317

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>