[FIX] base/0.0.0: set right model for attachment
There is a bug in 15.0 that is assigning the attachment to the
transient model. Specifically this line is wrong:
https://github.com/odoo/enterprise/blob/fd519260d93e76bafd5de08acf4bbfa6450e63f2/sign/wizard/sign_duplicate_template_with_pdf.py#L42

Attempt to patch the issue in odoo/enterprise#80751

The issue at upgrade is when cleaning transients. We would clean the
attachments for `sign.duplicate.template.pdf` but those attachments are
actually used by `sign.template`. Thus the templates are being removed
since its field `attachment_id` has cascade removal. We got errors only
in the cases where there is _also_ a sign request for the template that
blocks the removal.

```
2025-02-28 06:51:15,713 25 INFO db_2544532 odoo.upgrade.util: Cleaning references to transient models from ir_attachment
2025-02-28 06:51:15,818 25 ERROR ? odoo.sql_db: bad query: DELETE FROM "ir_attachment" WHERE "res_model"='sign.duplicate.template.pdf' AND "res_id" IS NOT NULL
ERROR: update or delete on table "sign_template" violates foreign key constraint "sign_request_template_id_fkey" on table "sign_request"
DETAIL:  Key (id)=(33) is still referenced from table "sign_request".
```
```
\d sign_template
...
Foreign-key constraints:
    "sign_template_attachment_id_fkey" FOREIGN KEY (attachment_id) REFERENCES ir_attachment(id) ON DELETE CASCADE
...
```

opw-4623484
upg-12544532

closes odoo/upgrade#7328

Signed-off-by: Christophe Simonis (chs) <chs@odoo.com>