[FIX] base/{13.0/14.0}: Add modules `l10n_mx_edi_stock{,_extended}`
Module was `l10n_mx_edi_stock_extended` added by
https://github.com/odoo/enterprise/commit/6b6b13dbca55e253a5a88202887fcf2d3410c5c0
and module `l10n_mx_edi_stock` by
https://github.com/odoo/enterprise/pull/24020/commits/b58ebb63c7dacde03e1f30f6f992a5555d3b8263
and they were missing from the upgrade script

upg-166373
```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/14.0/odoo/service/server.py", line 1199, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/odoo/src/odoo/14.0/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/src/odoo/14.0/odoo/modules/loading.py", line 503, in load_modules
    env['ir.model.data']._process_end(processed_modules)
  File "/tmp/tmpf5ayr2le/migrations/base/0.0.0/pre-models-no-model-data-delete.py", line 101, in _process_end
    return super(IrModelData, self)._process_end(modules)
  File "/home/odoo/src/odoo/14.0/odoo/addons/base/models/ir_model.py", line 2300, in _process_end
    self._process_end_unlink_record(record)
  File "/home/odoo/src/odoo/14.0/addons/website/models/ir_model_data.py", line 36, in _process_end_unlink_record
    return super()._process_end_unlink_record(record)
  File "/home/odoo/src/odoo/14.0/odoo/addons/base/models/ir_model.py", line 2223, in _process_end_unlink_record
    record.unlink()
  File "/tmp/tmpf5ayr2le/migrations/base/0.0.0/pre-models-ir_model.py", line 160, in unlink
    "💥 It looks like you forgot to call `util.remove_field` on the following fields: %s" % ", ".join(fields)
odoo.upgrade.util.exceptions.MigrationError: 💥 It looks like you forgot to call `util.remove_field` on the following fields: stock.picking.l10n_mx_edi_customs_no
```

fix

closes odoo/upgrade#3352

Signed-off-by: Christophe Simonis <chs@odoo.com>