[FIX] helpdesk_timesheet/saas~18.3: select existing
The entries in `timer.timer` might not always have a corresponding
entry in `helpdesk.ticket`. It can happen because indirect references
are broken, in unknown ways before upgrade.

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/saas-18.3/odoo/service/server.py", line 1396, in preload_registries
    registry = Registry.new(dbname, update_module=update_module, install_modules=config['init'], upgrade_modules=config['update'])
  File "<decorator-gen-6>", line 2, in new
  File "/home/odoo/src/odoo/saas-18.3/odoo/tools/func.py", line 83, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/saas-18.3/odoo/orm/registry.py", line 167, in new
    load_modules(
  File "/home/odoo/src/odoo/saas-18.3/odoo/modules/loading.py", line 450, in load_modules
    load_module_graph(
  File "/home/odoo/src/odoo/saas-18.3/odoo/modules/loading.py", line 232, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/home/odoo/src/odoo/saas-18.3/odoo/modules/migration.py", line 220, in migrate_module
    exec_script(self.cr, installed_version, pyfile, pkg.name, stage, stageformat[stage] % version)
  File "/home/odoo/src/odoo/saas-18.3/odoo/modules/migration.py", line 257, in exec_script
    mod.migrate(cr, installed_version)
  File "/tmp/tmp5uk8kibf/migrations/helpdesk_timesheet/saas~18.3.1.0/post-migrate.py", line 27, in migrate
    "project_id": ticket.project_id.id,
  File "/home/odoo/src/odoo/saas-18.3/odoo/orm/fields_relational.py", line 45, in __get__
    return super().__get__(records, owner)
  File "/home/odoo/src/odoo/saas-18.3/odoo/orm/fields.py", line 1464, in __get__
    raise MissingError("\n".join([
odoo.exceptions.MissingError: Record does not exist or has been deleted.
(Record: helpdesk.ticket(4,), User: 1)
```

Since we are filtering tickets with inactive account_ids or the one that
don't exist , we can get empty timesheet_vals_list while having timer_ids
```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/saas-18.3/odoo/service/server.py", line 1396, in preload_registries
    registry = Registry.new(dbname, update_module=update_module, install_modules=config['init'], upgrade_modules=config['update'])
  File "<decorator-gen-6>", line 2, in new
  File "/home/odoo/src/odoo/saas-18.3/odoo/tools/func.py", line 83, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/saas-18.3/odoo/orm/registry.py", line 167, in new
    load_modules(
  File "/home/odoo/src/odoo/saas-18.3/odoo/modules/loading.py", line 450, in load_modules
    load_module_graph(
  File "/home/odoo/src/odoo/saas-18.3/odoo/modules/loading.py", line 232, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/home/odoo/src/odoo/saas-18.3/odoo/modules/migration.py", line 220, in migrate_module
    exec_script(self.cr, installed_version, pyfile, pkg.name, stage, stageformat[stage] % version)
  File "/home/odoo/src/odoo/saas-18.3/odoo/modules/migration.py", line 257, in exec_script
    mod.migrate(cr, installed_version)
  File "/tmp/tmp1f1y0v5f/migrations/helpdesk_timesheet/saas~18.3.1.0/post-migrate.py", line 36, in migrate
    util.iter_browse(env["account.analytic.line"], []).create(timesheet_vals_list)
  File "/tmp/tmp1f1y0v5f/migrations/util/orm.py", line 444, in create
    raise ValueError("`create` cannot be called with an empty `values` argument")
ValueError: `create` cannot be called with an empty `values` argument
```

closes odoo/upgrade#7812

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>