[FIX] base/saas~17.5: handle missing type for company_dependent fields
With the migration to v18, significant changes were introduced to handle data
migration for company-dependent fields from `ir_property` to the `jsonb` column.
While most field types were addressed in the upgrade script, `datetime` fields
were missing, leading to a traceback during migration.

This commit resolves the issue by adding support for `datetime` field types in
the upgrade script. The fix ensures smooth migration for databases with custom
company-dependent fields of type `datetime`.

=> Reason for the fix:
- A customer encountered a migration failure due to a custom company-dependent
  field of type `datetime`.
- While no standard fields are `datetime` and company-dependent, such edge
  cases can arise for custom fields.
- Since `datetime` is a defined field type from here:

https://github.com/odoo/odoo/blob/18.0/odoo/fields.py#L64
https://github.com/odoo/odoo/blob/18.0/odoo/fields.py#L2431

It needs to be accounted for in the upgrade script to prevent migration block.

```Traceback
Traceback (most recent call last):
  File "/home/odoo/src/odoo/18.0/odoo/service/server.py", line 1306, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "<decorator-gen-13>", line 2, in new
  File "/home/odoo/src/odoo/18.0/odoo/tools/func.py", line 97, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/18.0/odoo/modules/registry.py", line 127, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/18.0/odoo/modules/loading.py", line 422, in load_modules
    loaded_modules, processed_modules = load_module_graph(
  File "/home/odoo/src/odoo/18.0/odoo/modules/loading.py", line 181, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/home/odoo/src/odoo/18.0/odoo/modules/migration.py", line 254, in migrate_module
    mod.migrate(self.cr, installed_version)
  File "/tmp/tmpsn81ygn8/migrations/base/saas~17.5.1.3/pre-company-dependent-jsonb.py", line 59, in migrate
    upgrade_company_dependent_field(cr, model_name, field_name, field_id, field_type, field_relation)
  File "/tmp/tmpsn81ygn8/migrations/base/saas~17.5.1.3/pre-company-dependent-jsonb.py", line 222, in upgrade_company_dependent_field
    raise util.MigrationError(f"unexpected field type {field_type} for {model_name}.{field_name}")
odoo.upgrade.util.exceptions.UpgradeError: unexpected field type datetime for account.move.qbo_transaction_date
```

OPW-4434022
UPG-2403978

closes odoo/upgrade#7019

Signed-off-by: Christophe Simonis (chs) <chs@odoo.com>