[FIX] product/saas~18.1: set parent_path for newly created uoms
`parent_path` field has been introduced in model `uom.uom` in saas~18.1.
commit: odoo/odoo@f48a2522ab236f25de898f928248eab7e70ad48d
[field](https://github.com/odoo/odoo/commit/f48a2522ab236f25de898f928248eab7e70ad48d#diff-7aa42e1663219ce82e34c884679a1f295e1fe26afd8daa7cb4d52d8663e79b83R32-R35)
During upgrade, the `uom` module is loaded before the `product` module.
The newly inserted uoms have there `parent_path` field as `NULL` because it is
created using sql instead of ORM. So while accessing those uoms in upgardes db
throws the following error:
```
UncaughtPromiseError > TypeError

Uncaught Promise > uom1.parent_path.split is not a function

TypeError: uom1.parent_path.split is not a function
```

The fix updated the the `parent_path` values by mimicking the ORM behavior
to avoid such runtime issues.

opw-4685873
upg-2556113

closes odoo/upgrade#7527

Signed-off-by: Christophe Simonis (chs) <chs@odoo.com>