[FIX] util/orm: add mock `x_email` field for mail.blacklist
Since odoo/odoo#119169 we add `x_email` as the email field for custom
modules inheriting `mail.thread.blacklist`. The issue is that when we
convert a custom model (non-manual) into manual this field may be
missing. The ORM then fails whenever `email_normalized` is computed
since it depends on the missing field.

Example traceback:
```
 Traceback (most recent call last):
   File "/tmp/tmpkahiavot/migrations/base/tests/test_mock_crawl.py", line 220, in crawl_menu
    self.mock_action(action_vals)
   File "/tmp/tmpkahiavot/migrations/base/tests/test_mock_crawl.py", line 316, in mock_action
    views = get_views(
   File "/home/odoo/src/odoo/16.0/odoo/addons/base/models/ir_ui_view.py", line 2489, in get_views
    result['views'] = {
   File "/home/odoo/src/odoo/16.0/odoo/addons/base/models/ir_ui_view.py", line 2490, in <dictcomp>
    v_type: self.get_view(
   File "/home/odoo/src/odoo/16.0/odoo/addons/base/models/ir_ui_view.py", line 2674, in get_view
    result = dict(self._get_view_cache(view_id, view_type, **options))
   File "<decorator-gen-48>", line 2, in _get_view_cache
   File "/home/odoo/src/odoo/16.0/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
   File "/home/odoo/src/odoo/16.0/odoo/addons/base/models/ir_ui_view.py", line 2637, in _get_view_cache
    arch, models = view.postprocess_and_fields(arch, model=self._name, **options)
   File "/home/odoo/src/odoo/16.0/odoo/addons/base/models/ir_ui_view.py", line 1036, in postprocess_and_fields
    name_manager = self._postprocess_view(node, model or self.model, **options)
   File "/home/odoo/src/odoo/16.0/odoo/addons/base/models/ir_ui_view.py", line 1152, in _postprocess_view
    self._postprocess_on_change(root, model)
   File "/home/odoo/src/odoo/16.0/odoo/addons/base/models/ir_ui_view.py", line 1216, in _postprocess_on_change
    if model._has_onchange(field, field_nodes):
   File "/home/odoo/src/odoo/16.0/odoo/models.py", line 6186, in _has_onchange
    for dep in self.pool.get_dependent_fields(field.base_field)
   File "/home/odoo/src/odoo/16.0/odoo/modules/registry.py", line 351, in get_dependent_fields
    if field not in self._field_triggers:
   File "/home/odoo/src/odoo/16.0/odoo/tools/func.py", line 28, in __get__
    value = self.fget(obj)
   File "/home/odoo/src/odoo/16.0/odoo/modules/registry.py", line 439, in _field_triggers
    dependencies = list(field.resolve_depends(self))
   File "/home/odoo/src/odoo/16.0/odoo/fields.py", line 791, in resolve_depends
    raise ValueError(
 ValueError: Wrong @depends on '_compute_email_normalized' (compute method of field fsm.person.email_normalized). Dependency field 'x_email' not found in model fsm.person.
```

upg-750338

closes odoo/upgrade#4656

Signed-off-by: Christophe Simonis <chs@odoo.com>