[FIX] base@saas~12.3: update `ar_AA` to `ar_001` for default partner lang
The lang `ar_AA` is renamed `ar_001`.
There is already an upgrade script for that, handling most cases.

In this database, there is a default value for the partner lang,
set to `ar_AA`, which needs to be updated to `ar_001` otherwise
it's not possible to create a partner as it tries to assign a lang
which doesn't exist by default

```
  File "/home/odoo/src/odoo/saas-12.3/odoo/addons/base/maintenance/migrations/account/saas~12.3.1.1/end-10-taxes.py", line 1951, in get_v13_migration_dicts
    partner = env["res.partner"].create({"name": "Tax migrator"})
  File "<decorator-gen-133>", line 2, in create
  File "/home/odoo/src/odoo/saas-12.3/odoo/api.py", line 457, in _model_create_multi
    return create(self, [arg])
  File "/home/odoo/src/odoo/saas-12.3/addons/partner_autocomplete/models/res_partner.py", line 176, in create
    partners = super(ResPartner, self).create(vals_list)
  File "<decorator-gen-85>", line 2, in create
  File "/home/odoo/src/odoo/saas-12.3/odoo/api.py", line 458, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/saas-12.3/odoo/addons/base/models/res_partner.py", line 602, in create
    partners = super(Partner, self).create(vals_list)
  File "<decorator-gen-119>", line 2, in create
  File "/home/odoo/src/odoo/saas-12.3/odoo/api.py", line 458, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/saas-12.3/addons/mail/models/mail_thread.py", line 273, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-96>", line 2, in create
  File "/home/odoo/src/odoo/saas-12.3/odoo/api.py", line 439, in _model_create_single
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/home/odoo/src/odoo/saas-12.3/odoo/api.py", line 439, in <genexpr>
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/home/odoo/src/odoo/saas-12.3/odoo/addons/base/maintenance/migrations/base/0.0.0/pre-models-match_uniq.py", line 22, in create
    return super(Base, self).create(values)
  File "<decorator-gen-3>", line 2, in create
  File "/home/odoo/src/odoo/saas-12.3/odoo/api.py", line 457, in _model_create_multi
    return create(self, [arg])
  File "/home/odoo/src/odoo/saas-12.3/odoo/models.py", line 3654, in create
    records = self._create(data_list)
  File "/home/odoo/src/odoo/saas-12.3/odoo/models.py", line 3740, in _create
    col_val = field.convert_to_column(val, self, stored)
  File "/home/odoo/src/odoo/saas-12.3/odoo/fields.py", line 2061, in convert_to_column
    value = self.convert_to_cache(value, record)
  File "/home/odoo/src/odoo/saas-12.3/odoo/fields.py", line 2073, in convert_to_cache
    raise ValueError("Wrong value for %s: %r" % (self, value))
ValueError: Wrong value for res.partner.lang: 'ar_AA'
```

upg-17888

closes odoo/upgrade#2597

Signed-off-by: Christophe Simonis <chs@odoo.com>