[FIX] {mrp,helpdesk}/saas~14.{2,5}: Remove action views
In v15 some views were removed, like Gantt for mrp.production or cohort for
helpdesk.ticket.
The custom actions defined with those modes no longer work. In the case of
mrp.production, because it lacks the fields for the view to work.

For helpdesk.ticket, there's no function `_get_default_cohort_view`.

upg-94944
upg-101914
upg-101750

```
Traceback (most recent call last):
  File "/tmp/tmpb7aeckcv/migrations/testing.py", line 208, in test_check
    self.check(value)
  File "/tmp/tmpb7aeckcv/migrations/base/tests/test_mock_crawl.py", line 85, in check
    self.assertFalse(diff, msg)
AssertionError: [('studio_customization.audio_visual_technol_913e21aa-820d-4e44-8bfe-a901e9afbc10', 168, 'Losev.Tech > Production Orders', 295), ('studio_customization.audio_visual_technol_8a4062cb-ed62-4d76-b1bc-25203f851f03', 165, 'Losev.Tech > Manufacturing', 292)] is not false : At least one menu or view working before upgrade is not working after upgrade.

('studio_customization.audio_visual_tecl_913e21aa-820d-4e44-8bfe-a901e9afbc10', 168, 'Losev.Tech > Production Orders', 295):
 Traceback (most recent call last):
   File "/tmp/tmpb7aeckcv/migrations/base/tests/test_mock_crawl.py", line 182, in crawl_menu
    self.mock_action(action_vals)
   File "/tmp/tmpb7aeckcv/migrations/base/tests/test_mock_crawl.py", line 256, in mock_action
    action["views"], options={"action_id": action.get("id"), "toolbar": True, "load_filters": True}
   File "/home/odoo/src/odoo/15.0/odoo/models.py", line 1632, in load_views
    for [v_id, v_type] in views
   File "/home/odoo/src/odoo/15.0/odoo/models.py", line 1632, in <dictcomp>
    for [v_id, v_type] in views
   File "/home/odoo/src/odoo/15.0/addons/web/models/models.py", line 249, in fields_view_get
    r = super().fields_view_get(view_id, view_type, toolbar, submenu)
   File "/home/odoo/src/odoo/15.0/odoo/models.py", line 1713, in fields_view_get
    result = self._fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
   File "/home/odoo/src/odoo/15.0/odoo/models.py", line 1684, in _fields_view_get
    arch_etree = getattr(self, '_get_default_%s_view' % view_type)()
   File "/home/odoo/src/enterprise/15.0/web_gantt/models/models.py", line 34, in _get_default_gantt_view
    raise UserError(_("Insufficient fields for Gantt View!"))
 odoo.exceptions.UserError: Insufficient fields for Gantt View!

('studio_customization.audio_visual_technol_8a4062cb-ed62-4d76-b1bc-25203f851f03', 165, 'Losev.Tech > Manufacturing', 292):
 Traceback (most recent call last):
   File "/tmp/tmpb7aeckcv/migrations/base/tests/test_mock_crawl.py", line 182, in crawl_menu
    self.mock_action(action_vals)
   File "/tmp/tmpb7aeckcv/migrations/base/tests/test_mock_crawl.py", line 256, in mock_action
    action["views"], options={"action_id": action.get("id"), "toolbar": True, "load_filters": True}
   File "/home/odoo/src/odoo/15.0/odoo/models.py", line 1632, in load_views
    for [v_id, v_type] in views
   File "/home/odoo/src/odoo/15.0/odoo/models.py", line 1632, in <dictcomp>
    for [v_id, v_type] in views
   File "/home/odoo/src/odoo/15.0/addons/web/models/models.py", line 249, in fields_view_get
    r = super().fields_view_get(view_id, view_type, toolbar, submenu)
   File "/home/odoo/src/odoo/15.0/odoo/models.py", line 1713, in fields_view_get
    result = self._fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
   File "/home/odoo/src/odoo/15.0/odoo/models.py", line 1684, in _fields_view_get
    arch_etree = getattr(self, '_get_default_%s_view' % view_type)()
   File "/home/odoo/src/enterprise/15.0/web_gantt/models/models.py", line 34, in _get_default_gantt_view
    raise UserError(_("Insufficient fields for Gantt View!"))
 odoo.exceptions.UserError: Insufficient fields for Gantt View!
```

```
Traceback (most recent call last):
  File "/tmp/tmpt100zwxl/migrations/testing.py", line 208, in test_check
    self.check(value)
  File "/tmp/tmpt100zwxl/migrations/base/tests/test_mock_crawl.py", line 85, in check
    self.assertFalse(diff, msg)
AssertionError: [('helpdesk.helpdesk_ticket_menu_all', 368, 'Helpdesk > Tickets > All Tickets', 533), ('helpdesk.helpdesk_ticket_report_menu', 365, 'Helpdesk > Reporting > Tickets Analysis', 547)] is not false : At least one menu or view working before upgrade is not working after upgrade.

('helpdesk.helpdesk_ticket_menu_all', 368, 'Helpdesk > Tickets > All Tickets', 533):
 Traceback (most recent call last):
   File "/home/odoo/src/odoo/15.0/odoo/models.py", line 1684, in _fields_view_get
    arch_etree = getattr(self, '_get_default_%s_view' % view_type)()
 AttributeError: 'helpdesk.ticket' object has no attribute '_get_default_cohort_view'

During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "/tmp/tmpt100zwxl/migrations/base/tests/test_mock_crawl.py", line 182, in crawl_menu
    self.mock_action(action_vals)
   File "/tmp/tmpt100zwxl/migrations/base/tests/test_mock_crawl.py", line 255, in mock_action
    views = model.load_views(
   File "/home/odoo/src/odoo/15.0/odoo/models.py", line 1629, in load_views
    result['fields_views'] = {
   File "/home/odoo/src/odoo/15.0/odoo/models.py", line 1630, in <dictcomp>
    v_type: self.fields_view_get(v_id, v_type if v_type != 'list' else 'tree',
   File "/home/odoo/src/odoo/15.0/addons/web/models/models.py", line 249, in fields_view_get
    r = super().fields_view_get(view_id, view_type, toolbar, submenu)
   File "/home/odoo/src/odoo/15.0/odoo/models.py", line 1713, in fields_view_get
    result = self._fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
   File "/home/odoo/src/enterprise/15.0/helpdesk_timesheet/models/helpdesk.py", line 155, in _fields_view_get
    result = super(HelpdeskTicket, self)._fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
   File "/home/odoo/src/odoo/15.0/odoo/models.py", line 1689, in _fields_view_get
    raise UserError(_("No default view of type '%s' could be found !", view_type))
 odoo.exceptions.UserError: No default view of type 'cohort' could be found !
```

closes odoo/upgrade#3013

Signed-off-by: Christophe Simonis <chs@odoo.com>