[FIX] stock/tests: warehouse context key changed
From saas-17.3, we will search location for quant
based on self.env.companies, we already fixed
it on test case :
https://github.com/odoo/upgrade/pull/6018/files#diff-545ba2806772bfbb3597467052144dcb45a70d59449133c5afca47b53589804cR125

but now warehouse context key has been changed
in standard code
see:
https://github.com/odoo/odoo/commit/cf65b8ca06aa2e4cd1d25bf261a5022bffc0092e#diff-1f24ce9f94c5795040749acca5924384d7d17c0ac39b1993cef3b484e4bd30afL275-R275

so we need to change keyword warehouse_id in self.env.context

upg-2389852

```
Traceback (most recent call last):
  File "/tmp/tmpzevxuxj4/migrations/testing.py", line 212, in test_check
    self.check(value)
  File "/tmp/tmpzevxuxj4/migrations/stock/tests/test_on_hand_quantity.py", line 148, in check
    self.assertEqual(before_results, after_results, self.message)
AssertionError: Lists differ: [[3, [5905 chars]'], [4762, '1'], [4773, '10'], [4774, '6'], [4[16659 chars]'2']] != [[3, [5905 chars]'], [5016, '19'], [5017, '4'], [5019, '12'], [[10562 chars]'2']]

First differing element 451:
[4762, '1']
[5016, '19']
```

closes odoo/upgrade#6928

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>