[FIX] l10n_mx/16.0: avoid duplicate record
using `ON CONFLICT DO NOTHING` for avoiding
duplicate data for `account_account_template_account_tag`

upg-785269

```
2023-09-26 09:02:40,448 27 ERROR db_785269 odoo.sql_db: bad query:
                WITH mx_account_with_tags AS (
                    SELECT
                        rel.account_account_template_id AS account_id,
                        ARRAY_AGG(tag.nature) AS tag_natures
                    FROM account_account_tag tag
                    JOIN account_account_template_account_tag rel ON rel.account_account_tag_id = tag.id
                    WHERE tag.nature IS NOT NULL
                    GROUP BY rel.account_account_template_id
                )
                INSERT INTO account_account_template_account_tag (account_account_template_id, account_account_tag_id)
                SELECT
                    mx_account_with_tags.account_id,
                    CASE WHEN mx_account_with_tags.tag_natures @> ARRAY[cast('A' AS varchar)] THEN 2770 ELSE 2769 END
                FROM mx_account_with_tags

ERROR: duplicate key value violates unique constraint "account_account_template_acco_account_account_template_id_a_key"
DETAIL:  Key (account_account_template_id, account_account_tag_id)=(4, 2769) already exists.

Traceback (most recent call last):
  File "/home/odoo/src/odoo/16.0/odoo/modules/registry.py", line 90, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/16.0/odoo/modules/loading.py", line 484, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/home/odoo/src/odoo/16.0/odoo/modules/loading.py", line 372, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/odoo/src/odoo/16.0/odoo/modules/loading.py", line 236, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/home/odoo/src/odoo/16.0/odoo/modules/migration.py", line 189, in migrate_module
    migrate(self.cr, installed_version)
  File "/tmp/tmpp5glzgc9/migrations/l10n_mx/16.0.2.0/post-migrate.py", line 12, in migrate
    cr.execute(
  File "/home/odoo/src/odoo/16.0/odoo/sql_db.py", line 321, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.UniqueViolation: duplicate key value violates unique constraint "account_account_template_acco_account_account_template_id_a_key"
DETAIL:  Key (account_account_template_id, account_account_tag_id)=(4, 2769) already exists.
```

Part-of: odoo/upgrade#5192