[FIX] website@saas~11.5: website with multiple root menu / without parent
Requests:
 - 46624
 - 45998
 - 45928

These databases have multiple website menus without parents.
e.g. for 45998:
```sql
_grupo=# select id,website_id,name,parent_id from website_menu where id in (1, 9);
 id | website_id |   name    | parent_id
----+------------+-----------+-----------
  9 |          1 | Help desk |
  1 |          1 | Top Menu  |
(2 rows)
``

In such a case, in Odoo, the main menu chosen is the one with the lowest
sequence and id, the natural order of `website.menu`:
`_order = "sequence, id"`

In this upgrade script,
as this order was not specified,
it could choose randomly one of the two.
And if it was the second (the one with id 9) which was chosen,
the wrong "main" menu was chosen, therefore:
1. The menus template was wrong, as it was based on the wrong main menu,
2. The main website `menu_id`could still be `website.main_menu`,
   and the upgrade failed when attempting to `env.ref` it just after deleting it,
   because of `website/saas~11.5.1.0/post-20-menus.py`:
   ```python
   main_website.menu_id.unlink()
   default_menu = env.ref('website.main_menu')
   ```

```
  File "/src/odoo/12.0/odoo/addons/base/maintenance/migrations/website/saas~11.5.1.0/post-20-menus.py", line 13, in migrate
    default_menu = env.ref('website.main_menu')
  File "/src/odoo/12.0/odoo/api.py", line 864, in ref
    return self['ir.model.data'].xmlid_to_object(xml_id, raise_if_not_found=raise_if_not_found)
  File "/src/odoo/12.0/odoo/addons/base/models/ir_model.py", line 1443, in xmlid_to_object
    t = self.xmlid_to_res_model_res_id(xmlid, raise_if_not_found)
  File "/src/odoo/12.0/odoo/addons/base/models/ir_model.py", line 1427, in xmlid_to_res_model_res_id
    return self.xmlid_lookup(xmlid)[1:3]
  File "<decorator-gen-25>", line 2, in xmlid_lookup
  File "/src/odoo/12.0/odoo/tools/cache.py", line 93, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/src/odoo/12.0/odoo/addons/base/models/ir_model.py", line 1416, in xmlid_lookup
    raise ValueError('External ID not found in the system: %s' % xmlid)
ValueError: External ID not found in the system: website.main_menu
``

closes odoo/upgrade#1174

Signed-off-by: Denis Ledoux (dle) <dle@odoo.com>