[FIX] base/0.0.0: remove check is_company from the clause
Following the change in this PR:
https://github.com/odoo/upgrade/pull/6396

Some DBs are still failing because the partner representing a company
is not set as a company.

```
yaih@(none):yaih_2004688> select id,name,is_company,company_id From res_partner where id = 99
+----+------------------------+------------+------------+
| id | name                   | is_company | company_id |
|----+------------------------+------------+------------|
| 99 | صيدلية الحبيب البيطرية | False      | 1          |
+----+------------------------+------------+------------+
SELECT 1
Time: 0.008s

Time: 0.000s
yaih@(none):yaih_2004688> SELECT id,name,partner_id FROM res_company WHERE id = 3
-[ RECORD 1 ]-------------------------
id         | 3
name       | صيدلية الحبيب البيطرية
partner_id | 99
SELECT 1
Time: 0.004s
```
```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/saas-17.4/odoo/service/server.py", line 1302, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "<decorator-gen-16>", line 2, in new
  File "/home/odoo/src/odoo/saas-17.4/odoo/tools/func.py", line 84, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/saas-17.4/odoo/modules/registry.py", line 124, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/saas-17.4/odoo/modules/loading.py", line 514, in load_modules
    migrations.migrate_module(package, 'end')
  File "/home/odoo/src/odoo/saas-17.4/odoo/modules/migration.py", line 240, in migrate_module
    migrate(self.cr, installed_version)
  File "/tmp/tmpb_2_pix5/migrations/stock/saas~17.3.1.1/end-migrate.py", line 12, in migrate
    warehouse.write(new_types_vals)
  File "/home/odoo/src/odoo/saas-17.4/addons/stock/models/stock_warehouse.py", line 199, in write
    res = super().write(vals)
  File "/home/odoo/src/odoo/saas-17.4/odoo/models.py", line 4597, in write
    self._check_company()
  File "/home/odoo/src/odoo/saas-17.4/odoo/models.py", line 4233, in _check_company
    raise UserError("\n".join(lines))
odoo.exceptions.UserError: Incompatible companies on records:
- “صيدلية الحبيب البيطرية (copy)” belongs to company “صيدلية الحبيب البيطرية” and “Address” (partner_id: 'صيدلية الحبيب البيطرية') belongs to another company.
```

closes odoo/upgrade#6419

Signed-off-by: Christophe Simonis (chs) <chs@odoo.com>