[FIX] sign@saas~13.5: `sign.group_sign_user` change of `implied_ids`
https://github.com/odoo/enterprise/commit/707694ff27db51304c5bf6b1004781aa6ff0a655#diff-28b43d854372eaebad3053ecacd7fd10657617fc15d828f5663a2ee3a338e13aL7

```
Traceback (most recent call last):
  File "/tmp/tmpl_m4lh7s/migrations/base/tests/test_mock_crawl.py", line 155, in crawl_menu
    self.mock_action(action_vals)
  File "/tmp/tmpl_m4lh7s/migrations/base/tests/test_mock_crawl.py", line 234, in mock_action
    mock_method(model, view, fields_list, domain, group_by)
  File "/tmp/tmpl_m4lh7s/migrations/base/tests/test_mock_crawl.py", line 324, in mock_view_kanban
    self.mock_web_search_read(model, view, [domain], fields_list)
  File "/tmp/tmpl_m4lh7s/migrations/base/tests/test_mock_crawl.py", line 383, in mock_web_search_read
    data = model.search_read(domain=domain, fields=fields_list, limit=80)
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 4837, in search_read
    result = records.read(fields)
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 3023, in read
    return self._read_format(fnames=fields, load=load)
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 3043, in _read_format
    vals[name] = convert(record[name], record, use_name_get)
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 5664, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/odoo/src/odoo/14.0/odoo/fields.py", line 1021, in __get__
    self.compute_value(record)
  File "/home/odoo/src/odoo/14.0/odoo/fields.py", line 1175, in compute_value
    records._compute_field_value(self)
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 4059, in _compute_field_value
    getattr(self, field.compute)()
  File "/home/odoo/src/enterprise/14.0/sign/models/sign_template.py", line 68, in _compute_signed_in_progress_template
    sign_requests = self.env['sign.request'].read_group([('state', '!=', 'canceled')], ['state', 'template_id'], ['state', 'template_id'], lazy=False)
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 2250, in read_group
    result = self._read_group_raw(domain, fields, groupby, offset=offset, limit=limit, orderby=orderby, lazy=lazy)
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 2272, in _read_group_raw
    self.check_access_rights('read')
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 3334, in check_access_rights
    return self.env['ir.model.access'].check(self._name, operation, raise_exception)
  File "<decorator-gen-33>", line 2, in check
  File "/home/odoo/src/odoo/14.0/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/odoo/src/odoo/14.0/odoo/addons/base/models/ir_model.py", line 1762, in check
    raise AccessError(msg)
odoo.exceptions.AccessError: You are not allowed to access 'Signature Request' (sign.request) records.

This operation is allowed for the following groups:
	- Sign/Employee: Send file to sign
	- User types/Portal

Contact your administrator to request access if necessary.
```

upg-8458
upg-8456

closes odoo/upgrade#2215

Signed-off-by: Christophe Simonis <chs@odoo.com>