[FIX] l10n_ph/17.0: Change companies' fiscal country
Databases created before the fix in https://github.com/odoo/odoo/pull/132932
have companies with their fiscal country by default set to United States.

Unless manually changed, all their tax groups and taxes are also set to US,
but all new records created since the patch will be properly set to Philippines.

During the upgrade, new tax records are created linked to existing tax groups
still set in the US, triggering a `ValidationError` because of the disparity in
countries.

TBG-1111

```
File "/home/odoo/src/odoo/17.0/addons/l10n_ph/migrations/1.1/post-migrate_update_taxes.py", line 8, in migrate
    env['account.chart.template'].try_loading('ph', company)
  File "/home/odoo/src/odoo/17.0/addons/account/models/chart_template.py", line 143, in try_loading
    return self._load(template_code, company, install_demo)
  File "/home/odoo/src/odoo/17.0/addons/account/models/chart_template.py", line 192, in _load
    self._load_data(data)
  File "/home/odoo/src/odoo/17.0/addons/account/models/chart_template.py", line 519, in _load_data
    created_vals[model] = self.with_context(lang='en_US').env[model]._load_records(create_vals)
  File "/home/odoo/src/odoo/17.0/odoo/models.py", line 5061, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/home/odoo/src/odoo/17.0/odoo/models.py", line 4972, in _load_records_create
    return self.create(values)
  File "<decorator-gen-199>", line 2, in create
  File "/home/odoo/src/odoo/17.0/odoo/api.py", line 415, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/17.0/addons/account/models/account_tax.py", line 534, in create
    taxes = super(AccountTax, self.with_context(context)).create([self._sanitize_vals(vals) for vals in vals_list])
  File "<decorator-gen-134>", line 2, in create
  File "/home/odoo/src/odoo/17.0/odoo/api.py", line 415, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/17.0/addons/mail/models/mail_thread.py", line 255, in create
    threads = super(MailThread, self).create(vals_list)
  File "<decorator-gen-123>", line 2, in create
  File "/home/odoo/src/odoo/17.0/odoo/api.py", line 415, in _model_create_multi
    return create(self, arg)
  File "/tmp/tmp6cekzox9/migrations/util/orm.py", line 212, in wrapper
    return f(*args, **kwargs)
  File "/tmp/tmp6cekzox9/migrations/base/0.0.0/pre-models-match_uniq.py", line 91, in create
    records = super().create([vals_list[idx] for idx in create_idx_list])
  File "<decorator-gen-12>", line 2, in create
  File "/home/odoo/src/odoo/17.0/odoo/api.py", line 415, in _model_create_multi
    return create(self, arg)
  File "/home/odoo/src/odoo/17.0/odoo/models.py", line 4601, in create
    records = self._create(data_list)
  File "/home/odoo/src/odoo/17.0/odoo/models.py", line 4862, in _create
    records._validate_fields(name for data in data_list for name in data['stored'])
  File "/home/odoo/src/odoo/17.0/odoo/models.py", line 1456, in _validate_fields
    check(self)
  File "/home/odoo/src/odoo/17.0/addons/account/models/account_tax.py", line 214, in validate_tax_group_id
    raise ValidationError(_("The tax group must have the same country_id as the tax using it."))
odoo.exceptions.ValidationError: The tax group must have the same country_id as the tax using it.
```

closes odoo/upgrade#5797

Signed-off-by: Agustín Castro Bugallo (agcb) <agcb@odoo.com>