[FIX] base/tests: avoid flush on `get_bindings`
`load_views` calls `fields_view_get` that calls `get_bindings`.
This will do a naked `flush` that then flushes _all_ values. This
fails for computed fields with failed computations. What's worse is that
since the flush cannot be done all subsequent actions also fail.

```
Traceback (most recent call last):
  File "/tmp/tmpzmzrstgk/migrations/base/tests/test_mock_crawl.py", line 220, in crawl_menu
    self.mock_action(action_vals)
  File "/tmp/tmpzmzrstgk/migrations/base/tests/test_mock_crawl.py", line 291, in mock_action
    action["views"], options={"action_id": action.get("id"), "toolbar": True, "load_filters": True}
  File "/home/odoo/src/odoo/13.0/odoo/models.py", line 1478, in load_views
    for [v_id, v_type] in views
  File "/home/odoo/src/odoo/13.0/odoo/models.py", line 1478, in <dictcomp>
    for [v_id, v_type] in views
  File "/home/odoo/src/odoo/13.0/addons/web/models/models.py", line 232, in fields_view_get
    r = super().fields_view_get(view_id, view_type, toolbar, submenu)
  File "/home/odoo/src/odoo/13.0/odoo/models.py", line 1572, in fields_view_get
    bindings = self.env['ir.actions.actions'].get_bindings(self._name)
  File "<decorator-gen-35>", line 2, in get_bindings
  File "/home/odoo/src/odoo/13.0/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/odoo/src/odoo/13.0/odoo/addons/base/models/ir_actions.py", line 96, in get_bindings
    self.flush()
  File "/home/odoo/src/odoo/13.0/odoo/models.py", line 5534, in flush
    self.recompute()
  File "/home/odoo/src/odoo/13.0/odoo/models.py", line 5976, in recompute
    process(field)
  File "/home/odoo/src/odoo/13.0/odoo/models.py", line 5960, in process
    recs.mapped(field.name)
  File "/home/odoo/src/odoo/13.0/odoo/models.py", line 5342, in mapped
    recs = recs._mapped_func(operator.itemgetter(name))
  File "/home/odoo/src/odoo/13.0/odoo/models.py", line 5301, in _mapped_func
    vals = [func(rec) for rec in self]
  File "/home/odoo/src/odoo/13.0/odoo/models.py", line 5301, in <listcomp>
    vals = [func(rec) for rec in self]
  File "/home/odoo/src/odoo/13.0/odoo/models.py", line 5766, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/odoo/src/odoo/13.0/odoo/fields.py", line 2370, in __get__
    return super().__get__(records, owner)
  File "/home/odoo/src/odoo/13.0/odoo/fields.py", line 1033, in __get__
    self.compute_value(recs)
  File "/home/odoo/src/odoo/13.0/odoo/fields.py", line 1147, in compute_value
    records._compute_field_value(self)
  File "/home/odoo/src/odoo/13.0/odoo/models.py", line 4018, in _compute_field_value
    getattr(self, field.compute)()
  File "/home/odoo/src/enterprise/13.0/account_asset/models/account_asset.py", line 121, in _compute_value
    raise UserError(_("All the lines should be posted"))
odoo.exceptions.UserError: ('All the lines should be posted', '')
```

Direct links:
https://github.com/odoo/odoo/blob/8a76f731c977852bbe4c1330a8a9d9059d79f777/odoo/models.py#L1476
https://github.com/odoo/odoo/blob/8a76f731c977852bbe4c1330a8a9d9059d79f777/odoo/models.py#L1572
https://github.com/odoo/odoo/blob/8a76f731c977852bbe4c1330a8a9d9059d79f777/odoo/addons/base/models/ir_actions.py#L96
https://github.com/odoo/odoo/blob/8a76f731c977852bbe4c1330a8a9d9059d79f777/odoo/models.py#L5532-L5534

upg-424429

closes odoo/upgrade#4148

Signed-off-by: Christophe Simonis <chs@odoo.com>