[FIX] base@saas~11.5: typo in query
No need to quote the column names. The column names returned by
util.get_fk will already be quoted if necessary.

Fixes this kind of error:
  psycopg2.ProgrammingError: zero-length delimited identifier at or near """"
  LINE 14: ...d UNION SELECT 1 FROM "helpdesk_ticket" x WHERE x.""x_studio...