[FIX] mrp/saas~13.4.2.0: fix typo
```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/12.0/odoo/service/server.py", line 1164, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/odoo/src/odoo/12.0/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/src/odoo/12.0/odoo/modules/loading.py", line 417, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/home/odoo/src/odoo/12.0/odoo/modules/loading.py", line 313, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/odoo/src/odoo/12.0/odoo/modules/loading.py", line 227, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/home/odoo/src/odoo/12.0/odoo/modules/migration.py", line 190, in migrate_module
    migrate(self.cr, installed_version)
  File "/home/odoo/src/odoo/12.0/odoo/addons/base/maintenance/migrations/point_of_sale/saas~11.5.1.0.1/post-migrate.py", line 143, in migrate
    """), table="pos_order")
TypeError: explode_query_range() missing 1 required positional argument: 'table'
```

upg-43496

closes odoo/upgrade#2979

Signed-off-by: Christophe Simonis <chs@odoo.com>