[FIX] spreadsheet_edition/saas~16.5: handle corner case
If no `attachment` with `attachment_id` is found we do not update
anything, thus return early.

Example traceback:

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/17.0/odoo/service/server.py", line 1302, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "<decorator-gen-16>", line 2, in new
  File "/home/odoo/src/odoo/17.0/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/17.0/odoo/modules/registry.py", line 113, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/17.0/odoo/modules/loading.py", line 476, in load_modules
    processed_modules += load_marked_modules(env, graph,
  File "/home/odoo/src/odoo/17.0/odoo/modules/loading.py", line 364, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/odoo/src/odoo/17.0/odoo/modules/loading.py", line 181, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/home/odoo/src/odoo/17.0/odoo/modules/migration.py", line 240, in migrate_module
    migrate(self.cr, installed_version)
  File "/tmp/tmpvhnr64gz/migrations/spreadsheet_edition/saas~16.5.1.0/pre-copy-images.py", line 26, in migrate
    if command["type"] == "CREATE_IMAGE" and fix_image_attachment(cr, res_model, res_id, command):
  File "/tmp/tmpvhnr64gz/migrations/spreadsheet_edition/saas~16.5.1.0/pre-copy-images.py", line 60, in fix_image_attachment
    attachment_res_model, attachment_res_id = cr.fetchone()
TypeError: cannot unpack non-iterable NoneType object
```

closes odoo/upgrade#5867

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>