[FIX] website/saas~17.2: Use html instead of etree
During `convert_bootstrap.innerxml`, since the `is_html` flag is used,
the content of the element is serialized as HTML.
This can make it invalid as XML (eg, making self-closing tags only HTML-valid)
so it can break while calling `etree.fromstring`.

Example:
`<img src="https://placeholder.com/600x400"/>`
gets changed to
`<img src="https://placeholder.com/600x400">`
which is valid as HTML but not as XML, triggering an error.

tbg-1289

Traceback:
```
  File "/tmp/tmpq_yuss7o/migrations/website/saas~17.2.1.0/pre-migrate.py", line 41, in migrate
    snippets.convert_html_content(
  File "/tmp/tmpq_yuss7o/migrations/util/snippets.py", line 321, in convert_html_content
    convert_html_columns(
  File "/tmp/tmpq_yuss7o/migrations/util/snippets.py", line 282, in convert_html_columns
    for data in executor.map(convert, cr.fetchall()):
  File "/usr/lib/python3.10/concurrent/futures/process.py", line 575, in _chain_from_iterable_of_lists
    for element in iterable:
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 621, in result_iterator
    yield _result_or_cancel(fs.pop())
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 319, in _result_or_cancel
    return fut.result(timeout)
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 458, in result
    return self.__get_result()
  File "/usr/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
TypeError: cannot pickle 'lxml.etree._ListErrorLog' object
```

closes odoo/upgrade#6115

Signed-off-by: Christophe Simonis (chs) <chs@odoo.com>