[FIX] base@saas~13.1: remove diagram mode from ir_act_window
Diagrams views are completely removed when upgrading
to saas~13.1.
https://github.com/odoo/upgrade/blob/f9b08bdcea667f1b2ff7023b248c00a05647d0fc/migrations/base/saas~13.1.1.3/pre-20-models.py#L31-L33

If the views are removed, the mode `diagram`
must be removed from the `ir.act.window` actions as well.
For actions in standard module, it's handled when loading
the actions from the xml data,
but for custom modules it's not the case.

```
Traceback (most recent call last):
  File "/tmp/tmpm0r2yoc6/migrations/testing.py", line 208, in test_check
    self.check(value)
  File "/tmp/tmpm0r2yoc6/migrations/base/tests/test_mock_crawl.py", line 85, in check
    self.assertFalse(diff, msg)
AssertionError: [('stock_scanner.menu_scanner_scenario', 259, 'Inventory > Configuration > Scanner Configuration > Scanner Scenario', 392)] is not false : At least one menu or view working before upgrade is not working after upgrade.

('stock_scanner.menu_scanner_scenario', 259, 'Inventory > Configuration > Scanner Configuration > Scanner Scenario', 392):
 Traceback (most recent call last):
   File "/home/odoo/src/odoo/14.0/odoo/models.py", line 1576, in _fields_view_get
    arch_etree = getattr(self, '_get_default_%s_view' % view_type)()
 AttributeError: 'scanner.scenario' object has no attribute '_get_default_diagram_view'

During handling of the above exception, another exception occurred:

 Traceback (most recent call last):
   File "/tmp/tmpm0r2yoc6/migrations/base/tests/test_mock_crawl.py", line 176, in crawl_menu
    self.mock_action(action_vals)
   File "/tmp/tmpm0r2yoc6/migrations/base/tests/test_mock_crawl.py", line 240, in mock_action
    action["views"], options={"action_id": action.get("id"), "toolbar": True, "load_filters": True}
   File "/home/odoo/src/odoo/14.0/odoo/models.py", line 1524, in load_views
    for [v_id, v_type] in views
   File "/home/odoo/src/odoo/14.0/odoo/models.py", line 1524, in <dictcomp>
    for [v_id, v_type] in views
   File "/home/odoo/src/odoo/14.0/addons/web/models/models.py", line 246, in fields_view_get
    r = super().fields_view_get(view_id, view_type, toolbar, submenu)
   File "/home/odoo/src/odoo/14.0/odoo/models.py", line 1605, in fields_view_get
    result = self._fields_view_get(view_id=view_id, view_type=view_type, toolbar=toolbar, submenu=submenu)
   File "/home/odoo/src/odoo/14.0/odoo/models.py", line 1581, in _fields_view_get
    raise UserError(_("No default view of type '%s' could be found !", view_type))
 odoo.exceptions.UserError: Aucune vue par défaut de type "diagram" n'a pu être trouvée!
```

upg-17335
upg-8145

closes odoo/upgrade#2690

Signed-off-by: Christophe Simonis <chs@odoo.com>