[FIX] base/0.0.0: match_uniq for ir.module.module
Some record info is missing on ir_model_data for base module.
Loading the xml data into it triggers a recreation of a record on
ir_module_module with the same name, which provokes the exception below.
To avoid this we allow the merging of xml entries on ir_model_data by
setting the _match_unique flag on ir.module.module.

```
Traceback (most recent call last):
  ...
  File "/home/odoo/src/odoo/12.0/odoo/addons/base/maintenance/migrations/base/0.0.0/pre-models-match_uniq.py", line 22, in create
    return super(Base, self).create(values)
  File "<decorator-gen-3>", line 2, in create
  File "/home/odoo/src/odoo/12.0/odoo/api.py", line 461, in _model_create_multi
    return create(self, [arg])
  File "/home/odoo/src/odoo/12.0/odoo/models.py", line 3603, in create
    records = self._create(data_list)
  File "/home/odoo/src/odoo/12.0/odoo/models.py", line 3703, in _create
    cr.execute(query, params)
  File "/home/odoo/src/odoo/12.0/odoo/sql_db.py", line 148, in wrapper
    return f(self, *args, **kwargs)
  File "/home/odoo/src/odoo/12.0/odoo/sql_db.py", line 225, in execute
    res = self._obj.execute(query, params)
odoo.tools.convert.ParseError: "duplicate key value violates unique constraint "ir_module_module_name_uniq"
DETAIL:  Key (name)=(account_accountant) already exists.
" while parsing /home/odoo/src/odoo/12.0/odoo/addons/base/data/ir_module_module.xml:33, near
<record model="ir.module.module" id="base.module_account_accountant">
            <field name="name">account_accountant</field>
            <field name="sequence">15</field>
            <field name="shortdesc">Accounting</field>
            <field name="category_id" ref="base.module_category_accounting_and_finance"/>
            <field name="application" eval="True"/>
            <field name="summary">Accounting, Taxes, Budgets, Assets...</field>
            <field name="license">OEEL-1</field>
            <field name="author">Odoo S.A.</field>
            <field name="to_buy" eval="True"/>
            <field name="icon">/base/static/img/icons/account_accountant.png</field>
            <field name="website">https://www.odoo.com/page/accounting?utm_source=db&amp;utm_medium=module</field>
        </record>
```

upg-9913