[FIX] l10n_ec/16.0: removed deprecated account template
Account 1105020 has been removed and with that same name
new account group has been created. The tax names of
account 11050201 is changed to a better accounting standard name
for the understanding of the accounting accounts to be configured
in the tax groups, based on the name of the new account group
created.

see: https://github.com/odoo/odoo/commit/d34d5fb803057653af08418ac7bb1940f44bb1e0

and view `account_l10n_ec_sri_payment` has been replaced by
`view_payment_method_tree`
see: https://github.com/odoo/odoo/commit/c9568fbb7544ededb37f57892f930d198083c06f

TGB: https://upgrade.odoo.com/web#id=809&active_id=944409&model=upgrade.request.traceback.group&view_type=form&cids=1&menu_id=107

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/16.0/odoo/service/server.py", line 1299, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "<decorator-gen-14>", line 2, in new
  File "/home/odoo/src/odoo/16.0/odoo/tools/func.py", line 87, in locked
    return func(inst, *args, **kwargs)
  File "/home/odoo/src/odoo/16.0/odoo/modules/registry.py", line 90, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/16.0/odoo/modules/loading.py", line 484, in load_modules
    processed_modules += load_marked_modules(cr, graph,
  File "/home/odoo/src/odoo/16.0/odoo/modules/loading.py", line 372, in load_marked_modules
    loaded, processed = load_module_graph(
  File "/home/odoo/src/odoo/16.0/odoo/modules/loading.py", line 231, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/home/odoo/src/odoo/16.0/odoo/modules/loading.py", line 71, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/home/odoo/src/odoo/16.0/odoo/tools/convert.py", line 763, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/home/odoo/src/odoo/16.0/odoo/tools/convert.py", line 829, in convert_xml_import
    obj.parse(doc.getroot())
  File "/home/odoo/src/odoo/16.0/odoo/tools/convert.py", line 749, in parse
    self._tag_root(de)
  File "/home/odoo/src/odoo/16.0/odoo/tools/convert.py", line 698, in _tag_root
    f(rec)
  File "/home/odoo/src/odoo/16.0/odoo/tools/convert.py", line 709, in _tag_root
    raise ParseError(msg) from None  # Restart with "--log-handler odoo.tools.convert:DEBUG" for complete traceback
odoo.tools.convert.ParseError: while parsing /home/odoo/src/odoo/16.0/addons/l10n_ec/data/account_group_template_data.xml:125
For external id l10n_ec.ec110502 when trying to create/update a record of model account.group.template found record of different model account.account.template (23392)
```

closes odoo/upgrade#4909

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>