[FIX] pos_enterprise/0.0.0: install pos_iot
Since odoo/enterprise#6323 -- targeted saas~13.1;  we alias
`is_posbox` to `module_pos_iot` in PoS Config model. As a consequence
when we write in a pos config that had is_posbox set we trigger the
installation of pos_iot:
https://github.com/odoo/odoo/blob/b917cd6af89d168bbf72e8253a6d7fa5193d6553/addons/point_of_sale/models/pos_config.py#L528

The problem is that some DB have is_posbox=True with pos_enterprise but
without `pos_iot` installed. Therefore if there is a write during the
upgrade in the pos config we get an error. Example:
```
  File "/home/odoo/src/odoo/17.0/addons/l10n_es_pos/__init__.py", line 21, in _l10n_es_pos_post_init_hook
    pos_configs.l10n_es_simplified_invoice_journal_id = simplified_inv_journal
  File "/home/odoo/src/odoo/17.0/odoo/fields.py", line 1322, in __set__
    records.write({self.name: write_value})
  File "/home/odoo/src/odoo/17.0/addons/point_of_sale/models/pos_config.py", line 449, in write
    self.sudo()._check_modules_to_install()
  File "/home/odoo/src/odoo/17.0/addons/point_of_sale/models/pos_config.py", line 541, in _check_modules_to_install
    modules.button_immediate_install()
  File "<decorator-gen-77>", line 2, in button_immediate_install
  File "/home/odoo/src/odoo/17.0/odoo/addons/base/models/ir_module.py", line 75, in check_and_log
    return method(self, *args, **kwargs)
  File "/home/odoo/src/odoo/17.0/odoo/addons/base/models/ir_module.py", line 466, in button_immediate_install
    return self._button_immediate_function(self.env.registry[self._name].button_install)
  File "/home/odoo/src/odoo/17.0/odoo/addons/base/models/ir_module.py", line 569, in _button_immediate_function
    raise UserError(_('The method _button_immediate_install cannot be called on init or non loaded registries. Please use button_install instead.'))
odoo.exceptions.UserError: El método _button_immediate_install no puede ser llamado en registros init o no cargados. Por favor, utilice button_install en su lugar.
```

upg-1439402
upg-1221116
upg-1440557
tbg-1070

closes odoo/upgrade#5877

Signed-off-by: Christophe Simonis (chs) <chs@odoo.com>