[FIX] website/saas~17.2:Add the conditon for cowed view
While upgrading to saas version 17.2, an error occurs due to the migration file.
The XPath expression  `//div[hasclass(s_embed_code_embedded)]` cannot be found
in all the customer databases in the cowed view. To resolve this error, the
condition should be bypassed.

```
File /tmp/tmp_gkfxzc3/migrations/website/saas~17.2.1.0/pre-migrate.py, line 12
in add_template_in_embed_code
    embedded_code = el.xpath('.//div[hasclass(s_embed_code_embedded)]')[0]
IndexError: list index out of range
```
opw - 4003561,  4013021
upg - 1751854, 1734062, 1733974, 1776636

closes odoo/upgrade#6188

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>