[FIX] base/tests: do not patch `read` for ir actions
Since odoo/odoo@a5a9a96 we specify a limited list of fields to read.

Forcing a list now causes the precise issue that the patch is trying to
avoid.
```
 Traceback (most recent call last):
   File "/tmp/tmpxq76w1wt/migrations/base/tests/test_mock_crawl.py", line 238, in crawl_menu
    self.mock_action(action_vals)
   File "/tmp/tmpxq76w1wt/migrations/base/tests/test_mock_crawl.py", line 334, in mock_action
    views = get_views(
   File "/home/odoo/src/odoo/16.0/odoo/addons/base/models/ir_ui_view.py", line 2533, in get_views
    bindings = self.env['ir.actions.actions'].get_bindings(self._name)
   File "/home/odoo/src/odoo/16.0/odoo/addons/base/models/ir_actions.py", line 98, in get_bindings
    for action_type, all_actions in self._get_bindings(model_name).items():
   File "<decorator-gen-56>", line 2, in _get_bindings
   File "/home/odoo/src/odoo/16.0/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
   File "/home/odoo/src/odoo/16.0/odoo/addons/base/models/ir_actions.py", line 141, in _get_bindings
    action = action.read(fields)[0]
   File "/tmp/tmpxq76w1wt/migrations/base/tests/test_mock_crawl.py", line 319, in <lambda>
    lambda self, *args, **kwargs: origin_read(self, fields=action_fields),
   File "/home/odoo/src/odoo/16.0/odoo/models.py", line 2978, in read
    raise ValueError("Invalid field %r on model %r" % (name, self._name))
 ValueError: Invalid field 'x_studio_responsable' on model 'ir.actions.server'
```

See also #1178

upg-1215277

closes odoo/upgrade#5560

Signed-off-by: Christophe Simonis (chs) <chs@odoo.com>