[FIX] product/saas~12.5: drop table cascade for failing query
When removing the `product_attribute_value_product_product_rel` table,
the upgrade fail because of bad query.

```
2021-11-05 08:33:14,781 3088 INFO arg_43661_15.0 odoo.modules.migration: module product: Running migration [>saas~12.5.1.2] pre-10-migrate
2021-11-05 08:33:15,123 3088 ERROR arg_43661_15.0 odoo.sql_db: bad query: DROP TABLE product_attribute_value_product_product_rel
ERROR: cannot drop table product_attribute_value_product_product_rel because other objects depend on it
DETAIL:  view sale_report_version depends on table product_attribute_value_product_product_rel
HINT:  Use DROP ... CASCADE to drop the dependent objects too.

2021-11-05 08:33:15,134 3088 WARNING arg_43661_15.0 odoo.modules.loading: Transient module states were reset
2021-11-05 08:33:15,134 3088 ERROR arg_43661_15.0 odoo.modules.registry: Failed to load registry
Traceback (most recent call last):
  File "/home/odoo/src/odoo/13.0/odoo/modules/registry.py", line 86, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/src/odoo/13.0/odoo/modules/loading.py", line 424, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/home/odoo/src/odoo/13.0/odoo/modules/loading.py", line 315, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/odoo/src/odoo/13.0/odoo/modules/loading.py", line 177, in load_module_graph
    migrations.migrate_module(package, 'pre')
  File "/home/odoo/src/odoo/13.0/odoo/modules/migration.py", line 180, in migrate_module
    migrate(self.cr, installed_version)
  File "/tmp/tmpwkx3ppvi/migrations/product/saas~12.5.1.2/pre-10-migrate.py", line 29, in migrate
    cr.execute("DROP TABLE product_attribute_value_product_product_rel")
  File "/home/odoo/src/odoo/13.0/odoo/sql_db.py", line 173, in wrapper
    return f(self, *args, **kwargs)
  File "/home/odoo/src/odoo/13.0/odoo/sql_db.py", line 250, in execute
    res = self._obj.execute(query, params)
psycopg2.errors.DependentObjectsStillExist: cannot drop table product_attribute_value_product_product_rel because other objects depend on it
DETAIL:  view sale_report_version depends on table product_attribute_value_product_product_rel
HINT:  Use DROP ... CASCADE to drop the dependent objects too.
```

upg-43661

closes odoo/upgrade#3008

Signed-off-by: Christophe Simonis <chs@odoo.com>