[IMP] base/tests: avoid false error
`tools/link-upgrade-util.py` symlinks `upgrade-util` dirs in
`migrations/util`. The symlink for `migrations/util/spreadsheet`
shouldn't be considered as a version dir.

Due to the complex definition of the version regexp, it's better to
leave it out of the reported error:
```
Traceback (most recent call last):
  File "/home/odoo/src/upgrade/migrations/base/tests/test_versions.py", line 24, in test_fs
    self.assertIsNotNone(migration.VERSION_RE.match(version), f"Invalid version {path.relative_to(ROOT)}")
AssertionError: unexpectedly None : Invalid version util/spreadsheet
```
before:
```
Traceback (most recent call last):
  File "/home/odoo/src/upgrade/migrations/base/tests/test_versions.py", line 24, in test_fs
    self.assertRegex(version, migration.VERSION_RE, f"Invalid version {path.relative_to(ROOT)}")
AssertionError: Regex didn't match: '^\n        # Optional prefix with Odoo version\n        ((\n            6\\.1|\n\n            # "x.0" version, with x >= 6.\n            [6-9]\\.0|\n\n            # multi digit
s "x.0" versions\n            [1-9]\\d+\\.0|\n\n            # x.saas~y, where x >= 7 and x <= 10\n            (7|8|9|10)\\.saas~[1-9]\\d*|\n\n            # saas~x.y, where x >= 11 and y between 1 and 9\n
  # FIXME handle version >= saas~100 (expected in year 2106)\n            saas~(1[1-9]|[2-9]\\d+)\\.[1-9]\n        )\\.)?\n        # After Odoo version we allow precisely 2 or 3 parts\n        # note this will als
o allow 0.0.0 which has a special meaning\n        \\d+\\.\\d+(\\.\\d+)?\n    $' not found in 'spreadsheet' : Invalid version util/spreadsheet
```

closes odoo/upgrade#8007

Signed-off-by: Christophe Simonis (chs) <chs@odoo.com>