[FIX] stock/tests: fix test_on_hand qty check
In https://github.com/odoo/upgrade/blob/2b1cc4529f9d47670074e51ef9889ad3ac0369da/migrations/stock/tests/test_on_hand_quantity.py#L24
we override `_generate_order_by_inner` method to resolve
boms ordering issue on computation of on hand qty.
But this method is deprecated in version 17.0
now `_order_to_sql` method so during upgrade
when we upgrade database, before upgrade on
pre test, it will append `NULLS LAST` on priority
field and that should be also appened after upgrade
test but as this method is deprecated on 17.0
it will not append `NULLS LAST` and then it will
take wrong BOM and we got mismatched on hand qty.

see method in 17.0:
https://github.com/odoo/odoo/blob/f6c0c516497b51d8808f3d2a6f5c9ce4a744b6c7/odoo/models.py#L5260

upg-1288037
```
IN saas-16.4:

 SELECT "mrp_bom".id, --this is the only column from the ORM
       "mrp_bom"."sequence" ,
        "mrp_bom__product_id__product_tmpl_id"."priority" DESC,
       "mrp_bom__product_id"."default_code" ,
       "mrp_bom__product_id"."id"
  FROM "mrp_bom"
  LEFT JOIN "product_product" AS "mrp_bom__product_id"
    ON ("mrp_bom"."product_id" = "mrp_bom__product_id"."id")
  LEFT JOIN "product_template" AS "mrp_bom__product_id__product_tmpl_id"
    ON ("mrp_bom__product_id"."product_tmpl_id" = "mrp_bom__product_id__product_tmpl_id"."id")
 WHERE (
            (
                ("mrp_bom"."active" = True)
            AND (
                    ("mrp_bom"."product_id" in (1591))
                 OR ("mrp_bom"."product_id" IS NULL  AND ("mrp_bom"."product_tmpl_id" in (1297)))
                )
            )
        AND ("mrp_bom"."type" = 'phantom')
        )
 ORDER BY  "mrp_bom"."sequence" ,
            "mrp_bom__product_id__product_tmpl_id"."priority" DESC NULLS LAST,
           "mrp_bom__product_id"."default_code" ,
           "mrp_bom__product_id"."id" ,
           "mrp_bom"."id";

```
```
Result:

 id | sequence | desc | default_code |  id
----+----------+------+--------------+------
  4 |          | 0    |              | 1591
  5 |          |      |              |
(2 rows)

```
```
In 17.0:

SELECT "mrp_bom".id, --this is the only column from the ORM
       "mrp_bom"."sequence" ,
        "mrp_bom__product_id__product_tmpl_id"."priority" DESC,
       "mrp_bom__product_id"."default_code" ,
       "mrp_bom__product_id"."id"
  FROM "mrp_bom"
  LEFT JOIN "product_product" AS "mrp_bom__product_id"
    ON ("mrp_bom"."product_id" = "mrp_bom__product_id"."id")
  LEFT JOIN "product_template" AS "mrp_bom__product_id__product_tmpl_id"
    ON ("mrp_bom__product_id"."product_tmpl_id" = "mrp_bom__product_id__product_tmpl_id"."id")
 WHERE (
            (
                ("mrp_bom"."active" = True)
            AND (
                    ("mrp_bom"."product_id" in (1591))
                 OR ("mrp_bom"."product_id" IS NULL  AND ("mrp_bom"."product_tmpl_id" in (1297)))
                )
            )
        AND ("mrp_bom"."type" = 'phantom')
        )
 ORDER BY  "mrp_bom"."sequence" ,
            "mrp_bom__product_id__product_tmpl_id"."priority" DESC,
           "mrp_bom__product_id"."default_code" ,
           "mrp_bom__product_id"."id" ,
           "mrp_bom"."id";
```
```
result:

 id | sequence | desc | default_code |  id
----+----------+------+--------------+------
  5 |          |      |              |
  4 |          | 0    |              | 1591
(2 rows)

```
```
Traceback (most recent call last):
  File "/tmp/tmpt793m_v_/migrations/testing.py", line 207, in test_check
    self.check(value)
  File "/tmp/tmpt793m_v_/migrations/stock/tests/test_on_hand_quantity.py", line 41, in check
    self.assertEqual(before_results, self.convert_check(after_results), self.message)
AssertionError: Lists differ: [[645[50 chars]1, '-2'], [874, '50'], [875, '50'], [1591, '-2'], [1605, '-2']] != [[645[50 chars]1, '-2'], [874, '50'], [875, '50'], [1605, '-2']]

First differing element 7:
[1591, '-2']
[1605, '-2']

```

closes odoo/upgrade#5651

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>