[FIX] l10n_mx_edi/15.0.0.3 Install `l10n_mx_edi_extended`
In v15, model res.city has been moved to l10n_mx_edi_extended. If this module
is not installed, upgrade will fail because the field added in that model
has not been removed.

Related:
https://github.com/odoo/enterprise/pull/22951/
https://github.com/odoo/upgrade/pull/3164

upg-93651

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/15.0/odoo/service/server.py", line 1246, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/odoo/src/odoo/15.0/odoo/modules/registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/15.0/odoo/modules/loading.py", line 513, in load_modules
    env['ir.model.data']._process_end(processed_modules)
  File "/tmp/tmpmguey86y/migrations/base/0.0.0/pre-models-no-model-data-delete.py", line 101, in _process_end
    return super(IrModelData, self)._process_end(modules)
  File "/home/odoo/src/odoo/15.0/odoo/addons/base/models/ir_model.py", line 2269, in _process_end
    self._process_end_unlink_record(record)
  File "/home/odoo/src/odoo/15.0/odoo/addons/base/models/ir_model.py", line 2198, in _process_end_unlink_record
    record.unlink()
  File "/tmp/tmpmguey86y/migrations/base/0.0.0/pre-models-ir_model.py", line 159, in unlink
    raise util.MigrationError(
odoo.upgrade.util.exceptions.MigrationError: 💥 It looks like you forgot to call `util.remove_field` on the following fields: res.city.l10n_mx_edi_code

```

closes odoo/upgrade#3193

Signed-off-by: Christophe Simonis <chs@odoo.com>