[FIX] mail/saas~14.3.1.3: remove call to update_field_reference
This migration:
https://github.com/odoo/upgrade/blob/master/migrations/mail/saas~14.3.1.3/pre-migrate.py#L40-L43

has for effect to change the field 'message_channel_ids' to 'message_ids'
for the 'note' module. This will impact all related domains.

This migration:
https://github.com/odoo/upgrade/blob/master/migrations/note/saas~14.3.1.0/pre-migrate.py#L8

should remove all domains linked the field 'message_channel_ids' in note.
The problem is that the domains have already been renamed to 'message_ids'
by the mail migration.
This may cause errors as these domains can then be malformed.

In the upg 40746:
  - correct domain before mail migration:
    `('message_channel_ids.channel_partner_ids', '=', user.partner_id.id)`
  - wrong domain after mail migration:
    `('message_ids.channel_partner_ids', '=', user.partner_id.id)`
The wrong domain is not deleted by the note migration

The fix is to remove the update_field_reference
call.

Changing message_channel_ids to message_ids
does not make sense as it is not
the same model.

```
Traceback (most recent call last):
  File "/tmp/tmpc03r6_fm/migrations/testing.py", line 208, in test_check
    self.check(value)
  File "/tmp/tmpc03r6_fm/migrations/base/tests/test_mock_crawl.py", line 85, in check
    self.assertFalse(diff, msg)
AssertionError: [('note.menu_note_notes', 117, 'Notes', 144)] is not false : At least one menu or view working before upgrade is not working after upgrade.

('note.menu_note_notes', 117, 'Notes', 144):
  Traceback (most recent call last):
    File "/tmp/tmpc03r6_fm/migrations/base/tests/test_mock_crawl.py", line 182, in crawl_menu
    self.mock_action(action_vals)
    File "/tmp/tmpc03r6_fm/migrations/base/tests/test_mock_crawl.py", line 293, in mock_action
    mock_method(model, view, fields_list, domain, group_by)
    File "/tmp/tmpc03r6_fm/migrations/base/tests/test_mock_crawl.py", line 381, in mock_view_kanban
    self.mock_web_read_group(model, view, domain, group_by, fields_list, limit_group=10)
    File "/tmp/tmpc03r6_fm/migrations/base/tests/test_mock_crawl.py", line 451, in mock_web_read_group
    data = model.web_read_group(domain, fields_list, group_by, limit=limit)["groups"]
    File "/home/odoo/src/odoo/15.0/addons/web/models/models.py", line 100, in web_read_group
    expand_limit, expand_orderby)
    File "/home/odoo/src/odoo/15.0/addons/web/models/models.py", line 131, in _web_read_group
    orderby=orderby, lazy=lazy)
    File "/home/odoo/src/odoo/15.0/addons/note/models/note.py", line 93, in read_group
    } for stage in stages]
    File "/home/odoo/src/odoo/15.0/addons/note/models/note.py", line 93, in <listcomp>
    } for stage in stages]
    File "/home/odoo/src/odoo/15.0/odoo/models.py", line 1787, in search_count
    res = self.search(args, count=True)
    File "/home/odoo/src/odoo/15.0/odoo/models.py", line 1810, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
    File "/home/odoo/src/odoo/15.0/odoo/models.py", line 4683, in _search
    self._apply_ir_rules(query, 'read')
    File "/home/odoo/src/odoo/15.0/odoo/models.py", line 4464, in _apply_ir_rules
    expression.expression(domain, self.sudo(), self._table, query)
    File "/home/odoo/src/odoo/15.0/odoo/osv/expression.py", line 442, in __init__
    self.parse()
    File "/home/odoo/src/odoo/15.0/odoo/osv/expression.py", line 693, in parse
    query = comodel.with_context(**field.context)._where_calc(domain)
    File "/home/odoo/src/odoo/15.0/odoo/models.py", line 4438, in _where_calc
    return expression.expression(domain, self).query
    File "/home/odoo/src/odoo/15.0/odoo/osv/expression.py", line 442, in __init__
    self.parse()
    File "/home/odoo/src/odoo/15.0/odoo/osv/expression.py", line 654, in parse
    raise ValueError("Invalid field %s.%s in leaf %s" % (model._name, path[0], str(leaf)))
  ValueError: Invalid field mail.message.channel_partner_ids in leaf ('channel_partner_ids', '=', 48)
```

upg 40746

closes odoo/upgrade#2931

Signed-off-by: Christophe Simonis <chs@odoo.com>