[FIX] base/0.0.0: do not fetch arch if file doesn't exist
Oversight of upgrade/commit@66e9e69

When the path doesn't exists calling `get_view_arch_from_file` raises an
error:
```
Traceback (most recent call last):
  File "/data/build/upgrade/migrations/base/0.0.0/pre-models-ir_ui_view.py", line 828, in validate_view
    view._check_xml()
  File "/data/build/upgrade/migrations/base/0.0.0/pre-models-ir_ui_view.py", line 798, in _check_xml
    if not _upgrade_fix_views(record, record):
  File "/data/build/upgrade/migrations/base/0.0.0/pre-models-ir_ui_view.py", line 711, in _upgrade_fix_views
    restore_from_file(fix_view, md)
  File "/data/build/upgrade/migrations/base/0.0.0/pre-models-ir_ui_view.py", line 614, in restore_from_file
    arch_db = get_view_arch_from_file(arch_fs_fullpath, view.xml_id)
  File "/data/build/odoo/odoo/addons/base/models/ir_ui_view.py", line 111, in get_view_arch_from_file
    document = etree.parse(filepath)
  File "src/lxml/etree.pyx", line 3536, in lxml.etree.parse
  File "src/lxml/parser.pxi", line 1899, in lxml.etree._parseDocument
TypeError: cannot parse from 'bool'
```

Part-of: odoo/upgrade#5090