[FIX] payment/saas~14.4: avoid to delete payment method line
when there are same provider in payment acquirer,
and one is in disabled and one in test or enabled state,
we are going to remove related payment method line
which are lined with disabled Acquirer.
there was no direct relation between acquirer and payment
method line. there is only relation between payment method
and acquirer using code field. so if there are two payment
acquirer with same code like 'paypal'
then we didnot identify which one link with payment
method. so we are going to unlink those payment
method line which are linked with disabled state
acquirer.
but when there is no any disabled state provider
we are going to delete one line without any checking.
so it raised constraints from here :
https://github.com/odoo/odoo/blob/42323a6799e1469ca47faacda0769615835e19bf/addons/payment/models/account_payment_method.py#L62

so we are going to unlink only payment method line
which linked with disabled acquirer only.

TGB: https://upgrade.odoo.com/web#id=835&action=178&model=upgrade.request.traceback.group&view_type=form&cids=1&menu_id=107

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/15.0/odoo/service/server.py", line 1260, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/odoo/src/odoo/15.0/odoo/modules/registry.py", line 87, in new
    odoo.modules.load_modules(registry, force_demo, status, update_module)
  File "/home/odoo/src/odoo/15.0/odoo/modules/loading.py", line 492, in load_modules
    migrations.migrate_module(package, 'end')
  File "/home/odoo/src/odoo/15.0/odoo/modules/migration.py", line 186, in migrate_module
    migrate(self.cr, installed_version)
  File "/tmp/tmp5h7gpo3c/migrations/payment/saas~14.4.2.0/end-migrate.py", line 104, in migrate
    env["account.payment.method.line"].search([("id", "in", to_unlink)]).unlink()
  File "/home/odoo/src/odoo/15.0/addons/account/models/account_payment_method.py", line 158, in unlink
    return super(AccountPaymentMethodLine, unused_payment_method_lines).unlink()
  File "/home/odoo/src/odoo/15.0/odoo/models.py", line 3642, in unlink
    func(self)
  File "/home/odoo/src/odoo/15.0/addons/payment/models/account_payment_method.py", line 62, in _unlink_except_active_acquirer
    raise UserError(_(
odoo.exceptions.UserError: You can't delete a payment method that is linked to a provider in the enabled or test state.
Linked providers(s): Stripe Credit
```

closes odoo/upgrade#4973

Signed-off-by: Christophe Simonis (chs) <chs@odoo.com>