[FIX] mail/0.0.0: Ensure admin mail
When the admin email or mail alias is not defined, the upgrade lead
to a crash. This script will ensure that admin have an email
in `res_partner.email`and create mail alias based on admin login
if missing.

```
Traceback (most recent call last):
  File "/home/odoo/src/odoo/9.0/openerp/service/server.py", line 894, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/home/odoo/src/odoo/9.0/openerp/modules/registry.py", line 386, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/src/odoo/9.0/openerp/modules/loading.py", line 374, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/home/odoo/src/odoo/9.0/openerp/modules/loading.py", line 271, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/odoo/src/odoo/9.0/openerp/modules/loading.py", line 188, in load_module_graph
    migrations.migrate_module(package, 'post')
  File "/home/odoo/src/odoo/9.0/openerp/modules/migration.py", line 160, in migrate_module
    migrate(self.cr, installed_version)
  File "/home/odoo/src/odoo/9.0/openerp/addons/base/maintenance/migrations/product/9.0.1.2/post-10-generic-product.py", line 28, in migrate
    'active': False,
  File "/home/odoo/src/odoo/9.0/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/src/odoo/9.0/openerp/api.py", line 490, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/home/odoo/src/odoo/9.0/addons/product/product.py", line 1184, in create
    product_id = super(product_product, self).create(cr, uid, vals, context=ctx)
  File "/home/odoo/src/odoo/9.0/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/src/odoo/9.0/openerp/api.py", line 354, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/odoo/9.0/addons/mail/models/mail_thread.py", line 235, in create
    thread = super(MailThread, self).create(values)
  File "/home/odoo/src/odoo/9.0/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/src/odoo/9.0/openerp/models.py", line 4175, in create
    record = self.browse(self._create(old_vals))
  File "/home/odoo/src/odoo/9.0/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/src/odoo/9.0/openerp/api.py", line 490, in new_api
    result = method(self._model, cr, uid, *args, **old_kwargs)
  File "/home/odoo/src/odoo/9.0/openerp/models.py", line 4237, in _create
    record_id = self.pool[table].create(cr, user, tocreate[table], context=context)
  File "/home/odoo/src/odoo/9.0/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/src/odoo/9.0/addons/product/product.py", line 675, in create
    product_template_id = super(product_template, self).create(cr, uid, vals, context=context)
  File "/home/odoo/src/odoo/9.0/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/odoo/src/odoo/9.0/openerp/api.py", line 354, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/odoo/src/odoo/9.0/addons/mail/models/mail_thread.py", line 240, in create
    thread.message_post(body=_('%s created') % doc_name)
  File "/home/odoo/src/odoo/9.0/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/src/odoo/9.0/addons/mail/models/mail_thread.py", line 1752, in message_post
    new_message = MailMessage.create(values)
  File "/home/odoo/src/odoo/9.0/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/src/odoo/9.0/addons/mail/models/mail_message.py", line 874, in create
    values['email_from'] = self._get_default_from()
  File "/home/odoo/src/odoo/9.0/openerp/api.py", line 248, in wrapper
    return new_api(self, *args, **kwargs)
  File "/home/odoo/src/odoo/9.0/addons/mail/models/mail_message.py", line 43, in _get_default_from
    raise UserError(_("Unable to send email, please configure the sender's email address or alias."))
UserError: (u"Unable to send email, please configure the sender's email address or alias.", None)
```

upg-36473
(May also affect databases without admin email)

closes odoo/upgrade#2897

Signed-off-by: Christophe Simonis <chs@odoo.com>