[FIX] hr_contract_sign@saas~13.5: ensure Contract Admin implies Sign Admin
This is required so contract managers can read `sign.request.item` records.
This is normally the case thanks to
https://github.com/odoo/enterprise/blob/707694ff27db51304c5bf6b1004781aa6ff0a655/hr_contract_sign/security/security.xml#L5
but as the group `group_hr_contract_manager` is within a `noupdate="1"`block,
it doesn't get updated with that group by default.

```
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/odoo/src/upgrade/migrations/base/tests/test_mock_crawl.py", line 155, in crawl_menu
    self.mock_action(action_vals)
  File "/home/odoo/src/upgrade/migrations/base/tests/test_mock_crawl.py", line 234, in mock_action
    mock_method(model, view, fields_list, domain, group_by)
  File "/home/odoo/src/upgrade/migrations/base/tests/test_mock_crawl.py", line 260, in mock_view_form
    [data] = record.read(fields_list)
  File "/home/odoo/src/odoo/14.0/addons/hr/models/hr_employee.py", line 142, in read
    return super(HrEmployeePrivate, self).read(fields, load=load)
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 3020, in read
    return self._read_format(fnames=fields, load=load)
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 3040, in _read_format
    vals[name] = convert(record[name], record, use_name_get)
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 5666, in __getitem__
    return self._fields[key].__get__(self, type(self))
  File "/home/odoo/src/odoo/14.0/odoo/fields.py", line 1021, in __get__
    self.compute_value(record)
  File "/home/odoo/src/odoo/14.0/odoo/fields.py", line 1175, in compute_value
    records._compute_field_value(self)
  File "/home/odoo/src/odoo/14.0/addons/mail/models/mail_thread.py", line 410, in _compute_field_value
    return super()._compute_field_value(field)
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 4061, in _compute_field_value
    getattr(self, field.compute)()
  File "/home/odoo/src/enterprise/14.0/hr_contract_sign/models/hr_employee.py", line 25, in _compute_sign_request_count
    ('role_id', '=', self.env.ref('sign.sign_item_role_employee').id)]).mapped('sign_request_id')
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 1708, in search
    res = self._search(args, offset=offset, limit=limit, order=order, count=count)
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 4485, in _search
    model.check_access_rights('read')
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 3331, in check_access_rights
    return self.env['ir.model.access'].check(self._name, operation, raise_exception)
  File "<decorator-gen-33>", line 2, in check
  File "/home/odoo/src/odoo/14.0/odoo/tools/cache.py", line 90, in lookup
    value = d[key] = self.method(*args, **kwargs)
  File "/home/odoo/src/odoo/14.0/odoo/addons/base/models/ir_model.py", line 1792, in check
    raise AccessError(msg)
odoo.exceptions.AccessError: You are not allowed to access 'Signature Request Item' (sign.request.item) records.

This operation is allowed for the following groups:
        - Sign/Employee
        - Sign/Employee
        - Sign/User: Own and Shared Templates
```

upg-9964

closes odoo/upgrade#2285

Signed-off-by: Christophe Simonis <chs@odoo.com>