[FIX] hr_recruitment: ensure mail alias to avoid unique conflict
Sometimes, the user deleted the `mail.alias` "jobs" record,
therefore for the `ir.model.data` to be deleted as well,
and then created manually a mail alias "jobs".

By ensuring this manually created "jobs" alias
to be linked to the `ir.model.data`,
we avoid the unique constraint.

```
2020-12-31 05:10:29,835 25 INFO db_3456 odoo.modules.loading: loading hr_recruitment/data/hr_recruitment_data.xml
2020-12-31 05:10:29,861 25 WARNING db_3456 odoo.modules.loading: Transient module states were reset
2020-12-31 05:10:29,871 25 ERROR db_3456 odoo.modules.registry: Failed to load registry
2020-12-31 05:10:29,871 25 CRITICAL db_3456 odoo.service.server: Failed to initialize database `db_3456`.
Traceback (most recent call last):
  File "/home/odoo/src/odoo/14.0/odoo/tools/convert.py", line 677, in _tag_root
    f(rec)
  File "/home/odoo/src/odoo/14.0/odoo/tools/convert.py", line 580, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 4203, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/home/odoo/src/odoo/14.0/odoo/models.py", line 4132, in _load_records_create
    return self.create(values)
  File "<decorator-gen-122>", line 2, in create
  File "/home/odoo/src/odoo/14.0/odoo/api.py", line 326, in _model_create_single
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/home/odoo/src/odoo/14.0/odoo/api.py", line 326, in <genexpr>
    return self.browse().concat(*(create(self, vals) for vals in arg))
  File "/home/odoo/src/odoo/14.0/addons/mail/models/mail_alias.py", line 115, in create
    vals['alias_name'] = self._clean_and_check_unique(vals.get('alias_name'))
  File "/home/odoo/src/odoo/14.0/addons/mail/models/mail_alias.py", line 153, in _clean_and_check_unique
    raise UserError(_('The e-mail alias is already used. Please enter another one.'))
odoo.exceptions.UserError: The e-mail alias is already used. Please enter another one.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/odoo/src/odoo/14.0/odoo/service/server.py", line 1198, in preload_registries
    registry = Registry.new(dbname, update_module=update_module)
  File "/home/odoo/src/odoo/14.0/odoo/modules/registry.py", line 89, in new
    odoo.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/odoo/src/odoo/14.0/odoo/modules/loading.py", line 451, in load_modules
    force, status, report, loaded_modules, update_module, models_to_check)
  File "/home/odoo/src/odoo/14.0/odoo/modules/loading.py", line 348, in load_marked_modules
    perform_checks=perform_checks, models_to_check=models_to_check
  File "/home/odoo/src/odoo/14.0/odoo/modules/loading.py", line 221, in load_module_graph
    load_data(cr, idref, mode, kind='data', package=package)
  File "/home/odoo/src/odoo/14.0/odoo/modules/loading.py", line 69, in load_data
    tools.convert_file(cr, package.name, filename, idref, mode, noupdate, kind)
  File "/home/odoo/src/odoo/14.0/odoo/tools/convert.py", line 733, in convert_file
    convert_xml_import(cr, module, fp, idref, mode, noupdate)
  File "/home/odoo/src/odoo/14.0/odoo/tools/convert.py", line 799, in convert_xml_import
    obj.parse(doc.getroot())
  File "/home/odoo/src/odoo/14.0/odoo/tools/convert.py", line 719, in parse
    self._tag_root(de)
  File "/home/odoo/src/odoo/14.0/odoo/tools/convert.py", line 677, in _tag_root
    f(rec)
  File "/home/odoo/src/odoo/14.0/odoo/tools/convert.py", line 685, in _tag_root
    )) from e
odoo.tools.convert.ParseError: while parsing /home/odoo/src/odoo/14.0/addons/hr_recruitment/data/hr_recruitment_data.xml:272, near
<record id="mail_alias_jobs" model="mail.alias">
        <field name="alias_name">jobs</field>
        <field name="alias_model_id" ref="model_hr_applicant"/>
        <field name="alias_user_id" ref="base.user_admin"/>
        <field name="alias_parent_model_id" ref="model_hr_job"/>
    </record>
```

upg-3456
upg-6169

closes odoo/upgrade#2125

Signed-off-by: Christophe Simonis <chs@odoo.com>