[FIX] uom/saas~18.1: only one reference uom_type
To reproduce:
1) activiate uoms
2) add a new uom and unselect active.
3) before saving changes, make that uom reference.
4) then upgrade.

we run into the traceback below. Because this query:
https://github.com/odoo/upgrade/blob/master/migrations/uom/saas~18.1.1.0/pre-migrate.py#L18
doesn't check for inactive uoms while calculating relative_uom_id. This
way we can have two reference uoms per category and can lead to a
recursive loop. This code:
https://github.com/odoo/odoo/blob/18.0/addons/uom/models/uom_uom.py#L20
ensures that we don't have two active `reference` uom_type.
parent_path is calculated when its added to model with parent_name, and
parent_store=True. The class for uom:
https://github.com/odoo/odoo/blob/saas-18.1/addons/uom/models/uom_uom.py#L13
where it was added. The method for calculation it triggers:
https://github.com/odoo/odoo/blob/saas-18.1/odoo/orm/models.py#L2986

before upgrade
```
select id,uom_type,active from uom_uom where category_id=1
+----+-----------+--------+
| id | uom_type  | active |
|----+-----------+--------|
| 27 | reference | False  |
| 2  | bigger    | True   |
| 28 | bigger    | True   |
| 29 | reference | False  |
| 1  | reference | True   |
+----+-----------+--------+
```

what it looks like just before end-script where we break the loop
https://github.com/odoo/upgrade/blob/master/migrations/uom/saas~18.1.1.0/end-migrate.py#L6
```
uom_18> select relative_uom_id,id,active from uom_uom where id IN (1,2,27,28,29)
+-----------------+----+--------+
| relative_uom_id | id | active |
|-----------------+----+--------|
| 1               | 27 | False  |
| 1               | 2  | True   |
| 1               | 28 | True   |
| 1               | 29 | False  |
| 29              | 1  | True   |
+-----------------+----+--------+
```

```
'project.menu_project_management_all_tasks', 349, 'Project > Tasks > All Tasks', 515):
 Traceback (most recent call last):
   File "/tmp/tmp5hjqado3/migrations/base/tests/test_mock_crawl.py", line 256, in crawl_menu
    self.mock_action(action_vals)
   File "/tmp/tmp5hjqado3/migrations/base/tests/test_mock_crawl.py", line 269, in mock_action
    return self.mock_act_window(action)
   File "/tmp/tmp5hjqado3/migrations/base/tests/test_mock_crawl.py", line 429, in mock_act_window
    mock_method(model, view, fields_list, domain, group_by)
   File "/tmp/tmp5hjqado3/migrations/base/tests/test_mock_crawl.py", line 550, in mock_view_list
    return self.mock_view_tree(model, view, fields_list, domain, group_by)
   File "/tmp/tmp5hjqado3/migrations/base/tests/test_mock_crawl.py", line 563, in mock_view_tree
    self.mock_web_search_read(model, view, [domain], fields_list)
   File "/tmp/tmp5hjqado3/migrations/base/tests/test_mock_crawl.py", line 597, in mock_web_search_read
    data = model.search_read(domain=domain, fields=fields_list, limit=80)
   File "/home/odoo/src/odoo/saas-18.1/odoo/orm/models.py", line 5929, in search_read
    return records._read_format(fnames=fields, **read_kwargs)
   File "/home/odoo/src/odoo/saas-18.1/odoo/orm/models.py", line 3841, in _read_format
    vals[name] = convert(record[name], record, use_display_name)
   File "/home/odoo/src/odoo/saas-18.1/odoo/orm/models.py", line 6880, in __getitem__
    return self._fields[key].__get__(self)
   File "/home/odoo/src/odoo/saas-18.1/odoo/orm/fields.py", line 1428, in __get__
    self.compute_value(recs)
   File "/home/odoo/src/odoo/saas-18.1/odoo/orm/fields.py", line 1594, in compute_value
    records._compute_field_value(self)
   File "/home/odoo/src/odoo/saas-18.1/addons/mail/models/mail_thread.py", line 441, in _compute_field_value
    return super()._compute_field_value(field)
   File "/home/odoo/src/odoo/saas-18.1/odoo/orm/models.py", line 5055, in _compute_field_value
    determine(field.compute, self)
   File "/home/odoo/src/odoo/saas-18.1/odoo/orm/fields.py", line 73, in determine
    return needle(records, *args)
   File "/home/odoo/src/odoo/saas-18.1/odoo/orm/fields.py", line 668, in _compute_related
    record[self.name] = self._process_related(value[self.related_field.name], record.env)
   File "/home/odoo/src/odoo/saas-18.1/odoo/orm/models.py", line 6880, in __getitem__
    return self._fields[key].__get__(self)
   File "/home/odoo/src/odoo/saas-18.1/odoo/orm/fields.py", line 1428, in __get__
    self.compute_value(recs)
   File "/home/odoo/src/odoo/saas-18.1/odoo/orm/fields.py", line 1594, in compute_value
    records._compute_field_value(self)
   File "/home/odoo/src/odoo/saas-18.1/odoo/orm/models.py", line 5055, in _compute_field_value
    determine(field.compute, self)
   File "/home/odoo/src/odoo/saas-18.1/odoo/orm/fields.py", line 70, in determine
    return needle(*args)
   File "/home/odoo/src/odoo/saas-18.1/addons/sale_timesheet/models/sale_order_line.py", line 49, in _compute_remaining_hours_available
    is_time_product = line.product_uom_id and line.product_uom_id._has_common_reference(self.env.ref('uom.product_uom_hour'))
   File "/home/odoo/src/odoo/saas-18.1/addons/uom/models/uom_uom.py", line 136, in _has_common_reference
    self_path = self.parent_path.split('/')
 AttributeError: 'bool' object has no attribute 'split'
```

closes odoo/upgrade#7220

Signed-off-by: Alvaro Fuentes Suarez (afu) <afu@odoo.com>