[FIX] util.remove_field: remove field from dependencies
When removing a field we need to check if it is on the dependencies list
of other fields and remove it from there.

Example traceback when this is not done
```
 Traceback (most recent call last):
   File "/tmp/tmp0mzpv7uo/migrations/base/tests/test_mock_crawl.py", line 179, in crawl_menu
    self.mock_action(action_vals)
   File "/tmp/tmp0mzpv7uo/migrations/base/tests/test_mock_crawl.py", line 288, in mock_action
    mock_method(model, view, fields_list, domain, group_by)
   File "/tmp/tmp0mzpv7uo/migrations/base/tests/test_mock_crawl.py", line 403, in mock_view_tree
    self.mock_web_search_read(model, view, [domain], fields_list)
   File "/tmp/tmp0mzpv7uo/migrations/base/tests/test_mock_crawl.py", line 437, in mock_web_search_read
    data = model.search_read(domain=domain, fields=fields_list, limit=80)
   File "/home/odoo/src/odoo/14.0/odoo/models.py", line 4835, in search_read
    result = records.read(fields)
   File "/home/odoo/src/odoo/14.0/odoo/models.py", line 3011, in read
    f = self._fields[dotname.split('.')[0]]
 KeyError: 'item_ids'
```

upg-22315

closes odoo/upgrade#2757

Signed-off-by: Christophe Simonis <chs@odoo.com>